UCONST_PLAYER_MATCH = 0
UCONST_RANKED_MATCH = 1
UCONST_REC_MATCH = 2
UCONST_PRIVATE_MATCH = 3
UCONST_RANKEDPROVIDERTAG = "PlaylistsRanked"
UCONST_UNRANKEDPROVIDERTAG = "PlaylistsUnranked"
UCONST_RECMODEPROVIDERTAG = "PlaylistsRecMode"
UCONST_PRIVATEPROVIDERTAG = "PlaylistsPrivate"
