#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UCustomizationGFxMovie()
{
    class_< UCustomizationGFxMovie, bases< UWillowGFxThirdPersonMovie >  , boost::noncopyable>("UCustomizationGFxMovie", no_init)
        .def_readwrite("CharacterCustomizationMenu", &UCustomizationGFxMovie::CharacterCustomizationMenu)
        .def_readwrite("CharacterCustomizationInfoCard", &UCustomizationGFxMovie::CharacterCustomizationInfoCard)
        .def_readonly("SkillBranchDescriptions", &UCustomizationGFxMovie::SkillBranchDescriptions)
        .def_readwrite("HeadCustomizations", &UCustomizationGFxMovie::HeadCustomizations)
        .def_readwrite("SeenHeadCustomizations", &UCustomizationGFxMovie::SeenHeadCustomizations)
        .def_readwrite("SkinCustomizations", &UCustomizationGFxMovie::SkinCustomizations)
        .def_readwrite("SeenSkinCustomizations", &UCustomizationGFxMovie::SeenSkinCustomizations)
        .def_readwrite("EquippedHeadCustomization", &UCustomizationGFxMovie::EquippedHeadCustomization)
        .def_readwrite("EquippedSkinCustomization", &UCustomizationGFxMovie::EquippedSkinCustomization)
        .def_readwrite("PreviewHeadCustomization", &UCustomizationGFxMovie::PreviewHeadCustomization)
        .def_readwrite("PreviewSkinCustomization", &UCustomizationGFxMovie::PreviewSkinCustomization)
        .def_readwrite("SelectedEntryIdx", &UCustomizationGFxMovie::SelectedEntryIdx)
        .def_readwrite("StringPreKeyboardUI", &UCustomizationGFxMovie::StringPreKeyboardUI)
        .def_readwrite("MaxNameLength", &UCustomizationGFxMovie::MaxNameLength)
        .def_readwrite("HeaderText", &UCustomizationGFxMovie::HeaderText)
        .def_readwrite("NoValidHeadCaption", &UCustomizationGFxMovie::NoValidHeadCaption)
        .def_readwrite("NoValidSkinCaption", &UCustomizationGFxMovie::NoValidSkinCaption)
        .def_readwrite("UnlockedText", &UCustomizationGFxMovie::UnlockedText)
        .def_readwrite("UnlockedHeadsNumbersText", &UCustomizationGFxMovie::UnlockedHeadsNumbersText)
        .def_readwrite("UnlockedSkinsNumbersText", &UCustomizationGFxMovie::UnlockedSkinsNumbersText)
        .def_readwrite("TooltipsPath", &UCustomizationGFxMovie::TooltipsPath)
        .def_readwrite("PreviewIndex", &UCustomizationGFxMovie::PreviewIndex)
        .def_readwrite("PreviewType", &UCustomizationGFxMovie::PreviewType)
        .def_readwrite("UnauthorizedHeadCustomizations", &UCustomizationGFxMovie::UnauthorizedHeadCustomizations)
        .def_readwrite("UnauthorizedSkinCustomizations", &UCustomizationGFxMovie::UnauthorizedSkinCustomizations)
        .def_readwrite("PotentialCustomizationForPurchase", &UCustomizationGFxMovie::PotentialCustomizationForPurchase)
        .def("StaticClass", &UCustomizationGFxMovie::StaticClass, return_value_policy< reference_existing_object >())
        .def("MarketplaceDownloadComplete", &UCustomizationGFxMovie::MarketplaceDownloadComplete)
        .def("GetOfferIdForCustomization", &UCustomizationGFxMovie::GetOfferIdForCustomization)
        .def("extGenericButtonClicked", &UCustomizationGFxMovie::extGenericButtonClicked)
        .def("InitForConsole", &UCustomizationGFxMovie::InitForConsole)
        .def("InitForPC", &UCustomizationGFxMovie::InitForPC)
        .def("eventGetCurrentTab", &UCustomizationGFxMovie::eventGetCurrentTab)
        .def("extInitSkinInfoCard", &UCustomizationGFxMovie::extInitSkinInfoCard)
        .def("extInitHeadInfoCard", &UCustomizationGFxMovie::extInitHeadInfoCard)
        .def("extInitRespecInfoCard", &UCustomizationGFxMovie::extInitRespecInfoCard)
        .def("extInitNameInfoCard", &UCustomizationGFxMovie::extInitNameInfoCard)
        .def("extInitPlayerClassDisplay", &UCustomizationGFxMovie::extInitPlayerClassDisplay)
        .def("SetToolTipsForPurchase", &UCustomizationGFxMovie::SetToolTipsForPurchase)
        .def("SetTooltips", &UCustomizationGFxMovie::SetTooltips)
        .def("extCharacterCustomizationOnLoad", &UCustomizationGFxMovie::extCharacterCustomizationOnLoad)
        .def("ValidatePlayerName", &UCustomizationGFxMovie::ValidatePlayerName)
        .def("SetPlayerName", &UCustomizationGFxMovie::SetPlayerName)
        .def("OnPlayerNameInputFinished", &UCustomizationGFxMovie::OnPlayerNameInputFinished)
        .def("InputName", &UCustomizationGFxMovie::InputName)
        .def("OnCurrencyChanged", &UCustomizationGFxMovie::OnCurrencyChanged)
        .def("OnSkillTreeReset", &UCustomizationGFxMovie::OnSkillTreeReset)
        .def("SetUnlockedText_Skins", &UCustomizationGFxMovie::SetUnlockedText_Skins)
        .def("SetUnlockedText_Heads", &UCustomizationGFxMovie::SetUnlockedText_Heads)
        .def("UpdateInfoCard", &UCustomizationGFxMovie::UpdateInfoCard)
        .def("UpdateSkinPreview", &UCustomizationGFxMovie::UpdateSkinPreview)
        .def("UpdateHeadPreview", &UCustomizationGFxMovie::UpdateHeadPreview)
        .def("CancelSkinCustomization", &UCustomizationGFxMovie::CancelSkinCustomization)
        .def("CancelHeadCustomization", &UCustomizationGFxMovie::CancelHeadCustomization)
        .def("OnPurchaseCanceled", &UCustomizationGFxMovie::OnPurchaseCanceled)
        .def("OnPurchaseRequest", &UCustomizationGFxMovie::OnPurchaseRequest)
        .def("ShowMarketplaceOfferFor", &UCustomizationGFxMovie::ShowMarketplaceOfferFor)
        .def("ShowPurchaseDialog", &UCustomizationGFxMovie::ShowPurchaseDialog)
        .def("CommitSkinCustomization", &UCustomizationGFxMovie::CommitSkinCustomization)
        .def("CommitHeadCustomization", &UCustomizationGFxMovie::CommitHeadCustomization)
        .def("HandleCustomizationEvent", &UCustomizationGFxMovie::HandleCustomizationEvent)
        .def("UsingGamepad", &UCustomizationGFxMovie::UsingGamepad)
        .def("HandleMenuEntryRollOver", &UCustomizationGFxMovie::HandleMenuEntryRollOver)
        .def("HandleMenuEntryFocus", &UCustomizationGFxMovie::HandleMenuEntryFocus)
        .def("HandleMenuEntryClick", &UCustomizationGFxMovie::HandleMenuEntryClick)
        .def("CacheCustomizations", &UCustomizationGFxMovie::CacheCustomizations)
        .def("CacheSkillBranchDescriptions", &UCustomizationGFxMovie::CacheSkillBranchDescriptions)
        .def("MainInputKey", &UCustomizationGFxMovie::MainInputKey)
        .def("OnClose", &UCustomizationGFxMovie::OnClose)
        .def("BeginClosing", &UCustomizationGFxMovie::BeginClosing)
        .def("eventStart", &UCustomizationGFxMovie::eventStart)
        .def("GetSonyTitleID", &UCustomizationGFxMovie::GetSonyTitleID)
        .staticmethod("StaticClass")
  ;
}