#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UTwoPanelInterfaceGFxObject()
{
    class_< UTwoPanelInterfaceGFxObject, bases< UBaseTopLevelPanelGFxObject >  , boost::noncopyable>("UTwoPanelInterfaceGFxObject", no_init)
        .def_readwrite("TwoPanelInterface", &UTwoPanelInterfaceGFxObject::TwoPanelInterface)
        .def_readonly("UnknownData00", &UTwoPanelInterfaceGFxObject::UnknownData00)
        .def_readwrite("StoragePanel", &UTwoPanelInterfaceGFxObject::StoragePanel)
        .def_readwrite("PlayerPanel", &UTwoPanelInterfaceGFxObject::PlayerPanel)
        .def_readwrite("frameNum", &UTwoPanelInterfaceGFxObject::frameNum)
        .def_readwrite("TransferringThing", &UTwoPanelInterfaceGFxObject::TransferringThing)
        .def_readwrite("DynamicCardName", &UTwoPanelInterfaceGFxObject::DynamicCardName)
        .def_readwrite("HeaderNavLeftTooltip", &UTwoPanelInterfaceGFxObject::HeaderNavLeftTooltip)
        .def_readwrite("HeaderNavRightTooltip", &UTwoPanelInterfaceGFxObject::HeaderNavRightTooltip)
        .def_readwrite("StoragePanelLabel", &UTwoPanelInterfaceGFxObject::StoragePanelLabel)
        .def_readwrite("PlayerPanelLabel", &UTwoPanelInterfaceGFxObject::PlayerPanelLabel)
        .def_readwrite("bCanAcceptInput", &UTwoPanelInterfaceGFxObject::bCanAcceptInput)
        .def("StaticClass", &UTwoPanelInterfaceGFxObject::StaticClass, return_value_policy< reference_existing_object >())
        .def("OnCellPressed", &UTwoPanelInterfaceGFxObject::OnCellPressed)
        .def("InitForConsole", &UTwoPanelInterfaceGFxObject::InitForConsole)
        .def("InitForPC", &UTwoPanelInterfaceGFxObject::InitForPC)
        .def("OnValidCell", &UTwoPanelInterfaceGFxObject::OnValidCell)
        .def("GetCurrentCellObject", &UTwoPanelInterfaceGFxObject::GetCurrentCellObject, return_value_policy< reference_existing_object >())
        .def("GetCurrentPanel", &UTwoPanelInterfaceGFxObject::GetCurrentPanel, return_value_policy< reference_existing_object >())
        .def("GetInspectedItemCurrencyType", &UTwoPanelInterfaceGFxObject::GetInspectedItemCurrencyType)
        .def("GetInspectedItemOverridePrice", &UTwoPanelInterfaceGFxObject::GetInspectedItemOverridePrice)
        .def("SetActivePanelSelectIndexByThing", &UTwoPanelInterfaceGFxObject::SetActivePanelSelectIndexByThing)
        .def("SetActivePanelSortConfiguration", &UTwoPanelInterfaceGFxObject::SetActivePanelSortConfiguration)
        .def("SetTabIconFrame", &UTwoPanelInterfaceGFxObject::SetTabIconFrame)
        .def("SetActiveTab", &UTwoPanelInterfaceGFxObject::SetActiveTab)
        .def("SetNavTooltips", &UTwoPanelInterfaceGFxObject::SetNavTooltips)
        .def("SetTooltipText", &UTwoPanelInterfaceGFxObject::SetTooltipText)
        .def("Cleanup", &UTwoPanelInterfaceGFxObject::Cleanup)
        .def("SetStorageInfoCardVisible", &UTwoPanelInterfaceGFxObject::SetStorageInfoCardVisible)
        .def("SetStorageInfoCardData", &UTwoPanelInterfaceGFxObject::SetStorageInfoCardData)
        .def("SetStorageInfoCardTitle", &UTwoPanelInterfaceGFxObject::SetStorageInfoCardTitle)
        .def("CycleSelectedThingAsTrashOrFavorite", &UTwoPanelInterfaceGFxObject::CycleSelectedThingAsTrashOrFavorite)
        .def("TweenCards", &UTwoPanelInterfaceGFxObject::TweenCards)
        .def("FinishTransfer", &UTwoPanelInterfaceGFxObject::FinishTransfer)
        .def("CancelTransfer", &UTwoPanelInterfaceGFxObject::CancelTransfer)
        .def("ConfirmTransfer", &UTwoPanelInterfaceGFxObject::ConfirmTransfer)
        .def("TransferInputKey", &UTwoPanelInterfaceGFxObject::TransferInputKey)
        .def("StartTransfer", &UTwoPanelInterfaceGFxObject::StartTransfer)
        .def("IsTransferring", &UTwoPanelInterfaceGFxObject::IsTransferring)
        .def("NormalInputKey", &UTwoPanelInterfaceGFxObject::NormalInputKey)
        .def("PanelInputKey", &UTwoPanelInterfaceGFxObject::PanelInputKey)
        .def("OnItemSelected", &UTwoPanelInterfaceGFxObject::OnItemSelected)
        .def("InitItemCards", &UTwoPanelInterfaceGFxObject::InitItemCards)
        .def("AssignItemCards", &UTwoPanelInterfaceGFxObject::AssignItemCards)
        .def("SetHeader", &UTwoPanelInterfaceGFxObject::SetHeader)
        .def("GetSelectedThing", &UTwoPanelInterfaceGFxObject::GetSelectedThing, return_value_policy< reference_existing_object >())
        .def("GetEquippedAnalogueThroughInterface", &UTwoPanelInterfaceGFxObject::GetEquippedAnalogueThroughInterface, return_value_policy< reference_existing_object >())
        .def("GetSelectedThingThroughInterface", &UTwoPanelInterfaceGFxObject::GetSelectedThingThroughInterface, return_value_policy< reference_existing_object >())
        .def("UpdateDynamicCard", &UTwoPanelInterfaceGFxObject::UpdateDynamicCard)
        .def("RefreshItemCards", &UTwoPanelInterfaceGFxObject::RefreshItemCards)
        .def("SetUpCard", &UTwoPanelInterfaceGFxObject::SetUpCard)
        .def("SetActive", &UTwoPanelInterfaceGFxObject::SetActive)
        .def("SwitchPanelsForComparing", &UTwoPanelInterfaceGFxObject::SwitchPanelsForComparing)
        .def("TrySwitchToRightPanel", &UTwoPanelInterfaceGFxObject::TrySwitchToRightPanel)
        .def("TrySwitchToLeftPanel", &UTwoPanelInterfaceGFxObject::TrySwitchToLeftPanel)
        .def("SwitchToRightPanel", &UTwoPanelInterfaceGFxObject::SwitchToRightPanel)
        .def("SwitchToLeftPanel", &UTwoPanelInterfaceGFxObject::SwitchToLeftPanel)
        .def("OnListSort", &UTwoPanelInterfaceGFxObject::OnListSort)
        .def("ConfigureForPlayer", &UTwoPanelInterfaceGFxObject::ConfigureForPlayer)
        .def("OnTick", &UTwoPanelInterfaceGFxObject::OnTick)
        .def("Refresh", &UTwoPanelInterfaceGFxObject::Refresh)
        .def("RefreshRightPanel", &UTwoPanelInterfaceGFxObject::RefreshRightPanel)
        .def("RefreshLeftPanel", &UTwoPanelInterfaceGFxObject::RefreshLeftPanel)
        .def("SetActiveHeaderIcon", &UTwoPanelInterfaceGFxObject::SetActiveHeaderIcon)
        .def("SetHeaderLabel", &UTwoPanelInterfaceGFxObject::SetHeaderLabel)
        .def("SetPlayerPanelHidden", &UTwoPanelInterfaceGFxObject::SetPlayerPanelHidden)
        .def("SetNavHeaderIconCount", &UTwoPanelInterfaceGFxObject::SetNavHeaderIconCount)
        .def("extInitRightPanel", &UTwoPanelInterfaceGFxObject::extInitRightPanel)
        .def("extInitLeftPanel", &UTwoPanelInterfaceGFxObject::extInitLeftPanel)
        .def("Init", &UTwoPanelInterfaceGFxObject::Init)
        .def("OnDynamicCardUpdated", &UTwoPanelInterfaceGFxObject::OnDynamicCardUpdated)
        .def("SwitchToStartingPanel", &UTwoPanelInterfaceGFxObject::SwitchToStartingPanel)
        .staticmethod("StaticClass")
  ;
}