#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UWillowNavigationHandle()
{
    py::class_< UWillowNavigationHandle,  UGearboxNavigationHandle   >("UWillowNavigationHandle")
        .def_readwrite("MyWillowMind", &UWillowNavigationHandle::MyWillowMind)
        .def_readwrite("MyWillowPawn", &UWillowNavigationHandle::MyWillowPawn)
        .def_readwrite("ControllingAction", &UWillowNavigationHandle::ControllingAction)
        .def_readwrite("PathFindActionIndex", &UWillowNavigationHandle::PathFindActionIndex)
        .def_readwrite("PathZone", &UWillowNavigationHandle::PathZone)
        .def_readwrite("FixMode", &UWillowNavigationHandle::FixMode)
        .def_readwrite("FlightMode", &UWillowNavigationHandle::FlightMode)
        .def_readwrite("FixStartTime", &UWillowNavigationHandle::FixStartTime)
        .def_readwrite("FixPosition", &UWillowNavigationHandle::FixPosition)
        .def_readwrite("FixWaitTime", &UWillowNavigationHandle::FixWaitTime)
        .def_readwrite("FixMoveTime", &UWillowNavigationHandle::FixMoveTime)
        .def_readwrite("FixLerpTime", &UWillowNavigationHandle::FixLerpTime)
        .def_readwrite("FixMaxDist", &UWillowNavigationHandle::FixMaxDist)
        .def_readwrite("FixFailedWaitTime", &UWillowNavigationHandle::FixFailedWaitTime)
        .def_readwrite("FlyHitIndex", &UWillowNavigationHandle::FlyHitIndex)
        .def_readwrite("OriginalFlyDirection", &UWillowNavigationHandle::OriginalFlyDirection)
        .def_readwrite("FlyHits", &UWillowNavigationHandle::FlyHits)
        .def_readwrite("FlyDirections", &UWillowNavigationHandle::FlyDirections)
        .def_readwrite("FlightObstacleDistPct", &UWillowNavigationHandle::FlightObstacleDistPct)
        .def_readwrite("FlyFixRate", &UWillowNavigationHandle::FlyFixRate)
        .def_readwrite("FlyFixLastCheckTime", &UWillowNavigationHandle::FlyFixLastCheckTime)
        .def_readwrite("FlyFixLocation", &UWillowNavigationHandle::FlyFixLocation)
        .def_readwrite("MyNextExpensiveFrame", &UWillowNavigationHandle::MyNextExpensiveFrame)
        .def("StaticClass", &UWillowNavigationHandle::StaticClass, py::return_value_policy::reference)
        .def("PassedCurrentFlyGoal", &UWillowNavigationHandle::PassedCurrentFlyGoal)
        .def("ReachedCurrentFlyGoal", &UWillowNavigationHandle::ReachedCurrentFlyGoal)
        .def("CheckFlying", &UWillowNavigationHandle::CheckFlying)
        .def("TickFlying", &UWillowNavigationHandle::TickFlying)
        .def("SetWantsToFly", &UWillowNavigationHandle::SetWantsToFly)
        .def("WantsToFly", &UWillowNavigationHandle::WantsToFly)
        .def("ShouldFly", &UWillowNavigationHandle::ShouldFly)
        .def("IsFlying", &UWillowNavigationHandle::IsFlying)
        .def("ProcessObstacleAvoidance", &UWillowNavigationHandle::ProcessObstacleAvoidance)
        .def("NotifyAvoidingObstacle", &UWillowNavigationHandle::NotifyAvoidingObstacle)
        .def("CanAvoidObstacles", &UWillowNavigationHandle::CanAvoidObstacles)
        .def("FixByLerping", &UWillowNavigationHandle::FixByLerping)
        .def("FixByMoving", &UWillowNavigationHandle::FixByMoving)
        .def("FixAnchor", &UWillowNavigationHandle::FixAnchor)
        .def("ClearSpecialMovement", &UWillowNavigationHandle::ClearSpecialMovement)
        .def("IsPaused", &UWillowNavigationHandle::IsPaused)
        .def("IsHardAttached", &UWillowNavigationHandle::IsHardAttached)
        .def("GoalReachable", &UWillowNavigationHandle::GoalReachable)
        .def("PointReachable", &UWillowNavigationHandle::PointReachable)
        .def("TrySpecialMove", &UWillowNavigationHandle::TrySpecialMove)
        .def("GetMoveVector", &UWillowNavigationHandle::GetMoveVector)
        .def("SetFacingPolicy", &UWillowNavigationHandle::SetFacingPolicy)
        .def("IsGoalValid", &UWillowNavigationHandle::IsGoalValid)
        .def("MovePawnToGoal", &UWillowNavigationHandle::MovePawnToGoal)
        .def("SetPawnPhysics", &UWillowNavigationHandle::SetPawnPhysics)
        .def("FindActionPaths", &UWillowNavigationHandle::FindActionPaths)
        .def("ClearPath", &UWillowNavigationHandle::ClearPath)
        .def("PathIsValid", &UWillowNavigationHandle::PathIsValid)
        .def("CanFollowPath", &UWillowNavigationHandle::CanFollowPath)
        .def("FollowPath", &UWillowNavigationHandle::FollowPath)
        .def("CreateConstrainedPath", &UWillowNavigationHandle::CreateConstrainedPath)
        .staticmethod("StaticClass")
  ;
}