#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UFiringModeDefinition(py::object m)
{
    py::class_< UFiringModeDefinition,  UGBXDefinition   >(m, "UFiringModeDefinition")
        .def_readwrite("FireType", &UFiringModeDefinition::FireType)
        .def_readwrite("BeamLockBehavior", &UFiringModeDefinition::BeamLockBehavior)
        .def_readwrite("DamageTypeDefinition", &UFiringModeDefinition::DamageTypeDefinition)
        .def_readwrite("ProjectileDefinition", &UFiringModeDefinition::ProjectileDefinition)
        .def_readwrite("ExplosionOverrideDefinition", &UFiringModeDefinition::ExplosionOverrideDefinition)
        .def_readwrite("ExplosionOverideInstanceDataName", &UFiringModeDefinition::ExplosionOverideInstanceDataName)
        .def_readwrite("PartSysTemplate", &UFiringModeDefinition::PartSysTemplate)
        .def_readwrite("ConditionalPartSysTemplate", &UFiringModeDefinition::ConditionalPartSysTemplate)
        .def_readwrite("OnAnyImpact", &UFiringModeDefinition::OnAnyImpact)
        .def_readwrite("ImpactResponses", &UFiringModeDefinition::ImpactResponses)
        .def_readwrite("Lifetime", &UFiringModeDefinition::Lifetime)
        .def_readwrite("TraceInterval", &UFiringModeDefinition::TraceInterval)
        .def_readwrite("OverchargedImpactTemplate", &UFiringModeDefinition::OverchargedImpactTemplate)
        .def_readwrite("NumRicochets", &UFiringModeDefinition::NumRicochets)
        .def_readwrite("Speed", &UFiringModeDefinition::Speed)
        .def_readwrite("Acceleration", &UFiringModeDefinition::Acceleration)
        .def_readwrite("WaveFreq", &UFiringModeDefinition::WaveFreq)
        .def_readwrite("WaveAmp", &UFiringModeDefinition::WaveAmp)
        .def_readwrite("WavePhase", &UFiringModeDefinition::WavePhase)
        .def_readwrite("RicochetFriction", &UFiringModeDefinition::RicochetFriction)
        .def_readwrite("AirFriction", &UFiringModeDefinition::AirFriction)
        .def_readwrite("TimerEvents", &UFiringModeDefinition::TimerEvents)
        .def_readwrite("RicochetResponse", &UFiringModeDefinition::RicochetResponse)
        .def_readwrite("TraceExtent", &UFiringModeDefinition::TraceExtent)
        .def_readwrite("LightProjectileSourceLocationName", &UFiringModeDefinition::LightProjectileSourceLocationName)
        .def_readwrite("BeamMaxLockOnDistance", &UFiringModeDefinition::BeamMaxLockOnDistance)
        .def_readwrite("BeamMaxLength", &UFiringModeDefinition::BeamMaxLength)
        .def_readwrite("BeamSourceTangentStrengthOverDistance", &UFiringModeDefinition::BeamSourceTangentStrengthOverDistance)
        .def_readwrite("BeamTargetTangentStrengthOverDistance", &UFiringModeDefinition::BeamTargetTangentStrengthOverDistance)
        .def_readwrite("BeamApproxRepUpdateTime", &UFiringModeDefinition::BeamApproxRepUpdateTime)
        .def_readwrite("BeamTraceNumSteps", &UFiringModeDefinition::BeamTraceNumSteps)
        .def_readwrite("BeamSourceLocationName", &UFiringModeDefinition::BeamSourceLocationName)
        .def_readwrite("BeamSourceTangentName", &UFiringModeDefinition::BeamSourceTangentName)
        .def_readwrite("BeamSourceStrengthName", &UFiringModeDefinition::BeamSourceStrengthName)
        .def_readwrite("BeamTargetLocationName", &UFiringModeDefinition::BeamTargetLocationName)
        .def_readwrite("BeamTargetTangentName", &UFiringModeDefinition::BeamTargetTangentName)
        .def_readwrite("BeamTargetStrengthName", &UFiringModeDefinition::BeamTargetStrengthName)
        .def_readwrite("BeamDirectionName", &UFiringModeDefinition::BeamDirectionName)
        .def_readwrite("BeamChainDelay", &UFiringModeDefinition::BeamChainDelay)
        .def_readwrite("BeamChainNum", &UFiringModeDefinition::BeamChainNum)
        .def_readwrite("BeamChainMaxDistance", &UFiringModeDefinition::BeamChainMaxDistance)
        .def_readwrite("BeamRandomBoneTimeMin", &UFiringModeDefinition::BeamRandomBoneTimeMin)
        .def_readwrite("BeamRandomBoneTimeMax", &UFiringModeDefinition::BeamRandomBoneTimeMax)
        .def_readwrite("SoundDefinition", &UFiringModeDefinition::SoundDefinition)
        .def_readwrite("FiringPatternLines", &UFiringModeDefinition::FiringPatternLines)
        .def_readwrite("BasePatternSpread", &UFiringModeDefinition::BasePatternSpread)
        .def_readwrite("MinPatternScale", &UFiringModeDefinition::MinPatternScale)
        .def("StaticClass", &UFiringModeDefinition::StaticClass, py::return_value_policy::reference)
        .def("GetParticleSystemTemplate", &UFiringModeDefinition::GetParticleSystemTemplate, py::return_value_policy::reference)
        .def("NotifyFiringPatternWhenShotComplete", &UFiringModeDefinition::NotifyFiringPatternWhenShotComplete)
        .def("GetFiringPatternAdjustments", &UFiringModeDefinition::GetFiringPatternAdjustments)
        .def("RunBehaviorsForImpact", &UFiringModeDefinition::RunBehaviorsForImpact)
        .def("GetImpactResponseIndex", &UFiringModeDefinition::GetImpactResponseIndex)
          ;
}