#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_USVehicleWheel(py::object m)
{
    py::class_< USVehicleWheel,  UComponent   >(m, "USVehicleWheel")
        .def_readwrite("Steer", &USVehicleWheel::Steer)
        .def_readwrite("MotorTorque", &USVehicleWheel::MotorTorque)
        .def_readwrite("BrakeTorque", &USVehicleWheel::BrakeTorque)
        .def_readwrite("ChassisTorque", &USVehicleWheel::ChassisTorque)
        .def_readwrite("SteerFactor", &USVehicleWheel::SteerFactor)
        .def_readwrite("SkelControlName", &USVehicleWheel::SkelControlName)
        .def_readwrite("WheelControl", &USVehicleWheel::WheelControl)
        .def_readwrite("BoneName", &USVehicleWheel::BoneName)
        .def_readwrite("BoneOffset", &USVehicleWheel::BoneOffset)
        .def_readwrite("WheelRadius", &USVehicleWheel::WheelRadius)
        .def_readwrite("SuspensionTravel", &USVehicleWheel::SuspensionTravel)
        .def_readwrite("SuspensionSpeed", &USVehicleWheel::SuspensionSpeed)
        .def_readwrite("WheelParticleSystem", &USVehicleWheel::WheelParticleSystem)
        .def_readwrite("Side", &USVehicleWheel::Side)
        .def_readwrite("LongSlipFactor", &USVehicleWheel::LongSlipFactor)
        .def_readwrite("LatSlipFactor", &USVehicleWheel::LatSlipFactor)
        .def_readwrite("HandbrakeLongSlipFactor", &USVehicleWheel::HandbrakeLongSlipFactor)
        .def_readwrite("HandbrakeLatSlipFactor", &USVehicleWheel::HandbrakeLatSlipFactor)
        .def_readwrite("ParkedSlipFactorLat", &USVehicleWheel::ParkedSlipFactorLat)
        .def_readwrite("ParkedSlipFactorLong", &USVehicleWheel::ParkedSlipFactorLong)
        .def_readwrite("WheelPosition", &USVehicleWheel::WheelPosition)
        .def_readwrite("SpinVel", &USVehicleWheel::SpinVel)
        .def_readwrite("LongSlipRatio", &USVehicleWheel::LongSlipRatio)
        .def_readwrite("LatSlipAngle", &USVehicleWheel::LatSlipAngle)
        .def_readwrite("ContactNormal", &USVehicleWheel::ContactNormal)
        .def_readwrite("LongDirection", &USVehicleWheel::LongDirection)
        .def_readwrite("LatDirection", &USVehicleWheel::LatDirection)
        .def_readwrite("ContactForce", &USVehicleWheel::ContactForce)
        .def_readwrite("LongImpulse", &USVehicleWheel::LongImpulse)
        .def_readwrite("LatImpulse", &USVehicleWheel::LatImpulse)
        .def_readwrite("ContactPhysMat", &USVehicleWheel::ContactPhysMat)
        .def_readwrite("WaterContactZOffset", &USVehicleWheel::WaterContactZOffset)
        .def_readwrite("DesiredSuspensionPosition", &USVehicleWheel::DesiredSuspensionPosition)
        .def_readwrite("SuspensionPosition", &USVehicleWheel::SuspensionPosition)
        .def_readwrite("CurrentRotation", &USVehicleWheel::CurrentRotation)
        .def_readwrite("WheelShape", &USVehicleWheel::WheelShape)
        .def_readwrite("WheelMaterialIndex", &USVehicleWheel::WheelMaterialIndex)
        .def_readwrite("WheelPSCClass", &USVehicleWheel::WheelPSCClass)
        .def_readwrite("WheelParticleComp", &USVehicleWheel::WheelParticleComp)
        .def_readwrite("SlipParticleParamName", &USVehicleWheel::SlipParticleParamName)
        .def("StaticClass", &USVehicleWheel::StaticClass, py::return_value_policy::reference)
          ;
}