#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UAIDebugCamera(py::module &m)
{
    py::class_< UAIDebugCamera,  UObject   >(m, "UAIDebugCamera")
		.def_static("StaticClass", &UAIDebugCamera::StaticClass, py::return_value_policy::reference)
        .def_readwrite("Mind", &UAIDebugCamera::Mind)
        .def_readwrite("RuleEngine", &UAIDebugCamera::RuleEngine)
        .def_readwrite("DisplayList", &UAIDebugCamera::DisplayList)
        .def_readwrite("SnapshotNdx", &UAIDebugCamera::SnapshotNdx)
        .def_readwrite("CurSnapshot", &UAIDebugCamera::CurSnapshot)
        .def_readwrite("PopUpGraphTop", &UAIDebugCamera::PopUpGraphTop)
        .def_readwrite("PopUpGraphCenter", &UAIDebugCamera::PopUpGraphCenter)
        .def_readwrite("CurrentInspectedTargetName", &UAIDebugCamera::CurrentInspectedTargetName)
        .def_readwrite("TopBarGraphStartXPct", &UAIDebugCamera::TopBarGraphStartXPct)
        .def_readwrite("TopBarGraphStartYPct", &UAIDebugCamera::TopBarGraphStartYPct)
        .def_readwrite("CenterBarGraphStartXPct", &UAIDebugCamera::CenterBarGraphStartXPct)
        .def_readwrite("CenterBarGraphStartYPct", &UAIDebugCamera::CenterBarGraphStartYPct)
        .def_readwrite("Column2XOffset", &UAIDebugCamera::Column2XOffset)
        .def_readwrite("Column1LastY", &UAIDebugCamera::Column1LastY)
        .def_readwrite("Column2LastY", &UAIDebugCamera::Column2LastY)
        .def_readwrite("LastColumnDrawnTo", &UAIDebugCamera::LastColumnDrawnTo)
        .def("ToggleAITree", &UAIDebugCamera::ToggleAITree)
        .def("ToggleTargetViewCones", &UAIDebugCamera::ToggleTargetViewCones)
        .def("ToggleAwarenessZones", &UAIDebugCamera::ToggleAwarenessZones)
        .def("ToggleRuleEngineLoadBalance", &UAIDebugCamera::ToggleRuleEngineLoadBalance)
        .def("ToggleCombat", &UAIDebugCamera::ToggleCombat)
        .def("ToggleShowTimers", &UAIDebugCamera::ToggleShowTimers)
        .def("ToggleResources", &UAIDebugCamera::ToggleResources)
        .def("ToggleInactiveRules", &UAIDebugCamera::ToggleInactiveRules)
        .def("ToggleRules", &UAIDebugCamera::ToggleRules)
        .def("ToggleFlags", &UAIDebugCamera::ToggleFlags)
        .def("GetTracker", &UAIDebugCamera::GetTracker, py::return_value_policy::reference)
        .def("SetMind", &UAIDebugCamera::SetMind)
        .def("InitDummies", &UAIDebugCamera::InitDummies)
        .def("WantsToDoCameraInspection", &UAIDebugCamera::WantsToDoCameraInspection)
        .def("SetCurrentInspectedTarget", &UAIDebugCamera::SetCurrentInspectedTarget)
        .def("CompareRuleSetAndAdjustRuleIdx", &UAIDebugCamera::CompareRuleSetAndAdjustRuleIdx)
        .def("SetRuleEngine", &UAIDebugCamera::SetRuleEngine)
        .def("SetPrevSnapshotRule", &UAIDebugCamera::SetPrevSnapshotRule)
        .def("SetNextSnapshotRule", &UAIDebugCamera::SetNextSnapshotRule)
        .def("SetPrevSnapshot", &UAIDebugCamera::SetPrevSnapshot)
        .def("SetNextSnapshot", &UAIDebugCamera::SetNextSnapshot)
        .def("NotifyGameUnPaused", &UAIDebugCamera::NotifyGameUnPaused)
        .def("NotifyGamePaused", &UAIDebugCamera::NotifyGamePaused)
        .def("Display", &UAIDebugCamera::Display)
          ;
}