#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_ACamera(py::object m)
{
    py::class_< ACamera,  AActor   >(m, "ACamera")
        .def_readwrite("PCOwner", &ACamera::PCOwner)
        .def_readwrite("CameraStyle", &ACamera::CameraStyle)
        .def_readwrite("DefaultFOV", &ACamera::DefaultFOV)
        .def_readwrite("LockedFOV", &ACamera::LockedFOV)
        .def_readwrite("ConstrainedAspectRatio", &ACamera::ConstrainedAspectRatio)
        .def_readwrite("DefaultAspectRatio", &ACamera::DefaultAspectRatio)
        .def_readwrite("OffAxisYawAngle", &ACamera::OffAxisYawAngle)
        .def_readwrite("OffAxisPitchAngle", &ACamera::OffAxisPitchAngle)
        .def_readwrite("FadeColor", &ACamera::FadeColor)
        .def_readwrite("FadeAmount", &ACamera::FadeAmount)
        .def_readwrite("CamOverridePostProcessAlpha", &ACamera::CamOverridePostProcessAlpha)
        .def_readwrite("CamPostProcessSettings", &ACamera::CamPostProcessSettings)
        .def_readwrite("RenderingOverrides", &ACamera::RenderingOverrides)
        .def_readwrite("ColorScale", &ACamera::ColorScale)
        .def_readwrite("DesiredColorScale", &ACamera::DesiredColorScale)
        .def_readwrite("OriginalColorScale", &ACamera::OriginalColorScale)
        .def_readwrite("ColorScaleInterpDuration", &ACamera::ColorScaleInterpDuration)
        .def_readwrite("ColorScaleInterpStartTime", &ACamera::ColorScaleInterpStartTime)
        .def_readwrite("CameraCache", &ACamera::CameraCache)
        .def_readwrite("LastFrameCameraCache", &ACamera::LastFrameCameraCache)
        .def_readwrite("ViewTarget", &ACamera::ViewTarget)
        .def_readwrite("PendingViewTarget", &ACamera::PendingViewTarget)
        .def_readwrite("BlendTimeToGo", &ACamera::BlendTimeToGo)
        .def_readwrite("BlendParams", &ACamera::BlendParams)
        .def_readwrite("ModifierList", &ACamera::ModifierList)
        .def_readwrite("FreeCamDistance", &ACamera::FreeCamDistance)
        .def_readwrite("FreeCamOffset", &ACamera::FreeCamOffset)
        .def_readwrite("FadeAlpha", &ACamera::FadeAlpha)
        .def_readwrite("FadeTime", &ACamera::FadeTime)
        .def_readwrite("FadeTimeRemaining", &ACamera::FadeTimeRemaining)
        .def_readwrite("CameraLensEffects", &ACamera::CameraLensEffects)
        .def_readwrite("CameraShakeCamMod", &ACamera::CameraShakeCamMod)
        .def_readwrite("CameraShakeCamModClass", &ACamera::CameraShakeCamModClass)
		.def_property_readonly("AnimInstPool", &ACamera::AnimInstPool)
        .def_readwrite("ActiveAnims", &ACamera::ActiveAnims)
        .def_readwrite("FreeAnims", &ACamera::FreeAnims)
        .def_readwrite("AnimCameraActor", &ACamera::AnimCameraActor)
        .def("StaticClass", &ACamera::StaticClass, py::return_value_policy::reference)
        .def("StopCameraAnim", &ACamera::StopCameraAnim)
        .def("StopAllCameraAnimsByType", &ACamera::StopAllCameraAnimsByType)
        .def("StopAllCameraAnims", &ACamera::StopAllCameraAnims)
        .def("PlayCameraAnim", &ACamera::PlayCameraAnim, py::return_value_policy::reference)
        .def("ClearAllCameraShakes", &ACamera::ClearAllCameraShakes)
        .def("PlayWorldCameraShake", &ACamera::PlayWorldCameraShake)
        .def("CalcRadialShakeScale", &ACamera::CalcRadialShakeScale)
        .def("StopCameraShake", &ACamera::StopCameraShake)
        .def("PlayCameraShake", &ACamera::PlayCameraShake)
        .def("ClearCameraLensEffects", &ACamera::ClearCameraLensEffects)
        .def("RemoveCameraLensEffect", &ACamera::RemoveCameraLensEffect)
        .def("AddCameraLensEffect", &ACamera::AddCameraLensEffect)
        .def("FindCameraLensEffect", &ACamera::FindCameraLensEffect, py::return_value_policy::reference)
        .def("ProcessViewRotation", &ACamera::ProcessViewRotation)
        .def("SetViewTarget", &ACamera::SetViewTarget)
        .def("UpdateViewTarget", &ACamera::UpdateViewTarget)
        .def("CheckViewTarget", &ACamera::CheckViewTarget)
        .def("FillCameraCache", &ACamera::FillCameraCache)
        .def("BlendViewTargets", &ACamera::BlendViewTargets)
        .def("DoUpdateCamera", &ACamera::DoUpdateCamera)
        .def("eventUpdateCamera", &ACamera::eventUpdateCamera)
        .def("SetDesiredColorScale", &ACamera::SetDesiredColorScale)
        .def("GetCameraRotation", &ACamera::GetCameraRotation)
        .def("GetCameraViewPoint", &ACamera::GetCameraViewPoint)
        .def("SetFOV", &ACamera::SetFOV)
        .def("GetFOVAngle", &ACamera::GetFOVAngle)
        .def("InitializeFor", &ACamera::InitializeFor)
        .def("ApplyCameraModifiers", &ACamera::ApplyCameraModifiers)
        .def("eventDestroyed", &ACamera::eventDestroyed)
        .def("PostBeginPlay", &ACamera::PostBeginPlay)
        .def("CreateCameraModifier", &ACamera::CreateCameraModifier, py::return_value_policy::reference)
          ;
}