#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UGearboxGlobals()
{
    class_< UGearboxGlobals, bases< UGearboxEngineGlobals >  , boost::noncopyable>("UGearboxGlobals", no_init)
        .def_readwrite("TheGlobalsDefinition", &UGearboxGlobals::TheGlobalsDefinition)
        .def_readwrite("ExposureUtilityClass", &UGearboxGlobals::ExposureUtilityClass)
        .def_readwrite("ExposureUtilityStrategyClass", &UGearboxGlobals::ExposureUtilityStrategyClass)
        .def_readwrite("TheExposureUtility", &UGearboxGlobals::TheExposureUtility)
        .def_readwrite("TheAIFactory", &UGearboxGlobals::TheAIFactory)
        .def_readwrite("TheRuleEngineLoadBalanceManager", &UGearboxGlobals::TheRuleEngineLoadBalanceManager)
        .def_readwrite("TheGBXActorList", &UGearboxGlobals::TheGBXActorList)
        .def_readwrite("TheGBXObjectList", &UGearboxGlobals::TheGBXObjectList)
        .def_readwrite("ValidNameList", &UGearboxGlobals::ValidNameList)
        .def_readwrite("TheWireMgr", &UGearboxGlobals::TheWireMgr)
        .def_readwrite("TheMessageManager", &UGearboxGlobals::TheMessageManager)
        .def_readwrite("TheDynamicTextureActorList", &UGearboxGlobals::TheDynamicTextureActorList)
        .def_readwrite("ThePopulationMaster", &UGearboxGlobals::ThePopulationMaster)
        .def_readwrite("TheBehaviorKernel", &UGearboxGlobals::TheBehaviorKernel)
        .def_readwrite("TheScreenSpaceManager", &UGearboxGlobals::TheScreenSpaceManager)
        .def_readwrite("TheGFxManager", &UGearboxGlobals::TheGFxManager)
        .def_readwrite("TheRenderTextureManager", &UGearboxGlobals::TheRenderTextureManager)
        .def_readwrite("GlobalInstanceClassName", &UGearboxGlobals::GlobalInstanceClassName)
        .def_readwrite("DefaultMaxPopulationActorCost", &UGearboxGlobals::DefaultMaxPopulationActorCost)
        .def_readwrite("StateRecords", &UGearboxGlobals::StateRecords)
        .def_readwrite("UIAudioComponent", &UGearboxGlobals::UIAudioComponent)
        .def_readwrite("TheDialogManager", &UGearboxGlobals::TheDialogManager)
        .def("StaticClass", &UGearboxGlobals::StaticClass, return_value_policy< reference_existing_object >())
        .def("GetBehaviorKernel", &UGearboxGlobals::GetBehaviorKernel, return_value_policy< reference_existing_object >())
        .def("GetDialogManager", &UGearboxGlobals::GetDialogManager, return_value_policy< reference_existing_object >())
        .def("GetPopulationRespawnDelay", &UGearboxGlobals::GetPopulationRespawnDelay)
        .def("eventShowDialog", &UGearboxGlobals::eventShowDialog, return_value_policy< reference_existing_object >())
        .def("NotifyActorDied", &UGearboxGlobals::NotifyActorDied)
        .def("DoesLOSIntersectSpecialOccluder", &UGearboxGlobals::DoesLOSIntersectSpecialOccluder)
        .def("HasPhysXCapableGPU", &UGearboxGlobals::HasPhysXCapableGPU)
        .def("GetPlatform", &UGearboxGlobals::GetPlatform)
        .def("ValidatePlayerName", &UGearboxGlobals::ValidatePlayerName)
        .def("RegisterStateKey", &UGearboxGlobals::RegisterStateKey)
        .def("DoesStateKeyExist", &UGearboxGlobals::DoesStateKeyExist)
        .def("FreeTexture2D", &UGearboxGlobals::FreeTexture2D)
        .def("GetTexture2D", &UGearboxGlobals::GetTexture2D, return_value_policy< reference_existing_object >())
        .def("GetRenderTextureManager", &UGearboxGlobals::GetRenderTextureManager, return_value_policy< reference_existing_object >())
        .def("GetGFxManager", &UGearboxGlobals::GetGFxManager, return_value_policy< reference_existing_object >())
        .def("GetScreenSpaceManager", &UGearboxGlobals::GetScreenSpaceManager, return_value_policy< reference_existing_object >())
        .def("GetMessageManager", &UGearboxGlobals::GetMessageManager, return_value_policy< reference_existing_object >())
        .def("RegDynamicTextureStreaming", &UGearboxGlobals::RegDynamicTextureStreaming)
        .def("GetDynamicTextureActorList", &UGearboxGlobals::GetDynamicTextureActorList, return_value_policy< reference_existing_object >())
        .def("GetPopulationMaster", &UGearboxGlobals::GetPopulationMaster, return_value_policy< reference_existing_object >())
        .def("GetWireManager", &UGearboxGlobals::GetWireManager, return_value_policy< reference_existing_object >())
        .def("GetGBXObjectList", &UGearboxGlobals::GetGBXObjectList, return_value_policy< reference_existing_object >())
        .def("GetGBXActorList", &UGearboxGlobals::GetGBXActorList, return_value_policy< reference_existing_object >())
        .def("GetRuleEngineLoadBalanceManager", &UGearboxGlobals::GetRuleEngineLoadBalanceManager, return_value_policy< reference_existing_object >())
        .def("GetGearboxAIFactory", &UGearboxGlobals::GetGearboxAIFactory, return_value_policy< reference_existing_object >())
        .def("GetExposureUtility", &UGearboxGlobals::GetExposureUtility, return_value_policy< reference_existing_object >())
        .def("GetGearboxGlobals", &UGearboxGlobals::GetGearboxGlobals, return_value_policy< reference_existing_object >())
        .staticmethod("StaticClass")
  ;
}