#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_APopulationOpportunityDen(py::module &m)
{
    py::class_< APopulationOpportunityDen,  APopulationOpportunity   >(m, "APopulationOpportunityDen")
        .def_readwrite("VfTable_IIAIInterface", &APopulationOpportunityDen::VfTable_IIAIInterface)
        .def_readwrite("MaxActiveActorsIsNormal", &APopulationOpportunityDen::MaxActiveActorsIsNormal)
        .def_readwrite("MaxActiveActorsThreatened", &APopulationOpportunityDen::MaxActiveActorsThreatened)
        .def_readwrite("MaxTotalActorsFormula", &APopulationOpportunityDen::MaxTotalActorsFormula)
        .def_readwrite("ParentEncounter", &APopulationOpportunityDen::ParentEncounter)
        .def_readwrite("ParentEncounterWave", &APopulationOpportunityDen::ParentEncounterWave)
        .def_readwrite("PopulationDef", &APopulationOpportunityDen::PopulationDef)
        .def_readwrite("RespawnDelay", &APopulationOpportunityDen::RespawnDelay)
        .def_readwrite("DetectionVolumes", &APopulationOpportunityDen::DetectionVolumes)
        .def_readwrite("DenHeight", &APopulationOpportunityDen::DenHeight)
        .def_readwrite("SpawnRadius", &APopulationOpportunityDen::SpawnRadius)
        .def_readwrite("PatrolRadius", &APopulationOpportunityDen::PatrolRadius)
        .def_readwrite("ThreatRadius", &APopulationOpportunityDen::ThreatRadius)
        .def_readwrite("SharedThreatDens", &APopulationOpportunityDen::SharedThreatDens)
        .def_readwrite("OverrideAllegiance", &APopulationOpportunityDen::OverrideAllegiance)
        .def_readwrite("CombatVolume", &APopulationOpportunityDen::CombatVolume)
        .def_readwrite("MaxTotalActors", &APopulationOpportunityDen::MaxTotalActors)
        .def_readwrite("Allegiance", &APopulationOpportunityDen::Allegiance)
        .def_readwrite("SpawnedDenMembers", &APopulationOpportunityDen::SpawnedDenMembers)
        .def_readwrite("SpawnData", &APopulationOpportunityDen::SpawnData)
        .def_readwrite("Leader", &APopulationOpportunityDen::Leader)
        .def_readwrite("Perches", &APopulationOpportunityDen::Perches)
        .def_readwrite("CurrentRallyPoint", &APopulationOpportunityDen::CurrentRallyPoint)
        .def_readwrite("RallyPoints", &APopulationOpportunityDen::RallyPoints)
        .def_readwrite("Flag_ShouldRally", &APopulationOpportunityDen::Flag_ShouldRally)
        .def_readwrite("AIComponent", &APopulationOpportunityDen::AIComponent)
        .def_readwrite("TrackedStat", &APopulationOpportunityDen::TrackedStat)
        .def_readwrite("StatValue", &APopulationOpportunityDen::StatValue)
        .def("StaticClass", &APopulationOpportunityDen::StaticClass, py::return_value_policy::reference)
        .def("ApplyPreviewBodyComposition", &APopulationOpportunityDen::ApplyPreviewBodyComposition)
        .def("GetBodyInfoProvider", &APopulationOpportunityDen::GetBodyInfoProvider, py::return_value_policy::reference)
        .def("OnAIAbortMoveToActor", &APopulationOpportunityDen::OnAIAbortMoveToActor)
        .def("OnAICombatVolume", &APopulationOpportunityDen::OnAICombatVolume)
        .def("OnAIScripted", &APopulationOpportunityDen::OnAIScripted)
        .def("OnAIScriptedAnim", &APopulationOpportunityDen::OnAIScriptedAnim)
        .def("OnAIScriptedDeath", &APopulationOpportunityDen::OnAIScriptedDeath)
        .def("OnAIScriptedFollow", &APopulationOpportunityDen::OnAIScriptedFollow)
        .def("OnAIScriptedHold", &APopulationOpportunityDen::OnAIScriptedHold)
        .def("OnAISetItemTossTarget", &APopulationOpportunityDen::OnAISetItemTossTarget)
        .def("OnAIProvoke", &APopulationOpportunityDen::OnAIProvoke)
        .def("RemoveStat", &APopulationOpportunityDen::RemoveStat)
        .def("AddStat", &APopulationOpportunityDen::AddStat)
        .def("InitSequence", &APopulationOpportunityDen::InitSequence)
        .def("GetAIDefinition", &APopulationOpportunityDen::GetAIDefinition, py::return_value_policy::reference)
        .def("GetAIComponent", &APopulationOpportunityDen::GetAIComponent, py::return_value_policy::reference)
        .def("GetAIParent", &APopulationOpportunityDen::GetAIParent, py::return_value_policy::reference)
        .def("GetAILocation", &APopulationOpportunityDen::GetAILocation)
        .def("GetAIActor", &APopulationOpportunityDen::GetAIActor, py::return_value_policy::reference)
        .def("CanTickAI", &APopulationOpportunityDen::CanTickAI)
        .def("TriggerProvokedEvents", &APopulationOpportunityDen::TriggerProvokedEvents)
        .def("SetAllegiance", &APopulationOpportunityDen::SetAllegiance)
        .def("GetAllegiance", &APopulationOpportunityDen::GetAllegiance, py::return_value_policy::reference)
        .def("GetDenMembers", &APopulationOpportunityDen::GetDenMembers)
        .def("eventTriggerKismetDeathEvent", &APopulationOpportunityDen::eventTriggerKismetDeathEvent)
        .def("SpawnedCanAttackVehicles", &APopulationOpportunityDen::SpawnedCanAttackVehicles)
        .def("GetNumSpawned", &APopulationOpportunityDen::GetNumSpawned)
        .def("GetNumAlive", &APopulationOpportunityDen::GetNumAlive)
        .def("GetNumDied", &APopulationOpportunityDen::GetNumDied)
        .def("GetRallyPoint", &APopulationOpportunityDen::GetRallyPoint, py::return_value_policy::reference)
        .def("ChooseNewRallyPoint", &APopulationOpportunityDen::ChooseNewRallyPoint)
        .def("FindRallyPoints", &APopulationOpportunityDen::FindRallyPoints)
        .def("TryToAddPerch", &APopulationOpportunityDen::TryToAddPerch)
        .def("FindPerches", &APopulationOpportunityDen::FindPerches)
        .def("EnableDebugging", &APopulationOpportunityDen::EnableDebugging)
        .def("RespawnKilledActors", &APopulationOpportunityDen::RespawnKilledActors)
        .def("DoSpawning", &APopulationOpportunityDen::DoSpawning)
        .def("PostBeginPlay", &APopulationOpportunityDen::PostBeginPlay)
          ;
}