#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UItemPickupGFxMovie(py::object m)
{
    py::class_< UItemPickupGFxMovie,  UGearboxGFxMovie   >(m, "UItemPickupGFxMovie")
        .def_readwrite("MatSrc", &UItemPickupGFxMovie::MatSrc)
        .def_readwrite("Particle", &UItemPickupGFxMovie::Particle)
        .def_readwrite("ParticleMatParamName", &UItemPickupGFxMovie::ParticleMatParamName)
        .def_readwrite("MatTexParamName", &UItemPickupGFxMovie::MatTexParamName)
        .def_readwrite("TallItemZOffsetPercentage", &UItemPickupGFxMovie::TallItemZOffsetPercentage)
        .def_readwrite("MyHUDOwner", &UItemPickupGFxMovie::MyHUDOwner)
        .def_readwrite("MyPSC", &UItemPickupGFxMovie::MyPSC)
        .def_readwrite("MyMati", &UItemPickupGFxMovie::MyMati)
        .def_readwrite("MyRenderTexture", &UItemPickupGFxMovie::MyRenderTexture)
        .def_readwrite("PickupTex", &UItemPickupGFxMovie::PickupTex)
        .def_readwrite("PickupMesh", &UItemPickupGFxMovie::PickupMesh)
        .def_readwrite("CompareAgainstThing", &UItemPickupGFxMovie::CompareAgainstThing)
        .def_readwrite("SplitIndex", &UItemPickupGFxMovie::SplitIndex)
        .def_readwrite("WeapTexName", &UItemPickupGFxMovie::WeapTexName)
        .def_readwrite("ItemCardHeight", &UItemPickupGFxMovie::ItemCardHeight)
        .def_readwrite("DefaultRTTSize_PC", &UWillowGFxMovie::DefaultRTTSize_PC)
        .def_readwrite("DefaultRTTSize_Console", &UWillowGFxMovie::DefaultRTTSize_Console)
        .def_readwrite("WPCOwner", &UWillowGFxMovie::WPCOwner)
        .def("StaticClass", &UItemPickupGFxMovie::StaticClass, py::return_value_policy::reference)
        .def("InitFromDefinition", &UItemPickupGFxMovie::InitFromDefinition)
        .def("EnableThumbnail", &UItemPickupGFxMovie::EnableThumbnail)
        .def("extOnItemCardHeightCalculated", &UItemPickupGFxMovie::extOnItemCardHeightCalculated)
        .def("extReadyForInventoryInfo", &UItemPickupGFxMovie::extReadyForInventoryInfo)
        .def("UpdateCompareAgainstThing", &UItemPickupGFxMovie::UpdateCompareAgainstThing)
        .def("GetCompareAgainstThing", &UItemPickupGFxMovie::GetCompareAgainstThing, py::return_value_policy::reference)
        .def("Show", &UItemPickupGFxMovie::Show)
        .def("InitializeFrom", &UItemPickupGFxMovie::InitializeFrom)
        .def("CreateBackupRenderTarget", &UItemPickupGFxMovie::CreateBackupRenderTarget)
        .def("SetOnItemCardHeightCalculatedHandler", &UItemPickupGFxMovie::SetOnItemCardHeightCalculatedHandler)
        .def("eventOnClose", &UItemPickupGFxMovie::eventOnClose)
        .def("eventStart", &UItemPickupGFxMovie::eventStart)
        .def("OnItemCardHeightCalculatedHandler", &UItemPickupGFxMovie::OnItemCardHeightCalculatedHandler)
        .def("GetQuadrantForControllerId", &UWillowGFxMovie::GetQuadrantForControllerId)
        .def("extConditionalBeginSway", &UWillowGFxMovie::extConditionalBeginSway)
        .def("GetRecommendedRTTSizesFor", &UWillowGFxMovie::GetRecommendedRTTSizesFor)
        .def("GetRecommendedThumbnail", &UWillowGFxMovie::GetRecommendedThumbnail, py::return_value_policy::reference)
        .def("eventFreeGFxThumbnails", &UWillowGFxMovie::eventFreeGFxThumbnails)
        .def("eventFreeGFxThumbnail", &UWillowGFxMovie::eventFreeGFxThumbnail)
        .def("eventGetGFxThumbnail", &UWillowGFxMovie::eventGetGFxThumbnail, py::return_value_policy::reference)
        .def("ResolveMission", &UWillowGFxMovie::ResolveMission)
        .def("IsPresenceContextMatch", &UWillowGFxMovie::IsPresenceContextMatch)
        .def("GetFriendCharacterClassAndLevel", &UWillowGFxMovie::GetFriendCharacterClassAndLevel)
        .def("GetFriendLocation", &UWillowGFxMovie::GetFriendLocation)
        .def("GetInviteType", &UWillowGFxMovie::GetInviteType)
        .def("GetNetworkType", &UWillowGFxMovie::GetNetworkType)
        .def("GetCappedDisplayCurrencyAmount", &UWillowGFxMovie::GetCappedDisplayCurrencyAmount)
        .def("GFxColoredText", &UWillowGFxMovie::GFxColoredText)
        .def("ConditionalLoadGame", &UWillowGFxMovie::ConditionalLoadGame)
        .def("NotifyLoadGameStarted", &UWillowGFxMovie::NotifyLoadGameStarted)
        .def("DoDeviceSelection", &UWillowGFxMovie::DoDeviceSelection)
        .def("GetGameInterface", &UWillowGFxMovie::GetGameInterface, py::return_value_policy::reference)
        .def("ShowGamerCardUI", &UWillowGFxMovie::ShowGamerCardUI)
        .def("ShowLivePartyUI", &UWillowGFxMovie::ShowLivePartyUI)
        .def("ShowAchievementsUI", &UWillowGFxMovie::ShowAchievementsUI)
        .def("CheckControllerStatus", &UWillowGFxMovie::CheckControllerStatus)
        .def("FocusOn", &UWillowGFxMovie::FocusOn)
        .def("GetControllerId", &UWillowGFxMovie::GetControllerId)
        .def("GetInputPlayerIndex", &UWillowGFxMovie::GetInputPlayerIndex)
        .def("GetWillowOwner", &UWillowGFxMovie::GetWillowOwner, py::return_value_policy::reference)
        .def("Movie_IsPlaying", &UWillowGFxMovie::Movie_IsPlaying)
        .def("Movie_Stop", &UWillowGFxMovie::Movie_Stop)
        .def("Movie_Play", &UWillowGFxMovie::Movie_Play)
        .def("LocText", &UWillowGFxMovie::LocText)
        .def("GetFallbackLocSection", &UWillowGFxMovie::GetFallbackLocSection)
        .def("GetFallbackLocFile", &UWillowGFxMovie::GetFallbackLocFile)
        .def("LookupFallbackAkEventFromGlobalsDefinition", &UWillowGFxMovie::LookupFallbackAkEventFromGlobalsDefinition, py::return_value_policy::reference)
        .def("UpdateHUDVisibility", &UWillowGFxMovie::UpdateHUDVisibility)
        .def("CleanupDestroyedMovies", &UWillowGFxMovie::CleanupDestroyedMovies)
        .def("SingleArgInvokeSF", &UWillowGFxMovie::SingleArgInvokeSF)
          ;
}