#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UAnimTree(py::object m)
{
    py::class_< UAnimTree,  UObject   >(m, "UAnimTree")
        .def_readwrite("AnimTreeTemplate", &UAnimTree::AnimTreeTemplate)
        .def_readwrite("AnimGroups", &UAnimTree::AnimGroups)
        .def_readwrite("PrioritizedSkelBranches", &UAnimTree::PrioritizedSkelBranches)
        .def_readwrite("ComposePrePassBoneNames", &UAnimTree::ComposePrePassBoneNames)
        .def_readwrite("ComposePostPassBoneNames", &UAnimTree::ComposePostPassBoneNames)
        .def_readwrite("RootMorphNodes", &UAnimTree::RootMorphNodes)
        .def_readwrite("SkelControlLists", &UAnimTree::SkelControlLists)
        .def_readwrite("SavedPose", &UAnimTree::SavedPose)
        .def_readwrite("AnimTickArray", &UAnimTree::AnimTickArray)
        .def_readwrite("Children", &UAnimNodeBlendBase::Children)
        .def_readwrite("BlendType", &UAnimNodeBlendBase::BlendType)
        .def_readwrite("NodeTickTag", &UAnimNode::NodeTickTag)
        .def_readwrite("NodeInitTag", &UAnimNode::NodeInitTag)
        .def_readwrite("TickArrayIndex", &UAnimNode::TickArrayIndex)
        .def_readwrite("NodeCachedAtomsTag", &UAnimNode::NodeCachedAtomsTag)
        .def_readwrite("NodeTotalWeight", &UAnimNode::NodeTotalWeight)
        .def_readwrite("ParentNodes", &UAnimNode::ParentNodes)
        .def_readwrite("NodeName", &UAnimNode::NodeName)
        .def_readwrite("CachedBoneAtoms", &UAnimNode::CachedBoneAtoms)
        .def_readwrite("CachedNumDesiredBones", &UAnimNode::CachedNumDesiredBones)
        .def_readonly("UnknownData00", &UAnimNode::UnknownData00)
        .def_readwrite("CachedRootMotionDelta", &UAnimNode::CachedRootMotionDelta)
        .def_readwrite("bCachedHasRootMotion", &UAnimNode::bCachedHasRootMotion)
        .def_readwrite("CachedCurveKeys", &UAnimNode::CachedCurveKeys)
        .def_readwrite("SearchTag", &UAnimNode::SearchTag)
        .def_readwrite("SkelComponent", &UAnimObject::SkelComponent)
        .def("StaticClass", &UAnimTree::StaticClass, py::return_value_policy::reference)
        .def("GetGroupIndex", &UAnimTree::GetGroupIndex)
        .def("GetGroupRateScale", &UAnimTree::GetGroupRateScale)
        .def("SetGroupRateScale", &UAnimTree::SetGroupRateScale)
        .def("GetGroupRelativePosition", &UAnimTree::GetGroupRelativePosition)
        .def("ForceGroupRelativePosition", &UAnimTree::ForceGroupRelativePosition)
        .def("GetGroupNotifyMaster", &UAnimTree::GetGroupNotifyMaster, py::return_value_policy::reference)
        .def("GetGroupSynchMaster", &UAnimTree::GetGroupSynchMaster, py::return_value_policy::reference)
        .def("SetAnimGroupForNode", &UAnimTree::SetAnimGroupForNode)
        .def("SetUseSavedPose", &UAnimTree::SetUseSavedPose)
        .def("FindMorphNode", &UAnimTree::FindMorphNode, py::return_value_policy::reference)
        .def("FindSkelControl", &UAnimTree::FindSkelControl, py::return_value_policy::reference)
        .def("ReplayAnim", &UAnimNodeBlendBase::ReplayAnim)
        .def("StopAnim", &UAnimNodeBlendBase::StopAnim)
        .def("PlayAnim", &UAnimNodeBlendBase::PlayAnim)
        .def("FindAllAnimNodes", &UAnimNode::FindAllAnimNodes)
        .def("FindAnimNode", &UAnimNode::FindAnimNode, py::return_value_policy::reference)
        .def("eventOnCeaseRelevant", &UAnimNode::eventOnCeaseRelevant)
        .def("eventOnBecomeRelevant", &UAnimNode::eventOnBecomeRelevant)
        .def("eventOnInit", &UAnimNode::eventOnInit)
          ;
}