#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UCanvas()
{
    class_< UCanvas, bases< UObject >  , boost::noncopyable>("UCanvas", no_init)
        .def_readwrite("Font", &UCanvas::Font)
        .def_readwrite("OrgX", &UCanvas::OrgX)
        .def_readwrite("OrgY", &UCanvas::OrgY)
        .def_readwrite("ClipX", &UCanvas::ClipX)
        .def_readwrite("ClipY", &UCanvas::ClipY)
        .def_readwrite("CurX", &UCanvas::CurX)
        .def_readwrite("CurY", &UCanvas::CurY)
        .def_readwrite("CurZ", &UCanvas::CurZ)
        .def_readwrite("CurYL", &UCanvas::CurYL)
        .def_readwrite("DrawColor", &UCanvas::DrawColor)
        .def_readwrite("SizeX", &UCanvas::SizeX)
        .def_readwrite("SizeY", &UCanvas::SizeY)
        .def_readwrite("Canvas", &UCanvas::Canvas)
        .def_readwrite("SceneView", &UCanvas::SceneView)
        .def_readonly("UnknownData00", &UCanvas::UnknownData00)
        .def_readwrite("ColorModulate", &UCanvas::ColorModulate)
        .def_readwrite("DefaultTexture", &UCanvas::DefaultTexture)
        .def_readwrite("BGColor", &UCanvas::BGColor)
        .def("StaticClass", &UCanvas::StaticClass, return_value_policy< reference_existing_object >())
        .def("DrawDebugGraph", &UCanvas::DrawDebugGraph)
        .def("DrawTextWithBG", &UCanvas::DrawTextWithBG)
        .def("DrawTextureDoubleLine", &UCanvas::DrawTextureDoubleLine)
        .def("DrawTextureLine", &UCanvas::DrawTextureLine)
        .def("Draw2DLine", &UCanvas::Draw2DLine)
        .def("SetBGColor", &UCanvas::SetBGColor)
        .def("SetDrawColorStruct", &UCanvas::SetDrawColorStruct)
        .def("SetDrawColor", &UCanvas::SetDrawColor)
        .def("DrawBox", &UCanvas::DrawBox)
        .def("DrawRect", &UCanvas::DrawRect)
        .def("DrawIcon", &UCanvas::DrawIcon)
        .def("DrawScaledIcon", &UCanvas::DrawScaledIcon)
        .def("MakeIcon", &UCanvas::MakeIcon)
        .def("DrawTextureBlended", &UCanvas::DrawTextureBlended)
        .def("DrawTexture", &UCanvas::DrawTexture)
        .def("SetClip", &UCanvas::SetClip)
        .def("SetOrigin", &UCanvas::SetOrigin)
        .def("SetPos", &UCanvas::SetPos)
        .def("GetDefaultCanvasFont", &UCanvas::GetDefaultCanvasFont, return_value_policy< reference_existing_object >())
        .def("eventReset", &UCanvas::eventReset)
        .def("PopTransform", &UCanvas::PopTransform)
        .def("PushTranslationMatrix", &UCanvas::PushTranslationMatrix)
        .def("DeProject", &UCanvas::DeProject)
        .def("Project", &UCanvas::Project)
        .def("DrawTextClipped", &UCanvas::DrawTextClipped)
        .def("DrawText", &UCanvas::DrawText)
        .def("TextSize", &UCanvas::TextSize)
        .def("StrLen", &UCanvas::StrLen)
        .def("CreateFontRenderInfo", &UCanvas::CreateFontRenderInfo)
        .def("DrawTris", &UCanvas::DrawTris)
        .def("DrawTileStretched", &UCanvas::DrawTileStretched)
        .def("DrawRotatedMaterialTile", &UCanvas::DrawRotatedMaterialTile)
        .def("DrawRotatedTile", &UCanvas::DrawRotatedTile)
        .def("DrawMaterialTile", &UCanvas::DrawMaterialTile)
        .def("PreOptimizeDrawTiles", &UCanvas::PreOptimizeDrawTiles)
        .def("DrawTile", &UCanvas::DrawTile)
        .staticmethod("StaticClass")
  ;
}