#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UOnlinePlayerStorage()
{
    py::class_< UOnlinePlayerStorage,  UObject   >("UOnlinePlayerStorage")
        .def_readwrite("VersionNumber", &UOnlinePlayerStorage::VersionNumber)
        .def_readwrite("VersionSettingsId", &UOnlinePlayerStorage::VersionSettingsId)
        .def_readwrite("SaveCountSettingId", &UOnlinePlayerStorage::SaveCountSettingId)
        .def_readwrite("ProfileSettings", &UOnlinePlayerStorage::ProfileSettings)
        .def_readwrite("ProfileMappings", &UOnlinePlayerStorage::ProfileMappings)
        .def_readwrite("AsyncState", &UOnlinePlayerStorage::AsyncState)
        .def_readwrite("DeviceID", &UOnlinePlayerStorage::DeviceID)
        .def("StaticClass", &UOnlinePlayerStorage::StaticClass, py::return_value_policy::reference)
        .def("SetDefaultVersionNumber", &UOnlinePlayerStorage::SetDefaultVersionNumber)
        .def("GetVersionNumber", &UOnlinePlayerStorage::GetVersionNumber)
        .def("AppendVersionToSettings", &UOnlinePlayerStorage::AppendVersionToSettings)
        .def("eventSetToDefaults", &UOnlinePlayerStorage::eventSetToDefaults)
        .def("AddSettingFloat", &UOnlinePlayerStorage::AddSettingFloat)
        .def("AddSettingInt", &UOnlinePlayerStorage::AddSettingInt)
        .def("GetRangedProfileSettingValue", &UOnlinePlayerStorage::GetRangedProfileSettingValue)
        .def("SetRangedProfileSettingValue", &UOnlinePlayerStorage::SetRangedProfileSettingValue)
        .def("GetProfileSettingRange", &UOnlinePlayerStorage::GetProfileSettingRange)
        .def("GetProfileSettingMappingIds", &UOnlinePlayerStorage::GetProfileSettingMappingIds)
        .def("GetProfileSettingMappingType", &UOnlinePlayerStorage::GetProfileSettingMappingType)
        .def("GetProfileSettingValueBlob", &UOnlinePlayerStorage::GetProfileSettingValueBlob)
        .def("SetProfileSettingValueBlob", &UOnlinePlayerStorage::SetProfileSettingValueBlob)
        .def("SetProfileSettingValueFloat", &UOnlinePlayerStorage::SetProfileSettingValueFloat)
        .def("SetProfileSettingValueInt", &UOnlinePlayerStorage::SetProfileSettingValueInt)
        .def("SetProfileSettingValueId", &UOnlinePlayerStorage::SetProfileSettingValueId)
        .def("SetProfileSettingValue", &UOnlinePlayerStorage::SetProfileSettingValue)
        .def("SetProfileSettingValueByName", &UOnlinePlayerStorage::SetProfileSettingValueByName)
        .def("GetProfileSettingValueFloat", &UOnlinePlayerStorage::GetProfileSettingValueFloat)
        .def("GetProfileSettingValueInt", &UOnlinePlayerStorage::GetProfileSettingValueInt)
        .def("GetProfileSettingValueFromListIndex", &UOnlinePlayerStorage::GetProfileSettingValueFromListIndex)
        .def("GetProfileSettingValueId", &UOnlinePlayerStorage::GetProfileSettingValueId)
        .def("GetProfileSettingValueByName", &UOnlinePlayerStorage::GetProfileSettingValueByName)
        .def("GetProfileSettingValues", &UOnlinePlayerStorage::GetProfileSettingValues)
        .def("GetProfileSettingValueName", &UOnlinePlayerStorage::GetProfileSettingValueName)
        .def("GetProfileSettingValue", &UOnlinePlayerStorage::GetProfileSettingValue)
        .def("IsProfileSettingIdMapped", &UOnlinePlayerStorage::IsProfileSettingIdMapped)
        .def("FindDefaultProfileMappingIndexByName", &UOnlinePlayerStorage::FindDefaultProfileMappingIndexByName)
        .def("FindProfileMappingIndexByName", &UOnlinePlayerStorage::FindProfileMappingIndexByName)
        .def("FindProfileMappingIndex", &UOnlinePlayerStorage::FindProfileMappingIndex)
        .def("FindProfileSettingIndex", &UOnlinePlayerStorage::FindProfileSettingIndex)
        .def("GetProfileSettingColumnHeader", &UOnlinePlayerStorage::GetProfileSettingColumnHeader)
        .def("GetProfileSettingName", &UOnlinePlayerStorage::GetProfileSettingName)
        .def("GetProfileSettingId", &UOnlinePlayerStorage::GetProfileSettingId)
        .staticmethod("StaticClass")
  ;
}