#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UBehaviorKernel()
{
    class_< UBehaviorKernel, bases< UObject >  , boost::noncopyable>("UBehaviorKernel", no_init)
        .def_readwrite("Processes", &UBehaviorKernel::Processes)
        .def_readwrite("ProcessDeathList", &UBehaviorKernel::ProcessDeathList)
        .def_readwrite("WaitingThreads", &UBehaviorKernel::WaitingThreads)
        .def_readwrite("Providers", &UBehaviorKernel::Providers)
        .def_readwrite("ProvidersIndexFreeList", &UBehaviorKernel::ProvidersIndexFreeList)
        .def_readwrite("ProvidersPendingRemoval", &UBehaviorKernel::ProvidersPendingRemoval)
        .def_readwrite("ObjectVariables", &UBehaviorKernel::ObjectVariables)
        .def_readwrite("ObjectVariablesIndexFreeList", &UBehaviorKernel::ObjectVariablesIndexFreeList)
        .def_readwrite("DynamicBehaviors", &UBehaviorKernel::DynamicBehaviors)
        .def_readwrite("DynamicBehaviorsIndexFreeList", &UBehaviorKernel::DynamicBehaviorsIndexFreeList)
        .def_readwrite("ProvidersListReserveLength", &UBehaviorKernel::ProvidersListReserveLength)
        .def_readwrite("ObjectVariablesListReserveLength", &UBehaviorKernel::ObjectVariablesListReserveLength)
        .def_readwrite("DynamicBehaviorsListReserveLength", &UBehaviorKernel::DynamicBehaviorsListReserveLength)
        .def_readwrite("WatchedPID", &UBehaviorKernel::WatchedPID)
        .def_readwrite("RecentlyRunBehaviors", &UBehaviorKernel::RecentlyRunBehaviors)
        .def_readwrite("CurrentDebugPage", &UBehaviorKernel::CurrentDebugPage)
        .def_readwrite("DebugPages", &UBehaviorKernel::DebugPages)
        .def_readwrite("EventFilterObjects", &UBehaviorKernel::EventFilterObjects)
        .def("StaticClass", &UBehaviorKernel::StaticClass, return_value_policy< reference_existing_object >())
        .def("RecentlyRunBehaviorsForSequence", &UBehaviorKernel::RecentlyRunBehaviorsForSequence)
        .def("AllEventStateForSequence", &UBehaviorKernel::AllEventStateForSequence)
        .def("AllWaitingThreadsForSequence", &UBehaviorKernel::AllWaitingThreadsForSequence)
        .def("AllSequencesForProvider", &UBehaviorKernel::AllSequencesForProvider)
        .def("AllProvidersForProcess", &UBehaviorKernel::AllProvidersForProcess)
        .def("AllProcesses", &UBehaviorKernel::AllProcesses)
        .def("GetVariableStateSummaryForSequence", &UBehaviorKernel::GetVariableStateSummaryForSequence)
        .def("GetChunkedListSummaries", &UBehaviorKernel::GetChunkedListSummaries)
        .def("GetBehaviorKernelStats", &UBehaviorKernel::GetBehaviorKernelStats)
        .def("IsBehaviorKernelWatchingConsumer", &UBehaviorKernel::IsBehaviorKernelWatchingConsumer)
        .def("IsBehaviorSequenceEnabled", &UBehaviorKernel::IsBehaviorSequenceEnabled)
        .def("ActivateBehaviorOutputLink", &UBehaviorKernel::ActivateBehaviorOutputLink)
        .def("PublishBoolOutputVariable", &UBehaviorKernel::PublishBoolOutputVariable)
        .def("PublishObjectOutputVariable", &UBehaviorKernel::PublishObjectOutputVariable)
        .def("PublishVectorOutputVariable", &UBehaviorKernel::PublishVectorOutputVariable)
        .def("PublishFloatOutputVariable", &UBehaviorKernel::PublishFloatOutputVariable)
        .def("PublishIntOutputVariable", &UBehaviorKernel::PublishIntOutputVariable)
        .def("BeginNondeterministicProviderRegistration", &UBehaviorKernel::BeginNondeterministicProviderRegistration)
        .def("ProcessReplicatedBehaviorEvent", &UBehaviorKernel::ProcessReplicatedBehaviorEvent)
        .def("ProcessReplicatedBehaviorConsumerState", &UBehaviorKernel::ProcessReplicatedBehaviorConsumerState)
        .def("ChangeBehaviorSequenceActivationStatus", &UBehaviorKernel::ChangeBehaviorSequenceActivationStatus)
        .def("ChangeBehaviorConsumerSuspensionStatus", &UBehaviorKernel::ChangeBehaviorConsumerSuspensionStatus)
        .def("BroadcastBehaviorEventFromScript", &UBehaviorKernel::BroadcastBehaviorEventFromScript)
        .def("ActivateBehaviorEventFromScript", &UBehaviorKernel::ActivateBehaviorEventFromScript)
        .def("RemoveBehaviorProviderFromConsumer", &UBehaviorKernel::RemoveBehaviorProviderFromConsumer)
        .def("IntializeBehaviorProviderForConsumer", &UBehaviorKernel::IntializeBehaviorProviderForConsumer)
        .def("ForceUnregisterBehaviorConsumer", &UBehaviorKernel::ForceUnregisterBehaviorConsumer)
        .def("RegisterBehaviorConsumer", &UBehaviorKernel::RegisterBehaviorConsumer)
        .staticmethod("StaticClass")
  ;
}