#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_AInventoryManager()
{
    class_< AInventoryManager, bases< AActor >  , boost::noncopyable>("AInventoryManager", no_init)
        .def_readwrite("InventoryChain", &AInventoryManager::InventoryChain)
        .def_readwrite("PendingWeapon", &AInventoryManager::PendingWeapon)
        .def_readwrite("PendingOffHandWeapon", &AInventoryManager::PendingOffHandWeapon)
        .def_readwrite("LastAttemptedSwitchToWeapon", &AInventoryManager::LastAttemptedSwitchToWeapon)
        .def_readwrite("PendingFire", &AInventoryManager::PendingFire)
        .def_readwrite("OffHandPendingFire", &AInventoryManager::OffHandPendingFire)
        .def("StaticClass", &AInventoryManager::StaticClass, return_value_policy< reference_existing_object >())
        .def("ClientConditionalIncrementPickupStats", &AInventoryManager::ClientConditionalIncrementPickupStats)
        .def("ClearInventoryReferences", &AInventoryManager::ClearInventoryReferences)
        .def("ShouldSwitchToBestWeapon", &AInventoryManager::ShouldSwitchToBestWeapon)
        .def("UpdateController", &AInventoryManager::UpdateController)
        .def("ClientWeaponSet", &AInventoryManager::ClientWeaponSet)
        .def("ChangedWeapon", &AInventoryManager::ChangedWeapon)
        .def("ClearPendingWeapon", &AInventoryManager::ClearPendingWeapon)
        .def("CancelWeaponChange", &AInventoryManager::CancelWeaponChange)
        .def("SetPendingWeapon", &AInventoryManager::SetPendingWeapon)
        .def("InternalSetCurrentWeapon", &AInventoryManager::InternalSetCurrentWeapon)
        .def("ServerSetCurrentWeapon", &AInventoryManager::ServerSetCurrentWeapon)
        .def("SetCurrentWeapon", &AInventoryManager::SetCurrentWeapon)
        .def("NextWeapon", &AInventoryManager::NextWeapon)
        .def("PrevWeapon", &AInventoryManager::PrevWeapon)
        .def("SwitchToBestWeapon", &AInventoryManager::SwitchToBestWeapon)
        .def("GetBestWeapon", &AInventoryManager::GetBestWeapon, return_value_policy< reference_existing_object >())
        .def("GetWeaponRatingFor", &AInventoryManager::GetWeaponRatingFor)
        .def("eventDrawHUD", &AInventoryManager::eventDrawHUD)
        .def("OwnerDied", &AInventoryManager::OwnerDied)
        .def("eventDiscardInventory", &AInventoryManager::eventDiscardInventory)
        .def("InventoryUnreadied", &AInventoryManager::InventoryUnreadied)
        .def("InventoryReadied", &AInventoryManager::InventoryReadied)
        .def("RemoveFromInventory", &AInventoryManager::RemoveFromInventory)
        .def("AddInventory", &AInventoryManager::AddInventory)
        .def("CreateInventory", &AInventoryManager::CreateInventory, return_value_policy< reference_existing_object >())
        .def("eventFindInventoryType", &AInventoryManager::eventFindInventoryType, return_value_policy< reference_existing_object >())
        .def("eventHandlePickupQuery", &AInventoryManager::eventHandlePickupQuery)
        .def("eventDestroyed", &AInventoryManager::eventDestroyed)
        .def("SetupFor", &AInventoryManager::SetupFor)
        .def("InventoryActors", &AInventoryManager::InventoryActors)
        .def("ClearAllPendingFire", &AInventoryManager::ClearAllPendingFire)
        .def("IsPendingFire", &AInventoryManager::IsPendingFire)
        .def("ClearPendingFire", &AInventoryManager::ClearPendingFire)
        .def("SetPendingFire", &AInventoryManager::SetPendingFire)
        .def("GetPendingFireLength", &AInventoryManager::GetPendingFireLength)
        .def("PostBeginPlay", &AInventoryManager::PostBeginPlay)
        .def("eventReplicatedEvent", &AInventoryManager::eventReplicatedEvent)
        .staticmethod("StaticClass")
  ;
}