#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UOnlineGameSettings(py::module &m)
{
    py::class_< UOnlineGameSettings,  UObject   >(m, "UOnlineGameSettings")
		.def_static("StaticClass", &UOnlineGameSettings::StaticClass, py::return_value_policy::reference)
        .def_readwrite("NumPublicConnections", &UOnlineGameSettings::NumPublicConnections)
        .def_readwrite("NumPrivateConnections", &UOnlineGameSettings::NumPrivateConnections)
        .def_readwrite("NumOpenPublicConnections", &UOnlineGameSettings::NumOpenPublicConnections)
        .def_readwrite("NumOpenPrivateConnections", &UOnlineGameSettings::NumOpenPrivateConnections)
        .def_readwrite("ServerNonce", &UOnlineGameSettings::ServerNonce)
        .def_readwrite("OwningPlayerName", &UOnlineGameSettings::OwningPlayerName)
        .def_readwrite("OwningPlayerId", &UOnlineGameSettings::OwningPlayerId)
        .def_readwrite("PingInMs", &UOnlineGameSettings::PingInMs)
        .def_readwrite("MatchQuality", &UOnlineGameSettings::MatchQuality)
        .def_readwrite("GameState", &UOnlineGameSettings::GameState)
        .def_readwrite("BuildUniqueId", &UOnlineGameSettings::BuildUniqueId)
        .def_readwrite("BuildUniqueString", &UOnlineGameSettings::BuildUniqueString)
        .def_readwrite("LocalizedSettings", &USettings::LocalizedSettings)
        .def_readwrite("Properties", &USettings::Properties)
        .def_readwrite("LocalizedSettingsMappings", &USettings::LocalizedSettingsMappings)
        .def_readwrite("PropertyMappings", &USettings::PropertyMappings)
        .def("GetGameVersionString", &UOnlineGameSettings::GetGameVersionString)
        .def("UpdateFromURL", &USettings::UpdateFromURL)
        .def("BuildURL", &USettings::BuildURL)
        .def("AppendContextsToURL", &USettings::AppendContextsToURL)
        .def("AppendPropertiesToURL", &USettings::AppendPropertiesToURL)
        .def("AppendDataBindingsToURL", &USettings::AppendDataBindingsToURL)
        .def("GetQoSAdvertisedStringSettings", &USettings::GetQoSAdvertisedStringSettings)
        .def("GetQoSAdvertisedProperties", &USettings::GetQoSAdvertisedProperties)
        .def("GetRangedPropertyValue", &USettings::GetRangedPropertyValue)
        .def("SetRangedPropertyValue", &USettings::SetRangedPropertyValue)
        .def("GetPropertyRange", &USettings::GetPropertyRange)
        .def("GetPropertyMappingType", &USettings::GetPropertyMappingType)
        .def("HasStringSetting", &USettings::HasStringSetting)
        .def("HasProperty", &USettings::HasProperty)
        .def("UpdateProperties", &USettings::UpdateProperties)
        .def("UpdateStringSettings", &USettings::UpdateStringSettings)
        .def("GetPropertyType", &USettings::GetPropertyType)
        .def("GetPropertyValueId", &USettings::GetPropertyValueId)
        .def("SetPropertyValueId", &USettings::SetPropertyValueId)
        .def("GetByteProperty", &USettings::GetByteProperty)
        .def("SetByteProperty", &USettings::SetByteProperty)
        .def("GetStringProperty", &USettings::GetStringProperty)
        .def("SetStringProperty", &USettings::SetStringProperty)
        .def("GetIntProperty", &USettings::GetIntProperty)
        .def("SetIntProperty", &USettings::SetIntProperty)
        .def("GetFloatProperty", &USettings::GetFloatProperty)
        .def("SetFloatProperty", &USettings::SetFloatProperty)
        .def("SetPropertyFromStringByName", &USettings::SetPropertyFromStringByName)
        .def("GetPropertyAsStringByName", &USettings::GetPropertyAsStringByName)
        .def("GetPropertyAsString", &USettings::GetPropertyAsString)
        .def("GetPropertyColumnHeader", &USettings::GetPropertyColumnHeader)
        .def("GetPropertyName", &USettings::GetPropertyName)
        .def("GetPropertyId", &USettings::GetPropertyId)
        .def("SetStringSettingValueFromStringByName", &USettings::SetStringSettingValueFromStringByName)
        .def("GetStringSettingValueNameByName", &USettings::GetStringSettingValueNameByName)
        .def("GetStringSettingValueName", &USettings::GetStringSettingValueName)
        .def("IsWildcardStringSetting", &USettings::IsWildcardStringSetting)
        .def("GetStringSettingColumnHeader", &USettings::GetStringSettingColumnHeader)
        .def("GetStringSettingName", &USettings::GetStringSettingName)
        .def("GetStringSettingId", &USettings::GetStringSettingId)
        .def("GetStringSettingValueByName", &USettings::GetStringSettingValueByName)
        .def("SetStringSettingValueByName", &USettings::SetStringSettingValueByName)
        .def("GetStringSettingValueNames", &USettings::GetStringSettingValueNames)
        .def("IncrementStringSettingValue", &USettings::IncrementStringSettingValue)
        .def("GetStringSettingValue", &USettings::GetStringSettingValue)
        .def("SetStringSettingValue", &USettings::SetStringSettingValue)
        .def("GetSettingsDataDateTime", &USettings::GetSettingsDataDateTime)
        .def("GetSettingsDataBlob", &USettings::GetSettingsDataBlob)
        .def("GetSettingsDataInt", &USettings::GetSettingsDataInt)
        .def("GetSettingsDataFloat", &USettings::GetSettingsDataFloat)
        .def("GetSettingsDataString", &USettings::GetSettingsDataString)
        .def("EmptySettingsData", &USettings::EmptySettingsData)
        .def("SetSettingsData", &USettings::SetSettingsData)
        .def("SetSettingsDataBlob", &USettings::SetSettingsDataBlob)
        .def("SetSettingsDataDateTime", &USettings::SetSettingsDataDateTime)
        .def("SetSettingsDataInt", &USettings::SetSettingsDataInt)
        .def("SetSettingsDataFloat", &USettings::SetSettingsDataFloat)
        .def("SetSettingsDataString", &USettings::SetSettingsDataString)
          ;
}