#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UVendingMachineExGFxMovie(py::object m)
{
    py::class_< UVendingMachineExGFxMovie,  UWillowInventoryGFxMovie   >(m, "UVendingMachineExGFxMovie")
        .def_readwrite("VM", &UVendingMachineExGFxMovie::VM)
        .def_readwrite("VMGFxDef", &UVendingMachineExGFxMovie::VMGFxDef)
        .def_readwrite("OwnerInventoryPawn", &UVendingMachineExGFxMovie::OwnerInventoryPawn)
        .def_readwrite("ItemOfTheDayData", &UVendingMachineExGFxMovie::ItemOfTheDayData)
        .def_readwrite("ShopItems", &UVendingMachineExGFxMovie::ShopItems)
        .def_readwrite("BuyBackItems", &UVendingMachineExGFxMovie::BuyBackItems)
        .def_readwrite("TwoPanelInterface", &UVendingMachineExGFxMovie::TwoPanelInterface)
        .def_readwrite("ItemOfTheDayPanel", &UVendingMachineExGFxMovie::ItemOfTheDayPanel)
        .def_readwrite("PlayerMoney", &UVendingMachineExGFxMovie::PlayerMoney)
        .def_readwrite("HealthBar", &UVendingMachineExGFxMovie::HealthBar)
        .def_readwrite("ShieldBar", &UVendingMachineExGFxMovie::ShieldBar)
        .def_readwrite("AmmoPanel", &UVendingMachineExGFxMovie::AmmoPanel)
        .def_readwrite("Feedback", &UVendingMachineExGFxMovie::Feedback)
        .def_readwrite("HealthShopTitle", &UVendingMachineExGFxMovie::HealthShopTitle)
        .def_readwrite("ItemsShopTitle", &UVendingMachineExGFxMovie::ItemsShopTitle)
        .def_readwrite("WeaponsShopTitle", &UVendingMachineExGFxMovie::WeaponsShopTitle)
        .def_readwrite("BlackMarketTitle", &UVendingMachineExGFxMovie::BlackMarketTitle)
        .def_readwrite("VisitLabel", &UVendingMachineExGFxMovie::VisitLabel)
        .def_readwrite("ItemOfTheDayLabel", &UVendingMachineExGFxMovie::ItemOfTheDayLabel)
        .def_readwrite("VisitLabel_BlackMarket", &UVendingMachineExGFxMovie::VisitLabel_BlackMarket)
        .def_readwrite("ItemOfTheDayLabel_BlackMarket", &UVendingMachineExGFxMovie::ItemOfTheDayLabel_BlackMarket)
        .def_readwrite("StoragePanelLabel", &UVendingMachineExGFxMovie::StoragePanelLabel)
        .def_readwrite("PlayerPanelLabel", &UVendingMachineExGFxMovie::PlayerPanelLabel)
        .def_readwrite("BuybackPanelLabel", &UVendingMachineExGFxMovie::BuybackPanelLabel)
        .def_readwrite("ComparePanelLabel", &UVendingMachineExGFxMovie::ComparePanelLabel)
        .def_readwrite("CurrentSelectionShopStatus", &UVendingMachineExGFxMovie::CurrentSelectionShopStatus)
        .def_readwrite("ShopType", &UVendingMachineExGFxMovie::ShopType)
        .def_readwrite("bCanAcceptInput", &UVendingMachineExGFxMovie::bCanAcceptInput)
        .def_readwrite("CurrentSelectionItem", &UVendingMachineExGFxMovie::CurrentSelectionItem)
        .def_readwrite("CachedCurrency", &UVendingMachineExGFxMovie::CachedCurrency)
        .def_readwrite("StoragePanelSortConfigIndex", &UVendingMachineExGFxMovie::StoragePanelSortConfigIndex)
        .def_readwrite("PlayerPanelSortConfigIndex", &UVendingMachineExGFxMovie::PlayerPanelSortConfigIndex)
        .def_readwrite("WeaponsSortConfigurations", &UVendingMachineExGFxMovie::WeaponsSortConfigurations)
        .def_readwrite("WeaponsSortConfigIndex", &UVendingMachineExGFxMovie::WeaponsSortConfigIndex)
        .def_readwrite("HealthSortConfigurations", &UVendingMachineExGFxMovie::HealthSortConfigurations)
        .def_readwrite("HealthSortConfigIndex", &UVendingMachineExGFxMovie::HealthSortConfigIndex)
        .def_readwrite("GrenadesSortConfigurations", &UVendingMachineExGFxMovie::GrenadesSortConfigurations)
        .def_readwrite("GrenadesSortConfigIndex", &UVendingMachineExGFxMovie::GrenadesSortConfigIndex)
        .def_readwrite("BlackMarketSortConfigurations", &UVendingMachineExGFxMovie::BlackMarketSortConfigurations)
        .def_readwrite("BlackMarketSortConfigIndex", &UVendingMachineExGFxMovie::BlackMarketSortConfigIndex)
        .def_readwrite("GenericSortConfigurations", &UVendingMachineExGFxMovie::GenericSortConfigurations)
        .def_readwrite("GenericSortConfigIndex", &UVendingMachineExGFxMovie::GenericSortConfigIndex)
        .def_readwrite("CompareConfiguration", &UVendingMachineExGFxMovie::CompareConfiguration)
        .def_readwrite("VendingMachineRefreshRate", &UVendingMachineExGFxMovie::VendingMachineRefreshRate)
        .def_readwrite("NumHeaderButtons", &UVendingMachineExGFxMovie::NumHeaderButtons)
        .def_readwrite("PCContextMenu", &UVendingMachineExGFxMovie::PCContextMenu)
        .def_readwrite("ShopIconBase", &UVendingMachineExGFxMovie::ShopIconBase)
        .def("StaticClass", &UVendingMachineExGFxMovie::StaticClass, py::return_value_policy::reference)
        .def("SetItemLocation", &UVendingMachineExGFxMovie::SetItemLocation)
        .def("CycleSelectedThingAsTrashOrFavorite", &UVendingMachineExGFxMovie::CycleSelectedThingAsTrashOrFavorite)
        .def("PressedHotkeyNumber", &UVendingMachineExGFxMovie::PressedHotkeyNumber)
        .def("extGenericButtonClicked", &UVendingMachineExGFxMovie::extGenericButtonClicked)
        .def("InitForConsole", &UVendingMachineExGFxMovie::InitForConsole)
        .def("InitForPC", &UVendingMachineExGFxMovie::InitForPC)
        .def("RefreshShieldBar", &UVendingMachineExGFxMovie::RefreshShieldBar)
        .def("RefreshHealthBar", &UVendingMachineExGFxMovie::RefreshHealthBar)
        .def("TweenOut", &UVendingMachineExGFxMovie::TweenOut)
        .def("BeginClosing", &UVendingMachineExGFxMovie::BeginClosing)
        .def("SetTooltips", &UVendingMachineExGFxMovie::SetTooltips)
        .def("FinishCompare", &UVendingMachineExGFxMovie::FinishCompare)
        .def("StartCompare", &UVendingMachineExGFxMovie::StartCompare)
        .def("CheckShopOpStatus", &UVendingMachineExGFxMovie::CheckShopOpStatus)
        .def("CanSellAllTrash", &UVendingMachineExGFxMovie::CanSellAllTrash)
        .def("SellAllTrash", &UVendingMachineExGFxMovie::SellAllTrash)
        .def("PlayFeedback_CannotCarryOrUse", &UVendingMachineExGFxMovie::PlayFeedback_CannotCarryOrUse)
        .def("PlayFeedback_CannotAfford", &UVendingMachineExGFxMovie::PlayFeedback_CannotAfford)
        .def("ConditionalStartTransfer", &UVendingMachineExGFxMovie::ConditionalStartTransfer)
        .def("GetCurrentShopMode", &UVendingMachineExGFxMovie::GetCurrentShopMode)
        .def("IsCurrentSelectionBuyBack", &UVendingMachineExGFxMovie::IsCurrentSelectionBuyBack)
        .def("IsCurrentSelectionSell", &UVendingMachineExGFxMovie::IsCurrentSelectionSell)
        .def("GetStatusForItem", &UVendingMachineExGFxMovie::GetStatusForItem)
        .def("EvaluateCurrentSelection", &UVendingMachineExGFxMovie::EvaluateCurrentSelection)
        .def("ShouldStoragePanelHighlightFrozen", &UVendingMachineExGFxMovie::ShouldStoragePanelHighlightFrozen)
        .def("SwitchToItemOfTheDay", &UVendingMachineExGFxMovie::SwitchToItemOfTheDay)
        .def("SwitchToPanels", &UVendingMachineExGFxMovie::SwitchToPanels)
        .def("OnPanelRollOver", &UVendingMachineExGFxMovie::OnPanelRollOver)
        .def("OnDynamicCardUpdated", &UVendingMachineExGFxMovie::OnDynamicCardUpdated)
        .def("InspectItem", &UVendingMachineExGFxMovie::InspectItem)
        .def("CompareInputKey", &UVendingMachineExGFxMovie::CompareInputKey)
        .def("HandleItemOfTheDayInput", &UVendingMachineExGFxMovie::HandleItemOfTheDayInput)
        .def("CanSwitchToBuyback", &UVendingMachineExGFxMovie::CanSwitchToBuyback)
        .def("MainInputKey", &UVendingMachineExGFxMovie::MainInputKey)
        .def("OnInventoryPanelSetActive", &UVendingMachineExGFxMovie::OnInventoryPanelSetActive)
        .def("ShowContextMenu", &UVendingMachineExGFxMovie::ShowContextMenu)
        .def("GetCurrentCellObject", &UVendingMachineExGFxMovie::GetCurrentCellObject, py::return_value_policy::reference)
        .def("ContextMenuClosed", &UVendingMachineExGFxMovie::ContextMenuClosed)
        .def("ContextMenuActivated", &UVendingMachineExGFxMovie::ContextMenuActivated)
        .def("OnCellPressed", &UVendingMachineExGFxMovie::OnCellPressed)
        .def("PanelOnItemSelected", &UVendingMachineExGFxMovie::PanelOnItemSelected)
        .def("GetSelectedThing", &UVendingMachineExGFxMovie::GetSelectedThing, py::return_value_policy::reference)
        .def("GetPlayerPanelLabel", &UVendingMachineExGFxMovie::GetPlayerPanelLabel)
        .def("GetStoragePanelLabel", &UVendingMachineExGFxMovie::GetStoragePanelLabel)
        .def("NotifySelectionChange", &UVendingMachineExGFxMovie::NotifySelectionChange)
        .def("GetCurrencyTypeForInventory", &UVendingMachineExGFxMovie::GetCurrencyTypeForInventory)
        .def("GetOverridePriceForInventory", &UVendingMachineExGFxMovie::GetOverridePriceForInventory)
        .def("GetSortConfigDataForPanel", &UVendingMachineExGFxMovie::GetSortConfigDataForPanel)
        .def("SetPlayerCurrencyType", &UVendingMachineExGFxMovie::SetPlayerCurrencyType)
        .def("GetStorageReferenceForTransferring", &UVendingMachineExGFxMovie::GetStorageReferenceForTransferring, py::return_value_policy::reference)
        .def("GetStorageReferenceForSwapping", &UVendingMachineExGFxMovie::GetStorageReferenceForSwapping, py::return_value_policy::reference)
        .def("GetPlayerPanelItems", &UVendingMachineExGFxMovie::GetPlayerPanelItems)
        .def("GetStoragePanelItems", &UVendingMachineExGFxMovie::GetStoragePanelItems)
        .def("GetTitle", &UVendingMachineExGFxMovie::GetTitle)
        .def("ShouldStartOnLeftPanel", &UVendingMachineExGFxMovie::ShouldStartOnLeftPanel)
        .def("ShouldShowPanelNavTooltips", &UVendingMachineExGFxMovie::ShouldShowPanelNavTooltips)
        .def("SetCreditsDisplay", &UVendingMachineExGFxMovie::SetCreditsDisplay)
        .def("GetCurrencyType", &UVendingMachineExGFxMovie::GetCurrencyType)
        .def("UpdateTimeRemaining", &UVendingMachineExGFxMovie::UpdateTimeRemaining)
        .def("eventOnTick", &UVendingMachineExGFxMovie::eventOnTick)
        .def("ConfigureShopForType", &UVendingMachineExGFxMovie::ConfigureShopForType)
        .def("Refresh", &UVendingMachineExGFxMovie::Refresh)
        .def("RefreshStoragePanelItems", &UVendingMachineExGFxMovie::RefreshStoragePanelItems)
        .def("RefreshTransientData", &UVendingMachineExGFxMovie::RefreshTransientData)
        .def("ClearVendingMachineRefreshTimer", &UVendingMachineExGFxMovie::ClearVendingMachineRefreshTimer)
        .def("SetVendingMachineRefreshTimer", &UVendingMachineExGFxMovie::SetVendingMachineRefreshTimer)
        .def("InitCardCellThumbnail", &UVendingMachineExGFxMovie::InitCardCellThumbnail, py::return_value_policy::reference)
        .def("FreeTextures", &UVendingMachineExGFxMovie::FreeTextures)
        .def("eventOnClose", &UVendingMachineExGFxMovie::eventOnClose)
        .def("ConfigureForType_IOTD", &UVendingMachineExGFxMovie::ConfigureForType_IOTD)
        .def("ConfigureForType_TPI", &UVendingMachineExGFxMovie::ConfigureForType_TPI)
        .def("ConfigureForType_Shop", &UVendingMachineExGFxMovie::ConfigureForType_Shop)
        .def("OnLeftPanelInit", &UVendingMachineExGFxMovie::OnLeftPanelInit)
        .def("extInitMainPanel", &UVendingMachineExGFxMovie::extInitMainPanel)
        .def("extInitCustomItemOfTheDayBackground", &UVendingMachineExGFxMovie::extInitCustomItemOfTheDayBackground)
        .def("extInitItemOfTheDayPanel", &UVendingMachineExGFxMovie::extInitItemOfTheDayPanel)
        .def("extInitVendingMachine", &UVendingMachineExGFxMovie::extInitVendingMachine)
        .def("eventStart", &UVendingMachineExGFxMovie::eventStart)
          ;
}