#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UTradingPanelGFxObject(py::module &m)
{
    py::class_< UTradingPanelGFxObject,  UBaseTopLevelPanelGFxObject   >(m, "UTradingPanelGFxObject")
		.def_static("StaticClass", &UTradingPanelGFxObject::StaticClass, py::return_value_policy::reference)
        .def_readwrite("BackpackPanel", &UTradingPanelGFxObject::BackpackPanel)
        .def_readwrite("OffersPanel", &UTradingPanelGFxObject::OffersPanel)
        .def_readwrite("CurrentPanel", &UTradingPanelGFxObject::CurrentPanel)
        .def_readwrite("ReturnPanel", &UTradingPanelGFxObject::ReturnPanel)
        .def_readwrite("OfferingThing", &UTradingPanelGFxObject::OfferingThing)
        .def_readwrite("CachedSortFilterConfig", &UTradingPanelGFxObject::CachedSortFilterConfig)
        .def("extCompleteDrag_Backpack", &UTradingPanelGFxObject::extCompleteDrag_Backpack)
        .def("extCompleteDrag_Offered", &UTradingPanelGFxObject::extCompleteDrag_Offered)
        .def("extCancelDrag", &UTradingPanelGFxObject::extCancelDrag)
        .def("CanDragSelectedThing", &UTradingPanelGFxObject::CanDragSelectedThing)
        .def("OnStartDrag", &UTradingPanelGFxObject::OnStartDrag)
        .def("SetLeftRightArrowVisibility", &UTradingPanelGFxObject::SetLeftRightArrowVisibility)
        .def("InspectItem", &UTradingPanelGFxObject::InspectItem)
        .def("SetBackpackList", &UTradingPanelGFxObject::SetBackpackList)
        .def("SetTooltipText", &UTradingPanelGFxObject::SetTooltipText)
        .def("SetTotalCredits", &UTradingPanelGFxObject::SetTotalCredits)
        .def("ConfigureForPlayer", &UTradingPanelGFxObject::ConfigureForPlayer)
        .def("FinishOffer", &UTradingPanelGFxObject::FinishOffer)
        .def("CancelOffer", &UTradingPanelGFxObject::CancelOffer)
        .def("CompleteOffer", &UTradingPanelGFxObject::CompleteOffer)
        .def("StartOffer", &UTradingPanelGFxObject::StartOffer)
        .def("CanUseCLIKButtons", &UTradingPanelGFxObject::CanUseCLIKButtons)
        .def("CanStartOffer", &UTradingPanelGFxObject::CanStartOffer)
        .def("OfferInputKey", &UTradingPanelGFxObject::OfferInputKey)
        .def("NormalInputKey", &UTradingPanelGFxObject::NormalInputKey)
        .def("BlockInput", &UTradingPanelGFxObject::BlockInput)
        .def("DeferInput", &UTradingPanelGFxObject::DeferInput)
        .def("PanelOnInputKey", &UTradingPanelGFxObject::PanelOnInputKey)
        .def("GetSelectedThing", &UTradingPanelGFxObject::GetSelectedThing, py::return_value_policy::reference)
        .def("RefreshItemCards", &UTradingPanelGFxObject::RefreshItemCards)
        .def("SwitchToPanel", &UTradingPanelGFxObject::SwitchToPanel)
        .def("SwitchFocus", &UTradingPanelGFxObject::SwitchFocus)
        .def("RestoreState", &UTradingPanelGFxObject::RestoreState)
        .def("OnItemSelected", &UTradingPanelGFxObject::OnItemSelected)
        .def("Refresh", &UTradingPanelGFxObject::Refresh)
        .def("OnListSort", &UTradingPanelGFxObject::OnListSort)
        .def("InitPanels", &UTradingPanelGFxObject::InitPanels)
        .def("AssignPanels", &UTradingPanelGFxObject::AssignPanels)
        .def("InitItemCards", &UTradingPanelGFxObject::InitItemCards)
        .def("AssignItemCards", &UTradingPanelGFxObject::AssignItemCards)
        .def("Init", &UTradingPanelGFxObject::Init)
          ;
}