#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UWeaponPartDefinition(py::object m)
{
    py::class_< UWeaponPartDefinition,  UWillowInventoryPartDefinition   >(m, "UWeaponPartDefinition")
        .def_readwrite("VfTable_IIBehaviorProvider", &UWeaponPartDefinition::VfTable_IIBehaviorProvider)
        .def_readwrite("TitleList", &UWeaponPartDefinition::TitleList)
        .def_readwrite("PrefixList", &UWeaponPartDefinition::PrefixList)
        .def_readwrite("CustomDamageTypeDefinition", &UWeaponPartDefinition::CustomDamageTypeDefinition)
        .def_readwrite("CustomFiringModeDefinition", &UWeaponPartDefinition::CustomFiringModeDefinition)
        .def_readwrite("ExternalAttributeEffects", &UWeaponPartDefinition::ExternalAttributeEffects)
        .def_readwrite("WeaponAttributeEffects", &UWeaponPartDefinition::WeaponAttributeEffects)
        .def_readwrite("ZoomExternalAttributeEffects", &UWeaponPartDefinition::ZoomExternalAttributeEffects)
        .def_readwrite("ZoomWeaponAttributeEffects", &UWeaponPartDefinition::ZoomWeaponAttributeEffects)
        .def_readwrite("WeaponCardAttributes", &UWeaponPartDefinition::WeaponCardAttributes)
        .def_readwrite("CustomPresentations", &UWeaponPartDefinition::CustomPresentations)
        .def_readwrite("PartType", &UWeaponPartDefinition::PartType)
        .def_readwrite("PartVariation", &UWeaponPartDefinition::PartVariation)
        .def_readwrite("NumPhysicalBarrelsToFireFrom", &UWeaponPartDefinition::NumPhysicalBarrelsToFireFrom)
        .def_readwrite("BoneControllers", &UWeaponPartDefinition::BoneControllers)
        .def_readwrite("VisibleAmmoBoneNames", &UWeaponPartDefinition::VisibleAmmoBoneNames)
        .def_readwrite("LeftHandIKHoldName", &UWeaponPartDefinition::LeftHandIKHoldName)
        .def_readwrite("SpinUpDuration", &UWeaponPartDefinition::SpinUpDuration)
        .def_readwrite("SpinDownDuration", &UWeaponPartDefinition::SpinDownDuration)
        .def_readwrite("StartingSpinUpFireIntervalMultiplier", &UWeaponPartDefinition::StartingSpinUpFireIntervalMultiplier)
        .def_readwrite("FlapsExpandDuration", &UWeaponPartDefinition::FlapsExpandDuration)
        .def_readwrite("FlapsCollapseDuration", &UWeaponPartDefinition::FlapsCollapseDuration)
        .def_readwrite("ShellCasingPSCTemplate", &UWeaponPartDefinition::ShellCasingPSCTemplate)
        .def_readwrite("ShellCasingSocket", &UWeaponPartDefinition::ShellCasingSocket)
        .def_readwrite("ScopedShellCasingOffset", &UWeaponPartDefinition::ScopedShellCasingOffset)
        .def_readwrite("OffHandShellCasingRotOffset", &UWeaponPartDefinition::OffHandShellCasingRotOffset)
        .def_readwrite("MuzzleFlashPSTemplates", &UWeaponPartDefinition::MuzzleFlashPSTemplates)
        .def_readwrite("AltMuzzleFlashSockets", &UWeaponPartDefinition::AltMuzzleFlashSockets)
        .def_readwrite("WeaponImpact", &UWeaponPartDefinition::WeaponImpact)
        .def_readwrite("FirstPersonParticle", &UWeaponPartDefinition::FirstPersonParticle)
        .def_readwrite("FirstPersonParticleSocketName", &UWeaponPartDefinition::FirstPersonParticleSocketName)
        .def_readwrite("FirstPersonParticleInstanceDataName", &UWeaponPartDefinition::FirstPersonParticleInstanceDataName)
        .def_readwrite("BehaviorProviderDefinition", &UWeaponPartDefinition::BehaviorProviderDefinition)
        .def_readwrite("ManufacturerDefinitionForScopeMovie", &UWeaponPartDefinition::ManufacturerDefinitionForScopeMovie)
        .def_readwrite("ZoomedFOVLerpPct", &UWeaponPartDefinition::ZoomedFOVLerpPct)
        .def_readwrite("SightFXCrosshairMaterial", &UWeaponPartDefinition::SightFXCrosshairMaterial)
        .def_readwrite("SightFXCrosshairParamName", &UWeaponPartDefinition::SightFXCrosshairParamName)
        .def_readwrite("SightFXCrosshairRefractionParamName", &UWeaponPartDefinition::SightFXCrosshairRefractionParamName)
        .def("StaticClass", &UWeaponPartDefinition::StaticClass, py::return_value_policy::reference)
        .def("OnAbortReload", &UWeaponPartDefinition::OnAbortReload)
        .def("OnZoomOut", &UWeaponPartDefinition::OnZoomOut)
        .def("OnZoomIn", &UWeaponPartDefinition::OnZoomIn)
        .def("OnUnequip", &UWeaponPartDefinition::OnUnequip)
        .def("OnEquip", &UWeaponPartDefinition::OnEquip)
        .def("OnCreate", &UWeaponPartDefinition::OnCreate)
        .def("SetBehaviorProviderDefinition", &UWeaponPartDefinition::SetBehaviorProviderDefinition)
        .def("GetBehaviorProviderDefinition", &UWeaponPartDefinition::GetBehaviorProviderDefinition, py::return_value_policy::reference)
          ;
}