#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UWillowGlobals()
{
    class_< UWillowGlobals, bases< UGearboxGlobals >  , boost::noncopyable>("UWillowGlobals", no_init)
        .def_readwrite("PlayerClassIdentifiers", &UWillowGlobals::PlayerClassIdentifiers)
        .def_readwrite("PlayerNameIdentifiers", &UWillowGlobals::PlayerNameIdentifiers)
        .def_readwrite("DefaultWorldBodyStandIn", &UWillowGlobals::DefaultWorldBodyStandIn)
        .def_readwrite("DamagePipelinePool", &UWillowGlobals::DamagePipelinePool)
        .def_readwrite("AutoAimDefinition", &UWillowGlobals::AutoAimDefinition)
        .def_readwrite("PlayerTrainingMessages", &UWillowGlobals::PlayerTrainingMessages)
        .def_readwrite("DefaultGlobalsDefinitionName", &UWillowGlobals::DefaultGlobalsDefinitionName)
        .def_readwrite("MasterFastTravelStationList", &UWillowGlobals::MasterFastTravelStationList)
        .def_readwrite("MasterLevelDependencyList", &UWillowGlobals::MasterLevelDependencyList)
        .def_readwrite("TheRelevanceUtility", &UWillowGlobals::TheRelevanceUtility)
        .def_readwrite("TheRelevanceUtilityClass", &UWillowGlobals::TheRelevanceUtilityClass)
        .def_readwrite("ClientInteractiveObjects", &UWillowGlobals::ClientInteractiveObjects)
        .def_readwrite("LoadingMovieExceptions", &UWillowGlobals::LoadingMovieExceptions)
        .def_readwrite("TheLCDHelper", &UWillowGlobals::TheLCDHelper)
        .def_readwrite("TheEffectsCoordinator", &UWillowGlobals::TheEffectsCoordinator)
        .def_readwrite("TheObstacleUtility", &UWillowGlobals::TheObstacleUtility)
        .def_readwrite("TheCustomizationManager", &UWillowGlobals::TheCustomizationManager)
        .def_readwrite("ThePlayerPawnDataManager", &UWillowGlobals::ThePlayerPawnDataManager)
        .def_readwrite("PersistentLevelSFXBank", &UWillowGlobals::PersistentLevelSFXBank)
        .def_readwrite("PersistentLevelVoiceBank", &UWillowGlobals::PersistentLevelVoiceBank)
        .def_readwrite("ActiveHomingProjectileList", &UWillowGlobals::ActiveHomingProjectileList)
        .def_readwrite("PickupList", &UWillowGlobals::PickupList)
        .def_readwrite("TheVehicleLifetimeManager", &UWillowGlobals::TheVehicleLifetimeManager)
        .def_readwrite("AggregatedVehicleCrewAnimSetTable", &UWillowGlobals::AggregatedVehicleCrewAnimSetTable)
        .def_readwrite("BoundaryTurretList", &UWillowGlobals::BoundaryTurretList)
        .def_readwrite("TheNPCLoadBalancer", &UWillowGlobals::TheNPCLoadBalancer)
        .def_readwrite("TheDamageOverTimeManager", &UWillowGlobals::TheDamageOverTimeManager)
        .def_readwrite("SpectatorPointList", &UWillowGlobals::SpectatorPointList)
        .def_readwrite("KnownCurrencies", &UWillowGlobals::KnownCurrencies)
        .def_readwrite("AssLibMan", &UWillowGlobals::AssLibMan)
        .def_readwrite("LegacyPlayerClassIdentifiers", &UWillowGlobals::LegacyPlayerClassIdentifiers)
        .def_readwrite("PlayThroughBasedBalanceModifiers", &UWillowGlobals::PlayThroughBasedBalanceModifiers)
        .def("StaticClass", &UWillowGlobals::StaticClass, return_value_policy< reference_existing_object >())
        .def("FindCurrencies", &UWillowGlobals::FindCurrencies)
        .def("FindCurrenciesIn", &UWillowGlobals::FindCurrenciesIn)
        .def("AddBoundaryTurret", &UWillowGlobals::AddBoundaryTurret)
        .def("GetDamageOverTimeManager", &UWillowGlobals::GetDamageOverTimeManager, return_value_policy< reference_existing_object >())
        .def("GetNPCLoadBalancer", &UWillowGlobals::GetNPCLoadBalancer, return_value_policy< reference_existing_object >())
        .def("GetCurrentGameReleaseDef", &UWillowGlobals::GetCurrentGameReleaseDef, return_value_policy< reference_existing_object >())
        .def("GetLocalizedDamageType", &UWillowGlobals::GetLocalizedDamageType)
        .def("GetLocalizedDamageCauser", &UWillowGlobals::GetLocalizedDamageCauser)
        .def("CheckIfSpawnWillFail", &UWillowGlobals::CheckIfSpawnWillFail)
        .def("PresetGetCaption", &UWillowGlobals::PresetGetCaption)
        .def("ApplyControllerPreset", &UWillowGlobals::ApplyControllerPreset)
        .def("GetPrevSpectatorPoint", &UWillowGlobals::GetPrevSpectatorPoint, return_value_policy< reference_existing_object >())
        .def("GetNextSpectatorPoint", &UWillowGlobals::GetNextSpectatorPoint, return_value_policy< reference_existing_object >())
        .def("GetFirstSpectatorPoint", &UWillowGlobals::GetFirstSpectatorPoint, return_value_policy< reference_existing_object >())
        .def("RemoveSpectatorPoint", &UWillowGlobals::RemoveSpectatorPoint)
        .def("AddSpectatorPoint", &UWillowGlobals::AddSpectatorPoint)
        .def("RemovePickup", &UWillowGlobals::RemovePickup)
        .def("AddPickup", &UWillowGlobals::AddPickup)
        .def("RemoveActiveHomingProjectile", &UWillowGlobals::RemoveActiveHomingProjectile)
        .def("AddActiveHomingProjectile", &UWillowGlobals::AddActiveHomingProjectile)
        .def("GetTimeOfDayDominantDirectionalLightComponent", &UWillowGlobals::GetTimeOfDayDominantDirectionalLightComponent, return_value_policy< reference_existing_object >())
        .def("ResolveCustomMarkupString", &UWillowGlobals::ResolveCustomMarkupString)
        .def("GetVehicleLifetimeManager", &UWillowGlobals::GetVehicleLifetimeManager, return_value_policy< reference_existing_object >())
        .def("GetPlayerPawnDataManager", &UWillowGlobals::GetPlayerPawnDataManager, return_value_policy< reference_existing_object >())
        .def("GetCustomizationManager", &UWillowGlobals::GetCustomizationManager, return_value_policy< reference_existing_object >())
        .def("GetUISortedValidPlayerNameIdentifiers", &UWillowGlobals::GetUISortedValidPlayerNameIdentifiers)
        .def("GetDefaultPlayerSaveGame", &UWillowGlobals::GetDefaultPlayerSaveGame, return_value_policy< reference_existing_object >())
        .def("GetPlayerNameIdentifierDefinition", &UWillowGlobals::GetPlayerNameIdentifierDefinition, return_value_policy< reference_existing_object >())
        .def("GetPlayerClassIdentifierDefinition", &UWillowGlobals::GetPlayerClassIdentifierDefinition, return_value_policy< reference_existing_object >())
        .def("GetPlayerChallenges", &UWillowGlobals::GetPlayerChallenges)
        .def("GetTheLCDHelper", &UWillowGlobals::GetTheLCDHelper, return_value_policy< reference_existing_object >())
        .def("ToggleUnlockCode", &UWillowGlobals::ToggleUnlockCode)
        .def("IsCodeUnlocked", &UWillowGlobals::IsCodeUnlocked)
        .def("SetLoadingMovieFinished", &UWillowGlobals::SetLoadingMovieFinished)
        .def("GetPawnRelevanceUtility", &UWillowGlobals::GetPawnRelevanceUtility, return_value_policy< reference_existing_object >())
        .def("GetLevelDependencyList", &UWillowGlobals::GetLevelDependencyList, return_value_policy< reference_existing_object >())
        .def("GetFastTravelStationsLookup", &UWillowGlobals::GetFastTravelStationsLookup, return_value_policy< reference_existing_object >())
        .def("GetEffectCoordinator", &UWillowGlobals::GetEffectCoordinator, return_value_policy< reference_existing_object >())
        .def("GetGlobalFallingDamageScale", &UWillowGlobals::GetGlobalFallingDamageScale)
        .def("GetGlobalAIRocketWeaponDamageScale", &UWillowGlobals::GetGlobalAIRocketWeaponDamageScale)
        .def("GetGlobalAIAssaultWeaponDamageScale", &UWillowGlobals::GetGlobalAIAssaultWeaponDamageScale)
        .def("GetGlobalAISniperWeaponDamageScale", &UWillowGlobals::GetGlobalAISniperWeaponDamageScale)
        .def("GetGlobalAISmgWeaponDamageScale", &UWillowGlobals::GetGlobalAISmgWeaponDamageScale)
        .def("GetGlobalAIShotgunWeaponDamageScale", &UWillowGlobals::GetGlobalAIShotgunWeaponDamageScale)
        .def("GetGlobalAIPistolWeaponDamageScale", &UWillowGlobals::GetGlobalAIPistolWeaponDamageScale)
        .def("GetGlobalAIWeaponDamageScale", &UWillowGlobals::GetGlobalAIWeaponDamageScale)
        .def("GetGlobalAIDamageScale", &UWillowGlobals::GetGlobalAIDamageScale)
        .def("GetGlobalsDefinition", &UWillowGlobals::GetGlobalsDefinition, return_value_policy< reference_existing_object >())
        .def("ReleaseDamagePipelineObject", &UWillowGlobals::ReleaseDamagePipelineObject)
        .def("GetDamagePipelineObject", &UWillowGlobals::GetDamagePipelineObject, return_value_policy< reference_existing_object >())
        .def("DeleteWorldBodyStandIn", &UWillowGlobals::DeleteWorldBodyStandIn)
        .def("CreateWorldBodyStandIn", &UWillowGlobals::CreateWorldBodyStandIn, return_value_policy< reference_existing_object >())
        .def("GetWillowSaveGameManager", &UWillowGlobals::GetWillowSaveGameManager, return_value_policy< reference_existing_object >())
        .def("GetWillowGlobals", &UWillowGlobals::GetWillowGlobals, return_value_policy< reference_existing_object >())
        .def("RemoveInteractiveObject", &UWillowGlobals::RemoveInteractiveObject)
        .def("AddInteractiveObject", &UWillowGlobals::AddInteractiveObject)
        .staticmethod("StaticClass")
  ;
}