#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UStatusMenuEquippedPanelGFxObject(py::module &m)
{
    py::class_< UStatusMenuEquippedPanelGFxObject,  UBaseInventoryPanelGFxObject   >(m, "UStatusMenuEquippedPanelGFxObject")
		.def_static("StaticClass", &UStatusMenuEquippedPanelGFxObject::StaticClass, py::return_value_policy::reference)
        .def_readwrite("SelectedCellSuffix", &UStatusMenuEquippedPanelGFxObject::SelectedCellSuffix)
        .def_readwrite("PreferredDownCellSuffix", &UStatusMenuEquippedPanelGFxObject::PreferredDownCellSuffix)
        .def_readwrite("EquippedTypeCellSuffix", &UStatusMenuEquippedPanelGFxObject::EquippedTypeCellSuffix)
        .def_readwrite("StatusDef", &UStatusMenuEquippedPanelGFxObject::StatusDef)
        .def_readwrite("CachedCurrentlySelectedCell", &UStatusMenuEquippedPanelGFxObject::CachedCurrentlySelectedCell)
        .def("ShowDualWieldInventoryGuides", &UStatusMenuEquippedPanelGFxObject::ShowDualWieldInventoryGuides)
        .def("CleanUpAfterCancelledDrag", &UStatusMenuEquippedPanelGFxObject::CleanUpAfterCancelledDrag)
        .def("PrepareForFinishDrag", &UStatusMenuEquippedPanelGFxObject::PrepareForFinishDrag)
        .def("CanFinishDragOnCell", &UStatusMenuEquippedPanelGFxObject::CanFinishDragOnCell)
        .def("OnStartDrag", &UStatusMenuEquippedPanelGFxObject::OnStartDrag)
        .def("SetCellMarkForIndex", &UStatusMenuEquippedPanelGFxObject::SetCellMarkForIndex)
        .def("SetCellMarkForThing", &UStatusMenuEquippedPanelGFxObject::SetCellMarkForThing)
        .def("extOnTrashFavChanged", &UStatusMenuEquippedPanelGFxObject::extOnTrashFavChanged)
        .def("GetMarkFromInventory", &UStatusMenuEquippedPanelGFxObject::GetMarkFromInventory)
        .def("SetCellInfo", &UStatusMenuEquippedPanelGFxObject::SetCellInfo)
        .def("GetSelectedCellInventoryType", &UStatusMenuEquippedPanelGFxObject::GetSelectedCellInventoryType)
        .def("GetSuffixFromQuickSlot", &UStatusMenuEquippedPanelGFxObject::GetSuffixFromQuickSlot)
        .def("GetWeaponSlotFromSuffix", &UStatusMenuEquippedPanelGFxObject::GetWeaponSlotFromSuffix)
        .def("GetWeaponSlotFromThing", &UStatusMenuEquippedPanelGFxObject::GetWeaponSlotFromThing)
        .def("GetHighlightedWeaponSlot", &UStatusMenuEquippedPanelGFxObject::GetHighlightedWeaponSlot)
        .def("GetTypeCellSuffixBasedOnPosition", &UStatusMenuEquippedPanelGFxObject::GetTypeCellSuffixBasedOnPosition)
        .def("GetTypeCellSuffixBasedOnThing", &UStatusMenuEquippedPanelGFxObject::GetTypeCellSuffixBasedOnThing)
        .def("IsAWeaponSuffix", &UStatusMenuEquippedPanelGFxObject::IsAWeaponSuffix)
        .def("StopEquip", &UStatusMenuEquippedPanelGFxObject::StopEquip)
        .def("SelectTypeCellBasedOnThing", &UStatusMenuEquippedPanelGFxObject::SelectTypeCellBasedOnThing)
        .def("StartEquip", &UStatusMenuEquippedPanelGFxObject::StartEquip)
        .def("EquippingMove", &UStatusMenuEquippedPanelGFxObject::EquippingMove)
        .def("extOnMouseUp", &UStatusMenuEquippedPanelGFxObject::extOnMouseUp)
        .def("extOnCellPressed", &UStatusMenuEquippedPanelGFxObject::extOnCellPressed)
        .def("extOnEquippedPanelPressed", &UStatusMenuEquippedPanelGFxObject::extOnEquippedPanelPressed)
        .def("NormalMove", &UStatusMenuEquippedPanelGFxObject::NormalMove)
        .def("RestoreCurrentSelectedCell", &UStatusMenuEquippedPanelGFxObject::RestoreCurrentSelectedCell)
        .def("CacheCurrentSelectedCellAndSetToNone", &UStatusMenuEquippedPanelGFxObject::CacheCurrentSelectedCellAndSetToNone)
        .def("ResetCacheCurrentSelectedCell", &UStatusMenuEquippedPanelGFxObject::ResetCacheCurrentSelectedCell)
        .def("GetCurrentSelectedCell", &UStatusMenuEquippedPanelGFxObject::GetCurrentSelectedCell, py::return_value_policy::reference)
        .def("extOnCellUnselected", &UStatusMenuEquippedPanelGFxObject::extOnCellUnselected)
        .def("extOnCellSelected", &UStatusMenuEquippedPanelGFxObject::extOnCellSelected)
        .def("GetThingByIndex", &UStatusMenuEquippedPanelGFxObject::GetThingByIndex, py::return_value_policy::reference)
        .def("GetSelectedThing", &UStatusMenuEquippedPanelGFxObject::GetSelectedThing, py::return_value_policy::reference)
        .def("SetCellsForEquipping", &UStatusMenuEquippedPanelGFxObject::SetCellsForEquipping)
        .def("SetSelectedCell", &UStatusMenuEquippedPanelGFxObject::SetSelectedCell)
        .def("PanelOnInputKey", &UStatusMenuEquippedPanelGFxObject::PanelOnInputKey)
        .def("SetReadyWeaponRight", &UStatusMenuEquippedPanelGFxObject::SetReadyWeaponRight)
        .def("SetReadyWeaponLeft", &UStatusMenuEquippedPanelGFxObject::SetReadyWeaponLeft)
        .def("FlourishWeaponLeft", &UStatusMenuEquippedPanelGFxObject::FlourishWeaponLeft)
        .def("FlourishWeaponRight", &UStatusMenuEquippedPanelGFxObject::FlourishWeaponRight)
        .def("SetUpEquippedSlotIcons", &UStatusMenuEquippedPanelGFxObject::SetUpEquippedSlotIcons)
        .def("Refresh", &UStatusMenuEquippedPanelGFxObject::Refresh)
        .def("Init", &UStatusMenuEquippedPanelGFxObject::Init)
        .def("MoveFunction", &UStatusMenuEquippedPanelGFxObject::MoveFunction)
          ;
}