#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UDecalComponent(py::module &m)
{
    py::class_< UDecalComponent,  UPrimitiveComponent   >(m, "UDecalComponent")
        .def_readwrite("DecalMaterial", &UDecalComponent::DecalMaterial)
        .def_readwrite("Width", &UDecalComponent::Width)
        .def_readwrite("Height", &UDecalComponent::Height)
        .def_readwrite("TileX", &UDecalComponent::TileX)
        .def_readwrite("TileY", &UDecalComponent::TileY)
        .def_readwrite("OffsetX", &UDecalComponent::OffsetX)
        .def_readwrite("OffsetY", &UDecalComponent::OffsetY)
        .def_readwrite("DecalRotation", &UDecalComponent::DecalRotation)
        .def_readwrite("FieldOfView", &UDecalComponent::FieldOfView)
        .def_readwrite("NearPlane", &UDecalComponent::NearPlane)
        .def_readwrite("FarPlane", &UDecalComponent::FarPlane)
        .def_readwrite("Location", &UDecalComponent::Location)
        .def_readwrite("Orientation", &UDecalComponent::Orientation)
        .def_readwrite("HitLocation", &UDecalComponent::HitLocation)
        .def_readwrite("HitNormal", &UDecalComponent::HitNormal)
        .def_readwrite("HitTangent", &UDecalComponent::HitTangent)
        .def_readwrite("HitBinormal", &UDecalComponent::HitBinormal)
        .def_readwrite("HitComponent", &UDecalComponent::HitComponent)
        .def_readwrite("HitBone", &UDecalComponent::HitBone)
        .def_readwrite("HitNodeIndex", &UDecalComponent::HitNodeIndex)
        .def_readwrite("HitLevelIndex", &UDecalComponent::HitLevelIndex)
        .def_readwrite("FracturedStaticMeshComponentIndex", &UDecalComponent::FracturedStaticMeshComponentIndex)
        .def_readwrite("HitNodeIndices", &UDecalComponent::HitNodeIndices)
        .def_readwrite("DecalReceivers", &UDecalComponent::DecalReceivers)
        .def_readwrite("StaticReceivers", &UDecalComponent::StaticReceivers)
        .def_readwrite("ReleaseResourcesFence", &UDecalComponent::ReleaseResourcesFence)
        .def_readwrite("Planes", &UDecalComponent::Planes)
        .def_readwrite("DepthBias", &UDecalComponent::DepthBias)
        .def_readwrite("SlopeScaleDepthBias", &UDecalComponent::SlopeScaleDepthBias)
        .def_readwrite("SortOrder", &UDecalComponent::SortOrder)
        .def_readwrite("BackfaceAngle", &UDecalComponent::BackfaceAngle)
        .def_readwrite("BlendRange", &UDecalComponent::BlendRange)
        .def_readwrite("StreamingDistanceMultiplier", &UDecalComponent::StreamingDistanceMultiplier)
        .def_readwrite("DecalTransform", &UDecalComponent::DecalTransform)
        .def_readwrite("FilterMode", &UDecalComponent::FilterMode)
        .def_readwrite("Filter", &UDecalComponent::Filter)
        .def_readwrite("ReceiverImages", &UDecalComponent::ReceiverImages)
        .def_readwrite("ParentRelativeLocation", &UDecalComponent::ParentRelativeLocation)
        .def_readwrite("ParentRelativeOrientation", &UDecalComponent::ParentRelativeOrientation)
        .def_readwrite("ParentRelLocRotMatrix", &UDecalComponent::ParentRelLocRotMatrix)
        .def("IsWaitingForResetToDefaultsToComplete", &UDecalComponent::IsWaitingForResetToDefaultsToComplete)
        .def("GetDecalMaterial", &UDecalComponent::GetDecalMaterial, py::return_value_policy::reference)
        .def("SetDecalMaterial", &UDecalComponent::SetDecalMaterial)
        .def("ResetToDefaults", &UDecalComponent::ResetToDefaults)
          ;
}