#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UProjectileDefinition()
{
    class_< UProjectileDefinition, bases< UGBXDefinition >  , boost::noncopyable>("UProjectileDefinition", no_init)
        .def_readwrite("VfTable_IIConstructObject", &UProjectileDefinition::VfTable_IIConstructObject)
        .def_readwrite("VfTable_IIBodyInfoProvider", &UProjectileDefinition::VfTable_IIBodyInfoProvider)
        .def_readwrite("VfTable_IIBehaviorProvider", &UProjectileDefinition::VfTable_IIBehaviorProvider)
        .def_readwrite("Mesh", &UProjectileDefinition::Mesh)
        .def_readwrite("AmbientAkEvent", &UProjectileDefinition::AmbientAkEvent)
        .def_readwrite("InFlightEffects", &UProjectileDefinition::InFlightEffects)
        .def_readwrite("InFlightEffectsOverrideContext", &UProjectileDefinition::InFlightEffectsOverrideContext)
        .def_readwrite("InFlightEffectsOverrideName", &UProjectileDefinition::InFlightEffectsOverrideName)
        .def_readwrite("InFlightEffectsScale", &UProjectileDefinition::InFlightEffectsScale)
        .def_readwrite("OverchargedPSCTemplate", &UProjectileDefinition::OverchargedPSCTemplate)
        .def_readwrite("TemporalField", &UProjectileDefinition::TemporalField)
        .def_readwrite("DamageTypeOverrideContext", &UProjectileDefinition::DamageTypeOverrideContext)
        .def_readwrite("DamageTypeOverrideName", &UProjectileDefinition::DamageTypeOverrideName)
        .def_readwrite("DefaultDamageTypeDefinition", &UProjectileDefinition::DefaultDamageTypeDefinition)
        .def_readwrite("BounceImpact", &UProjectileDefinition::BounceImpact)
        .def_readwrite("BounceImpactAkRtpc", &UProjectileDefinition::BounceImpactAkRtpc)
        .def_readwrite("ExplosionOverrideContext", &UProjectileDefinition::ExplosionOverrideContext)
        .def_readwrite("ExplosionOverrideName", &UProjectileDefinition::ExplosionOverrideName)
        .def_readwrite("DefaultExplosionDefinition", &UProjectileDefinition::DefaultExplosionDefinition)
        .def_readwrite("DamageTypeParameterName", &UProjectileDefinition::DamageTypeParameterName)
        .def_readwrite("RigidBodyImpactEffectThreshold", &UProjectileDefinition::RigidBodyImpactEffectThreshold)
        .def_readwrite("RigidBodyImpactEffectDelay", &UProjectileDefinition::RigidBodyImpactEffectDelay)
        .def_readwrite("CustomAimDirection", &UProjectileDefinition::CustomAimDirection)
        .def_readwrite("UpwardVelocityBonus", &UProjectileDefinition::UpwardVelocityBonus)
        .def_readwrite("SpeedFormula", &UProjectileDefinition::SpeedFormula)
        .def_readwrite("Speed", &UProjectileDefinition::Speed)
        .def_readwrite("PhysicsMode", &UProjectileDefinition::PhysicsMode)
        .def_readwrite("AutoAimProfile", &UProjectileDefinition::AutoAimProfile)
        .def_readwrite("ProjectileType", &UProjectileDefinition::ProjectileType)
        .def_readwrite("AtRestSpeedThreshold", &UProjectileDefinition::AtRestSpeedThreshold)
        .def_readwrite("GravityScaling", &UProjectileDefinition::GravityScaling)
        .def_readwrite("WaveAmp", &UProjectileDefinition::WaveAmp)
        .def_readwrite("WaveFreq", &UProjectileDefinition::WaveFreq)
        .def_readwrite("WavePhase", &UProjectileDefinition::WavePhase)
        .def_readwrite("BulletListenerComponent", &UProjectileDefinition::BulletListenerComponent)
        .def_readwrite("StickyChildSpawnCollisionIgnoreTime", &UProjectileDefinition::StickyChildSpawnCollisionIgnoreTime)
        .def_readwrite("Damage", &UProjectileDefinition::Damage)
        .def_readwrite("DamageRadius", &UProjectileDefinition::DamageRadius)
        .def_readwrite("MomentumTransfer", &UProjectileDefinition::MomentumTransfer)
        .def_readwrite("FuseTime", &UProjectileDefinition::FuseTime)
        .def_readwrite("NumberOfChildProjectiles", &UProjectileDefinition::NumberOfChildProjectiles)
        .def_readwrite("MaxLifespan", &UProjectileDefinition::MaxLifespan)
        .def_readwrite("Allegiance", &UProjectileDefinition::Allegiance)
        .def_readwrite("ViewGuideDistance", &UProjectileDefinition::ViewGuideDistance)
        .def_readwrite("ViewGuideLockOnAngle", &UProjectileDefinition::ViewGuideLockOnAngle)
        .def_readwrite("SearchRadius", &UProjectileDefinition::SearchRadius)
        .def_readwrite("TurningRadius", &UProjectileDefinition::TurningRadius)
        .def_readwrite("TurnThresholdTight", &UProjectileDefinition::TurnThresholdTight)
        .def_readwrite("TurnThresholdWide", &UProjectileDefinition::TurnThresholdWide)
        .def_readwrite("HomingRollAmt", &UProjectileDefinition::HomingRollAmt)
        .def_readwrite("HomingRollSpeed", &UProjectileDefinition::HomingRollSpeed)
        .def_readwrite("HomingThresholds", &UProjectileDefinition::HomingThresholds)
        .def_readwrite("HomingRotationRate", &UProjectileDefinition::HomingRotationRate)
        .def_readwrite("ProjectileClass", &UProjectileDefinition::ProjectileClass)
        .def_readwrite("Resource", &UProjectileDefinition::Resource)
        .def_readwrite("ResourceCost", &UProjectileDefinition::ResourceCost)
        .def_readwrite("ExpPoints", &UProjectileDefinition::ExpPoints)
        .def_readwrite("LightingBoundsScale", &UProjectileDefinition::LightingBoundsScale)
        .def_readwrite("ModShadowFadeoutExponent", &UProjectileDefinition::ModShadowFadeoutExponent)
        .def_readwrite("ModShadowFadeoutTime", &UProjectileDefinition::ModShadowFadeoutTime)
        .def_readwrite("AmbientGlow", &UProjectileDefinition::AmbientGlow)
        .def_readwrite("AmbientShadowSourceDirection", &UProjectileDefinition::AmbientShadowSourceDirection)
        .def_readwrite("AmbientShadowColor", &UProjectileDefinition::AmbientShadowColor)
        .def_readwrite("DominantShadowTransitionStartDistance", &UProjectileDefinition::DominantShadowTransitionStartDistance)
        .def_readwrite("DominantShadowTransitionEndDistance", &UProjectileDefinition::DominantShadowTransitionEndDistance)
        .def_readwrite("AIAvoidRadius", &UProjectileDefinition::AIAvoidRadius)
        .def_readwrite("FlashIconName", &UProjectileDefinition::FlashIconName)
        .def_readwrite("BodyComposition", &UProjectileDefinition::BodyComposition)
        .def_readwrite("BehaviorProviderDefinition", &UProjectileDefinition::BehaviorProviderDefinition)
        .def("StaticClass", &UProjectileDefinition::StaticClass, return_value_policy< reference_existing_object >())
        .def("SetBehaviorProviderDefinition", &UProjectileDefinition::SetBehaviorProviderDefinition)
        .def("GetBehaviorProviderDefinition", &UProjectileDefinition::GetBehaviorProviderDefinition, return_value_policy< reference_existing_object >())
        .def("OnHomingTargetChanged", &UProjectileDefinition::OnHomingTargetChanged)
        .def("OnReflected", &UProjectileDefinition::OnReflected)
        .def("OnTouchProximity", &UProjectileDefinition::OnTouchProximity)
        .def("OnHitTheWorld", &UProjectileDefinition::OnHitTheWorld)
        .def("OnHitDamagableObject", &UProjectileDefinition::OnHitDamagableObject)
        .def("OnKilledEnemy", &UProjectileDefinition::OnKilledEnemy)
        .def("OnKilledFriendly", &UProjectileDefinition::OnKilledFriendly)
        .def("OnKilledNeutral", &UProjectileDefinition::OnKilledNeutral)
        .def("OnDamagedNeutral", &UProjectileDefinition::OnDamagedNeutral)
        .def("OnDamagedFriendly", &UProjectileDefinition::OnDamagedFriendly)
        .def("OnDamagedEnemy", &UProjectileDefinition::OnDamagedEnemy)
        .def("OnCounterEvent", &UProjectileDefinition::OnCounterEvent)
        .def("OnTimerEvent", &UProjectileDefinition::OnTimerEvent)
        .def("OnTookDirectOrRadiusDamage", &UProjectileDefinition::OnTookDirectOrRadiusDamage)
        .def("OnTookRadiusDamage", &UProjectileDefinition::OnTookRadiusDamage)
        .def("OnTookDirectDamage", &UProjectileDefinition::OnTookDirectDamage)
        .def("OnComeToRest", &UProjectileDefinition::OnComeToRest)
        .def("OnHitWall", &UProjectileDefinition::OnHitWall)
        .def("OnHitShields", &UProjectileDefinition::OnHitShields)
        .def("OnHitArmor", &UProjectileDefinition::OnHitArmor)
        .def("OnHitFleshOrArmor", &UProjectileDefinition::OnHitFleshOrArmor)
        .def("OnHitFlesh", &UProjectileDefinition::OnHitFlesh)
        .def("OnTouched", &UProjectileDefinition::OnTouched)
        .def("OnHitWater", &UProjectileDefinition::OnHitWater)
        .def("OnExplode", &UProjectileDefinition::OnExplode)
        .def("OnSpawn", &UProjectileDefinition::OnSpawn)
        .staticmethod("StaticClass")
  ;
}