#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_USparkInterfaceImpl(py::module &m)
{
    py::class_< USparkInterfaceImpl,  UObject   >(m, "USparkInterfaceImpl")
		.def_static("StaticClass", &USparkInterfaceImpl::StaticClass, py::return_value_policy::reference)
        .def_readwrite("VfTable_ISparkInterface", &USparkInterfaceImpl::VfTable_ISparkInterface)
        .def_readwrite("VfTable_FTickableObject", &USparkInterfaceImpl::VfTable_FTickableObject)
        .def_readwrite("SparkInitialization", &USparkInterfaceImpl::SparkInitialization)
        .def_readwrite("SecondaryInitialization", &USparkInterfaceImpl::SecondaryInitialization)
        .def_readwrite("Accounts", &USparkInterfaceImpl::Accounts)
        .def_readwrite("LeviathanServiceClassName", &USparkInterfaceImpl::LeviathanServiceClassName)
        .def_readwrite("LeviathanSvc", &USparkInterfaceImpl::LeviathanSvc)
        .def_readwrite("ReadBufferSize", &USparkInterfaceImpl::ReadBufferSize)
        .def_readwrite("EmergencyMessage", &USparkInterfaceImpl::EmergencyMessage)
        .def_readwrite("Requests", &USparkInterfaceImpl::Requests)
        .def_readwrite("LastHttpRequestRetries", &USparkInterfaceImpl::LastHttpRequestRetries)
        .def_readwrite("LastHttpRequestResponseTime", &USparkInterfaceImpl::LastHttpRequestResponseTime)
        .def_readwrite("RecentHttpRequestFailures", &USparkInterfaceImpl::RecentHttpRequestFailures)
        .def_readwrite("InteractionMinWaitSeconds", &USparkInterfaceImpl::InteractionMinWaitSeconds)
        .def_readwrite("InteractionGraceTries", &USparkInterfaceImpl::InteractionGraceTries)
        .def_readwrite("InteractionPunishmentMinWaitSeconds", &USparkInterfaceImpl::InteractionPunishmentMinWaitSeconds)
        .def_readwrite("InteractionTries", &USparkInterfaceImpl::InteractionTries)
        .def_readwrite("TitleStorageService", &USparkInterfaceImpl::TitleStorageService)
        .def_readwrite("TitleStorageUrl", &USparkInterfaceImpl::TitleStorageUrl)
        .def_readwrite("NewsService", &USparkInterfaceImpl::NewsService)
        .def("GetNewsService", &USparkInterfaceImpl::GetNewsService, py::return_value_policy::reference)
        .def("GetTitleStorageServiceConfiguration", &USparkInterfaceImpl::GetTitleStorageServiceConfiguration, py::return_value_policy::reference)
        .def("GetTitleStorageUrl", &USparkInterfaceImpl::GetTitleStorageUrl)
        .def("OnSparkInitialized", &USparkInterfaceImpl::OnSparkInitialized)
        .def("IncreaseInteractionTries", &USparkInterfaceImpl::IncreaseInteractionTries)
        .def("GetInteractionTries", &USparkInterfaceImpl::GetInteractionTries)
        .def("GetInteractionGraceTries", &USparkInterfaceImpl::GetInteractionGraceTries)
        .def("GetInteractionPunishmentMinWaitSeconds", &USparkInterfaceImpl::GetInteractionPunishmentMinWaitSeconds)
        .def("GetInteractionMinWaitSeconds", &USparkInterfaceImpl::GetInteractionMinWaitSeconds)
        .def("ConvertUtcTimeToLocalTime", &USparkInterfaceImpl::ConvertUtcTimeToLocalTime)
        .def("ShouldUpdateEmergencyMessage", &USparkInterfaceImpl::ShouldUpdateEmergencyMessage)
        .def("GetEmergencyMessage", &USparkInterfaceImpl::GetEmergencyMessage)
        .def("SetEmergencyMessage", &USparkInterfaceImpl::SetEmergencyMessage)
        .def("IsTmsComplete", &USparkInterfaceImpl::IsTmsComplete)
        .def("SetTmsComplete", &USparkInterfaceImpl::SetTmsComplete)
        .def("RestartSparkInitializationFromScript", &USparkInterfaceImpl::RestartSparkInitializationFromScript)
        .def("eventRestartSparkInitialization", &USparkInterfaceImpl::eventRestartSparkInitialization)
        .def("StartSparkInitialization", &USparkInterfaceImpl::StartSparkInitialization)
        .def("ResetInitializationStatus", &USparkInterfaceImpl::ResetInitializationStatus)
        .def("ResetSecondaryInitializationStatus", &USparkInterfaceImpl::ResetSecondaryInitializationStatus)
        .def("StartSecondaryInitialization", &USparkInterfaceImpl::StartSecondaryInitialization)
        .def("GetSparkInitialization", &USparkInterfaceImpl::GetSparkInitialization, py::return_value_policy::reference)
        .def("SignInGearboxAccount", &USparkInterfaceImpl::SignInGearboxAccount)
        .def("eventGetGearboxAccountData", &USparkInterfaceImpl::eventGetGearboxAccountData, py::return_value_policy::reference)
        .def("SignOutGearboxAccount", &USparkInterfaceImpl::SignOutGearboxAccount)
        .def("ValidPlayerIndex", &USparkInterfaceImpl::ValidPlayerIndex)
        .def("GetPlayerIndex", &USparkInterfaceImpl::GetPlayerIndex)
        .def("ClearGearboxAccountData", &USparkInterfaceImpl::ClearGearboxAccountData)
        .def("IsGearboxAccountSignedIn", &USparkInterfaceImpl::IsGearboxAccountSignedIn)
        .def("eventIsGearboxAccountAuthenticated", &USparkInterfaceImpl::eventIsGearboxAccountAuthenticated)
        .def("GetGameName", &USparkInterfaceImpl::GetGameName)
        .def("GetHardwareName", &USparkInterfaceImpl::GetHardwareName)
        .def("GetPlatformName", &USparkInterfaceImpl::GetPlatformName)
        .def("GetPlatformTicket", &USparkInterfaceImpl::GetPlatformTicket)
        .def("ClearSparkConfigReceivedDelegate", &USparkInterfaceImpl::ClearSparkConfigReceivedDelegate)
        .def("AddSparkConfigReceivedDelegate", &USparkInterfaceImpl::AddSparkConfigReceivedDelegate)
        .def("GetPlatformLoginNameFromController", &USparkInterfaceImpl::GetPlatformLoginNameFromController)
        .def("eventGetPlatformLoginNameFromSplitscreenIndex", &USparkInterfaceImpl::eventGetPlatformLoginNameFromSplitscreenIndex)
        .def("eventGetPlatformLoginName", &USparkInterfaceImpl::eventGetPlatformLoginName)
        .def("eventGetLoginStatus", &USparkInterfaceImpl::eventGetLoginStatus)
        .def("eventIsShiftEnabled", &USparkInterfaceImpl::eventIsShiftEnabled)
        .def("eventIsSparkEnabled", &USparkInterfaceImpl::eventIsSparkEnabled)
        .def("WithShift", &USparkInterfaceImpl::WithShift)
        .def("WithSpark", &USparkInterfaceImpl::WithSpark)
        .def("IssueSparkStringRequest", &USparkInterfaceImpl::IssueSparkStringRequest)
        .def("IssueSparkRequest", &USparkInterfaceImpl::IssueSparkRequest)
        .def("AlternativeXboxlivePlatformId", &USparkInterfaceImpl::AlternativeXboxlivePlatformId)
        .def("OnSparkEmergencyMessageUpdated", &USparkInterfaceImpl::OnSparkEmergencyMessageUpdated)
        .def("OnSparkConfigReceived", &USparkInterfaceImpl::OnSparkConfigReceived)
        .def("OnSparkRequestComplete", &USparkInterfaceImpl::OnSparkRequestComplete)
          ;
}