#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UHashDisplayGFxMovie(py::module &m)
{
    py::class_< UHashDisplayGFxMovie,  UWillowGFxMovie   >(m, "UHashDisplayGFxMovie")
        .def_readwrite("WInvMgr", &UHashDisplayGFxMovie::WInvMgr)
        .def_readwrite("HashDisplayDef", &UHashDisplayGFxMovie::HashDisplayDef)
        .def_readwrite("LeftSideTextList", &UHashDisplayGFxMovie::LeftSideTextList)
        .def_readwrite("RTM", &UHashDisplayGFxMovie::RTM)
        .def_readwrite("Card1Tex", &UHashDisplayGFxMovie::Card1Tex)
        .def_readwrite("Card1Mesh", &UHashDisplayGFxMovie::Card1Mesh)
        .def_readwrite("SortConfigurations", &UHashDisplayGFxMovie::SortConfigurations)
        .def_readwrite("LeftSideSortConfigIndex", &UHashDisplayGFxMovie::LeftSideSortConfigIndex)
        .def_readwrite("UsedInvTypes", &UHashDisplayGFxMovie::UsedInvTypes)
        .def_readwrite("UsedManufacturers", &UHashDisplayGFxMovie::UsedManufacturers)
        .def_readwrite("UsedWeaponTypes", &UHashDisplayGFxMovie::UsedWeaponTypes)
        .def_readwrite("EquippedLabels", &UHashDisplayGFxMovie::EquippedLabels)
        .def_readwrite("EmptySlotText", &UHashDisplayGFxMovie::EmptySlotText)
        .def("StaticClass", &UHashDisplayGFxMovie::StaticClass, py::return_value_policy::reference)
        .def("ConfigureForPlayer", &UHashDisplayGFxMovie::ConfigureForPlayer)
        .def("FadePopup_AS", &UHashDisplayGFxMovie::FadePopup_AS)
        .def("ShowPopup_AS", &UHashDisplayGFxMovie::ShowPopup_AS)
        .def("ShowPopup", &UHashDisplayGFxMovie::ShowPopup)
        .def("SetAmmoCount", &UHashDisplayGFxMovie::SetAmmoCount)
        .def("SetAllAmmoCounts", &UHashDisplayGFxMovie::SetAllAmmoCounts)
        .def("ToggleSort", &UHashDisplayGFxMovie::ToggleSort)
        .def("UpdateCardPanelWithCurrentActiveListEntry", &UHashDisplayGFxMovie::UpdateCardPanelWithCurrentActiveListEntry)
        .def("UpdateCardPanel", &UHashDisplayGFxMovie::UpdateCardPanel)
        .def("GetHashDisplayStringForItem", &UHashDisplayGFxMovie::GetHashDisplayStringForItem)
        .def("GetHashDisplayStringForWeapon", &UHashDisplayGFxMovie::GetHashDisplayStringForWeapon)
        .def("MoveHighlightBar", &UHashDisplayGFxMovie::MoveHighlightBar)
        .def("SortContainer", &UHashDisplayGFxMovie::SortContainer)
        .def("SetupContainerWithData", &UHashDisplayGFxMovie::SetupContainerWithData)
        .def("StartClosing", &UHashDisplayGFxMovie::StartClosing)
        .def("extUpdateLeftListSize", &UHashDisplayGFxMovie::extUpdateLeftListSize)
        .def("extPopupFading", &UHashDisplayGFxMovie::extPopupFading)
        .def("SetCredits_Wrapper", &UHashDisplayGFxMovie::SetCredits_Wrapper)
        .def("SetCredits", &UHashDisplayGFxMovie::SetCredits)
        .def("extSetupScreen", &UHashDisplayGFxMovie::extSetupScreen)
        .def("HandleMove", &UHashDisplayGFxMovie::HandleMove)
        .def("PopupStateInputKey", &UHashDisplayGFxMovie::PopupStateInputKey)
        .def("NormalStateInputKey", &UHashDisplayGFxMovie::NormalStateInputKey)
        .def("MainInputKey", &UHashDisplayGFxMovie::MainInputKey)
        .def("eventOnClose", &UHashDisplayGFxMovie::eventOnClose)
        .def("eventStart", &UHashDisplayGFxMovie::eventStart)
        .def("OnStatefulInputKey", &UHashDisplayGFxMovie::OnStatefulInputKey)
          ;
}