#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UAudioComponent()
{
    class_< UAudioComponent, bases< UActorComponent >  , boost::noncopyable>("UAudioComponent", no_init)
        .def_readwrite("SoundCue", &UAudioComponent::SoundCue)
        .def_readwrite("CueFirstNode", &UAudioComponent::CueFirstNode)
        .def_readwrite("InstanceParameters", &UAudioComponent::InstanceParameters)
        .def_readwrite("StereoBleed", &UAudioComponent::StereoBleed)
        .def_readwrite("LFEBleed", &UAudioComponent::LFEBleed)
        .def_readwrite("WaveInstances", &UAudioComponent::WaveInstances)
        .def_readwrite("SoundNodeData", &UAudioComponent::SoundNodeData)
        .def_readonly("UnknownData00", &UAudioComponent::UnknownData00)
        .def_readwrite("SoundNodeResetWaveMap", &UAudioComponent::SoundNodeResetWaveMap)
        .def_readwrite("Listener", &UAudioComponent::Listener)
        .def_readwrite("PlaybackTime", &UAudioComponent::PlaybackTime)
        .def_readwrite("PortalVolume", &UAudioComponent::PortalVolume)
        .def_readwrite("Location", &UAudioComponent::Location)
        .def_readwrite("ComponentLocation", &UAudioComponent::ComponentLocation)
        .def_readwrite("LastOwner", &UAudioComponent::LastOwner)
        .def_readwrite("SubtitlePriority", &UAudioComponent::SubtitlePriority)
        .def_readwrite("FadeInStartTime", &UAudioComponent::FadeInStartTime)
        .def_readwrite("FadeInStopTime", &UAudioComponent::FadeInStopTime)
        .def_readwrite("FadeInTargetVolume", &UAudioComponent::FadeInTargetVolume)
        .def_readwrite("FadeOutStartTime", &UAudioComponent::FadeOutStartTime)
        .def_readwrite("FadeOutStopTime", &UAudioComponent::FadeOutStopTime)
        .def_readwrite("FadeOutTargetVolume", &UAudioComponent::FadeOutTargetVolume)
        .def_readwrite("AdjustVolumeStartTime", &UAudioComponent::AdjustVolumeStartTime)
        .def_readwrite("AdjustVolumeStopTime", &UAudioComponent::AdjustVolumeStopTime)
        .def_readwrite("AdjustVolumeTargetVolume", &UAudioComponent::AdjustVolumeTargetVolume)
        .def_readwrite("CurrAdjustVolumeTargetVolume", &UAudioComponent::CurrAdjustVolumeTargetVolume)
        .def_readwrite("CurrentNotifyBufferFinishedHook", &UAudioComponent::CurrentNotifyBufferFinishedHook)
        .def_readwrite("CurrentLocation", &UAudioComponent::CurrentLocation)
        .def_readwrite("CurrentVolume", &UAudioComponent::CurrentVolume)
        .def_readwrite("CurrentPitch", &UAudioComponent::CurrentPitch)
        .def_readwrite("CurrentHighFrequencyGain", &UAudioComponent::CurrentHighFrequencyGain)
        .def_readwrite("CurrentUseSpatialization", &UAudioComponent::CurrentUseSpatialization)
        .def_readwrite("CurrentNotifyOnLoop", &UAudioComponent::CurrentNotifyOnLoop)
        .def_readwrite("CurrentVolumeMultiplier", &UAudioComponent::CurrentVolumeMultiplier)
        .def_readwrite("CurrentPitchMultiplier", &UAudioComponent::CurrentPitchMultiplier)
        .def_readwrite("CurrentHighFrequencyGainMultiplier", &UAudioComponent::CurrentHighFrequencyGainMultiplier)
        .def_readwrite("CurrentVoiceCenterChannelVolume", &UAudioComponent::CurrentVoiceCenterChannelVolume)
        .def_readwrite("CurrentRadioFilterVolume", &UAudioComponent::CurrentRadioFilterVolume)
        .def_readwrite("CurrentRadioFilterVolumeThreshold", &UAudioComponent::CurrentRadioFilterVolumeThreshold)
        .def_readwrite("LastUpdateTime", &UAudioComponent::LastUpdateTime)
        .def_readwrite("SourceInteriorVolume", &UAudioComponent::SourceInteriorVolume)
        .def_readwrite("SourceInteriorLPF", &UAudioComponent::SourceInteriorLPF)
        .def_readwrite("CurrentInteriorVolume", &UAudioComponent::CurrentInteriorVolume)
        .def_readwrite("CurrentInteriorLPF", &UAudioComponent::CurrentInteriorLPF)
        .def_readwrite("LastLocation", &UAudioComponent::LastLocation)
        .def_readwrite("LastInteriorSettings", &UAudioComponent::LastInteriorSettings)
        .def_readwrite("LastReverbVolumeIndex", &UAudioComponent::LastReverbVolumeIndex)
        .def_readwrite("VolumeMultiplier", &UAudioComponent::VolumeMultiplier)
        .def_readwrite("PitchMultiplier", &UAudioComponent::PitchMultiplier)
        .def_readwrite("HighFrequencyGainMultiplier", &UAudioComponent::HighFrequencyGainMultiplier)
        .def_readwrite("OcclusionCheckInterval", &UAudioComponent::OcclusionCheckInterval)
        .def_readwrite("LastOcclusionCheckTime", &UAudioComponent::LastOcclusionCheckTime)
        .def_readwrite("PreviewSoundRadius", &UAudioComponent::PreviewSoundRadius)
        .def("StaticClass", &UAudioComponent::StaticClass, return_value_policy< reference_existing_object >())
        .def("eventOcclusionChanged", &UAudioComponent::eventOcclusionChanged)
        .def("OnQueueSubtitles", &UAudioComponent::OnQueueSubtitles)
        .def("OnAudioFinished", &UAudioComponent::OnAudioFinished)
        .def("ResetToDefaults", &UAudioComponent::ResetToDefaults)
        .def("SetWaveParameter", &UAudioComponent::SetWaveParameter)
        .def("SetFloatParameter", &UAudioComponent::SetFloatParameter)
        .def("AdjustVolume", &UAudioComponent::AdjustVolume)
        .def("FadeOut", &UAudioComponent::FadeOut)
        .def("FadeIn", &UAudioComponent::FadeIn)
        .def("IsFadingOut", &UAudioComponent::IsFadingOut)
        .def("IsFadingIn", &UAudioComponent::IsFadingIn)
        .def("IsPlaying", &UAudioComponent::IsPlaying)
        .def("Stop", &UAudioComponent::Stop)
        .def("Play", &UAudioComponent::Play)
        .staticmethod("StaticClass")
  ;
}