#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UOnlineGameInterface(py::object m)
{
    py::class_< UOnlineGameInterface,  UInterface   >(m, "UOnlineGameInterface")
        .def("StaticClass", &UOnlineGameInterface::StaticClass, py::return_value_policy::reference)
        .def("HasPendingBootInvite", &UOnlineGameInterface::HasPendingBootInvite)
        .def("CancelNATNegotiation", &UOnlineGameInterface::CancelNATNegotiation)
        .def("ClearJoinMigratedOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearJoinMigratedOnlineGameCompleteDelegate)
        .def("AddJoinMigratedOnlineGameCompleteDelegate", &UOnlineGameInterface::AddJoinMigratedOnlineGameCompleteDelegate)
        .def("OnJoinMigratedOnlineGameComplete", &UOnlineGameInterface::OnJoinMigratedOnlineGameComplete)
        .def("JoinMigratedOnlineGame", &UOnlineGameInterface::JoinMigratedOnlineGame)
        .def("ClearMigrateOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearMigrateOnlineGameCompleteDelegate)
        .def("AddMigrateOnlineGameCompleteDelegate", &UOnlineGameInterface::AddMigrateOnlineGameCompleteDelegate)
        .def("OnMigrateOnlineGameComplete", &UOnlineGameInterface::OnMigrateOnlineGameComplete)
        .def("MigrateOnlineGame", &UOnlineGameInterface::MigrateOnlineGame)
        .def("ClearRecalculateSkillRatingCompleteDelegate", &UOnlineGameInterface::ClearRecalculateSkillRatingCompleteDelegate)
        .def("AddRecalculateSkillRatingCompleteDelegate", &UOnlineGameInterface::AddRecalculateSkillRatingCompleteDelegate)
        .def("OnRecalculateSkillRatingComplete", &UOnlineGameInterface::OnRecalculateSkillRatingComplete)
        .def("RecalculateSkillRating", &UOnlineGameInterface::RecalculateSkillRating)
        .def("ClearGameInviteProcessingStartedDelegate", &UOnlineGameInterface::ClearGameInviteProcessingStartedDelegate)
        .def("AddGameInviteProcessingStartedDelegate", &UOnlineGameInterface::AddGameInviteProcessingStartedDelegate)
        .def("OnGameInviteProcessingStarted", &UOnlineGameInterface::OnGameInviteProcessingStarted)
        .def("AcceptGameInvite", &UOnlineGameInterface::AcceptGameInvite)
        .def("ClearGameInviteAcceptedDelegate", &UOnlineGameInterface::ClearGameInviteAcceptedDelegate)
        .def("AddGameInviteAcceptedDelegate", &UOnlineGameInterface::AddGameInviteAcceptedDelegate)
        .def("OnGameInviteAccepted", &UOnlineGameInterface::OnGameInviteAccepted)
        .def("GetArbitratedPlayers", &UOnlineGameInterface::GetArbitratedPlayers)
        .def("ClearArbitrationRegistrationCompleteDelegate", &UOnlineGameInterface::ClearArbitrationRegistrationCompleteDelegate)
        .def("AddArbitrationRegistrationCompleteDelegate", &UOnlineGameInterface::AddArbitrationRegistrationCompleteDelegate)
        .def("OnArbitrationRegistrationComplete", &UOnlineGameInterface::OnArbitrationRegistrationComplete)
        .def("RegisterForArbitration", &UOnlineGameInterface::RegisterForArbitration)
        .def("ClearEndOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearEndOnlineGameCompleteDelegate)
        .def("AddEndOnlineGameCompleteDelegate", &UOnlineGameInterface::AddEndOnlineGameCompleteDelegate)
        .def("OnEndOnlineGameComplete", &UOnlineGameInterface::OnEndOnlineGameComplete)
        .def("EndOnlineGame", &UOnlineGameInterface::EndOnlineGame)
        .def("ClearStartOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearStartOnlineGameCompleteDelegate)
        .def("AddStartOnlineGameCompleteDelegate", &UOnlineGameInterface::AddStartOnlineGameCompleteDelegate)
        .def("OnStartOnlineGameComplete", &UOnlineGameInterface::OnStartOnlineGameComplete)
        .def("StartOnlineGame", &UOnlineGameInterface::StartOnlineGame)
        .def("ClearUnregisterPlayerCompleteDelegate", &UOnlineGameInterface::ClearUnregisterPlayerCompleteDelegate)
        .def("AddUnregisterPlayerCompleteDelegate", &UOnlineGameInterface::AddUnregisterPlayerCompleteDelegate)
        .def("OnUnregisterPlayerComplete", &UOnlineGameInterface::OnUnregisterPlayerComplete)
        .def("UnregisterPlayers", &UOnlineGameInterface::UnregisterPlayers)
        .def("UnregisterPlayer", &UOnlineGameInterface::UnregisterPlayer)
        .def("ClearRegisterPlayerCompleteDelegate", &UOnlineGameInterface::ClearRegisterPlayerCompleteDelegate)
        .def("AddRegisterPlayerCompleteDelegate", &UOnlineGameInterface::AddRegisterPlayerCompleteDelegate)
        .def("OnRegisterPlayerComplete", &UOnlineGameInterface::OnRegisterPlayerComplete)
        .def("RegisterPlayers", &UOnlineGameInterface::RegisterPlayers)
        .def("RegisterPlayer", &UOnlineGameInterface::RegisterPlayer)
        .def("GetResolvedConnectString", &UOnlineGameInterface::GetResolvedConnectString)
        .def("ClearJoinOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearJoinOnlineGameCompleteDelegate)
        .def("AddJoinOnlineGameCompleteDelegate", &UOnlineGameInterface::AddJoinOnlineGameCompleteDelegate)
        .def("OnJoinOnlineGameComplete", &UOnlineGameInterface::OnJoinOnlineGameComplete)
        .def("JoinOnlineGame", &UOnlineGameInterface::JoinOnlineGame)
        .def("QueryNonAdvertisedData", &UOnlineGameInterface::QueryNonAdvertisedData)
        .def("FreeSearchResults", &UOnlineGameInterface::FreeSearchResults)
        .def("GetGameSearch", &UOnlineGameInterface::GetGameSearch, py::return_value_policy::reference)
        .def("BindPlatformSpecificSessionToSearch", &UOnlineGameInterface::BindPlatformSpecificSessionToSearch)
        .def("ReadPlatformSpecificSessionInfoBySessionName", &UOnlineGameInterface::ReadPlatformSpecificSessionInfoBySessionName)
        .def("ReadPlatformSpecificSessionInfo", &UOnlineGameInterface::ReadPlatformSpecificSessionInfo)
        .def("ClearQosStatusChangedDelegate", &UOnlineGameInterface::ClearQosStatusChangedDelegate)
        .def("AddQosStatusChangedDelegate", &UOnlineGameInterface::AddQosStatusChangedDelegate)
        .def("OnQosStatusChanged", &UOnlineGameInterface::OnQosStatusChanged)
        .def("ClearCancelFindOnlineGamesCompleteDelegate", &UOnlineGameInterface::ClearCancelFindOnlineGamesCompleteDelegate)
        .def("AddCancelFindOnlineGamesCompleteDelegate", &UOnlineGameInterface::AddCancelFindOnlineGamesCompleteDelegate)
        .def("OnCancelFindOnlineGamesComplete", &UOnlineGameInterface::OnCancelFindOnlineGamesComplete)
        .def("CancelFindOnlineGames", &UOnlineGameInterface::CancelFindOnlineGames)
        .def("ClearFindOnlineGamesCompleteDelegate", &UOnlineGameInterface::ClearFindOnlineGamesCompleteDelegate)
        .def("AddFindOnlineGamesCompleteDelegate", &UOnlineGameInterface::AddFindOnlineGamesCompleteDelegate)
        .def("OnFindOnlineGamesComplete", &UOnlineGameInterface::OnFindOnlineGamesComplete)
        .def("FindOnlineGames", &UOnlineGameInterface::FindOnlineGames)
        .def("ClearDestroyOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearDestroyOnlineGameCompleteDelegate)
        .def("AddDestroyOnlineGameCompleteDelegate", &UOnlineGameInterface::AddDestroyOnlineGameCompleteDelegate)
        .def("OnDestroyOnlineGameComplete", &UOnlineGameInterface::OnDestroyOnlineGameComplete)
        .def("DestroyOnlineGame", &UOnlineGameInterface::DestroyOnlineGame)
        .def("GetGameSettings", &UOnlineGameInterface::GetGameSettings, py::return_value_policy::reference)
        .def("ClearUpdateOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearUpdateOnlineGameCompleteDelegate)
        .def("AddUpdateOnlineGameCompleteDelegate", &UOnlineGameInterface::AddUpdateOnlineGameCompleteDelegate)
        .def("OnUpdateOnlineGameComplete", &UOnlineGameInterface::OnUpdateOnlineGameComplete)
        .def("UpdateOnlineGame", &UOnlineGameInterface::UpdateOnlineGame)
        .def("ClearCreateOnlineGameCompleteDelegate", &UOnlineGameInterface::ClearCreateOnlineGameCompleteDelegate)
        .def("AddCreateOnlineGameCompleteDelegate", &UOnlineGameInterface::AddCreateOnlineGameCompleteDelegate)
        .def("OnCreateOnlineGameComplete", &UOnlineGameInterface::OnCreateOnlineGameComplete)
        .def("CreateOnlineGame", &UOnlineGameInterface::CreateOnlineGame)
          ;
}