#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UParticleSystemComponent(py::object m)
{
    py::class_< UParticleSystemComponent,  UPrimitiveComponent   >(m, "UParticleSystemComponent")
        .def_readwrite("Template", &UParticleSystemComponent::Template)
        .def_readwrite("LightEnvironmentClass", &UParticleSystemComponent::LightEnvironmentClass)
        .def_readwrite("LightEnvironmentSharedInstigator", &UParticleSystemComponent::LightEnvironmentSharedInstigator)
        .def_readwrite("MaxLightEnvironmentPooledReuses", &UParticleSystemComponent::MaxLightEnvironmentPooledReuses)
        .def_readwrite("EmitterInstances", &UParticleSystemComponent::EmitterInstances)
        .def_readwrite("SMComponents", &UParticleSystemComponent::SMComponents)
        .def_readwrite("SMMaterialInterfaces", &UParticleSystemComponent::SMMaterialInterfaces)
        .def_readwrite("SkelMeshComponents", &UParticleSystemComponent::SkelMeshComponents)
        .def_readwrite("ViewMBInfoArray", &UParticleSystemComponent::ViewMBInfoArray)
        .def_readwrite("InstanceParameters", &UParticleSystemComponent::InstanceParameters)
        .def_readwrite("OldPosition", &UParticleSystemComponent::OldPosition)
        .def_readwrite("PartSysVelocity", &UParticleSystemComponent::PartSysVelocity)
        .def_readwrite("WarmupTime", &UParticleSystemComponent::WarmupTime)
        .def_readwrite("LODLevel", &UParticleSystemComponent::LODLevel)
        .def_readwrite("SecondsBeforeInactive", &UParticleSystemComponent::SecondsBeforeInactive)
        .def_readwrite("TimeSinceLastForceUpdateTransform", &UParticleSystemComponent::TimeSinceLastForceUpdateTransform)
        .def_readwrite("MaxTimeBeforeForceUpdateTransform", &UParticleSystemComponent::MaxTimeBeforeForceUpdateTransform)
        .def_readwrite("AccumTickTime", &UParticleSystemComponent::AccumTickTime)
        .def_readwrite("LODMethod", &UParticleSystemComponent::LODMethod)
        .def_readwrite("ReplayState", &UParticleSystemComponent::ReplayState)
        .def_readwrite("CachedViewRelevanceFlags", &UParticleSystemComponent::CachedViewRelevanceFlags)
        .def_readwrite("ReplayClips", &UParticleSystemComponent::ReplayClips)
        .def_readwrite("ReplayClipIDNumber", &UParticleSystemComponent::ReplayClipIDNumber)
        .def_readwrite("ReplayFrameIndex", &UParticleSystemComponent::ReplayFrameIndex)
        .def_readwrite("AccumLODDistanceCheckTime", &UParticleSystemComponent::AccumLODDistanceCheckTime)
        .def_readwrite("SpawnEvents", &UParticleSystemComponent::SpawnEvents)
        .def_readwrite("DeathEvents", &UParticleSystemComponent::DeathEvents)
        .def_readwrite("CollisionEvents", &UParticleSystemComponent::CollisionEvents)
        .def_readwrite("TraceEvents", &UParticleSystemComponent::TraceEvents)
        .def_readwrite("KismetEvents", &UParticleSystemComponent::KismetEvents)
        .def_readwrite("ReleaseResourcesFence", &UParticleSystemComponent::ReleaseResourcesFence)
        .def_readwrite("CustomTimeDilation", &UParticleSystemComponent::CustomTimeDilation)
        .def_readwrite("EmitterDelay", &UParticleSystemComponent::EmitterDelay)
        .def_readwrite("AudioEventDelay", &UParticleSystemComponent::AudioEventDelay)
        .def_readwrite("LoopingAkPlayingInfo", &UParticleSystemComponent::LoopingAkPlayingInfo)
        .def("StaticClass", &UParticleSystemComponent::StaticClass, py::return_value_policy::reference)
        .def("Behavior_ChangeParticleSystemActiveState", &UParticleSystemComponent::Behavior_ChangeParticleSystemActiveState)
        .def("Behavior_SetVectorParameterValue", &UParticleSystemComponent::Behavior_SetVectorParameterValue)
        .def("Behavior_SetColorParameterValue", &UParticleSystemComponent::Behavior_SetColorParameterValue)
        .def("Behavior_SetObjectParameterValue", &UParticleSystemComponent::Behavior_SetObjectParameterValue)
        .def("Behavior_SetFloatParameterValue", &UParticleSystemComponent::Behavior_SetFloatParameterValue)
        .def("Behavior_GetObjectParameterValue", &UParticleSystemComponent::Behavior_GetObjectParameterValue)
        .def("Behavior_GetVectorParameterValue", &UParticleSystemComponent::Behavior_GetVectorParameterValue)
        .def("Behavior_GetColorParameterValue", &UParticleSystemComponent::Behavior_GetColorParameterValue)
        .def("Behavior_GetFloatParameterValue", &UParticleSystemComponent::Behavior_GetFloatParameterValue)
        .def("SetStopSpawning", &UParticleSystemComponent::SetStopSpawning)
        .def("ResetToDefaults", &UParticleSystemComponent::ResetToDefaults)
        .def("SetActive", &UParticleSystemComponent::SetActive)
        .def("ClearParameter", &UParticleSystemComponent::ClearParameter)
        .def("GetMaterialParameter", &UParticleSystemComponent::GetMaterialParameter)
        .def("GetActorParameter", &UParticleSystemComponent::GetActorParameter)
        .def("GetColorParameter", &UParticleSystemComponent::GetColorParameter)
        .def("GetVectorParameter", &UParticleSystemComponent::GetVectorParameter)
        .def("GetFloatParameter", &UParticleSystemComponent::GetFloatParameter)
        .def("SetMaterialParameter", &UParticleSystemComponent::SetMaterialParameter)
        .def("SetActorParameter", &UParticleSystemComponent::SetActorParameter)
        .def("SetColorParameter", &UParticleSystemComponent::SetColorParameter)
        .def("SetVectorRandParameter", &UParticleSystemComponent::SetVectorRandParameter)
        .def("SetVectorParameter", &UParticleSystemComponent::SetVectorParameter)
        .def("SetFloatRandParameter", &UParticleSystemComponent::SetFloatRandParameter)
        .def("SetFloatParameter", &UParticleSystemComponent::SetFloatParameter)
        .def("GetEditorLODLevel", &UParticleSystemComponent::GetEditorLODLevel)
        .def("GetLODLevel", &UParticleSystemComponent::GetLODLevel)
        .def("SetEditorLODLevel", &UParticleSystemComponent::SetEditorLODLevel)
        .def("SetLODLevel", &UParticleSystemComponent::SetLODLevel)
        .def("SystemHasCompleted", &UParticleSystemComponent::SystemHasCompleted)
        .def("GetMaxLifespan", &UParticleSystemComponent::GetMaxLifespan)
        .def("DetermineLODLevelForLocation", &UParticleSystemComponent::DetermineLODLevelForLocation)
        .def("SetBeamTargetStrength", &UParticleSystemComponent::SetBeamTargetStrength)
        .def("SetBeamTargetTangent", &UParticleSystemComponent::SetBeamTargetTangent)
        .def("SetBeamTargetPoint", &UParticleSystemComponent::SetBeamTargetPoint)
        .def("SetBeamSourceStrength", &UParticleSystemComponent::SetBeamSourceStrength)
        .def("SetBeamSourceTangent", &UParticleSystemComponent::SetBeamSourceTangent)
        .def("SetBeamSourcePoint", &UParticleSystemComponent::SetBeamSourcePoint)
        .def("SetBeamDistance", &UParticleSystemComponent::SetBeamDistance)
        .def("SetBeamEndPoint", &UParticleSystemComponent::SetBeamEndPoint)
        .def("SetBeamTessellationFactor", &UParticleSystemComponent::SetBeamTessellationFactor)
        .def("SetBeamType", &UParticleSystemComponent::SetBeamType)
        .def("RewindEmitterInstances", &UParticleSystemComponent::RewindEmitterInstances)
        .def("RewindEmitterInstance", &UParticleSystemComponent::RewindEmitterInstance)
        .def("SetKillOnCompleted", &UParticleSystemComponent::SetKillOnCompleted)
        .def("SetKillOnDeactivate", &UParticleSystemComponent::SetKillOnDeactivate)
        .def("GetSkipBoundsUpdate", &UParticleSystemComponent::GetSkipBoundsUpdate)
        .def("SetSkipBoundsUpdate", &UParticleSystemComponent::SetSkipBoundsUpdate)
        .def("GetSkipUpdateDynamicDataDuringTick", &UParticleSystemComponent::GetSkipUpdateDynamicDataDuringTick)
        .def("SetSkipUpdateDynamicDataDuringTick", &UParticleSystemComponent::SetSkipUpdateDynamicDataDuringTick)
        .def("KillParticlesInEmitter", &UParticleSystemComponent::KillParticlesInEmitter)
        .def("KillParticlesForced", &UParticleSystemComponent::KillParticlesForced)
        .def("DeactivateSystem", &UParticleSystemComponent::DeactivateSystem)
        .def("ActivateSystem", &UParticleSystemComponent::ActivateSystem)
        .def("SetTemplate", &UParticleSystemComponent::SetTemplate)
        .def("OnSystemFinished", &UParticleSystemComponent::OnSystemFinished)
          ;
}