#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UBaseTopLevelPanelGFxObject()
{
    class_< UBaseTopLevelPanelGFxObject, bases< UGFxObject >  , boost::noncopyable>("UBaseTopLevelPanelGFxObject", no_init)
        .def_readwrite("ParentMovie", &UBaseTopLevelPanelGFxObject::ParentMovie)
        .def_readwrite("ParentMovieDef", &UBaseTopLevelPanelGFxObject::ParentMovieDef)
        .def_readwrite("ItemCards", &UBaseTopLevelPanelGFxObject::ItemCards)
        .def_readwrite("QueuedTriggerKey", &UBaseTopLevelPanelGFxObject::QueuedTriggerKey)
        .def_readwrite("QueuedInputKey", &UBaseTopLevelPanelGFxObject::QueuedInputKey)
        .def("StaticClass", &UBaseTopLevelPanelGFxObject::StaticClass, return_value_policy< reference_existing_object >())
        .def("OnTrashFavChanged", &UBaseTopLevelPanelGFxObject::OnTrashFavChanged)
        .def("OnCellPressed", &UBaseTopLevelPanelGFxObject::OnCellPressed)
        .def("OnStartDrag", &UBaseTopLevelPanelGFxObject::OnStartDrag)
        .def("GetInspectedItemCurrencyType", &UBaseTopLevelPanelGFxObject::GetInspectedItemCurrencyType)
        .def("GetInspectedItemOverridePrice", &UBaseTopLevelPanelGFxObject::GetInspectedItemOverridePrice)
        .def("SetComparingTweenInfo", &UBaseTopLevelPanelGFxObject::SetComparingTweenInfo)
        .def("GetCard", &UBaseTopLevelPanelGFxObject::GetCard)
        .def("OnItemSelected", &UBaseTopLevelPanelGFxObject::OnItemSelected)
        .def("UpdateDynamicCard", &UBaseTopLevelPanelGFxObject::UpdateDynamicCard)
        .def("SetUpCardEx", &UBaseTopLevelPanelGFxObject::SetUpCardEx)
        .def("SetUpCard", &UBaseTopLevelPanelGFxObject::SetUpCard)
        .def("GetItemCardContentIndex", &UBaseTopLevelPanelGFxObject::GetItemCardContentIndex)
        .def("GetItemCard", &UBaseTopLevelPanelGFxObject::GetItemCard, return_value_policy< reference_existing_object >())
        .def("GetItemCardInfo", &UBaseTopLevelPanelGFxObject::GetItemCardInfo)
        .def("GetPanel", &UBaseTopLevelPanelGFxObject::GetPanel)
        .def("extInitComplete", &UBaseTopLevelPanelGFxObject::extInitComplete)
        .def("extInitRightPanel", &UBaseTopLevelPanelGFxObject::extInitRightPanel)
        .def("extInitLeftPanel", &UBaseTopLevelPanelGFxObject::extInitLeftPanel)
        .def("InitPanels", &UBaseTopLevelPanelGFxObject::InitPanels)
        .def("AssignPanels", &UBaseTopLevelPanelGFxObject::AssignPanels)
        .def("extInitPanels", &UBaseTopLevelPanelGFxObject::extInitPanels)
        .def("RefreshItemCards", &UBaseTopLevelPanelGFxObject::RefreshItemCards)
        .def("InitItemCards", &UBaseTopLevelPanelGFxObject::InitItemCards)
        .def("AssignItemCards", &UBaseTopLevelPanelGFxObject::AssignItemCards)
        .def("extInitItemCards", &UBaseTopLevelPanelGFxObject::extInitItemCards)
        .def("SetActivePanelByName", &UBaseTopLevelPanelGFxObject::SetActivePanelByName)
        .def("OnPanelPressed", &UBaseTopLevelPanelGFxObject::OnPanelPressed)
        .def("TweenPanel", &UBaseTopLevelPanelGFxObject::TweenPanel)
        .def("TweenPanelToPosition", &UBaseTopLevelPanelGFxObject::TweenPanelToPosition)
        .def("SetFocusUnfocusedCompareTweenPositions", &UBaseTopLevelPanelGFxObject::SetFocusUnfocusedCompareTweenPositions)
        .def("SwitchToQueuedInputHandler", &UBaseTopLevelPanelGFxObject::SwitchToQueuedInputHandler)
        .def("QueueNewInputHandler", &UBaseTopLevelPanelGFxObject::QueueNewInputHandler)
        .def("Init", &UBaseTopLevelPanelGFxObject::Init)
        .def("OnInputKey", &UBaseTopLevelPanelGFxObject::OnInputKey)
        .staticmethod("StaticClass")
  ;
}