#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_AWillowPickup(py::object m)
{
    py::class_< AWillowPickup,  ADroppedPickup   >(m, "AWillowPickup")
        .def_readwrite("VfTable_IIMission", &AWillowPickup::VfTable_IIMission)
        .def_readwrite("VfTable_IIMissionDirector", &AWillowPickup::VfTable_IIMissionDirector)
        .def_readwrite("VfTable_IIFocusable", &AWillowPickup::VfTable_IIFocusable)
        .def_readwrite("PickupParticleComponent", &AWillowPickup::PickupParticleComponent)
        .def_readwrite("PickupParticles", &AWillowPickup::PickupParticles)
        .def_readonly("UnknownData00", &AWillowPickup::UnknownData00)
        .def_readwrite("RBState", &AWillowPickup::RBState)
        .def_readwrite("AngErrorAccumulator", &AWillowPickup::AngErrorAccumulator)
        .def_readwrite("LifeSpanType", &AWillowPickup::LifeSpanType)
        .def_readwrite("CostsToPickUpType", &AWillowPickup::CostsToPickUpType)
        .def_readwrite("VeryShortLivedDropLifeSpan", &AWillowPickup::VeryShortLivedDropLifeSpan)
        .def_readwrite("ShortLivedDropLifeSpan", &AWillowPickup::ShortLivedDropLifeSpan)
        .def_readwrite("LongLivedDropLifeSpan", &AWillowPickup::LongLivedDropLifeSpan)
        .def_readwrite("PickupShrinkDuration", &AWillowPickup::PickupShrinkDuration)
        .def_readwrite("MaxRBAwakeTime", &AWillowPickup::MaxRBAwakeTime)
        .def_readwrite("ImpactEffectPlayCount", &AWillowPickup::ImpactEffectPlayCount)
        .def_readwrite("LastImpactEffectTime", &AWillowPickup::LastImpactEffectTime)
        .def_readwrite("MaxImpactEffectPlayCount", &AWillowPickup::MaxImpactEffectPlayCount)
        .def_readwrite("ImpactEffectDelay", &AWillowPickup::ImpactEffectDelay)
        .def_readwrite("ImpactVelocityAkRtpc", &AWillowPickup::ImpactVelocityAkRtpc)
        .def_readwrite("MissionDirectorParticle", &AWillowPickup::MissionDirectorParticle)
        .def_readwrite("InventoryRarityLevel", &AWillowPickup::InventoryRarityLevel)
        .def_readwrite("AlwaysRelevantDistanceSquared", &AWillowPickup::AlwaysRelevantDistanceSquared)
        .def_readwrite("DynamicLightEnvironment", &AWillowPickup::DynamicLightEnvironment)
        .def_readwrite("InteractionIconOverride", &AWillowPickup::InteractionIconOverride)
        .def_readwrite("CostsToPickUpAmount", &AWillowPickup::CostsToPickUpAmount)
        .def_readwrite("PickedUpByActor", &AWillowPickup::PickedUpByActor)
        .def("StaticClass", &AWillowPickup::StaticClass, py::return_value_policy::reference)
        .def("OnPlayerClosedMissionUI", &AWillowPickup::OnPlayerClosedMissionUI)
        .def("OnPlayerOpenedMissionUI", &AWillowPickup::OnPlayerOpenedMissionUI)
        .def("SetInteractionIcon", &AWillowPickup::SetInteractionIcon)
        .def("CanSplash", &AWillowPickup::CanSplash)
        .def("HasAnyMissionsForPlayer", &AWillowPickup::HasAnyMissionsForPlayer)
        .def("GetMissionDirectorLocation", &AWillowPickup::GetMissionDirectorLocation)
        .def("GetAllDirectorData", &AWillowPickup::GetAllDirectorData)
        .def("GetFocusScreenOffset", &AWillowPickup::GetFocusScreenOffset)
        .def("GetFocusRadius", &AWillowPickup::GetFocusRadius)
        .def("GetFocusLocation", &AWillowPickup::GetFocusLocation)
        .def("EndFocus", &AWillowPickup::EndFocus)
        .def("BeginFocus", &AWillowPickup::BeginFocus)
        .def("eventBeginShrinking", &AWillowPickup::eventBeginShrinking)
        .def("PickedUpBy", &AWillowPickup::PickedUpBy)
        .def("GiveTo", &AWillowPickup::GiveTo)
        .def("CreatePickupFromMemento", &AWillowPickup::CreatePickupFromMemento, py::return_value_policy::reference)
        .def("eventConvertFixedToRigidBody", &AWillowPickup::eventConvertFixedToRigidBody)
        .def("eventConvertRigidBodyToFixed", &AWillowPickup::eventConvertRigidBodyToFixed)
        .def("FailedPickup", &AWillowPickup::FailedPickup)
        .def("GetMemento", &AWillowPickup::GetMemento)
        .def("AdjustPickupPhysicsAndCollisionForBeingDropped", &AWillowPickup::AdjustPickupPhysicsAndCollisionForBeingDropped)
        .def("AdjustPickupPhysicsAndCollisionForBeingAttached", &AWillowPickup::AdjustPickupPhysicsAndCollisionForBeingAttached)
        .def("AttachPickupToWorldBody", &AWillowPickup::AttachPickupToWorldBody)
        .def("GetPickupableMeshActor", &AWillowPickup::GetPickupableMeshActor, py::return_value_policy::reference)
        .def("Pickupable_IsEnabled", &AWillowPickup::Pickupable_IsEnabled)
        .def("SetSaveRotation", &AWillowPickup::SetSaveRotation)
        .def("GetSaveRotation", &AWillowPickup::GetSaveRotation)
        .def("Behavior_Destroy", &AWillowPickup::Behavior_Destroy)
        .def("SetMissionMaterialParameter", &AWillowPickup::SetMissionMaterialParameter)
        .def("SetPickupability", &AWillowPickup::SetPickupability)
        .def("Behavior_ChangeUsabilityCost", &AWillowPickup::Behavior_ChangeUsabilityCost)
        .def("Behavior_ChangeUsability", &AWillowPickup::Behavior_ChangeUsability)
        .def("DestroyPickupParticles", &AWillowPickup::DestroyPickupParticles)
        .def("SpawnPickupParticles", &AWillowPickup::SpawnPickupParticles)
        .def("GetPickupParticleOffset", &AWillowPickup::GetPickupParticleOffset)
        .def("SetInteractParticles", &AWillowPickup::SetInteractParticles)
        .def("TryToSetInteractParticles", &AWillowPickup::TryToSetInteractParticles)
        .def("PickupAtRest", &AWillowPickup::PickupAtRest)
        .def("eventLanded", &AWillowPickup::eventLanded)
        .def("CheckForRigidBodySleepState", &AWillowPickup::CheckForRigidBodySleepState)
        .def("MaxRBAwakeTimer", &AWillowPickup::MaxRBAwakeTimer)
        .def("StartRigidBodyTimers", &AWillowPickup::StartRigidBodyTimers)
        .def("eventRigidBodyCollision", &AWillowPickup::eventRigidBodyCollision)
        .def("EnableRagdollCollision", &AWillowPickup::EnableRagdollCollision)
        .def("InitializePickupForRBPhysics", &AWillowPickup::InitializePickupForRBPhysics)
        .def("InventoryAssociated", &AWillowPickup::InventoryAssociated)
        .def("UpdateTouchRadiusForAutomaticallyPickedUpInventory", &AWillowPickup::UpdateTouchRadiusForAutomaticallyPickedUpInventory)
        .def("InitializeRBPhysics", &AWillowPickup::InitializeRBPhysics)
        .def("CanBeGrabbedByTheAI", &AWillowPickup::CanBeGrabbedByTheAI)
        .def("ShouldSaveInPopulationSystem", &AWillowPickup::ShouldSaveInPopulationSystem)
        .def("ShrinkPickupBeforeDestruction", &AWillowPickup::ShrinkPickupBeforeDestruction)
        .def("InitializeDropLifespan", &AWillowPickup::InitializeDropLifespan)
        .def("eventDeactivateMissionDirectorParticle", &AWillowPickup::eventDeactivateMissionDirectorParticle)
        .def("eventSetMissionDirectorParticle", &AWillowPickup::eventSetMissionDirectorParticle)
        .def("eventMissionStatusChanged", &AWillowPickup::eventMissionStatusChanged)
        .def("OnPlayerTurnedInMission", &AWillowPickup::OnPlayerTurnedInMission)
        .def("OnPlayerAcceptedMission", &AWillowPickup::OnPlayerAcceptedMission)
        .def("GetEligibleMissions", &AWillowPickup::GetEligibleMissions)
        .def("GetInProgressMissions", &AWillowPickup::GetInProgressMissions)
        .def("GetRedeemableMissions", &AWillowPickup::GetRedeemableMissions)
        .def("eventAddMissionDirective", &AWillowPickup::eventAddMissionDirective)
        .def("RegisterMissionDirector", &AWillowPickup::RegisterMissionDirector)
        .def("DenyPickupAttempt", &AWillowPickup::DenyPickupAttempt)
        .def("eventMissionReactionObjectiveComplete", &AWillowPickup::eventMissionReactionObjectiveComplete)
        .def("eventMissionReactionObjectiveCleared", &AWillowPickup::eventMissionReactionObjectiveCleared)
        .def("eventMissionReactionObjectiveUpdated", &AWillowPickup::eventMissionReactionObjectiveUpdated)
        .def("eventMissionReactionObjectiveSetChanged", &AWillowPickup::eventMissionReactionObjectiveSetChanged)
        .def("eventMissionReactionStatusChanged", &AWillowPickup::eventMissionReactionStatusChanged)
        .def("eventMissionReactionLevelLoad", &AWillowPickup::eventMissionReactionLevelLoad)
        .def("CheckRemoveWaypoint", &AWillowPickup::CheckRemoveWaypoint)
        .def("SetPickupStatusFromMissionTracker", &AWillowPickup::SetPickupStatusFromMissionTracker)
        .def("InitializeFromInventory", &AWillowPickup::InitializeFromInventory)
        .def("WaitingForDefinitionForRegisterMissionDirector", &AWillowPickup::WaitingForDefinitionForRegisterMissionDirector)
        .def("eventReplicatedEvent", &AWillowPickup::eventReplicatedEvent)
        .def("eventDestroyed", &AWillowPickup::eventDestroyed)
        .def("PostBeginPlay", &AWillowPickup::PostBeginPlay)
          ;
}