#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UVehicleClassDefinition(py::module &m)
{
    py::class_< UVehicleClassDefinition,  UGBXDefinition   >(m, "UVehicleClassDefinition")
        .def_readwrite("VfTable_IIBehaviorProvider", &UVehicleClassDefinition::VfTable_IIBehaviorProvider)
        .def_readwrite("BehaviorProviderDefinition", &UVehicleClassDefinition::BehaviorProviderDefinition)
        .def_readwrite("VehicleImpactDamage", &UVehicleClassDefinition::VehicleImpactDamage)
        .def_readwrite("VehicleRunOverDamage", &UVehicleClassDefinition::VehicleRunOverDamage)
        .def_readwrite("VehicleFeedbackDamage", &UVehicleClassDefinition::VehicleFeedbackDamage)
        .def_readwrite("DelayBetweenCollisionDamageDealtToSelf", &UVehicleClassDefinition::DelayBetweenCollisionDamageDealtToSelf)
        .def_readwrite("Seats", &UVehicleClassDefinition::Seats)
        .def_readwrite("SpeedVDamageCurve", &UVehicleClassDefinition::SpeedVDamageCurve)
        .def_readwrite("NormalDamageModifiers", &UVehicleClassDefinition::NormalDamageModifiers)
        .def_readwrite("ExplosiveDamageModifiers", &UVehicleClassDefinition::ExplosiveDamageModifiers)
        .def_readwrite("ShockDamageModifiers", &UVehicleClassDefinition::ShockDamageModifiers)
        .def_readwrite("CorrosiveDamageModifiers", &UVehicleClassDefinition::CorrosiveDamageModifiers)
        .def_readwrite("IncendiaryDamageModifiers", &UVehicleClassDefinition::IncendiaryDamageModifiers)
        .def_readwrite("AmpDamageModifiers", &UVehicleClassDefinition::AmpDamageModifiers)
        .def_readwrite("IgniteResistanceModifiers", &UVehicleClassDefinition::IgniteResistanceModifiers)
        .def_readwrite("ShockResistanceModifiers", &UVehicleClassDefinition::ShockResistanceModifiers)
        .def_readwrite("CorrosiveResistanceModifiers", &UVehicleClassDefinition::CorrosiveResistanceModifiers)
        .def_readwrite("AmpResistanceModifiers", &UVehicleClassDefinition::AmpResistanceModifiers)
        .def_readwrite("DisplayName", &UVehicleClassDefinition::DisplayName)
        .def_readwrite("HealthPoolDefinition", &UVehicleClassDefinition::HealthPoolDefinition)
        .def_readwrite("DeathImpulseScalar", &UVehicleClassDefinition::DeathImpulseScalar)
        .def_readwrite("PlayerShieldDamagePercentOnVehicleDeath", &UVehicleClassDefinition::PlayerShieldDamagePercentOnVehicleDeath)
        .def_readwrite("PlayerHealthDamagePercentOnVehicleDeath", &UVehicleClassDefinition::PlayerHealthDamagePercentOnVehicleDeath)
        .def_readwrite("RestThreshold", &UVehicleClassDefinition::RestThreshold)
        .def_readwrite("AfterburnerSpeed", &UVehicleClassDefinition::AfterburnerSpeed)
        .def_readwrite("AfterburnerForceMagnitude", &UVehicleClassDefinition::AfterburnerForceMagnitude)
        .def_readwrite("AfterburnerActivationSpeed", &UVehicleClassDefinition::AfterburnerActivationSpeed)
        .def_readwrite("AfterburnerMinSpeed", &UVehicleClassDefinition::AfterburnerMinSpeed)
        .def_readwrite("AfterburnerMinSpeedTimeoutDuration", &UVehicleClassDefinition::AfterburnerMinSpeedTimeoutDuration)
        .def_readwrite("AfterburnerCameraShake", &UVehicleClassDefinition::AfterburnerCameraShake)
        .def_readwrite("AfterburnerCameraShakeRepeatTime", &UVehicleClassDefinition::AfterburnerCameraShakeRepeatTime)
        .def_readwrite("AfterburnerBoostTime", &UVehicleClassDefinition::AfterburnerBoostTime)
        .def_readwrite("AfterburnerMaxFOV", &UVehicleClassDefinition::AfterburnerMaxFOV)
        .def_readwrite("AfterburnerImpulseOrigin", &UVehicleClassDefinition::AfterburnerImpulseOrigin)
        .def_readwrite("AfterburnerPoolDefinition", &UVehicleClassDefinition::AfterburnerPoolDefinition)
        .def_readwrite("AfterburnerBrakingBonus", &UVehicleClassDefinition::AfterburnerBrakingBonus)
        .def_readwrite("AfterburnerImpulse", &UVehicleClassDefinition::AfterburnerImpulse)
        .def_readwrite("AfterburnerChassisTorqueScalar", &UVehicleClassDefinition::AfterburnerChassisTorqueScalar)
        .def_readwrite("AfterburnerTorqueBonus", &UVehicleClassDefinition::AfterburnerTorqueBonus)
        .def_readwrite("AfterburnerTorqueDecayRate", &UVehicleClassDefinition::AfterburnerTorqueDecayRate)
        .def_readwrite("AfterburnerRumble", &UVehicleClassDefinition::AfterburnerRumble)
        .def_readwrite("BrakingRumble", &UVehicleClassDefinition::BrakingRumble)
        .def_readwrite("BrakingRumbleScaleAdjustment", &UVehicleClassDefinition::BrakingRumbleScaleAdjustment)
        .def_readwrite("SkidParticleScale", &UVehicleClassDefinition::SkidParticleScale)
        .def_readwrite("SkidParticleScaleDecaySpeed", &UVehicleClassDefinition::SkidParticleScaleDecaySpeed)
        .def_readwrite("SkidParticleMinVehicleSpeed", &UVehicleClassDefinition::SkidParticleMinVehicleSpeed)
        .def_readwrite("FOV", &UVehicleClassDefinition::FOV)
        .def_readwrite("DefaultFOVModifierSpeed", &UVehicleClassDefinition::DefaultFOVModifierSpeed)
        .def_readwrite("AfterburnerOnFOVModifierSpeed", &UVehicleClassDefinition::AfterburnerOnFOVModifierSpeed)
        .def_readwrite("AfterburnerOffFOVModifierSpeed", &UVehicleClassDefinition::AfterburnerOffFOVModifierSpeed)
        .def_readwrite("PlayerSpeed", &UVehicleClassDefinition::PlayerSpeed)
        .def_readwrite("AIPatrolSpeed", &UVehicleClassDefinition::AIPatrolSpeed)
        .def_readwrite("AIPursuitSpeed", &UVehicleClassDefinition::AIPursuitSpeed)
        .def_readwrite("AICatchUpSpeed", &UVehicleClassDefinition::AICatchUpSpeed)
        .def_readwrite("AIMatchDistance", &UVehicleClassDefinition::AIMatchDistance)
        .def_readwrite("AIAdjustDistance", &UVehicleClassDefinition::AIAdjustDistance)
        .def_readwrite("AISpeedModifier", &UVehicleClassDefinition::AISpeedModifier)
        .def_readwrite("AIDirectionModifier", &UVehicleClassDefinition::AIDirectionModifier)
        .def_readwrite("AITargetSpeedLimit", &UVehicleClassDefinition::AITargetSpeedLimit)
        .def_readwrite("TargetableSocket", &UVehicleClassDefinition::TargetableSocket)
        .def_readwrite("DefaultRootRotationMode", &UVehicleClassDefinition::DefaultRootRotationMode)
        .def_readwrite("DefaultRootTranslationMode", &UVehicleClassDefinition::DefaultRootTranslationMode)
        .def_readwrite("RotationRate", &UVehicleClassDefinition::RotationRate)
        .def_readwrite("CrewAnimSetLookupTable", &UVehicleClassDefinition::CrewAnimSetLookupTable)
        .def_readwrite("StatNameFirstTimeUse", &UVehicleClassDefinition::StatNameFirstTimeUse)
        .def("StaticClass", &UVehicleClassDefinition::StaticClass, py::return_value_policy::reference)
        .def("GetSpeedDamageModifier", &UVehicleClassDefinition::GetSpeedDamageModifier)
        .def("GetEjectionVelocity", &UVehicleClassDefinition::GetEjectionVelocity)
        .def("GetSeatIndexFromPrefix", &UVehicleClassDefinition::GetSeatIndexFromPrefix)
        .def("GetEnterAnim", &UVehicleClassDefinition::GetEnterAnim, py::return_value_policy::reference)
        .def("EvaluateDamageFormula", &UVehicleClassDefinition::EvaluateDamageFormula)
        .def("OnReverseLightsDeactivated", &UVehicleClassDefinition::OnReverseLightsDeactivated)
        .def("OnReverseLightsActivated", &UVehicleClassDefinition::OnReverseLightsActivated)
        .def("OnBrakeLightsDeactivated", &UVehicleClassDefinition::OnBrakeLightsDeactivated)
        .def("OnBrakeLightsActivated", &UVehicleClassDefinition::OnBrakeLightsActivated)
        .def("OnHeadlightsDeactivated", &UVehicleClassDefinition::OnHeadlightsDeactivated)
        .def("OnHeadlightsActivated", &UVehicleClassDefinition::OnHeadlightsActivated)
        .def("OnSeatExited", &UVehicleClassDefinition::OnSeatExited)
        .def("OnSeatEntered", &UVehicleClassDefinition::OnSeatEntered)
        .def("OnSpawn", &UVehicleClassDefinition::OnSpawn)
        .def("OnStopHandbrake", &UVehicleClassDefinition::OnStopHandbrake)
        .def("OnStartHandbrake", &UVehicleClassDefinition::OnStartHandbrake)
        .def("OnTurretStoppedRotation", &UVehicleClassDefinition::OnTurretStoppedRotation)
        .def("OnTurretRotated", &UVehicleClassDefinition::OnTurretRotated)
        .def("OnCollision", &UVehicleClassDefinition::OnCollision)
        .def("OnTakeDamage", &UVehicleClassDefinition::OnTakeDamage)
        .def("OnDestroy", &UVehicleClassDefinition::OnDestroy)
        .def("OnKilledBy", &UVehicleClassDefinition::OnKilledBy)
        .def("OnDeath", &UVehicleClassDefinition::OnDeath)
        .def("OnAfterburnerDisengaged", &UVehicleClassDefinition::OnAfterburnerDisengaged)
        .def("OnAfterburnerEngaged", &UVehicleClassDefinition::OnAfterburnerEngaged)
        .def("OnPlayHorn", &UVehicleClassDefinition::OnPlayHorn)
        .def("ProcessSeatEvent", &UVehicleClassDefinition::ProcessSeatEvent)
        .def("GetCollisionDamageTypeForSpeed", &UVehicleClassDefinition::GetCollisionDamageTypeForSpeed, py::return_value_policy::reference)
        .def("SetBehaviorProviderDefinition", &UVehicleClassDefinition::SetBehaviorProviderDefinition)
        .def("GetBehaviorProviderDefinition", &UVehicleClassDefinition::GetBehaviorProviderDefinition, py::return_value_policy::reference)
          ;
}