#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UITargetable()
{
    py::class_< UITargetable,  UInterface   >("UITargetable")
        .def("StaticClass", &UITargetable::StaticClass, py::return_value_policy::reference)
        .def("SetPatsy", &UITargetable::SetPatsy)
        .def("GetPatsy", &UITargetable::GetPatsy, py::return_value_policy::reference)
        .def("IsBeingHealed", &UITargetable::IsBeingHealed)
        .def("SetBeingHealed", &UITargetable::SetBeingHealed)
        .def("IsBoss", &UITargetable::IsBoss)
        .def("Behavior_RegisterTargetable", &UITargetable::Behavior_RegisterTargetable)
        .def("IsTargetableProxy", &UITargetable::IsTargetableProxy)
        .def("GetAutoAimProfile", &UITargetable::GetAutoAimProfile)
        .def("GetMagnetismRange", &UITargetable::GetMagnetismRange)
        .def("GetMagnetismOrigin", &UITargetable::GetMagnetismOrigin)
        .def("IsAutoAimTarget", &UITargetable::IsAutoAimTarget)
        .def("GetTargetingModifier", &UITargetable::GetTargetingModifier)
        .def("HasHomingTargetComponents", &UITargetable::HasHomingTargetComponents)
        .def("IsValidHomingTarget", &UITargetable::IsValidHomingTarget)
        .def("GetTargetableIsHidden", &UITargetable::GetTargetableIsHidden)
        .def("CanSnapZoom", &UITargetable::CanSnapZoom)
        .def("GetSnapLocation", &UITargetable::GetSnapLocation)
        .def("GetTargetableLocation", &UITargetable::GetTargetableLocation)
        .def("Behavior_SetCanTarget", &UITargetable::Behavior_SetCanTarget)
        .def("IsTargetable", &UITargetable::IsTargetable)
        .def("ShowSelfAsTarget", &UITargetable::ShowSelfAsTarget)
        .def("GetOpinion", &UITargetable::GetOpinion)
        .def("SetAllegiance", &UITargetable::SetAllegiance)
        .def("GetDefaultAllegiance", &UITargetable::GetDefaultAllegiance, py::return_value_policy::reference)
        .def("GetObjectAllegiance", &UITargetable::GetObjectAllegiance, py::return_value_policy::reference)
        .def("IsSameAllegiance", &UITargetable::IsSameAllegiance)
        .def("IsNeutral", &UITargetable::IsNeutral)
        .def("IsFriendly", &UITargetable::IsFriendly)
        .def("IsEnemy", &UITargetable::IsEnemy)
        .def("SetInfoBarVisibility", &UITargetable::SetInfoBarVisibility)
        .def("HideTargetInfoOnHud", &UITargetable::HideTargetInfoOnHud)
        .def("IsChampion", &UITargetable::IsChampion)
        .def("eventGetTargetName", &UITargetable::eventGetTargetName)
        .def("DoesTargetableTakeDamage", &UITargetable::DoesTargetableTakeDamage)
        .def("DisplayParentInfo", &UITargetable::DisplayParentInfo)
        .def("GetAllBarInfo", &UITargetable::GetAllBarInfo)
        .def("GetExpInfo", &UITargetable::GetExpInfo)
        .def("GetTargetableActor", &UITargetable::GetTargetableActor, py::return_value_policy::reference)
        .staticmethod("StaticClass")
  ;
}