#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UAction_GoToScriptedDestination(py::module &m)
{
    py::class_< UAction_GoToScriptedDestination,  UWillowActionSequencePawn   >(m, "UAction_GoToScriptedDestination")
        .def_readwrite("FindLookAtTargetTime", &UAction_GoToScriptedDestination::FindLookAtTargetTime)
        .def_readwrite("PerchData", &UAction_FollowPath::PerchData)
        .def_readwrite("MoveNode", &UAction_FollowPath::MoveNode)
        .def_readwrite("NextNode", &UAction_FollowPath::NextNode)
        .def_readwrite("LastPathFailTime", &UAction_FollowPath::LastPathFailTime)
        .def_readwrite("TimeToStopLooping", &UAction_FollowPath::TimeToStopLooping)
        .def_readwrite("BurrowEnter", &UAction_Burrow::BurrowEnter)
        .def_readwrite("BurrowExit", &UAction_Burrow::BurrowExit)
        .def("StaticClass", &UAction_GoToScriptedDestination::StaticClass, py::return_value_policy::reference)
        .def("FindLookAtTarget", &UAction_GoToScriptedDestination::FindLookAtTarget)
        .def("ReachedFormation", &UAction_GoToScriptedDestination::ReachedFormation)
        .def("CanFollowFormationOwner", &UAction_GoToScriptedDestination::CanFollowFormationOwner)
        .def("InRange", &UAction_GoToScriptedDestination::InRange)
        .def("WantsPath", &UAction_GoToScriptedDestination::WantsPath)
        .def("SetMoveNode", &UAction_GoToScriptedDestination::SetMoveNode)
        .def("GetMoveNode", &UAction_GoToScriptedDestination::GetMoveNode, py::return_value_policy::reference)
        .def("SetMoveNodeSpeed", &UAction_GoToScriptedDestination::SetMoveNodeSpeed)
        .def("GetDefaultMoveNodeSpeed", &UAction_GoToScriptedDestination::GetDefaultMoveNodeSpeed)
        .def("SetMoveFacingPolicy", &UAction_GoToScriptedDestination::SetMoveFacingPolicy)
        .def("LookAtScriptedFocus", &UAction_GoToScriptedDestination::LookAtScriptedFocus)
        .def("CheckStateTransition", &UAction_GoToScriptedDestination::CheckStateTransition)
        .def("GetDesiredStateName", &UAction_GoToScriptedDestination::GetDesiredStateName)
        .def("ShouldLookAtPlayer", &UAction_GoToScriptedDestination::ShouldLookAtPlayer)
        .def("eventActivateEvent", &UAction_GoToScriptedDestination::eventActivateEvent)
        .def("eventUpdate", &UAction_GoToScriptedDestination::eventUpdate)
        .def("eventStop", &UAction_GoToScriptedDestination::eventStop)
        .def("eventStart", &UAction_GoToScriptedDestination::eventStart)
        .def("eventCanRun", &UAction_GoToScriptedDestination::eventCanRun)
        .def("PathAttemptFinished", &UAction_FollowPath::PathAttemptFinished)
        .def("PerchStop", &UAction_FollowPath::PerchStop)
        .def("PerchDone", &UAction_FollowPath::PerchDone)
        .def("PerchPlayStop", &UAction_FollowPath::PerchPlayStop)
        .def("PerchPlayLoop", &UAction_FollowPath::PerchPlayLoop)
        .def("PerchPlayIdle", &UAction_FollowPath::PerchPlayIdle)
        .def("PerchStart", &UAction_FollowPath::PerchStart)
        .def("GetPerchConsumerHandle", &UAction_FollowPath::GetPerchConsumerHandle)
        .def("SetPerch", &UAction_FollowPath::SetPerch)
        .def("SpecialMoveCallback", &UAction_FollowPath::SpecialMoveCallback)
        .def("SetSpecialMoves", &UAction_FollowPath::SetSpecialMoves)
        .def("MoveTimerCallback", &UAction_FollowPath::MoveTimerCallback)
        .def("SetMoveTimer", &UAction_FollowPath::SetMoveTimer)
        .def("CheckCloaked", &UAction_Burrow::CheckCloaked)
        .def("SafeToUncloak", &UAction_Burrow::SafeToUncloak)
        .def("ForceUncloak", &UAction_Burrow::ForceUncloak)
        .def("ForceCloak", &UAction_Burrow::ForceCloak)
          ;
}