#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_USkillDefinition()
{
    py::class_< USkillDefinition,  UGBXDefinition   >("USkillDefinition")
        .def_readwrite("VfTable_IIConstructObject", &USkillDefinition::VfTable_IIConstructObject)
        .def_readwrite("VfTable_IIBehaviorProvider", &USkillDefinition::VfTable_IIBehaviorProvider)
        .def_readwrite("SkillEffectUpdateIterval", &USkillDefinition::SkillEffectUpdateIterval)
        .def_readwrite("SkillName", &USkillDefinition::SkillName)
        .def_readwrite("SkillDescription", &USkillDefinition::SkillDescription)
        .def_readwrite("ScaleformFrameName", &USkillDefinition::ScaleformFrameName)
        .def_readwrite("SkillType", &USkillDefinition::SkillType)
        .def_readwrite("DurationType", &USkillDefinition::DurationType)
        .def_readwrite("TrackedSkillType", &USkillDefinition::TrackedSkillType)
        .def_readwrite("TrackedSkillHUDSlot", &USkillDefinition::TrackedSkillHUDSlot)
        .def_readwrite("InitialDuration", &USkillDefinition::InitialDuration)
        .def_readwrite("BaseRange", &USkillDefinition::BaseRange)
        .def_readwrite("EffectSourceInstanceDataName", &USkillDefinition::EffectSourceInstanceDataName)
        .def_readwrite("SkillEffectDefinitions", &USkillDefinition::SkillEffectDefinitions)
        .def_readwrite("SkillConstraints", &USkillDefinition::SkillConstraints)
        .def_readwrite("SkillEffectPresentations", &USkillDefinition::SkillEffectPresentations)
        .def_readwrite("ActionSkillArchetype", &USkillDefinition::ActionSkillArchetype)
        .def_readwrite("SkillActivationActions", &USkillDefinition::SkillActivationActions)
        .def_readwrite("SkillDeactivationActions", &USkillDefinition::SkillDeactivationActions)
        .def_readwrite("EventResponses", &USkillDefinition::EventResponses)
        .def_readwrite("DefaultStartingGrade", &USkillDefinition::DefaultStartingGrade)
        .def_readwrite("MaxGrade", &USkillDefinition::MaxGrade)
        .def_readwrite("PlayerLevelRequirement", &USkillDefinition::PlayerLevelRequirement)
        .def_readwrite("SkillIcon", &USkillDefinition::SkillIcon)
        .def_readwrite("CustomStackCount", &USkillDefinition::CustomStackCount)
        .def_readwrite("TrackedActiveSkill", &USkillDefinition::TrackedActiveSkill)
        .def_readwrite("TrackedActiveSkills", &USkillDefinition::TrackedActiveSkills)
        .def_readwrite("SkillClass", &USkillDefinition::SkillClass)
        .def_readwrite("LockedSkillDetailStr", &USkillDefinition::LockedSkillDetailStr)
        .def_readwrite("CustomEvents", &USkillDefinition::CustomEvents)
        .def_readwrite("DamageEvents", &USkillDefinition::DamageEvents)
        .def_readwrite("KillEvents", &USkillDefinition::KillEvents)
        .def_readwrite("BehaviorProviderDefinition", &USkillDefinition::BehaviorProviderDefinition)
        .def("StaticClass", &USkillDefinition::StaticClass, py::return_value_policy::reference)
        .def("FireCustomEvent", &USkillDefinition::FireCustomEvent)
        .def("DoesSkillPassMinGradeTest", &USkillDefinition::DoesSkillPassMinGradeTest)
        .def("GetSkillEffectPresentations", &USkillDefinition::GetSkillEffectPresentations)
        .def("GetHumanReadableSkillEffects", &USkillDefinition::GetHumanReadableSkillEffects)
        .def("SetBehaviorProviderDefinition", &USkillDefinition::SetBehaviorProviderDefinition)
        .def("GetBehaviorProviderDefinition", &USkillDefinition::GetBehaviorProviderDefinition, py::return_value_policy::reference)
        .def("OnStatusEffectTypeEnd", &USkillDefinition::OnStatusEffectTypeEnd)
        .def("OnStatusEffectTypeBegin", &USkillDefinition::OnStatusEffectTypeBegin)
        .def("OnMeleeAttack", &USkillDefinition::OnMeleeAttack)
        .def("OnBledOut", &USkillDefinition::OnBledOut)
        .def("OnDownStateEnd", &USkillDefinition::OnDownStateEnd)
        .def("OnDownStateBegin", &USkillDefinition::OnDownStateBegin)
        .def("OnAppliedStatusEffectToEnemy", &USkillDefinition::OnAppliedStatusEffectToEnemy)
        .def("OnDamagedEnemyWithMeleeFromBehind", &USkillDefinition::OnDamagedEnemyWithMeleeFromBehind)
        .def("OnDamagedUnawareEnemy", &USkillDefinition::OnDamagedUnawareEnemy)
        .def("OnActionSkillActiveAbilityActivated", &USkillDefinition::OnActionSkillActiveAbilityActivated)
        .def("OnActionSkillCooldownAbilityActivated", &USkillDefinition::OnActionSkillCooldownAbilityActivated)
        .def("OnPlayerResurrected", &USkillDefinition::OnPlayerResurrected)
        .def("OnPlayerRecoveredFromDownState", &USkillDefinition::OnPlayerRecoveredFromDownState)
        .def("OnPlayerDeathAverted", &USkillDefinition::OnPlayerDeathAverted)
        .def("OnMissedWeaponShot", &USkillDefinition::OnMissedWeaponShot)
        .def("OnDamagedByFriendly", &USkillDefinition::OnDamagedByFriendly)
        .def("OnDamagedByEnemy", &USkillDefinition::OnDamagedByEnemy)
        .def("OnDamagedFriendly", &USkillDefinition::OnDamagedFriendly)
        .def("OnDamagedEnemyExposeDamageSurfaceType", &USkillDefinition::OnDamagedEnemyExposeDamageSurfaceType)
        .def("OnDamagedEnemy", &USkillDefinition::OnDamagedEnemy)
        .def("OnWeaponStartReload", &USkillDefinition::OnWeaponStartReload)
        .def("OnKilledByEnemy", &USkillDefinition::OnKilledByEnemy)
        .def("OnKilledEnemy", &USkillDefinition::OnKilledEnemy)
        .def("OnShieldFull", &USkillDefinition::OnShieldFull)
        .def("OnShieldDepleted", &USkillDefinition::OnShieldDepleted)
        .def("OnShieldDepletedAfterBeingFull", &USkillDefinition::OnShieldDepletedAfterBeingFull)
        .def("OnWeaponSwapped", &USkillDefinition::OnWeaponSwapped)
        .def("OnWeaponManuallyReloaded", &USkillDefinition::OnWeaponManuallyReloaded)
        .def("OnWeaponReloaded", &USkillDefinition::OnWeaponReloaded)
        .def("OnWeaponFired", &USkillDefinition::OnWeaponFired)
        .def("OnWeaponUnzoomed", &USkillDefinition::OnWeaponUnzoomed)
        .def("OnWeaponZoomed", &USkillDefinition::OnWeaponZoomed)
        .def("OnThrowGrenadeOverrideSkillActivated", &USkillDefinition::OnThrowGrenadeOverrideSkillActivated)
        .def("OnMeleeOverrideSkillActivated", &USkillDefinition::OnMeleeOverrideSkillActivated)
        .def("OnResumed", &USkillDefinition::OnResumed)
        .def("OnPaused", &USkillDefinition::OnPaused)
        .def("OnDeactivated", &USkillDefinition::OnDeactivated)
        .def("OnActivated", &USkillDefinition::OnActivated)
        .staticmethod("StaticClass")
  ;
}