#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UConsole(py::object m)
{
    py::class_< UConsole,  UInteraction   >(m, "UConsole")
        .def_readwrite("ConsoleTargetPlayer", &UConsole::ConsoleTargetPlayer)
        .def_readwrite("DefaultTexture_Black", &UConsole::DefaultTexture_Black)
        .def_readwrite("DefaultTexture_White", &UConsole::DefaultTexture_White)
        .def_readwrite("ConsoleKey", &UConsole::ConsoleKey)
        .def_readwrite("TypeKey", &UConsole::TypeKey)
        .def_readwrite("MaxScrollbackSize", &UConsole::MaxScrollbackSize)
        .def_readwrite("Scrollback", &UConsole::Scrollback)
        .def_readwrite("SBHead", &UConsole::SBHead)
        .def_readwrite("SBPos", &UConsole::SBPos)
        .def_readwrite("HistoryTop", &UConsole::HistoryTop)
        .def_readwrite("HistoryBot", &UConsole::HistoryBot)
        .def_readwrite("HistoryCur", &UConsole::HistoryCur)
        .def_readwrite("TypedStr", &UConsole::TypedStr)
        .def_readwrite("TypedStrPos", &UConsole::TypedStrPos)
        .def_readwrite("ManualAutoCompleteList", &UConsole::ManualAutoCompleteList)
        .def_readwrite("AutoCompleteList", &UConsole::AutoCompleteList)
        .def_readwrite("AutoCompleteIndex", &UConsole::AutoCompleteIndex)
        .def_readwrite("AutoCompleteTree", &UConsole::AutoCompleteTree)
        .def_readwrite("AutoCompleteIndices", &UConsole::AutoCompleteIndices)
        .def("StaticClass", &UConsole::StaticClass, py::return_value_policy::reference)
        .def("UpdateCompleteIndices", &UConsole::UpdateCompleteIndices)
        .def("BuildRuntimeAutoCompleteList", &UConsole::BuildRuntimeAutoCompleteList)
        .def("AppendInputText", &UConsole::AppendInputText)
        .def("ProcessControlKey", &UConsole::ProcessControlKey)
        .def("FlushPlayerInput", &UConsole::FlushPlayerInput)
        .def("InputChar", &UConsole::InputChar)
        .def("InputKey", &UConsole::InputKey)
        .def("PostRender_Console", &UConsole::PostRender_Console)
        .def("StartTyping", &UConsole::StartTyping)
        .def("eventOutputText", &UConsole::eventOutputText)
        .def("OutputTextLine", &UConsole::OutputTextLine)
        .def("ClearOutput", &UConsole::ClearOutput)
        .def("eventConsoleCommand", &UConsole::eventConsoleCommand)
        .def("ShippingConsoleCommand", &UConsole::ShippingConsoleCommand)
        .def("PurgeCommandFromHistory", &UConsole::PurgeCommandFromHistory)
        .def("SetCursorPos", &UConsole::SetCursorPos)
        .def("SetInputText", &UConsole::SetInputText)
        .def("Initialized", &UConsole::Initialized)
          ;
}