#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UUIInteraction()
{
    class_< UUIInteraction, bases< UInteraction >  , boost::noncopyable>("UUIInteraction", no_init)
        .def_readwrite("VfTable_FExec", &UUIInteraction::VfTable_FExec)
        .def_readwrite("VfTable_FGlobalDataStoreClientManager", &UUIInteraction::VfTable_FGlobalDataStoreClientManager)
        .def_readwrite("VfTable_FCallbackEventDevice", &UUIInteraction::VfTable_FCallbackEventDevice)
        .def_readwrite("UIManager", &UUIInteraction::UIManager)
        .def_readwrite("UIManagerClass", &UUIInteraction::UIManagerClass)
        .def_readwrite("SceneClientClass", &UUIInteraction::SceneClientClass)
        .def_readwrite("SceneClient", &UUIInteraction::SceneClient)
        .def_readwrite("SupportedDoubleClickKeys", &UUIInteraction::SupportedDoubleClickKeys)
        .def_readwrite("DataStoreManager", &UUIInteraction::DataStoreManager)
        .def_readonly("bProcessInput", &UUIInteraction::bProcessInput)
        .def_readwrite("UIJoystickDeadZone", &UUIInteraction::UIJoystickDeadZone)
        .def_readwrite("UIAxisMultiplier", &UUIInteraction::UIAxisMultiplier)
        .def_readwrite("AxisRepeatDelay", &UUIInteraction::AxisRepeatDelay)
        .def_readwrite("MouseButtonRepeatDelay", &UUIInteraction::MouseButtonRepeatDelay)
        .def_readwrite("DoubleClickTriggerSeconds", &UUIInteraction::DoubleClickTriggerSeconds)
        .def_readwrite("DoubleClickPixelTolerance", &UUIInteraction::DoubleClickPixelTolerance)
        .def_readwrite("MouseButtonRepeatInfo", &UUIInteraction::MouseButtonRepeatInfo)
        .def_readwrite("ConfiguredAxisEmulationDefinitions", &UUIInteraction::ConfiguredAxisEmulationDefinitions)
        .def_readonly("UnknownData00", &UUIInteraction::UnknownData00)
        .def_readonly("AxisInputEmulation", &UUIInteraction::AxisInputEmulation)
        .def("StaticClass", &UUIInteraction::StaticClass, return_value_policy< reference_existing_object >())
        .def("NotifyGameSessionEnded", &UUIInteraction::NotifyGameSessionEnded)
        .def("eventGetNATType", &UUIInteraction::eventGetNATType)
        .def("eventCanCommunicate", &UUIInteraction::eventCanCommunicate)
        .def("GetConnectedGamepadCount", &UUIInteraction::GetConnectedGamepadCount)
        .def("IsGamepadConnected", &UUIInteraction::IsGamepadConnected)
        .def("GetNumGuestsLoggedIn", &UUIInteraction::GetNumGuestsLoggedIn)
        .def("GetLoggedInPlayerCount", &UUIInteraction::GetLoggedInPlayerCount)
        .def("eventIsLoggedIn", &UUIInteraction::eventIsLoggedIn)
        .def("eventHasLinkConnection", &UUIInteraction::eventHasLinkConnection)
        .def("GetLowestLoginStatusOfControllers", &UUIInteraction::GetLowestLoginStatusOfControllers)
        .def("eventGetLoginStatus", &UUIInteraction::eventGetLoginStatus)
        .def("NotifyPlayerRemoved", &UUIInteraction::NotifyPlayerRemoved)
        .def("NotifyPlayerAdded", &UUIInteraction::NotifyPlayerAdded)
        .def("GetLocalPlayer", &UUIInteraction::GetLocalPlayer, return_value_policy< reference_existing_object >())
        .def("GetDataStoreClient", &UUIInteraction::GetDataStoreClient, return_value_policy< reference_existing_object >())
        .def("GetPlayerControllerId", &UUIInteraction::GetPlayerControllerId)
        .def("GetPlayerIndex", &UUIInteraction::GetPlayerIndex)
        .def("GetPlayerCount", &UUIInteraction::GetPlayerCount)
        .staticmethod("StaticClass")
  ;
}