#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UStatusEffectsComponent(py::module &m)
{
    py::class_< UStatusEffectsComponent,  UActorComponent   >(m, "UStatusEffectsComponent")
        .def_readwrite("OwnerTarget", &UStatusEffectsComponent::OwnerTarget)
        .def_readwrite("BodyConsumptionPercent", &UStatusEffectsComponent::BodyConsumptionPercent)
        .def_readwrite("ActiveStatusEffects", &UStatusEffectsComponent::ActiveStatusEffects)
        .def_readwrite("LastPrimaryStatusEffect", &UStatusEffectsComponent::LastPrimaryStatusEffect)
        .def_readwrite("ActiveEmitters", &UStatusEffectsComponent::ActiveEmitters)
        .def_readwrite("ActiveEffectSounds", &UStatusEffectsComponent::ActiveEffectSounds)
        .def_readwrite("ClientEmitters", &UStatusEffectsComponent::ClientEmitters)
        .def_readwrite("IgniteChanceResistanceModifier", &UStatusEffectsComponent::IgniteChanceResistanceModifier)
        .def_readwrite("IgniteChanceResistanceModifierBaseValue", &UStatusEffectsComponent::IgniteChanceResistanceModifierBaseValue)
        .def_readwrite("IgniteChanceResistanceModifierModifierStack", &UStatusEffectsComponent::IgniteChanceResistanceModifierModifierStack)
        .def_readwrite("ShockChanceResistanceModifier", &UStatusEffectsComponent::ShockChanceResistanceModifier)
        .def_readwrite("ShockChanceResistanceModifierBaseValue", &UStatusEffectsComponent::ShockChanceResistanceModifierBaseValue)
        .def_readwrite("ShockChanceResistanceModifierModifierStack", &UStatusEffectsComponent::ShockChanceResistanceModifierModifierStack)
        .def_readwrite("CorrosiveChanceResistanceModifier", &UStatusEffectsComponent::CorrosiveChanceResistanceModifier)
        .def_readwrite("CorrosiveChanceResistanceModifierBaseValue", &UStatusEffectsComponent::CorrosiveChanceResistanceModifierBaseValue)
        .def_readwrite("CorrosiveChanceResistanceModifierModifierStack", &UStatusEffectsComponent::CorrosiveChanceResistanceModifierModifierStack)
        .def_readwrite("SlowChanceResistanceModifier", &UStatusEffectsComponent::SlowChanceResistanceModifier)
        .def_readwrite("SlowChanceResistanceModifierBaseValue", &UStatusEffectsComponent::SlowChanceResistanceModifierBaseValue)
        .def_readwrite("SlowChanceResistanceModifierModifierStack", &UStatusEffectsComponent::SlowChanceResistanceModifierModifierStack)
        .def_readwrite("AmpChanceResistanceModifier", &UStatusEffectsComponent::AmpChanceResistanceModifier)
        .def_readwrite("AmpChanceResistanceModifierBaseValue", &UStatusEffectsComponent::AmpChanceResistanceModifierBaseValue)
        .def_readwrite("AmpChanceResistanceModifierModifierStack", &UStatusEffectsComponent::AmpChanceResistanceModifierModifierStack)
        .def_readwrite("IgniteDurationResistanceModifier", &UStatusEffectsComponent::IgniteDurationResistanceModifier)
        .def_readwrite("IgniteDurationResistanceModifierBaseValue", &UStatusEffectsComponent::IgniteDurationResistanceModifierBaseValue)
        .def_readwrite("IgniteDurationResistanceModifierModifierStack", &UStatusEffectsComponent::IgniteDurationResistanceModifierModifierStack)
        .def_readwrite("ShockDurationResistanceModifier", &UStatusEffectsComponent::ShockDurationResistanceModifier)
        .def_readwrite("ShockDurationResistanceModifierBaseValue", &UStatusEffectsComponent::ShockDurationResistanceModifierBaseValue)
        .def_readwrite("ShockDurationResistanceModifierModifierStack", &UStatusEffectsComponent::ShockDurationResistanceModifierModifierStack)
        .def_readwrite("CorrosiveDurationResistanceModifier", &UStatusEffectsComponent::CorrosiveDurationResistanceModifier)
        .def_readwrite("CorrosiveDurationResistanceModifierBaseValue", &UStatusEffectsComponent::CorrosiveDurationResistanceModifierBaseValue)
        .def_readwrite("CorrosiveDurationResistanceModifierModifierStack", &UStatusEffectsComponent::CorrosiveDurationResistanceModifierModifierStack)
        .def_readwrite("SlowDurationResistanceModifier", &UStatusEffectsComponent::SlowDurationResistanceModifier)
        .def_readwrite("SlowDurationResistanceModifierBaseValue", &UStatusEffectsComponent::SlowDurationResistanceModifierBaseValue)
        .def_readwrite("SlowDurationResistanceModifierModifierStack", &UStatusEffectsComponent::SlowDurationResistanceModifierModifierStack)
        .def_readwrite("AmpDurationResistanceModifier", &UStatusEffectsComponent::AmpDurationResistanceModifier)
        .def_readwrite("AmpDurationResistanceModifierBaseValue", &UStatusEffectsComponent::AmpDurationResistanceModifierBaseValue)
        .def_readwrite("AmpDurationResistanceModifierModifierStack", &UStatusEffectsComponent::AmpDurationResistanceModifierModifierStack)
        .def_readwrite("OngoingEffects", &UStatusEffectsComponent::OngoingEffects)
        .def_readwrite("DebugPawnMarkerInst", &UStatusEffectsComponent::DebugPawnMarkerInst)
        .def("RemoveDenStat", &UStatusEffectsComponent::RemoveDenStat)
        .def("AddDenStat", &UStatusEffectsComponent::AddDenStat)
        .def("ClearDenStats", &UStatusEffectsComponent::ClearDenStats)
        .def("ConditionalCreateDebugPawnMarkerInst", &UStatusEffectsComponent::ConditionalCreateDebugPawnMarkerInst)
        .def("GetActiveEffectSounds", &UStatusEffectsComponent::GetActiveEffectSounds)
        .def("StopEffectSound", &UStatusEffectsComponent::StopEffectSound)
        .def("StartEffectSound", &UStatusEffectsComponent::StartEffectSound)
        .def("IsTypeActive", &UStatusEffectsComponent::IsTypeActive)
        .def("FillEffectActivityLists", &UStatusEffectsComponent::FillEffectActivityLists)
        .def("eventUpdateAudio", &UStatusEffectsComponent::eventUpdateAudio)
        .def("UnRegisterEmitter", &UStatusEffectsComponent::UnRegisterEmitter)
        .def("RegisterEmitter", &UStatusEffectsComponent::RegisterEmitter)
        .def("EmitterUpdated", &UStatusEffectsComponent::EmitterUpdated)
        .def("OwnerDied", &UStatusEffectsComponent::OwnerDied)
        .def("SetEnabled", &UStatusEffectsComponent::SetEnabled)
        .def("GetNonRegionSpecificEffects", &UStatusEffectsComponent::GetNonRegionSpecificEffects)
        .def("GetRegionSpecificEffects", &UStatusEffectsComponent::GetRegionSpecificEffects)
        .def("GetStatusEffects", &UStatusEffectsComponent::GetStatusEffects)
        .def("eventOnStatusEffectEnd", &UStatusEffectsComponent::eventOnStatusEffectEnd)
        .def("GetEmitterForSocketRegion", &UStatusEffectsComponent::GetEmitterForSocketRegion, py::return_value_policy::reference)
        .def("GetRegionSocketNames", &UStatusEffectsComponent::GetRegionSocketNames)
        .def("eventUpdateRegionData", &UStatusEffectsComponent::eventUpdateRegionData)
        .def("CreateTraceHitInfo", &UStatusEffectsComponent::CreateTraceHitInfo)
        .def("eventApplyStatusEffect", &UStatusEffectsComponent::eventApplyStatusEffect)
        .def("CheatApplyStatusEffect", &UStatusEffectsComponent::CheatApplyStatusEffect)
        .def("IsGuaranteedSpreadEnabled", &UStatusEffectsComponent::IsGuaranteedSpreadEnabled)
        .def("SetGuaranteedSpreadEnabled", &UStatusEffectsComponent::SetGuaranteedSpreadEnabled)
        .def("IsEnableLogSpreadingEnabled", &UStatusEffectsComponent::IsEnableLogSpreadingEnabled)
        .def("IsLogOnlyInspectedTargetsEnabled", &UStatusEffectsComponent::IsLogOnlyInspectedTargetsEnabled)
        .def("IsStatusEffectDebugEnabled", &UStatusEffectsComponent::IsStatusEffectDebugEnabled)
        .def("SetLogOnlyInspectedTargets", &UStatusEffectsComponent::SetLogOnlyInspectedTargets)
        .def("SetEnableLogSpreading", &UStatusEffectsComponent::SetEnableLogSpreading)
        .def("SetEnableLog", &UStatusEffectsComponent::SetEnableLog)
        .def("ToggleStatusEffectDebug", &UStatusEffectsComponent::ToggleStatusEffectDebug)
        .def("ClearAllStatusEffects", &UStatusEffectsComponent::ClearAllStatusEffects)
        .def("IsEnabled", &UStatusEffectsComponent::IsEnabled)
        .def("UpdateBodyConsumptionPercent", &UStatusEffectsComponent::UpdateBodyConsumptionPercent)
        .def("GetRegionStatusEffects", &UStatusEffectsComponent::GetRegionStatusEffects)
        .def("IsRegionAffectedWithStatusEffect", &UStatusEffectsComponent::IsRegionAffectedWithStatusEffect)
        .def("IsAffectedWithStatusEffectFromDamageType", &UStatusEffectsComponent::IsAffectedWithStatusEffectFromDamageType)
        .def("IsAffectedWithStatusEffectType", &UStatusEffectsComponent::IsAffectedWithStatusEffectType)
        .def("RollChanceForStatusEffect", &UStatusEffectsComponent::RollChanceForStatusEffect)
        .def("GetActiveStatusEffectTypes", &UStatusEffectsComponent::GetActiveStatusEffectTypes)
        .def("HasActiveStatusEffects", &UStatusEffectsComponent::HasActiveStatusEffects)
        .def("eventGetMostRecentStatusEffect", &UStatusEffectsComponent::eventGetMostRecentStatusEffect, py::return_value_policy::reference)
        .def("GetMostRecentEffectHitRegion", &UStatusEffectsComponent::GetMostRecentEffectHitRegion, py::return_value_policy::reference)
          ;
}