#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_USkill(py::module &m)
{
    py::class_< USkill,  UObject   >(m, "USkill")
        .def_readwrite("VfTable_IIBehaviorConsumer", &USkill::VfTable_IIBehaviorConsumer)
        .def_readwrite("Definition", &USkill::Definition)
        .def_readwrite("SkillEffects", &USkill::SkillEffects)
        .def_readwrite("Grade", &USkill::Grade)
        .def_readwrite("GradeBaseValue", &USkill::GradeBaseValue)
        .def_readwrite("GradeModifierStack", &USkill::GradeModifierStack)
        .def_readwrite("BonusGradePointsOnExpConversion", &USkill::BonusGradePointsOnExpConversion)
        .def_readwrite("BonusGradePointsOnExpConversionBaseValue", &USkill::BonusGradePointsOnExpConversionBaseValue)
        .def_readwrite("BonusGradePointsOnExpConversionModifierStack", &USkill::BonusGradePointsOnExpConversionModifierStack)
        .def_readwrite("Duration", &USkill::Duration)
        .def_readwrite("DurationBaseValue", &USkill::DurationBaseValue)
        .def_readwrite("DurationModifierStack", &USkill::DurationModifierStack)
        .def_readwrite("Range", &USkill::Range)
        .def_readwrite("RangeBaseValue", &USkill::RangeBaseValue)
        .def_readwrite("RangeModifierStack", &USkill::RangeModifierStack)
        .def_readwrite("StartTime", &USkill::StartTime)
        .def_readwrite("ActivatedTime", &USkill::ActivatedTime)
        .def_readwrite("SkillState", &USkill::SkillState)
        .def_readwrite("NextContextUpdateTime", &USkill::NextContextUpdateTime)
        .def_readwrite("SkillInstigator", &USkill::SkillInstigator)
        .def_readwrite("AdditionalSkillTarget", &USkill::AdditionalSkillTarget)
        .def_readwrite("CachedActionSkill", &USkill::CachedActionSkill)
        .def_readwrite("ConsumerHandle", &USkill::ConsumerHandle)
        .def("GetBehaviorConsumerHandle", &USkill::GetBehaviorConsumerHandle)
        .def("ForceRefresh", &USkill::ForceRefresh)
        .def("GetGrade", &USkill::GetGrade)
        .def("GetSkillDebug", &USkill::GetSkillDebug)
        .def("eventRunSkillEventResponses", &USkill::eventRunSkillEventResponses)
        .def("NotifySkillDamagedEvent", &USkill::NotifySkillDamagedEvent)
        .def("NotifySkillEvent", &USkill::NotifySkillEvent)
        .def("GetSkillGradeForResponseData", &USkill::GetSkillGradeForResponseData)
        .def("CalculateModifierValueFromDefinitionEffectArray", &USkill::CalculateModifierValueFromDefinitionEffectArray)
        .def("CalculateModifierValue", &USkill::CalculateModifierValue)
        .def("AdjustModifiers", &USkill::AdjustModifiers)
        .def("GetAttributeContexts", &USkill::GetAttributeContexts)
        .def("GetEffectInstigator", &USkill::GetEffectInstigator, py::return_value_policy::reference)
        .def("IsSkillForInstigator", &USkill::IsSkillForInstigator)
        .def("UpdateGrade", &USkill::UpdateGrade)
        .def("CalculateStateBasedOnConstraints", &USkill::CalculateStateBasedOnConstraints)
        .def("GetSkillInstigator", &USkill::GetSkillInstigator, py::return_value_policy::reference)
        .def("GetSkillState", &USkill::GetSkillState)
        .def("eventResume", &USkill::eventResume)
        .def("eventPause", &USkill::eventPause)
        .def("eventDeactivate", &USkill::eventDeactivate)
        .def("eventActivate", &USkill::eventActivate)
        .def("BuildSkillEffects", &USkill::BuildSkillEffects)
        .def("AddSkillEffect", &USkill::AddSkillEffect)
        .def("Initialize", &USkill::Initialize)
        .def("OnSkillStateChanged", &USkill::OnSkillStateChanged)
          ;
}