#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UOnlinePlayerInterface(py::module &m)
{
    py::class_< UOnlinePlayerInterface,  UInterface   >(m, "UOnlinePlayerInterface")
        .def("StaticClass", &UOnlinePlayerInterface::StaticClass, py::return_value_policy::reference)
        .def("GetAchievements", &UOnlinePlayerInterface::GetAchievements)
        .def("ClearReadAchievementsCompleteDelegate", &UOnlinePlayerInterface::ClearReadAchievementsCompleteDelegate)
        .def("AddReadAchievementsCompleteDelegate", &UOnlinePlayerInterface::AddReadAchievementsCompleteDelegate)
        .def("OnReadAchievementsComplete", &UOnlinePlayerInterface::OnReadAchievementsComplete)
        .def("ReadAchievements", &UOnlinePlayerInterface::ReadAchievements)
        .def("ClearUnlockAchievementCompleteDelegate", &UOnlinePlayerInterface::ClearUnlockAchievementCompleteDelegate)
        .def("AddUnlockAchievementCompleteDelegate", &UOnlinePlayerInterface::AddUnlockAchievementCompleteDelegate)
        .def("OnUnlockAchievementComplete", &UOnlinePlayerInterface::OnUnlockAchievementComplete)
        .def("UnlockAchievement", &UOnlinePlayerInterface::UnlockAchievement)
        .def("DeleteMessage", &UOnlinePlayerInterface::DeleteMessage)
        .def("ClearFriendMessageReceivedDelegate", &UOnlinePlayerInterface::ClearFriendMessageReceivedDelegate)
        .def("AddFriendMessageReceivedDelegate", &UOnlinePlayerInterface::AddFriendMessageReceivedDelegate)
        .def("OnFriendMessageReceived", &UOnlinePlayerInterface::OnFriendMessageReceived)
        .def("GetFriendMessages", &UOnlinePlayerInterface::GetFriendMessages)
        .def("ClearJoinFriendGameCompleteDelegate", &UOnlinePlayerInterface::ClearJoinFriendGameCompleteDelegate)
        .def("AddJoinFriendGameCompleteDelegate", &UOnlinePlayerInterface::AddJoinFriendGameCompleteDelegate)
        .def("OnJoinFriendGameComplete", &UOnlinePlayerInterface::OnJoinFriendGameComplete)
        .def("JoinFriendGame", &UOnlinePlayerInterface::JoinFriendGame)
        .def("ClearReceivedGameInviteDelegate", &UOnlinePlayerInterface::ClearReceivedGameInviteDelegate)
        .def("AddReceivedGameInviteDelegate", &UOnlinePlayerInterface::AddReceivedGameInviteDelegate)
        .def("OnReceivedGameInvite", &UOnlinePlayerInterface::OnReceivedGameInvite)
        .def("ClearSentGameInviteDelegate", &UOnlinePlayerInterface::ClearSentGameInviteDelegate)
        .def("AddSentGameInviteDelegate", &UOnlinePlayerInterface::AddSentGameInviteDelegate)
        .def("OnSentGameInvite", &UOnlinePlayerInterface::OnSentGameInvite)
        .def("SendGameInviteToFriends", &UOnlinePlayerInterface::SendGameInviteToFriends)
        .def("SendGameInviteToFriend", &UOnlinePlayerInterface::SendGameInviteToFriend)
        .def("SendMessageToFriend", &UOnlinePlayerInterface::SendMessageToFriend)
        .def("ClearFriendInviteReceivedDelegate", &UOnlinePlayerInterface::ClearFriendInviteReceivedDelegate)
        .def("AddFriendInviteReceivedDelegate", &UOnlinePlayerInterface::AddFriendInviteReceivedDelegate)
        .def("OnFriendInviteReceived", &UOnlinePlayerInterface::OnFriendInviteReceived)
        .def("RemoveFriend", &UOnlinePlayerInterface::RemoveFriend)
        .def("DenyFriendInvite", &UOnlinePlayerInterface::DenyFriendInvite)
        .def("AcceptFriendInvite", &UOnlinePlayerInterface::AcceptFriendInvite)
        .def("ClearAddFriendByNameCompleteDelegate", &UOnlinePlayerInterface::ClearAddFriendByNameCompleteDelegate)
        .def("AddAddFriendByNameCompleteDelegate", &UOnlinePlayerInterface::AddAddFriendByNameCompleteDelegate)
        .def("OnAddFriendByNameComplete", &UOnlinePlayerInterface::OnAddFriendByNameComplete)
        .def("AddFriendByName", &UOnlinePlayerInterface::AddFriendByName)
        .def("AddFriend", &UOnlinePlayerInterface::AddFriend)
        .def("GetKeyboardInputResults", &UOnlinePlayerInterface::GetKeyboardInputResults)
        .def("ClearKeyboardInputDoneDelegate", &UOnlinePlayerInterface::ClearKeyboardInputDoneDelegate)
        .def("AddKeyboardInputDoneDelegate", &UOnlinePlayerInterface::AddKeyboardInputDoneDelegate)
        .def("OnKeyboardInputComplete", &UOnlinePlayerInterface::OnKeyboardInputComplete)
        .def("ShowKeyboardUI", &UOnlinePlayerInterface::ShowKeyboardUI)
        .def("SetOnlineStatus", &UOnlinePlayerInterface::SetOnlineStatus)
        .def("GetFriendsList", &UOnlinePlayerInterface::GetFriendsList)
        .def("ClearReadFriendsCompleteDelegate", &UOnlinePlayerInterface::ClearReadFriendsCompleteDelegate)
        .def("AddReadFriendsCompleteDelegate", &UOnlinePlayerInterface::AddReadFriendsCompleteDelegate)
        .def("OnReadFriendsComplete", &UOnlinePlayerInterface::OnReadFriendsComplete)
        .def("ReadFriendsList", &UOnlinePlayerInterface::ReadFriendsList)
        .def("ClearWritePlayerStorageCompleteDelegate", &UOnlinePlayerInterface::ClearWritePlayerStorageCompleteDelegate)
        .def("AddWritePlayerStorageCompleteDelegate", &UOnlinePlayerInterface::AddWritePlayerStorageCompleteDelegate)
        .def("OnWritePlayerStorageComplete", &UOnlinePlayerInterface::OnWritePlayerStorageComplete)
        .def("WritePlayerStorage", &UOnlinePlayerInterface::WritePlayerStorage)
        .def("GetPlayerStorage", &UOnlinePlayerInterface::GetPlayerStorage, py::return_value_policy::reference)
        .def("ClearReadPlayerStorageForNetIdCompleteDelegate", &UOnlinePlayerInterface::ClearReadPlayerStorageForNetIdCompleteDelegate)
        .def("AddReadPlayerStorageForNetIdCompleteDelegate", &UOnlinePlayerInterface::AddReadPlayerStorageForNetIdCompleteDelegate)
        .def("OnReadPlayerStorageForNetIdComplete", &UOnlinePlayerInterface::OnReadPlayerStorageForNetIdComplete)
        .def("ReadPlayerStorageForNetId", &UOnlinePlayerInterface::ReadPlayerStorageForNetId)
        .def("ClearReadPlayerStorageCompleteDelegate", &UOnlinePlayerInterface::ClearReadPlayerStorageCompleteDelegate)
        .def("AddReadPlayerStorageCompleteDelegate", &UOnlinePlayerInterface::AddReadPlayerStorageCompleteDelegate)
        .def("OnReadPlayerStorageComplete", &UOnlinePlayerInterface::OnReadPlayerStorageComplete)
        .def("ReadPlayerStorage", &UOnlinePlayerInterface::ReadPlayerStorage)
        .def("ClearWriteProfileSettingsCompleteDelegate", &UOnlinePlayerInterface::ClearWriteProfileSettingsCompleteDelegate)
        .def("AddWriteProfileSettingsCompleteDelegate", &UOnlinePlayerInterface::AddWriteProfileSettingsCompleteDelegate)
        .def("OnWriteProfileSettingsComplete", &UOnlinePlayerInterface::OnWriteProfileSettingsComplete)
        .def("WriteProfileSettings", &UOnlinePlayerInterface::WriteProfileSettings)
        .def("GetProfileSettings", &UOnlinePlayerInterface::GetProfileSettings, py::return_value_policy::reference)
        .def("ClearReadProfileSettingsCompleteDelegate", &UOnlinePlayerInterface::ClearReadProfileSettingsCompleteDelegate)
        .def("AddReadProfileSettingsCompleteDelegate", &UOnlinePlayerInterface::AddReadProfileSettingsCompleteDelegate)
        .def("OnReadProfileSettingsComplete", &UOnlinePlayerInterface::OnReadProfileSettingsComplete)
        .def("ReadProfileSettings", &UOnlinePlayerInterface::ReadProfileSettings)
        .def("ClearFriendsChangeDelegate", &UOnlinePlayerInterface::ClearFriendsChangeDelegate)
        .def("AddFriendsChangeDelegate", &UOnlinePlayerInterface::AddFriendsChangeDelegate)
        .def("ClearMutingChangeDelegate", &UOnlinePlayerInterface::ClearMutingChangeDelegate)
        .def("AddMutingChangeDelegate", &UOnlinePlayerInterface::AddMutingChangeDelegate)
        .def("ClearLoginCancelledDelegate", &UOnlinePlayerInterface::ClearLoginCancelledDelegate)
        .def("AddLoginCancelledDelegate", &UOnlinePlayerInterface::AddLoginCancelledDelegate)
        .def("ClearLoginStatusChangeDelegate", &UOnlinePlayerInterface::ClearLoginStatusChangeDelegate)
        .def("AddLoginStatusChangeDelegate", &UOnlinePlayerInterface::AddLoginStatusChangeDelegate)
        .def("OnLoginStatusChange", &UOnlinePlayerInterface::OnLoginStatusChange)
        .def("ClearLoginChangeDelegate", &UOnlinePlayerInterface::ClearLoginChangeDelegate)
        .def("AddLoginChangeDelegate", &UOnlinePlayerInterface::AddLoginChangeDelegate)
        .def("ShowFriendsUI", &UOnlinePlayerInterface::ShowFriendsUI)
        .def("IsMuted", &UOnlinePlayerInterface::IsMuted)
        .def("AreAnyFriends", &UOnlinePlayerInterface::AreAnyFriends)
        .def("IsFriend", &UOnlinePlayerInterface::IsFriend)
        .def("CanShowPresenceInformation", &UOnlinePlayerInterface::CanShowPresenceInformation)
        .def("CanViewPlayerProfiles", &UOnlinePlayerInterface::CanViewPlayerProfiles)
        .def("CanPurchaseContent", &UOnlinePlayerInterface::CanPurchaseContent)
        .def("CanDownloadUserContent", &UOnlinePlayerInterface::CanDownloadUserContent)
        .def("CanCommunicate", &UOnlinePlayerInterface::CanCommunicate)
        .def("CanPlayOnline", &UOnlinePlayerInterface::CanPlayOnline)
        .def("ClearGetUserAgeGroupDelegate", &UOnlinePlayerInterface::ClearGetUserAgeGroupDelegate)
        .def("AddGetUserAgeGroupDelegate", &UOnlinePlayerInterface::AddGetUserAgeGroupDelegate)
        .def("GetUserAgeGroup", &UOnlinePlayerInterface::GetUserAgeGroup)
        .def("OnGetUserAgeGroup", &UOnlinePlayerInterface::OnGetUserAgeGroup)
        .def("IsLocalLogin", &UOnlinePlayerInterface::IsLocalLogin)
        .def("IsGuestLogin", &UOnlinePlayerInterface::IsGuestLogin)
        .def("GetPlayerNickname", &UOnlinePlayerInterface::GetPlayerNickname)
        .def("GetUniquePlayerId", &UOnlinePlayerInterface::GetUniquePlayerId)
        .def("GetLoginStatus", &UOnlinePlayerInterface::GetLoginStatus)
        .def("ClearLogoutCompletedDelegate", &UOnlinePlayerInterface::ClearLogoutCompletedDelegate)
        .def("AddLogoutCompletedDelegate", &UOnlinePlayerInterface::AddLogoutCompletedDelegate)
        .def("OnLogoutCompleted", &UOnlinePlayerInterface::OnLogoutCompleted)
        .def("Logout", &UOnlinePlayerInterface::Logout)
        .def("ClearLoginFailedDelegate", &UOnlinePlayerInterface::ClearLoginFailedDelegate)
        .def("AddLoginFailedDelegate", &UOnlinePlayerInterface::AddLoginFailedDelegate)
        .def("OnLoginFailed", &UOnlinePlayerInterface::OnLoginFailed)
        .def("AutoLogin", &UOnlinePlayerInterface::AutoLogin)
        .def("Login", &UOnlinePlayerInterface::Login)
        .def("ShowLoginUI", &UOnlinePlayerInterface::ShowLoginUI)
        .def("OnFriendsChange", &UOnlinePlayerInterface::OnFriendsChange)
        .def("OnMutingChange", &UOnlinePlayerInterface::OnMutingChange)
        .def("OnLoginCancelled", &UOnlinePlayerInterface::OnLoginCancelled)
        .def("OnLoginChange", &UOnlinePlayerInterface::OnLoginChange)
          ;
}