#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UResourcePool()
{
    class_< UResourcePool, bases< UObject >  , boost::noncopyable>("UResourcePool", no_init)
        .def_readwrite("Definition", &UResourcePool::Definition)
        .def_readwrite("PoolGUID", &UResourcePool::PoolGUID)
        .def_readwrite("MinValue", &UResourcePool::MinValue)
        .def_readwrite("MinValueBaseValue", &UResourcePool::MinValueBaseValue)
        .def_readwrite("MinValueModifierStack", &UResourcePool::MinValueModifierStack)
        .def_readwrite("MaxValue", &UResourcePool::MaxValue)
        .def_readwrite("MaxValueBaseValue", &UResourcePool::MaxValueBaseValue)
        .def_readwrite("MaxValueModifierStack", &UResourcePool::MaxValueModifierStack)
        .def_readwrite("CurrentValue", &UResourcePool::CurrentValue)
        .def_readwrite("ConsumptionRate", &UResourcePool::ConsumptionRate)
        .def_readwrite("ConsumptionRateBaseValue", &UResourcePool::ConsumptionRateBaseValue)
        .def_readwrite("ConsumptionRateModifierStack", &UResourcePool::ConsumptionRateModifierStack)
        .def_readwrite("ActiveRegenerationRate", &UResourcePool::ActiveRegenerationRate)
        .def_readwrite("ActiveRegenerationRateBaseValue", &UResourcePool::ActiveRegenerationRateBaseValue)
        .def_readwrite("ActiveRegenerationRateModifierStack", &UResourcePool::ActiveRegenerationRateModifierStack)
        .def_readwrite("OnIdleRegenerationRate", &UResourcePool::OnIdleRegenerationRate)
        .def_readwrite("OnIdleRegenerationRateBaseValue", &UResourcePool::OnIdleRegenerationRateBaseValue)
        .def_readwrite("OnIdleRegenerationRateModifierStack", &UResourcePool::OnIdleRegenerationRateModifierStack)
        .def_readwrite("OnIdleRegenerationDelay", &UResourcePool::OnIdleRegenerationDelay)
        .def_readwrite("OnIdleRegenerationDelayBaseValue", &UResourcePool::OnIdleRegenerationDelayBaseValue)
        .def_readwrite("OnIdleRegenerationDelayModifierStack", &UResourcePool::OnIdleRegenerationDelayModifierStack)
        .def_readwrite("PassiveRegenerationRate", &UResourcePool::PassiveRegenerationRate)
        .def_readwrite("PassiveRegenerationRateBaseValue", &UResourcePool::PassiveRegenerationRateBaseValue)
        .def_readwrite("PassiveRegenerationRateModifierStack", &UResourcePool::PassiveRegenerationRateModifierStack)
        .def_readwrite("LastMinValue", &UResourcePool::LastMinValue)
        .def_readwrite("LastMaxValue", &UResourcePool::LastMaxValue)
        .def_readwrite("LastCurrentValue", &UResourcePool::LastCurrentValue)
        .def_readwrite("PoolIdleDelayStartTime", &UResourcePool::PoolIdleDelayStartTime)
        .def_readwrite("RateRemainder", &UResourcePool::RateRemainder)
        .def_readwrite("RecentImpulseCount", &UResourcePool::RecentImpulseCount)
        .def_readwrite("RegenerationDisabled", &UResourcePool::RegenerationDisabled)
        .def_readwrite("RegenerationDisabledBaseValue", &UResourcePool::RegenerationDisabledBaseValue)
        .def_readwrite("RegenerationDisabledModifierStack", &UResourcePool::RegenerationDisabledModifierStack)
        .def_readwrite("ResetRecentImpulseCountTime", &UResourcePool::ResetRecentImpulseCountTime)
        .def_readwrite("AssociatedProvider", &UResourcePool::AssociatedProvider)
        .def_readwrite("HUDMaterialInstance", &UResourcePool::HUDMaterialInstance)
        .def_readwrite("RegenerationPool", &UResourcePool::RegenerationPool)
        .def_readwrite("IsRegenerating", &UResourcePool::IsRegenerating)
        .def("StaticClass", &UResourcePool::StaticClass, return_value_policy< reference_existing_object >())
        .def("IsResourcePoolInState", &UResourcePool::IsResourcePoolInState)
        .def("WasCreatedAndNotModified", &UResourcePool::WasCreatedAndNotModified)
        .def("IsAuthoritative", &UResourcePool::IsAuthoritative)
        .def("SetAuthoritative", &UResourcePool::SetAuthoritative)
        .def("GetTimeSeconds", &UResourcePool::GetTimeSeconds)
        .def("GetMinimalDebugText", &UResourcePool::GetMinimalDebugText)
        .def("GetDebugText", &UResourcePool::GetDebugText)
        .def("RefillPercentage", &UResourcePool::RefillPercentage)
        .def("HasIdleDelayPassed", &UResourcePool::HasIdleDelayPassed)
        .def("ResetIdleTimer", &UResourcePool::ResetIdleTimer)
        .def("UpdateCreatedAndNotModified", &UResourcePool::UpdateCreatedAndNotModified)
        .def("UpdateLastValues", &UResourcePool::UpdateLastValues)
        .def("SetMaxValueFromProfile", &UResourcePool::SetMaxValueFromProfile)
        .def("PoolIsNowFull", &UResourcePool::PoolIsNowFull)
        .def("GetMinValue", &UResourcePool::GetMinValue)
        .def("GetMaxValue", &UResourcePool::GetMaxValue)
        .def("GetTotalRegenRate", &UResourcePool::GetTotalRegenRate)
        .def("GetCurrentPulseSpeed", &UResourcePool::GetCurrentPulseSpeed)
        .def("GetCurrentValue", &UResourcePool::GetCurrentValue)
        .def("SetCurrentValue", &UResourcePool::SetCurrentValue)
        .def("AddCurrentValueImpulse", &UResourcePool::AddCurrentValueImpulse)
        .def("IsResourcePoolForResourceDefinition", &UResourcePool::IsResourcePoolForResourceDefinition)
        .def("UpdateCurrentValueOnExtremaChange", &UResourcePool::UpdateCurrentValueOnExtremaChange)
        .def("eventCalculateBaseValues", &UResourcePool::eventCalculateBaseValues)
        .def("ApplyUpgrades", &UResourcePool::ApplyUpgrades)
        .def("SetUpgradeLevel", &UResourcePool::SetUpgradeLevel)
        .def("GetUpgradeLevel", &UResourcePool::GetUpgradeLevel)
        .def("eventReinitialize", &UResourcePool::eventReinitialize)
        .def("ClearAttributeModifierStacks", &UResourcePool::ClearAttributeModifierStacks)
        .def("eventShutDown", &UResourcePool::eventShutDown)
        .def("eventInitializeAuthoritative", &UResourcePool::eventInitializeAuthoritative)
        .staticmethod("StaticClass")
  ;
}