#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UWillowVehicleSimChopper(py::module &m)
{
    py::class_< UWillowVehicleSimChopper,  USVehicleSimBase   >(m, "UWillowVehicleSimChopper")
        .def_readwrite("MaxThrustForce", &UWillowVehicleSimChopper::MaxThrustForce)
        .def_readwrite("MaxReverseForce", &UWillowVehicleSimChopper::MaxReverseForce)
        .def_readwrite("LongDamping", &UWillowVehicleSimChopper::LongDamping)
        .def_readwrite("MaxStrafeForce", &UWillowVehicleSimChopper::MaxStrafeForce)
        .def_readwrite("LatDamping", &UWillowVehicleSimChopper::LatDamping)
        .def_readwrite("DirectionChangeForce", &UWillowVehicleSimChopper::DirectionChangeForce)
        .def_readwrite("MaxRiseForce", &UWillowVehicleSimChopper::MaxRiseForce)
        .def_readwrite("UpDamping", &UWillowVehicleSimChopper::UpDamping)
        .def_readwrite("TurnTorqueFactor", &UWillowVehicleSimChopper::TurnTorqueFactor)
        .def_readwrite("TurnTorqueMax", &UWillowVehicleSimChopper::TurnTorqueMax)
        .def_readwrite("TurnDamping", &UWillowVehicleSimChopper::TurnDamping)
        .def_readwrite("MaxYawRate", &UWillowVehicleSimChopper::MaxYawRate)
        .def_readwrite("PitchTorqueFactor", &UWillowVehicleSimChopper::PitchTorqueFactor)
        .def_readwrite("PitchTorqueMax", &UWillowVehicleSimChopper::PitchTorqueMax)
        .def_readwrite("PitchDamping", &UWillowVehicleSimChopper::PitchDamping)
        .def_readwrite("RollTorqueTurnFactor", &UWillowVehicleSimChopper::RollTorqueTurnFactor)
        .def_readwrite("RollTorqueStrafeFactor", &UWillowVehicleSimChopper::RollTorqueStrafeFactor)
        .def_readwrite("RollTorqueMax", &UWillowVehicleSimChopper::RollTorqueMax)
        .def_readwrite("RollDamping", &UWillowVehicleSimChopper::RollDamping)
        .def_readwrite("StopThreshold", &UWillowVehicleSimChopper::StopThreshold)
        .def_readwrite("MaxRandForce", &UWillowVehicleSimChopper::MaxRandForce)
        .def_readwrite("RandForceInterval", &UWillowVehicleSimChopper::RandForceInterval)
        .def_readwrite("StrafeTurnDamping", &UWillowVehicleSimChopper::StrafeTurnDamping)
        .def_readwrite("TargetHeading", &UWillowVehicleSimChopper::TargetHeading)
        .def_readwrite("TargetPitch", &UWillowVehicleSimChopper::TargetPitch)
        .def_readwrite("PitchViewCorrelation", &UWillowVehicleSimChopper::PitchViewCorrelation)
        .def_readwrite("RandForce", &UWillowVehicleSimChopper::RandForce)
        .def_readwrite("RandTorque", &UWillowVehicleSimChopper::RandTorque)
        .def_readwrite("AccumulatedTime", &UWillowVehicleSimChopper::AccumulatedTime)
        .def_readwrite("StabilizationForceMultiplier", &UWillowVehicleSimChopper::StabilizationForceMultiplier)
        .def_readwrite("CurrentStabilizationMultiplier", &UWillowVehicleSimChopper::CurrentStabilizationMultiplier)
        .def_readwrite("OldVelocity", &UWillowVehicleSimChopper::OldVelocity)
        .def_readwrite("StoppedBrakeTorque", &UWillowVehicleSimChopper::StoppedBrakeTorque)
        .def_readwrite("HardLimitAirSpeedScale", &UWillowVehicleSimChopper::HardLimitAirSpeedScale)
        .def_readwrite("MaxVelocityWhenAdjustingHover", &UWillowVehicleSimChopper::MaxVelocityWhenAdjustingHover)
        .def_readwrite("HoverDeadZone", &UWillowVehicleSimChopper::HoverDeadZone)
        .def_readwrite("RiseAdjustmentInterval", &UWillowVehicleSimChopper::RiseAdjustmentInterval)
        .def_readwrite("DesiredHoverHeight", &UWillowVehicleSimChopper::DesiredHoverHeight)
        .def_readwrite("PreviousZVel", &UWillowVehicleSimChopper::PreviousZVel)
        .def_readwrite("AdjustedRise", &UWillowVehicleSimChopper::AdjustedRise)
          ;
}