#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UWillowDamagePipeline(py::object m)
{
    py::class_< UWillowDamagePipeline,  UDamagePipeline   >(m, "UWillowDamagePipeline")
        .def_readwrite("WillowDamageTypeDef", &UWillowDamagePipeline::WillowDamageTypeDef)
        .def_readwrite("WillowImpactDefinition", &UWillowDamagePipeline::WillowImpactDefinition)
        .def_readwrite("DamageInstigator", &UWillowDamagePipeline::DamageInstigator)
        .def_readwrite("HitLocation", &UWillowDamagePipeline::HitLocation)
        .def_readwrite("HitMomentum", &UWillowDamagePipeline::HitMomentum)
        .def_readwrite("HitInfo", &UWillowDamagePipeline::HitInfo)
        .def_readwrite("DamageSource", &UWillowDamagePipeline::DamageSource)
        .def_readwrite("Globals", &UWillowDamagePipeline::Globals)
        .def_readwrite("GlobalsDef", &UWillowDamagePipeline::GlobalsDef)
        .def_readwrite("WorldInfo", &UWillowDamagePipeline::WorldInfo)
        .def_readwrite("WGRI", &UWillowDamagePipeline::WGRI)
        .def_readwrite("DamagedActor", &UWillowDamagePipeline::DamagedActor)
        .def_readwrite("DamagedPawnBase", &UWillowDamagePipeline::DamagedPawnBase)
        .def_readwrite("DamagedIO", &UWillowDamagePipeline::DamagedIO)
        .def_readwrite("DamagedPawn", &UWillowDamagePipeline::DamagedPawn)
        .def_readwrite("DamagedAIPawn", &UWillowDamagePipeline::DamagedAIPawn)
        .def_readwrite("DamageInstigatorWPC", &UWillowDamagePipeline::DamageInstigatorWPC)
        .def_readwrite("HitRegionDef", &UWillowDamagePipeline::HitRegionDef)
        .def_readwrite("DamageableInt", &UWillowDamagePipeline::DamageableInt)
        .def_readwrite("HitRegionConsumerInt", &UWillowDamagePipeline::HitRegionConsumerInt)
        .def_readwrite("ProtectableInt", &UWillowDamagePipeline::ProtectableInt)
        .def_readwrite("DamagedReflectableInt", &UWillowDamagePipeline::DamagedReflectableInt)
        .def_readwrite("InstigatorReflectableInt", &UWillowDamagePipeline::InstigatorReflectableInt)
        .def_readwrite("DamagedTargetableInt", &UWillowDamagePipeline::DamagedTargetableInt)
        .def_readwrite("InstigatorTargetableInt", &UWillowDamagePipeline::InstigatorTargetableInt)
        .def_readwrite("BulletFromClipType", &UWillowDamagePipeline::BulletFromClipType)
        .def_readwrite("TakingRadiusDamageOnHitRegions", &UWillowDamagePipeline::TakingRadiusDamageOnHitRegions)
        .def_readwrite("ResistDamageReductionThreshold", &UWillowDamagePipeline::ResistDamageReductionThreshold)
        .def("StaticClass", &UWillowDamagePipeline::StaticClass, py::return_value_policy::reference)
        .def("eventKillPlayer", &UWillowDamagePipeline::eventKillPlayer)
        .def("GetWouldBeHealedSomehowByFriendlyFire", &UWillowDamagePipeline::GetWouldBeHealedSomehowByFriendlyFire)
        .def("DamageDealtSkillEventsTriggered", &UWillowDamagePipeline::DamageDealtSkillEventsTriggered)
        .def("DamageTakenSkillEventsTriggered", &UWillowDamagePipeline::DamageTakenSkillEventsTriggered)
        .def("SetAlwaysCrit", &UWillowDamagePipeline::SetAlwaysCrit)
        .def("IsAlwaysCritCheatActive", &UWillowDamagePipeline::IsAlwaysCritCheatActive)
        .def("SetTakingRadiusDamageOnHitRegions", &UWillowDamagePipeline::SetTakingRadiusDamageOnHitRegions)
        .def("SetBulletClipType", &UWillowDamagePipeline::SetBulletClipType)
        .def("SetCanReflect", &UWillowDamagePipeline::SetCanReflect)
        .def("ResetToDefaults", &UWillowDamagePipeline::ResetToDefaults)
        .def("ConvertDamageToHealing", &UWillowDamagePipeline::ConvertDamageToHealing)
        .def("AdjustDamage", &UWillowDamagePipeline::AdjustDamage)
          ;
}