#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UWillowSaveGameManager(py::object m)
{
    py::class_< UWillowSaveGameManager,  UObject   >(m, "UWillowSaveGameManager")
        .def_readwrite("VfTable_FTickableObject", &UWillowSaveGameManager::VfTable_FTickableObject)
        .def_readonly("AsyncResult", &UWillowSaveGameManager::AsyncResult)
        .def_readonly("CurrentState", &UWillowSaveGameManager::CurrentState)
        .def_readwrite("PendingLoadInfo", &UWillowSaveGameManager::PendingLoadInfo)
        .def_readwrite("CrossTitleLoadInfo", &UWillowSaveGameManager::CrossTitleLoadInfo)
        .def_readwrite("LastLoadedSaveGameData", &UWillowSaveGameManager::LastLoadedSaveGameData)
        .def_readwrite("LastLoadedFileTimeStamp", &UWillowSaveGameManager::LastLoadedFileTimeStamp)
        .def_readwrite("LastLoadedFilePath", &UWillowSaveGameManager::LastLoadedFilePath)
        .def_readwrite("SaveDataLoadedFromList", &UWillowSaveGameManager::SaveDataLoadedFromList)
        .def_readwrite("SaveGameTitle", &UWillowSaveGameManager::SaveGameTitle)
        .def_readwrite("GraveyardTitle", &UWillowSaveGameManager::GraveyardTitle)
        .def_readwrite("GraveyardSubTitle", &UWillowSaveGameManager::GraveyardSubTitle)
        .def_readwrite("LevelStr", &UWillowSaveGameManager::LevelStr)
        .def_readwrite("SaveStartTime", &UWillowSaveGameManager::SaveStartTime)
        .def_readwrite("CorruptSaveDataString", &UWillowSaveGameManager::CorruptSaveDataString)
        .def_readwrite("UnloadableDlcSaveDataString", &UWillowSaveGameManager::UnloadableDlcSaveDataString)
        .def_readwrite("DateFormat", &UWillowSaveGameManager::DateFormat)
        .def_readwrite("TimeFormat", &UWillowSaveGameManager::TimeFormat)
        .def_readwrite("SingularSecond", &UWillowSaveGameManager::SingularSecond)
        .def_readwrite("PluralSeconds", &UWillowSaveGameManager::PluralSeconds)
        .def_readwrite("SingularMinute", &UWillowSaveGameManager::SingularMinute)
        .def_readwrite("PluralMinutes", &UWillowSaveGameManager::PluralMinutes)
        .def_readwrite("SingularHour", &UWillowSaveGameManager::SingularHour)
        .def_readwrite("PluralHours", &UWillowSaveGameManager::PluralHours)
        .def_readwrite("SingularDay", &UWillowSaveGameManager::SingularDay)
        .def_readwrite("PluralDays", &UWillowSaveGameManager::PluralDays)
        .def_readonly("bNeedsProfileWrite", &UWillowSaveGameManager::bNeedsProfileWrite)
        .def("StaticClass", &UWillowSaveGameManager::StaticClass, py::return_value_policy::reference)
        .def("DestroyAllRegisteredDelegates", &UWillowSaveGameManager::DestroyAllRegisteredDelegates)
        .def("AttemptProfileWriteIfNecessary", &UWillowSaveGameManager::AttemptProfileWriteIfNecessary)
        .def("NotifyProfileWriteComplete", &UWillowSaveGameManager::NotifyProfileWriteComplete)
        .def("SetNeedsProfileWrite", &UWillowSaveGameManager::SetNeedsProfileWrite)
        .def("GetNeedsProfileWrite", &UWillowSaveGameManager::GetNeedsProfileWrite)
        .def("PopulatePlayerSaveDataDefinitionContent", &UWillowSaveGameManager::PopulatePlayerSaveDataDefinitionContent)
        .def("GetHumanReadableStringFromTimePlayed", &UWillowSaveGameManager::GetHumanReadableStringFromTimePlayed)
        .def("GetHumanReadableStringFromSaveDateString", &UWillowSaveGameManager::GetHumanReadableStringFromSaveDateString)
        .def("GetCurrentSaveDateString", &UWillowSaveGameManager::GetCurrentSaveDateString)
        .def("BeginCountNumCrossTitleSaveGames", &UWillowSaveGameManager::BeginCountNumCrossTitleSaveGames)
        .def("SetNumCrossTitleSaveGames", &UWillowSaveGameManager::SetNumCrossTitleSaveGames)
        .def("GetNumCrossTitleSaveGames", &UWillowSaveGameManager::GetNumCrossTitleSaveGames)
        .def("SetNumSaveGames", &UWillowSaveGameManager::SetNumSaveGames)
        .def("GetNumSaveGames", &UWillowSaveGameManager::GetNumSaveGames)
        .def("NotifySaveComplete", &UWillowSaveGameManager::NotifySaveComplete)
        .def("NotifySaveStarted", &UWillowSaveGameManager::NotifySaveStarted)
        .def("GetXboxDevice", &UWillowSaveGameManager::GetXboxDevice)
        .def("SetXboxDevice", &UWillowSaveGameManager::SetXboxDevice)
        .def("SaveGame", &UWillowSaveGameManager::SaveGame)
        .def("ValidateSaveData", &UWillowSaveGameManager::ValidateSaveData)
        .def("DeleteSaveGame", &UWillowSaveGameManager::DeleteSaveGame)
        .def("GetHighestSaveIdFromFileList", &UWillowSaveGameManager::GetHighestSaveIdFromFileList)
        .def("GetLastSaveGameId", &UWillowSaveGameManager::GetLastSaveGameId)
        .def("GetLastSaveGame", &UWillowSaveGameManager::GetLastSaveGame)
        .def("EndGetSaveGameDataFromList", &UWillowSaveGameManager::EndGetSaveGameDataFromList)
        .def("BeginGetSaveGameDataFromList", &UWillowSaveGameManager::BeginGetSaveGameDataFromList)
        .def("GetCrossTitleSaveGameList", &UWillowSaveGameManager::GetCrossTitleSaveGameList)
        .def("GetSaveGameList", &UWillowSaveGameManager::GetSaveGameList)
        .def("LoadRawData", &UWillowSaveGameManager::LoadRawData)
        .def("LoadGraveyard", &UWillowSaveGameManager::LoadGraveyard, py::return_value_policy::reference)
        .def("EndLoadWillowOneGame", &UWillowSaveGameManager::EndLoadWillowOneGame)
        .def("BeginLoadWillowOneGame", &UWillowSaveGameManager::BeginLoadWillowOneGame)
        .def("EndLoadGame", &UWillowSaveGameManager::EndLoadGame, py::return_value_policy::reference)
        .def("BeginLoadGame", &UWillowSaveGameManager::BeginLoadGame)
        .def("SetCachedPlayerSaveGame", &UWillowSaveGameManager::SetCachedPlayerSaveGame)
        .def("HasCachedPlayerSaveGame", &UWillowSaveGameManager::HasCachedPlayerSaveGame)
        .def("GetCachedPlayerSaveGame", &UWillowSaveGameManager::GetCachedPlayerSaveGame, py::return_value_policy::reference)
        .def("SaveRawData", &UWillowSaveGameManager::SaveRawData)
        .def("SaveGraveyard", &UWillowSaveGameManager::SaveGraveyard)
        .def("Save", &UWillowSaveGameManager::Save)
        .def("ClearCache", &UWillowSaveGameManager::ClearCache)
        .def("OnCountNumCrossTitleSaveGamesComplete", &UWillowSaveGameManager::OnCountNumCrossTitleSaveGamesComplete)
        .def("OnWillowOneLoadComplete", &UWillowSaveGameManager::OnWillowOneLoadComplete)
        .def("OnListLoadComplete", &UWillowSaveGameManager::OnListLoadComplete)
        .def("OnLoadComplete", &UWillowSaveGameManager::OnLoadComplete)
        .def("OnSaveComplete", &UWillowSaveGameManager::OnSaveComplete)
        .def("OnValidationComplete", &UWillowSaveGameManager::OnValidationComplete)
        .def("OnDeleteComplete", &UWillowSaveGameManager::OnDeleteComplete)
        .def("GetResult", &UWillowSaveGameManager::GetResult)
          ;
}