#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_ACoverLink(py::module &m)
{
    py::class_< ACoverLink,  ANavigationPoint   >(m, "ACoverLink")
        .def_readwrite("VfTable_IIGBXNavMeshSpecialMove", &ACoverLink::VfTable_IIGBXNavMeshSpecialMove)
        .def_readwrite("LeanTraceDist", &ACoverLink::LeanTraceDist)
        .def_readwrite("Slots", &ACoverLink::Slots)
        .def_readwrite("DynamicLinkInfos", &ACoverLink::DynamicLinkInfos)
        .def_readwrite("Claims", &ACoverLink::Claims)
        .def_readwrite("InvalidateDistance", &ACoverLink::InvalidateDistance)
        .def_readwrite("MaxFireLinkDist", &ACoverLink::MaxFireLinkDist)
        .def_readwrite("CircularOrigin", &ACoverLink::CircularOrigin)
        .def_readwrite("CircularRadius", &ACoverLink::CircularRadius)
        .def_readwrite("AlignDist", &ACoverLink::AlignDist)
        .def_readwrite("AutoCoverSlotInterval", &ACoverLink::AutoCoverSlotInterval)
        .def_readwrite("StandHeight", &ACoverLink::StandHeight)
        .def_readwrite("MidHeight", &ACoverLink::MidHeight)
        .def_readwrite("StandingLeanOffset", &ACoverLink::StandingLeanOffset)
        .def_readwrite("CrouchLeanOffset", &ACoverLink::CrouchLeanOffset)
        .def_readwrite("PopupOffset", &ACoverLink::PopupOffset)
        .def_readwrite("SlipDist", &ACoverLink::SlipDist)
        .def_readwrite("TurnDist", &ACoverLink::TurnDist)
        .def_readwrite("DangerScale", &ACoverLink::DangerScale)
        .def_readwrite("CoverSlotMarkerClassName", &ACoverLink::CoverSlotMarkerClassName)
        .def_readwrite("NextCoverLink", &ACoverLink::NextCoverLink)
        .def_readwrite("LocationDescription", &ACoverLink::LocationDescription)
        .def("eventGetDebugAbbrev", &ACoverLink::eventGetDebugAbbrev)
        .def("GetLocationDescription", &ACoverLink::GetLocationDescription)
        .def("eventGetDebugString", &ACoverLink::eventGetDebugString)
        .def("AddCoverSlot", &ACoverLink::AddCoverSlot)
        .def("GetSwatTurnTarget", &ACoverLink::GetSwatTurnTarget)
        .def("eventShutDown", &ACoverLink::eventShutDown)
        .def("ApplyCheckpointRecord", &ACoverLink::ApplyCheckpointRecord)
        .def("CreateCheckpointRecord", &ACoverLink::CreateCheckpointRecord)
        .def("OnToggle", &ACoverLink::OnToggle)
        .def("IsEnabled", &ACoverLink::IsEnabled)
        .def("AutoAdjustSlot", &ACoverLink::AutoAdjustSlot)
        .def("OnModifyCover", &ACoverLink::OnModifyCover)
        .def("eventSetSlotPlayerOnly", &ACoverLink::eventSetSlotPlayerOnly)
        .def("NotifySlotOwnerCoverDisabled", &ACoverLink::NotifySlotOwnerCoverDisabled)
        .def("eventSetSlotEnabled", &ACoverLink::eventSetSlotEnabled)
        .def("eventSetDisabled", &ACoverLink::eventSetDisabled)
        .def("GetSlotActions", &ACoverLink::GetSlotActions)
        .def("HasFireLinkTo", &ACoverLink::HasFireLinkTo)
        .def("GetFireLinkTo", &ACoverLink::GetFireLinkTo)
        .def("AllowLeftTransition", &ACoverLink::AllowLeftTransition)
        .def("AllowRightTransition", &ACoverLink::AllowRightTransition)
        .def("GetSlotIdxToRight", &ACoverLink::GetSlotIdxToRight)
        .def("GetSlotIdxToLeft", &ACoverLink::GetSlotIdxToLeft)
        .def("IsRightEdgeSlot", &ACoverLink::IsRightEdgeSlot)
        .def("IsLeftEdgeSlot", &ACoverLink::IsLeftEdgeSlot)
        .def("IsEdgeSlot", &ACoverLink::IsEdgeSlot)
        .def("FindSlots", &ACoverLink::FindSlots)
        .def("IsStationarySlot", &ACoverLink::IsStationarySlot)
        .def("IsValidClaimBetween", &ACoverLink::IsValidClaimBetween)
        .def("IsValidClaim", &ACoverLink::IsValidClaim)
        .def("eventUnClaim", &ACoverLink::eventUnClaim)
        .def("eventClaim", &ACoverLink::eventClaim)
        .def("eventSetInvalidUntil", &ACoverLink::eventSetInvalidUntil)
        .def("IsExposedTo", &ACoverLink::IsExposedTo)
        .def("GetSlotViewPoint", &ACoverLink::GetSlotViewPoint)
        .def("GetSlotRotation", &ACoverLink::GetSlotRotation)
        .def("GetSlotLocation", &ACoverLink::GetSlotLocation)
        .def("UnPackFireLinkInteractionInfo", &ACoverLink::UnPackFireLinkInteractionInfo)
        .def("PackFireLinkInteractionInfo", &ACoverLink::PackFireLinkInteractionInfo)
        .def("GetFireLinkTargetCoverInfo", &ACoverLink::GetFireLinkTargetCoverInfo)
          ;
}