#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UAttributePresentationDefinition()
{
    class_< UAttributePresentationDefinition, bases< UGBXDefinition >  , boost::noncopyable>("UAttributePresentationDefinition", no_init)
        .def_readwrite("BasePriority", &UAttributePresentationDefinition::BasePriority)
        .def_readwrite("Attribute", &UAttributePresentationDefinition::Attribute)
        .def_readwrite("Description", &UAttributePresentationDefinition::Description)
        .def_readwrite("NoConstraintText", &UAttributePresentationDefinition::NoConstraintText)
        .def_readwrite("Suffix", &UAttributePresentationDefinition::Suffix)
        .def_readwrite("Prefix", &UAttributePresentationDefinition::Prefix)
        .def_readwrite("RoundingMode", &UAttributePresentationDefinition::RoundingMode)
        .def_readwrite("SignStyle", &UAttributePresentationDefinition::SignStyle)
        .def_readwrite("TextColor", &UAttributePresentationDefinition::TextColor)
        .def_readwrite("FloatPrecision", &UAttributePresentationDefinition::FloatPrecision)
        .def_readwrite("Icon", &UAttributePresentationDefinition::Icon)
        .def_readwrite("RemappingData", &UAttributePresentationDefinition::RemappingData)
        .def("StaticClass", &UAttributePresentationDefinition::StaticClass, return_value_policy< reference_existing_object >())
        .def("IncludePrefixInTranslation", &UAttributePresentationDefinition::IncludePrefixInTranslation)
        .def("IncludeSuffixInTranslation", &UAttributePresentationDefinition::IncludeSuffixInTranslation)
        .def("IsTextColorEnabled", &UAttributePresentationDefinition::IsTextColorEnabled)
        .def("GetTextColor", &UAttributePresentationDefinition::GetTextColor)
        .def("GetSignStyle", &UAttributePresentationDefinition::GetSignStyle)
        .def("GetEffectiveRoundingMode", &UAttributePresentationDefinition::GetEffectiveRoundingMode)
        .def("GetRoundingMode", &UAttributePresentationDefinition::GetRoundingMode)
        .def("ShouldUseCustomNumberPlacement", &UAttributePresentationDefinition::ShouldUseCustomNumberPlacement)
        .def("ShouldDisplayPlusSign", &UAttributePresentationDefinition::ShouldDisplayPlusSign)
        .def("ShouldDisplayNumberInTranslation", &UAttributePresentationDefinition::ShouldDisplayNumberInTranslation)
        .def("ShouldDisplayAsInverse", &UAttributePresentationDefinition::ShouldDisplayAsInverse)
        .def("ShouldDisplayAsPercentage", &UAttributePresentationDefinition::ShouldDisplayAsPercentage)
        .def("IsBiggerBetter", &UAttributePresentationDefinition::IsBiggerBetter)
        .def("GetIconFramename", &UAttributePresentationDefinition::GetIconFramename)
        .def("GetPrefix", &UAttributePresentationDefinition::GetPrefix)
        .def("GetSuffix", &UAttributePresentationDefinition::GetSuffix)
        .def("GetNoConstraintText", &UAttributePresentationDefinition::GetNoConstraintText)
        .def("GetDescription", &UAttributePresentationDefinition::GetDescription)
        .def("GetBasePriority", &UAttributePresentationDefinition::GetBasePriority)
        .def("RemapValue", &UAttributePresentationDefinition::RemapValue)
        .def("RoundValue", &UAttributePresentationDefinition::RoundValue)
        .def("ApplyPresentationRulesToValue", &UAttributePresentationDefinition::ApplyPresentationRulesToValue)
        .def("ValueToString", &UAttributePresentationDefinition::ValueToString)
        .def("TranslateValue", &UAttributePresentationDefinition::TranslateValue)
        .def("TranslateStatData", &UAttributePresentationDefinition::TranslateStatData)
        .staticmethod("StaticClass")
  ;
}