#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_AWillowShield(py::object m)
{
    py::class_< AWillowShield,  AWillowEquipAbleItem   >(m, "AWillowShield")
        .def_readwrite("PercentChanceToAbsorbAmmo", &AWillowShield::PercentChanceToAbsorbAmmo)
        .def_readwrite("PercentChanceToAbsorbAmmoBaseValue", &AWillowShield::PercentChanceToAbsorbAmmoBaseValue)
        .def_readwrite("PercentChanceToAbsorbAmmoModifierStack", &AWillowShield::PercentChanceToAbsorbAmmoModifierStack)
        .def_readwrite("PercentDamageToNegateWhenAmmoAbsorbed", &AWillowShield::PercentDamageToNegateWhenAmmoAbsorbed)
        .def_readwrite("PercentDamageToNegateWhenAmmoAbsorbedBaseValue", &AWillowShield::PercentDamageToNegateWhenAmmoAbsorbedBaseValue)
        .def_readwrite("PercentDamageToNegateWhenAmmoAbsorbedModifierStack", &AWillowShield::PercentDamageToNegateWhenAmmoAbsorbedModifierStack)
        .def_readwrite("GenericStatusEffectDamageModifier", &AWillowShield::GenericStatusEffectDamageModifier)
        .def_readwrite("GenericStatusEffectDamageModifierBaseValue", &AWillowShield::GenericStatusEffectDamageModifierBaseValue)
        .def_readwrite("GenericStatusEffectDamageModifierModifierStack", &AWillowShield::GenericStatusEffectDamageModifierModifierStack)
        .def_readwrite("NovaCorrosiveExplosionSize", &AWillowShield::NovaCorrosiveExplosionSize)
        .def_readwrite("NovaCorrosiveExplosionSizeBaseValue", &AWillowShield::NovaCorrosiveExplosionSizeBaseValue)
        .def_readwrite("NovaCorrosiveExplosionSizeModifierStack", &AWillowShield::NovaCorrosiveExplosionSizeModifierStack)
        .def_readwrite("NovaExplosiveExplosionSize", &AWillowShield::NovaExplosiveExplosionSize)
        .def_readwrite("NovaExplosiveExplosionSizeBaseValue", &AWillowShield::NovaExplosiveExplosionSizeBaseValue)
        .def_readwrite("NovaExplosiveExplosionSizeModifierStack", &AWillowShield::NovaExplosiveExplosionSizeModifierStack)
        .def_readwrite("NovaFireExplosionSize", &AWillowShield::NovaFireExplosionSize)
        .def_readwrite("NovaFireExplosionSizeBaseValue", &AWillowShield::NovaFireExplosionSizeBaseValue)
        .def_readwrite("NovaFireExplosionSizeModifierStack", &AWillowShield::NovaFireExplosionSizeModifierStack)
        .def_readwrite("NovaShockExplosionSize", &AWillowShield::NovaShockExplosionSize)
        .def_readwrite("NovaShockExplosionSizeBaseValue", &AWillowShield::NovaShockExplosionSizeBaseValue)
        .def_readwrite("NovaShockExplosionSizeModifierStack", &AWillowShield::NovaShockExplosionSizeModifierStack)
        .def_readwrite("NovaCorrosiveExplosionDamage", &AWillowShield::NovaCorrosiveExplosionDamage)
        .def_readwrite("NovaCorrosiveExplosionDamageBaseValue", &AWillowShield::NovaCorrosiveExplosionDamageBaseValue)
        .def_readwrite("NovaCorrosiveExplosionDamageModifierStack", &AWillowShield::NovaCorrosiveExplosionDamageModifierStack)
        .def_readwrite("NovaExplosiveExplosionDamage", &AWillowShield::NovaExplosiveExplosionDamage)
        .def_readwrite("NovaExplosiveExplosionDamageBaseValue", &AWillowShield::NovaExplosiveExplosionDamageBaseValue)
        .def_readwrite("NovaExplosiveExplosionDamageModifierStack", &AWillowShield::NovaExplosiveExplosionDamageModifierStack)
        .def_readwrite("NovaFireExplosionDamage", &AWillowShield::NovaFireExplosionDamage)
        .def_readwrite("NovaFireExplosionDamageBaseValue", &AWillowShield::NovaFireExplosionDamageBaseValue)
        .def_readwrite("NovaFireExplosionDamageModifierStack", &AWillowShield::NovaFireExplosionDamageModifierStack)
        .def_readwrite("NovaShockExplosionDamage", &AWillowShield::NovaShockExplosionDamage)
        .def_readwrite("NovaShockExplosionDamageBaseValue", &AWillowShield::NovaShockExplosionDamageBaseValue)
        .def_readwrite("NovaShockExplosionDamageModifierStack", &AWillowShield::NovaShockExplosionDamageModifierStack)
        .def_readwrite("SpikeCorrosiveDamage", &AWillowShield::SpikeCorrosiveDamage)
        .def_readwrite("SpikeCorrosiveDamageBaseValue", &AWillowShield::SpikeCorrosiveDamageBaseValue)
        .def_readwrite("SpikeCorrosiveDamageModifierStack", &AWillowShield::SpikeCorrosiveDamageModifierStack)
        .def_readwrite("SpikeExplosiveDamage", &AWillowShield::SpikeExplosiveDamage)
        .def_readwrite("SpikeExplosiveDamageBaseValue", &AWillowShield::SpikeExplosiveDamageBaseValue)
        .def_readwrite("SpikeExplosiveDamageModifierStack", &AWillowShield::SpikeExplosiveDamageModifierStack)
        .def_readwrite("SpikeFireDamage", &AWillowShield::SpikeFireDamage)
        .def_readwrite("SpikeFireDamageBaseValue", &AWillowShield::SpikeFireDamageBaseValue)
        .def_readwrite("SpikeFireDamageModifierStack", &AWillowShield::SpikeFireDamageModifierStack)
        .def_readwrite("SpikeShockDamage", &AWillowShield::SpikeShockDamage)
        .def_readwrite("SpikeShockDamageBaseValue", &AWillowShield::SpikeShockDamageBaseValue)
        .def_readwrite("SpikeShockDamageModifierStack", &AWillowShield::SpikeShockDamageModifierStack)
        .def_readwrite("RoidMeleeDamage", &AWillowShield::RoidMeleeDamage)
        .def_readwrite("RoidMeleeDamageBaseValue", &AWillowShield::RoidMeleeDamageBaseValue)
        .def_readwrite("RoidMeleeDamageModifierStack", &AWillowShield::RoidMeleeDamageModifierStack)
        .def_readwrite("PercentChanceToSpawnBoosterItem", &AWillowShield::PercentChanceToSpawnBoosterItem)
        .def_readwrite("PercentChanceToSpawnBoosterItemBaseValue", &AWillowShield::PercentChanceToSpawnBoosterItemBaseValue)
        .def_readwrite("PercentChanceToSpawnBoosterItemModifierStack", &AWillowShield::PercentChanceToSpawnBoosterItemModifierStack)
        .def_readwrite("ImpactDamageBonus", &AWillowShield::ImpactDamageBonus)
        .def_readwrite("ImpactDamageBonusBaseValue", &AWillowShield::ImpactDamageBonusBaseValue)
        .def_readwrite("ImpactDamageBonusModifierStack", &AWillowShield::ImpactDamageBonusModifierStack)
        .def_readwrite("PercentShieldToConsumeOnImpactProc", &AWillowShield::PercentShieldToConsumeOnImpactProc)
        .def_readwrite("PercentShieldToConsumeOnImpactProcBaseValue", &AWillowShield::PercentShieldToConsumeOnImpactProcBaseValue)
        .def_readwrite("PercentShieldToConsumeOnImpactProcModifierStack", &AWillowShield::PercentShieldToConsumeOnImpactProcModifierStack)
        .def_readwrite("ShieldDef", &AWillowShield::ShieldDef)
        .def_readwrite("DamageResistanceType", &AWillowShield::DamageResistanceType)
        .def_readwrite("ShieldCapacitySlotGradeMinusRarity", &AWillowShield::ShieldCapacitySlotGradeMinusRarity)
        .def_readwrite("ShieldCapacitySlotGradeMinusRarityBaseValue", &AWillowShield::ShieldCapacitySlotGradeMinusRarityBaseValue)
        .def_readwrite("ShieldCapacitySlotGradeMinusRarityModifierStack", &AWillowShield::ShieldCapacitySlotGradeMinusRarityModifierStack)
        .def_readwrite("ShieldRechargeRateSlotGradeMinusRarity", &AWillowShield::ShieldRechargeRateSlotGradeMinusRarity)
        .def_readwrite("ShieldRechargeRateSlotGradeMinusRarityBaseValue", &AWillowShield::ShieldRechargeRateSlotGradeMinusRarityBaseValue)
        .def_readwrite("ShieldRechargeRateSlotGradeMinusRarityModifierStack", &AWillowShield::ShieldRechargeRateSlotGradeMinusRarityModifierStack)
        .def_readwrite("ShieldRechargeDelaySlotGradeMinusRarity", &AWillowShield::ShieldRechargeDelaySlotGradeMinusRarity)
        .def_readwrite("ShieldRechargeDelaySlotGradeMinusRarityBaseValue", &AWillowShield::ShieldRechargeDelaySlotGradeMinusRarityBaseValue)
        .def_readwrite("ShieldRechargeDelaySlotGradeMinusRarityModifierStack", &AWillowShield::ShieldRechargeDelaySlotGradeMinusRarityModifierStack)
        .def_readwrite("ShieldSpecialSlotGradeMinusRarity", &AWillowShield::ShieldSpecialSlotGradeMinusRarity)
        .def_readwrite("ShieldSpecialSlotGradeMinusRarityBaseValue", &AWillowShield::ShieldSpecialSlotGradeMinusRarityBaseValue)
        .def_readwrite("ShieldSpecialSlotGradeMinusRarityModifierStack", &AWillowShield::ShieldSpecialSlotGradeMinusRarityModifierStack)
        .def("StaticClass", &AWillowShield::StaticClass, py::return_value_policy::reference)
        .def("GetHolsteredGearLikenessType", &AWillowShield::GetHolsteredGearLikenessType)
        .def("GetItemCardTopSectionString", &AWillowShield::GetItemCardTopSectionString)
        .def("GetAttributePresentationOverride", &AWillowShield::GetAttributePresentationOverride, py::return_value_policy::reference)
        .def("IsSameShieldTypeAs", [](AWillowShield &self ) { class AWillowShield** pyCompareShield = 0 ;  bool ret =  self.IsSameShieldTypeAs(pyCompareShield); return py::make_tuple(ret, *pyCompareShield); })
        .def("CanCompareUIStat", [](AWillowShield &self ) { class UAttributeDefinition** pyAttrib = 0 ; class UAttributeDefinition** pyCompareAttrib = 0 ; class AWillowInventory** pyCompareItem = 0 ;  bool ret =  self.CanCompareUIStat(pyAttrib, pyCompareAttrib, pyCompareItem); return py::make_tuple(ret, *pyAttrib, *pyCompareAttrib, *pyCompareItem); })
        .def("ValidateDefinitions", &AWillowShield::ValidateDefinitions)
        .def("GetEquippedStat", &AWillowShield::GetEquippedStat)
        .def("eventGetEquipmentLocation", &AWillowShield::eventGetEquipmentLocation)
        .def("eventSetDamageResistanceType", &AWillowShield::eventSetDamageResistanceType)
        .def("ShieldTriggered", &AWillowShield::ShieldTriggered)
        .def("eventShieldPrimedStateChanged", &AWillowShield::eventShieldPrimedStateChanged)
        .def("TryAbsorbingAmmo", [](AWillowShield &self , class UObject* DamageSource, class UWillowDamageTypeDefinition* DamageType) { float* pyPercentDamageToAbsorb = (float*)malloc(sizeof(float)) ;  bool ret =  self.TryAbsorbingAmmo(DamageSource, DamageType, pyPercentDamageToAbsorb); return py::make_tuple(ret, *pyPercentDamageToAbsorb); })
        .def("ItemUnequipped", &AWillowShield::ItemUnequipped)
        .def("ItemEquipped", &AWillowShield::ItemEquipped)
        .def("ClientInitializeFromItemDefinition", &AWillowShield::ClientInitializeFromItemDefinition)
        .def("eventReplicatedEvent", &AWillowShield::eventReplicatedEvent)
          ;
}