#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UStatusMenuMapGFxObject(py::object m)
{
    py::class_< UStatusMenuMapGFxObject,  UGFxObject   >(m, "UStatusMenuMapGFxObject")
        .def_readwrite("ViewBorder", &UStatusMenuMapGFxObject::ViewBorder)
        .def_readwrite("PanRate", &UStatusMenuMapGFxObject::PanRate)
        .def_readwrite("PlayerOwner", &UStatusMenuMapGFxObject::PlayerOwner)
        .def_readwrite("MapObjects", &UStatusMenuMapGFxObject::MapObjects)
        .def_readwrite("Transform", &UStatusMenuMapGFxObject::Transform)
        .def_readwrite("CoordScale", &UStatusMenuMapGFxObject::CoordScale)
        .def_readwrite("ClipSize", &UStatusMenuMapGFxObject::ClipSize)
        .def_readwrite("MapClipRect", &UStatusMenuMapGFxObject::MapClipRect)
        .def_readwrite("ViewSize", &UStatusMenuMapGFxObject::ViewSize)
        .def_readwrite("ViewOffset", &UStatusMenuMapGFxObject::ViewOffset)
        .def_readwrite("DesiredCenter", &UStatusMenuMapGFxObject::DesiredCenter)
        .def_readwrite("PanScalingFactor", &UStatusMenuMapGFxObject::PanScalingFactor)
        .def_readwrite("CurrScaleVal", &UStatusMenuMapGFxObject::CurrScaleVal)
        .def_readwrite("ZoomSpeedFactor", &UStatusMenuMapGFxObject::ZoomSpeedFactor)
        .def_readwrite("MaxScale", &UStatusMenuMapGFxObject::MaxScale)
        .def_readwrite("MinScale", &UStatusMenuMapGFxObject::MinScale)
        .def_readwrite("TacticalMapVolume", &UStatusMenuMapGFxObject::TacticalMapVolume)
        .def_readwrite("UnrealUnitsPerPixel", &UStatusMenuMapGFxObject::UnrealUnitsPerPixel)
        .def_readwrite("MapPlaceholderClip", &UStatusMenuMapGFxObject::MapPlaceholderClip)
        .def_readwrite("MaskClip", &UStatusMenuMapGFxObject::MaskClip)
        .def_readwrite("InfoBoxClip", &UStatusMenuMapGFxObject::InfoBoxClip)
        .def_readwrite("InfoBoxIconIndex", &UStatusMenuMapGFxObject::InfoBoxIconIndex)
        .def_readwrite("InfoBoxDistance", &UStatusMenuMapGFxObject::InfoBoxDistance)
        .def_readwrite("PanIncrement", &UStatusMenuMapGFxObject::PanIncrement)
        .def_readwrite("PanZoomFactor", &UStatusMenuMapGFxObject::PanZoomFactor)
        .def_readwrite("CursorPos", &UStatusMenuMapGFxObject::CursorPos)
        .def_readwrite("MapYawOffset", &UStatusMenuMapGFxObject::MapYawOffset)
        .def_readwrite("AndMore", &UStatusMenuMapGFxObject::AndMore)
        .def_readwrite("CustomObjectiveToggle", &UStatusMenuMapGFxObject::CustomObjectiveToggle)
        .def_readwrite("Title_Player", &UStatusMenuMapGFxObject::Title_Player)
        .def_readwrite("Title_CustomObjective", &UStatusMenuMapGFxObject::Title_CustomObjective)
        .def_readwrite("Title_MissionAvailable", &UStatusMenuMapGFxObject::Title_MissionAvailable)
        .def_readwrite("Title_MissionComplete", &UStatusMenuMapGFxObject::Title_MissionComplete)
        .def_readwrite("Title_Vehicle", &UStatusMenuMapGFxObject::Title_Vehicle)
        .def_readwrite("Title_Objective", &UStatusMenuMapGFxObject::Title_Objective)
        .def_readwrite("Title_AreaObjective", &UStatusMenuMapGFxObject::Title_AreaObjective)
        .def_readwrite("Title_InteractiveObject", &UStatusMenuMapGFxObject::Title_InteractiveObject)
        .def_readwrite("MissionTurnIn", &UStatusMenuMapGFxObject::MissionTurnIn)
        .def("StaticClass", &UStatusMenuMapGFxObject::StaticClass, py::return_value_policy::reference)
        .def("ToggleFogOfWarBlob", &UStatusMenuMapGFxObject::ToggleFogOfWarBlob)
        .def("ToggleLegend", &UStatusMenuMapGFxObject::ToggleLegend)
        .def("eventSetPlayerInfo", &UStatusMenuMapGFxObject::eventSetPlayerInfo)
        .def("eventHidePlayerInfo", &UStatusMenuMapGFxObject::eventHidePlayerInfo)
        .def("SetMapScale", &UStatusMenuMapGFxObject::SetMapScale)
        .def("SetMapMovie", &UStatusMenuMapGFxObject::SetMapMovie)
        .def("FindLandmarks", &UStatusMenuMapGFxObject::FindLandmarks)
        .def("PanVert", &UStatusMenuMapGFxObject::PanVert)
        .def("PanHorz", &UStatusMenuMapGFxObject::PanHorz)
        .def("GetZoomScalingFactor", &UStatusMenuMapGFxObject::GetZoomScalingFactor)
        .def("ApplyAnalogScale", &UStatusMenuMapGFxObject::ApplyAnalogScale)
        .def("AnalogScale", &UStatusMenuMapGFxObject::AnalogScale)
        .def("GetDeltaTimeScalar", &UStatusMenuMapGFxObject::GetDeltaTimeScalar)
        .def("ResetMapObjects", &UStatusMenuMapGFxObject::ResetMapObjects)
        .def("OnClose", &UStatusMenuMapGFxObject::OnClose)
        .def("PostMapMovieLoad", &UStatusMenuMapGFxObject::PostMapMovieLoad)
        .def("Init", &UStatusMenuMapGFxObject::Init)
        .def("UpdateInfoBox", &UStatusMenuMapGFxObject::UpdateInfoBox)
        .def("QuickAccessInit", &UStatusMenuMapGFxObject::QuickAccessInit)
        .def("PlaceCustomObjective", &UStatusMenuMapGFxObject::PlaceCustomObjective)
        .def("RemoveCustomObjective", &UStatusMenuMapGFxObject::RemoveCustomObjective)
        .def("AddCustomObjective", &UStatusMenuMapGFxObject::AddCustomObjective)
        .def("GetCustomObjectiveIndex", &UStatusMenuMapGFxObject::GetCustomObjectiveIndex)
        .def("HasCustomObjective", &UStatusMenuMapGFxObject::HasCustomObjective)
        .def("GetUnrealMapScale", &UStatusMenuMapGFxObject::GetUnrealMapScale)
        .def("FindObjects", &UStatusMenuMapGFxObject::FindObjects)
        .def("FindPlayers", &UStatusMenuMapGFxObject::FindPlayers)
        .def("UpdateObjects", &UStatusMenuMapGFxObject::UpdateObjects)
        .def("ApplyFlash", &UStatusMenuMapGFxObject::ApplyFlash)
        .def("SetMapHeader", &UStatusMenuMapGFxObject::SetMapHeader)
        .def("InitMapFrameVars", &UStatusMenuMapGFxObject::InitMapFrameVars)
          ;
}