#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_AProjectile(py::object m)
{
    py::class_< AProjectile,  AActor   >(m, "AProjectile")
        .def_readwrite("Speed", &AProjectile::Speed)
        .def_readwrite("MaxSpeed", &AProjectile::MaxSpeed)
        .def_readwrite("ZeroCollider", &AProjectile::ZeroCollider)
        .def_readwrite("ZeroColliderComponent", &AProjectile::ZeroColliderComponent)
        .def_readwrite("Damage", &AProjectile::Damage)
        .def_readwrite("DamageBaseValue", &AProjectile::DamageBaseValue)
        .def_readwrite("DamageModifierStack", &AProjectile::DamageModifierStack)
        .def_readwrite("DamageRadius", &AProjectile::DamageRadius)
        .def_readwrite("DamageRadiusBaseValue", &AProjectile::DamageRadiusBaseValue)
        .def_readwrite("DamageRadiusModifierStack", &AProjectile::DamageRadiusModifierStack)
        .def_readwrite("MomentumTransfer", &AProjectile::MomentumTransfer)
        .def_readwrite("MomentumTransferBaseValue", &AProjectile::MomentumTransferBaseValue)
        .def_readwrite("MomentumTransferModifierStack", &AProjectile::MomentumTransferModifierStack)
        .def_readwrite("MyDamageType", &AProjectile::MyDamageType)
        .def_readwrite("SpawnSound", &AProjectile::SpawnSound)
        .def_readwrite("ImpactSound", &AProjectile::ImpactSound)
        .def_readwrite("InstigatorController", &AProjectile::InstigatorController)
        .def_readwrite("ImpactedActor", &AProjectile::ImpactedActor)
        .def_readwrite("NetCullDistanceSquared", &AProjectile::NetCullDistanceSquared)
        .def_readwrite("CylinderComponent", &AProjectile::CylinderComponent)
        .def("StaticClass", &AProjectile::StaticClass, py::return_value_policy::reference)
        .def("ApplyFluidSurfaceImpact", &AProjectile::ApplyFluidSurfaceImpact)
        .def("GetRange", &AProjectile::GetRange)
        .def("StaticGetTimeToLocation", &AProjectile::StaticGetTimeToLocation)
        .def("GetTimeToLocation", &AProjectile::GetTimeToLocation)
        .def("eventFellOutOfWorld", &AProjectile::eventFellOutOfWorld)
        .def("RandSpin", &AProjectile::RandSpin)
        .def("Explode", &AProjectile::Explode)
        .def("eventEncroachedBy", &AProjectile::eventEncroachedBy)
        .def("eventHitWall", &AProjectile::eventHitWall)
        .def("ProcessTouch", &AProjectile::ProcessTouch)
        .def("eventTouch", &AProjectile::eventTouch)
        .def("HurtRadius", &AProjectile::HurtRadius)
        .def("ProjectileHurtRadius", &AProjectile::ProjectileHurtRadius)
        .def("Reset", &AProjectile::Reset)
        .def("CanSplash", &AProjectile::CanSplash)
        .def("GetTeamNum", &AProjectile::GetTeamNum)
        .def("Init", &AProjectile::Init)
        .def("eventPostBeginPlay", &AProjectile::eventPostBeginPlay)
        .def("eventPreBeginPlay", &AProjectile::eventPreBeginPlay)
        .def("eventEncroachingOn", &AProjectile::eventEncroachingOn)
          ;
}