#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UWillowDownloadableContentManager(py::module &m)
{
    py::class_< UWillowDownloadableContentManager,  UDownloadableContentManager   >(m, "UWillowDownloadableContentManager")
        .def_readwrite("ContentPackages", &UWillowDownloadableContentManager::ContentPackages)
        .def_readwrite("AllContent", &UWillowDownloadableContentManager::AllContent)
        .def_readwrite("Expansions", &UWillowDownloadableContentManager::Expansions)
        .def_readwrite("Characters", &UWillowDownloadableContentManager::Characters)
        .def_readwrite("Vehicles", &UWillowDownloadableContentManager::Vehicles)
        .def_readwrite("Items", &UWillowDownloadableContentManager::Items)
        .def_readwrite("Customizations", &UWillowDownloadableContentManager::Customizations)
        .def_readwrite("AssetLibraries", &UWillowDownloadableContentManager::AssetLibraries)
        .def_readwrite("AsyncPackageLoadsPending", &UWillowDownloadableContentManager::AsyncPackageLoadsPending)
        .def_readwrite("DlcFullyLoadedPackageReferencers", &UWillowDownloadableContentManager::DlcFullyLoadedPackageReferencers)
        .def_readwrite("CurrentInstallState", &UWillowDownloadableContentManager::CurrentInstallState)
        .def_readwrite("LoadedPackages", &UWillowDownloadableContentManager::LoadedPackages)
        .def_readwrite("CachedCompatibilityInfo", &UWillowDownloadableContentManager::CachedCompatibilityInfo)
        .def_readwrite("CachedSimplePackageLicenseInfo", &UWillowDownloadableContentManager::CachedSimplePackageLicenseInfo)
        .def_readwrite("SeasonPassOfferIds", &UWillowDownloadableContentManager::SeasonPassOfferIds)
        .def_readwrite("SeasonPassPackageCounts", &UWillowDownloadableContentManager::SeasonPassPackageCounts)
        .def_readwrite("NewOfferVersion", &UWillowDownloadableContentManager::NewOfferVersion)
        .def_readwrite("NewOfferIds", &UWillowDownloadableContentManager::NewOfferIds)
        .def_readwrite("DLCMissions", &UWillowDownloadableContentManager::DLCMissions)
        .def_readwrite("OnlineCompatibilityInfo", &UWillowDownloadableContentManager::OnlineCompatibilityInfo)
        .def_readwrite("CompatibilityContentInstallInterval", &UWillowDownloadableContentManager::CompatibilityContentInstallInterval)
        .def_readwrite("NextDlcContentInstallNotificationTimeRemaining", &UWillowDownloadableContentManager::NextDlcContentInstallNotificationTimeRemaining)
        .def_readwrite("GoldenKeyCollection", &UWillowDownloadableContentManager::GoldenKeyCollection)
        .def_readwrite("DownloadableBalanceModifiers", &UWillowDownloadableContentManager::DownloadableBalanceModifiers)
        .def_readwrite("TaggedDLC", &UWillowDownloadableContentManager::TaggedDLC)
        .def_readwrite("FastTravelAccessibilityTimes", &UWillowDownloadableContentManager::FastTravelAccessibilityTimes)
        .def_readwrite("CachedExtendedLicenseInfo", &UWillowDownloadableContentManager::CachedExtendedLicenseInfo)
        .def("StaticClass", &UWillowDownloadableContentManager::StaticClass, py::return_value_policy::reference)
        .def("GetSeasonPassPackageCount", &UWillowDownloadableContentManager::GetSeasonPassPackageCount)
        .def("HasSeasonPassContentToInstall", &UWillowDownloadableContentManager::HasSeasonPassContentToInstall)
        .def("HasFutureSeasonPassContentToInstall", &UWillowDownloadableContentManager::HasFutureSeasonPassContentToInstall)
        .def("GetNumberOfLicensedLevelCapUpgrades", &UWillowDownloadableContentManager::GetNumberOfLicensedLevelCapUpgrades)
        .def("GetGoldenKeys", &UWillowDownloadableContentManager::GetGoldenKeys)
        .def("AddGoldenKey", &UWillowDownloadableContentManager::AddGoldenKey)
        .def("StaticIsMarketplaceOfferType", &UWillowDownloadableContentManager::StaticIsMarketplaceOfferType)
        .def("GetCompatibilityPackOfferId", &UWillowDownloadableContentManager::GetCompatibilityPackOfferId)
        .def("GetCompatibilityPackInstalledState", &UWillowDownloadableContentManager::GetCompatibilityPackInstalledState)
        .def("NeedsCompatibilityPack", &UWillowDownloadableContentManager::NeedsCompatibilityPack)
        .def("HasCompatibilityData", &UWillowDownloadableContentManager::HasCompatibilityData)
        .def("ResetDlcCompatInstallRemindTimer", &UWillowDownloadableContentManager::ResetDlcCompatInstallRemindTimer)
        .def("TriggerRefreshComplete", &UWillowDownloadableContentManager::TriggerRefreshComplete)
        .def("IsNewOffer", &UWillowDownloadableContentManager::IsNewOffer)
        .def("GetFreeOfferAssociatedWithPaidOffer", &UWillowDownloadableContentManager::GetFreeOfferAssociatedWithPaidOffer)
        .def("OfferBelongsToSeasonPass", &UWillowDownloadableContentManager::OfferBelongsToSeasonPass)
        .def("StaticGetDlcContentIdForCurrentMap", &UWillowDownloadableContentManager::StaticGetDlcContentIdForCurrentMap)
        .def("StaticGetDlcContentIdForMap", &UWillowDownloadableContentManager::StaticGetDlcContentIdForMap)
        .def("ValidateInstalledContentReachability", &UWillowDownloadableContentManager::ValidateInstalledContentReachability)
        .def("GetDownloadableContentDefinitionFromDlcContentId", &UWillowDownloadableContentManager::GetDownloadableContentDefinitionFromDlcContentId, py::return_value_policy::reference)
        .def("GetDownloadableContentDefinitionFromId", &UWillowDownloadableContentManager::GetDownloadableContentDefinitionFromId, py::return_value_policy::reference)
        .def("GetDownloadablePackageDefinitionFromId", &UWillowDownloadableContentManager::GetDownloadablePackageDefinitionFromId, py::return_value_policy::reference)
        .def("GetDownloadablePackageDefinitionFromDLCName", &UWillowDownloadableContentManager::GetDownloadablePackageDefinitionFromDLCName, py::return_value_policy::reference)
        .def("GetDlcIniPath", &UWillowDownloadableContentManager::GetDlcIniPath)
        .def("IsContentInstalled", &UWillowDownloadableContentManager::IsContentInstalled)
        .def("IsContentLicensed", &UWillowDownloadableContentManager::IsContentLicensed)
        .def("IsPackageFullyInstalled", &UWillowDownloadableContentManager::IsPackageFullyInstalled)
        .def("IsPackageFullyLicensed", &UWillowDownloadableContentManager::IsPackageFullyLicensed)
        .def("FindExpansionForMap", &UWillowDownloadableContentManager::FindExpansionForMap, py::return_value_policy::reference)
        .def("FindMatchingDlcLevelTravelDestination", &UWillowDownloadableContentManager::FindMatchingDlcLevelTravelDestination, py::return_value_policy::reference)
          ;
}