#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_AActionSkill()
{
    class_< AActionSkill, bases< AActor >  , boost::noncopyable>("AActionSkill", no_init)
        .def_readwrite("VfTable_IIInstanceData", &AActionSkill::VfTable_IIInstanceData)
        .def_readwrite("VfTable_IITimerBehavior", &AActionSkill::VfTable_IITimerBehavior)
        .def_readwrite("VfTable_IICustomEvent", &AActionSkill::VfTable_IICustomEvent)
        .def_readwrite("VfTable_IIBehaviorConsumer", &AActionSkill::VfTable_IIBehaviorConsumer)
        .def_readwrite("VfTable_IIBehaviorProvider", &AActionSkill::VfTable_IIBehaviorProvider)
        .def_readwrite("VfTable_IIConstructObject", &AActionSkill::VfTable_IIConstructObject)
        .def_readwrite("TickRate", &AActionSkill::TickRate)
        .def_readwrite("NextTick", &AActionSkill::NextTick)
        .def_readwrite("MyController", &AActionSkill::MyController)
        .def_readwrite("MyWillowPawn", &AActionSkill::MyWillowPawn)
        .def_readwrite("MyWillowPlayerPawn", &AActionSkill::MyWillowPlayerPawn)
        .def_readwrite("MyWillowPC", &AActionSkill::MyWillowPC)
        .def_readwrite("MyWillowMind", &AActionSkill::MyWillowMind)
        .def_readwrite("TargetPawn", &AActionSkill::TargetPawn)
        .def_readwrite("InstanceState", &AActionSkill::InstanceState)
        .def_readwrite("ConsumerHandle", &AActionSkill::ConsumerHandle)
        .def_readwrite("ReplicatedBehaviorConsumerState", &AActionSkill::ReplicatedBehaviorConsumerState)
        .def_readwrite("ReplicatedBehaviorEvent", &AActionSkill::ReplicatedBehaviorEvent)
        .def_readwrite("BehaviorProviderDefinition", &AActionSkill::BehaviorProviderDefinition)
        .def_readwrite("ActionSkillTimers", &AActionSkill::ActionSkillTimers)
        .def_readwrite("CustomEventReplication", &AActionSkill::CustomEventReplication)
        .def_readwrite("ActionSkillNearingCompletionTime", &AActionSkill::ActionSkillNearingCompletionTime)
        .def_readwrite("MaxActivationCountPerActiveCycle", &AActionSkill::MaxActivationCountPerActiveCycle)
        .def_readwrite("ActiveAbilityActivationTimeFrequency", &AActionSkill::ActiveAbilityActivationTimeFrequency)
        .def_readwrite("MaxActivationCountPerCooldownCycle", &AActionSkill::MaxActivationCountPerCooldownCycle)
        .def_readwrite("CooldownAbilityActivationTimeFrequency", &AActionSkill::CooldownAbilityActivationTimeFrequency)
        .def_readwrite("MeleeOverrideSkill", &AActionSkill::MeleeOverrideSkill)
        .def_readwrite("TimeStarted", &AActionSkill::TimeStarted)
        .def("StaticClass", &AActionSkill::StaticClass, return_value_policy< reference_existing_object >())
        .def("ShouldResetOnInterruptedGrenadeThrow", &AActionSkill::ShouldResetOnInterruptedGrenadeThrow)
        .def("CanResetActionSkill", &AActionSkill::CanResetActionSkill)
        .def("eventOverrideCrosshairVisibility", &AActionSkill::eventOverrideCrosshairVisibility)
        .def("eventGetDeferredActionSkillTime", &AActionSkill::eventGetDeferredActionSkillTime)
        .def("eventTickActionSkillHUD", &AActionSkill::eventTickActionSkillHUD)
        .def("eventDisableActionSkillHUD", &AActionSkill::eventDisableActionSkillHUD)
        .def("eventEnableActionSkillHUD", &AActionSkill::eventEnableActionSkillHUD)
        .def("GetBehaviorConsumerHandle", &AActionSkill::GetBehaviorConsumerHandle)
        .def("GetActionSkillEventContextObject", &AActionSkill::GetActionSkillEventContextObject, return_value_policy< reference_existing_object >())
        .def("eventRunCustomEvent", &AActionSkill::eventRunCustomEvent)
        .def("eventHandleTimerEvent", &AActionSkill::eventHandleTimerEvent)
        .def("SetTimerState", &AActionSkill::SetTimerState)
        .def("GetTimerState", &AActionSkill::GetTimerState)
        .def("GetTimeSeconds", &AActionSkill::GetTimeSeconds)
        .def("GetReplicatedInstanceDataState", &AActionSkill::GetReplicatedInstanceDataState)
        .def("GetInstanceDataState", &AActionSkill::GetInstanceDataState)
        .def("DestroyOwnedInstanceData", &AActionSkill::DestroyOwnedInstanceData)
        .def("eventRemoveInstanceDataObject", &AActionSkill::eventRemoveInstanceDataObject)
        .def("eventRemoveInstanceData", &AActionSkill::eventRemoveInstanceData)
        .def("eventGetInstanceData", &AActionSkill::eventGetInstanceData)
        .def("SetInstanceData", &AActionSkill::SetInstanceData)
        .def("EnableDebug", &AActionSkill::EnableDebug)
        .def("NotifyActionSkillActiveAbility", &AActionSkill::NotifyActionSkillActiveAbility)
        .def("StartActionSkillActiveAbility", &AActionSkill::StartActionSkillActiveAbility)
        .def("ClientStartActionSkillActiveAbility", &AActionSkill::ClientStartActionSkillActiveAbility)
        .def("AllowNewActiveAbilityActivation", &AActionSkill::AllowNewActiveAbilityActivation)
        .def("AllowAutomaticActiveAbilityActivation", &AActionSkill::AllowAutomaticActiveAbilityActivation)
        .def("AllowNewCooldownAbilityActivation", &AActionSkill::AllowNewCooldownAbilityActivation)
        .def("AllowAutomaticCooldownAbilityActivation", &AActionSkill::AllowAutomaticCooldownAbilityActivation)
        .def("eventOnActionSkillTick", &AActionSkill::eventOnActionSkillTick)
        .def("OverridesStandardMelee", &AActionSkill::OverridesStandardMelee)
        .def("ReadyToInterceptMelee", &AActionSkill::ReadyToInterceptMelee)
        .def("OnActionSkillOwnerMelee", &AActionSkill::OnActionSkillOwnerMelee)
        .def("OnActionSkillWeaponsRestricted", &AActionSkill::OnActionSkillWeaponsRestricted)
        .def("OnActionSkillOwnerInjured", &AActionSkill::OnActionSkillOwnerInjured)
        .def("OnActionSkillKilledEnemy", &AActionSkill::OnActionSkillKilledEnemy)
        .def("OnActionSkillShowBackMenu", &AActionSkill::OnActionSkillShowBackMenu)
        .def("OnActionSkillFakePause", &AActionSkill::OnActionSkillFakePause)
        .def("OnActionSkillOwnerTouchedActor", &AActionSkill::OnActionSkillOwnerTouchedActor)
        .def("OnActionSkillOwnerHitWall", &AActionSkill::OnActionSkillOwnerHitWall)
        .def("OnActionSkillOwnerStoppedWalking", &AActionSkill::OnActionSkillOwnerStoppedWalking)
        .def("OnActionSkillOwnerBeganWalking", &AActionSkill::OnActionSkillOwnerBeganWalking)
        .def("OnActionSkillOwnerBeganFalling", &AActionSkill::OnActionSkillOwnerBeganFalling)
        .def("eventOnActionSkillOwnerAllieganceChanged", &AActionSkill::eventOnActionSkillOwnerAllieganceChanged)
        .def("OnActionSkillOwnerWeaponSwitched", &AActionSkill::OnActionSkillOwnerWeaponSwitched)
        .def("OnActionSkillOwnerDied", &AActionSkill::OnActionSkillOwnerDied)
        .def("eventOwnerLostAutoAimTarget", &AActionSkill::eventOwnerLostAutoAimTarget)
        .def("eventOwnerAcquiredAutoAimTarget", &AActionSkill::eventOwnerAcquiredAutoAimTarget)
        .def("eventTornOff", &AActionSkill::eventTornOff)
        .def("TearOff", &AActionSkill::TearOff)
        .def("OnActionSkillEnded", &AActionSkill::OnActionSkillEnded)
        .def("eventIsDeactivateBlocked", &AActionSkill::eventIsDeactivateBlocked)
        .def("ClientActionSkillWantsToDeactivate", &AActionSkill::ClientActionSkillWantsToDeactivate)
        .def("eventOnActionSkillWantsToDeactivate", &AActionSkill::eventOnActionSkillWantsToDeactivate)
        .def("OnActionSkillStarted", &AActionSkill::OnActionSkillStarted)
        .def("eventReplicatedEvent", &AActionSkill::eventReplicatedEvent)
        .def("OnActionSkillOwnerShowBackMenu", &AActionSkill::OnActionSkillOwnerShowBackMenu)
        .def("OnTimerEvent", &AActionSkill::OnTimerEvent)
        .def("OnActionSkillNearingCompletion", &AActionSkill::OnActionSkillNearingCompletion)
        .def("OnActionSkillOwnerMeleeOverridden", &AActionSkill::OnActionSkillOwnerMeleeOverridden)
        .def("OnOwnerLostAutoAimTarget", &AActionSkill::OnOwnerLostAutoAimTarget)
        .def("OnOwnerAcquiredAutoAimTarget", &AActionSkill::OnOwnerAcquiredAutoAimTarget)
        .def("OnActionSkillDeactivated", &AActionSkill::OnActionSkillDeactivated)
        .def("OnActionSkillActivated", &AActionSkill::OnActionSkillActivated)
        .def("OnActionSkillActiveAbilityNotified", &AActionSkill::OnActionSkillActiveAbilityNotified)
        .def("OnActionSkillActiveAbilityActivated", &AActionSkill::OnActionSkillActiveAbilityActivated)
        .def("SetBehaviorProviderDefinition", &AActionSkill::SetBehaviorProviderDefinition)
        .def("GetBehaviorProviderDefinition", &AActionSkill::GetBehaviorProviderDefinition, return_value_policy< reference_existing_object >())
        .staticmethod("StaticClass")
  ;
}