#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UAction_ScriptedNPC()
{
    py::class_< UAction_ScriptedNPC,  UWillowActionSequencePawn   >("UAction_ScriptedNPC")
        .def_readwrite("FindLookAtTargetTime", &UAction_GoToScriptedDestination::FindLookAtTargetTime)
        .def_readwrite("PerchData", &UAction_FollowPath::PerchData)
        .def_readwrite("MoveNode", &UAction_FollowPath::MoveNode)
        .def_readwrite("NextNode", &UAction_FollowPath::NextNode)
        .def_readwrite("LastPathFailTime", &UAction_FollowPath::LastPathFailTime)
        .def_readwrite("TimeToStopLooping", &UAction_FollowPath::TimeToStopLooping)
        .def_readwrite("BurrowEnter", &UAction_Burrow::BurrowEnter)
        .def_readwrite("BurrowExit", &UAction_Burrow::BurrowExit)
        .def("StaticClass", &UAction_ScriptedNPC::StaticClass, py::return_value_policy::reference)
        .def("PerchPlayStopBalanced", &UAction_ScriptedNPC::PerchPlayStopBalanced)
        .def("PerchPlayStop", &UAction_ScriptedNPC::PerchPlayStop)
        .def("PerchDone", &UAction_ScriptedNPC::PerchDone)
        .def("PerchStart", &UAction_ScriptedNPC::PerchStart)
        .def("GetDefaultMoveNodeSpeed", &UAction_ScriptedNPC::GetDefaultMoveNodeSpeed)
        .def("SetMoveFacingPolicy", &UAction_ScriptedNPC::SetMoveFacingPolicy)
        .def("SetupLoadBalancePathing", &UAction_ScriptedNPC::SetupLoadBalancePathing)
        .def("SetupLoadBalanceDefaults", &UAction_ScriptedNPC::SetupLoadBalanceDefaults)
        .def("CreateVectorPath", &UAction_ScriptedNPC::CreateVectorPath)
        .def("CreateActorPath", &UAction_ScriptedNPC::CreateActorPath)
        .def("SetPerch", &UAction_ScriptedNPC::SetPerch)
        .def("PathAttemptFinished", &UAction_ScriptedNPC::PathAttemptFinished)
        .def("GetDesiredStateName", &UAction_ScriptedNPC::GetDesiredStateName)
        .def("CheckStateTransition", &UAction_ScriptedNPC::CheckStateTransition)
        .def("eventCanRun", &UAction_ScriptedNPC::eventCanRun)
        .def("FindLookAtTarget", &UAction_GoToScriptedDestination::FindLookAtTarget)
        .def("ReachedFormation", &UAction_GoToScriptedDestination::ReachedFormation)
        .def("CanFollowFormationOwner", &UAction_GoToScriptedDestination::CanFollowFormationOwner)
        .def("InRange", &UAction_GoToScriptedDestination::InRange)
        .def("WantsPath", &UAction_GoToScriptedDestination::WantsPath)
        .def("SetMoveNode", &UAction_GoToScriptedDestination::SetMoveNode)
        .def("GetMoveNode", &UAction_GoToScriptedDestination::GetMoveNode, py::return_value_policy::reference)
        .def("SetMoveNodeSpeed", &UAction_GoToScriptedDestination::SetMoveNodeSpeed)
        .def("LookAtScriptedFocus", &UAction_GoToScriptedDestination::LookAtScriptedFocus)
        .def("ShouldLookAtPlayer", &UAction_GoToScriptedDestination::ShouldLookAtPlayer)
        .def("eventActivateEvent", &UAction_GoToScriptedDestination::eventActivateEvent)
        .def("eventUpdate", &UAction_GoToScriptedDestination::eventUpdate)
        .def("eventStop", &UAction_GoToScriptedDestination::eventStop)
        .def("eventStart", &UAction_GoToScriptedDestination::eventStart)
        .def("PerchStop", &UAction_FollowPath::PerchStop)
        .def("PerchPlayLoop", &UAction_FollowPath::PerchPlayLoop)
        .def("PerchPlayIdle", &UAction_FollowPath::PerchPlayIdle)
        .def("GetPerchConsumerHandle", &UAction_FollowPath::GetPerchConsumerHandle)
        .def("SpecialMoveCallback", &UAction_FollowPath::SpecialMoveCallback)
        .def("SetSpecialMoves", &UAction_FollowPath::SetSpecialMoves)
        .def("MoveTimerCallback", &UAction_FollowPath::MoveTimerCallback)
        .def("SetMoveTimer", &UAction_FollowPath::SetMoveTimer)
        .def("CheckCloaked", &UAction_Burrow::CheckCloaked)
        .def("SafeToUncloak", &UAction_Burrow::SafeToUncloak)
        .def("ForceUncloak", &UAction_Burrow::ForceUncloak)
        .def("ForceCloak", &UAction_Burrow::ForceCloak)
        .staticmethod("StaticClass")
  ;
}