#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_AWillowGrenadeMod()
{
    py::class_< AWillowGrenadeMod,  AWillowEquipAbleItem   >("AWillowGrenadeMod")
        .def_readwrite("GrenadeDamage", &AWillowGrenadeMod::GrenadeDamage)
        .def_readwrite("GrenadeDamageBaseValue", &AWillowGrenadeMod::GrenadeDamageBaseValue)
        .def_readwrite("GrenadeDamageModifierStack", &AWillowGrenadeMod::GrenadeDamageModifierStack)
        .def_readwrite("BlastRadius", &AWillowGrenadeMod::BlastRadius)
        .def_readwrite("BlastRadiusBaseValue", &AWillowGrenadeMod::BlastRadiusBaseValue)
        .def_readwrite("BlastRadiusModifierStack", &AWillowGrenadeMod::BlastRadiusModifierStack)
        .def_readwrite("FuseTime", &AWillowGrenadeMod::FuseTime)
        .def_readwrite("FuseTimeBaseValue", &AWillowGrenadeMod::FuseTimeBaseValue)
        .def_readwrite("FuseTimeModifierStack", &AWillowGrenadeMod::FuseTimeModifierStack)
        .def_readwrite("NumberOfChildProjectiles", &AWillowGrenadeMod::NumberOfChildProjectiles)
        .def_readwrite("NumberOfChildProjectilesBaseValue", &AWillowGrenadeMod::NumberOfChildProjectilesBaseValue)
        .def_readwrite("NumberOfChildProjectilesModifierStack", &AWillowGrenadeMod::NumberOfChildProjectilesModifierStack)
        .def_readwrite("BaseStatusEffectChanceModifier", &AWillowGrenadeMod::BaseStatusEffectChanceModifier)
        .def_readwrite("BaseStatusEffectChanceModifierBaseValue", &AWillowGrenadeMod::BaseStatusEffectChanceModifierBaseValue)
        .def_readwrite("BaseStatusEffectChanceModifierModifierStack", &AWillowGrenadeMod::BaseStatusEffectChanceModifierModifierStack)
        .def_readwrite("StatusEffectChanceModifier", &AWillowGrenadeMod::StatusEffectChanceModifier)
        .def_readwrite("StatusEffectChanceModifierBaseValue", &AWillowGrenadeMod::StatusEffectChanceModifierBaseValue)
        .def_readwrite("StatusEffectChanceModifierModifierStack", &AWillowGrenadeMod::StatusEffectChanceModifierModifierStack)
        .def_readwrite("StatusEffectDamage", &AWillowGrenadeMod::StatusEffectDamage)
        .def_readwrite("StatusEffectDamageBaseValue", &AWillowGrenadeMod::StatusEffectDamageBaseValue)
        .def_readwrite("StatusEffectDamageModifierStack", &AWillowGrenadeMod::StatusEffectDamageModifierStack)
        .def("StaticClass", &AWillowGrenadeMod::StaticClass, py::return_value_policy::reference)
        .def("GetItemCardTopSectionString", &AWillowGrenadeMod::GetItemCardTopSectionString)
        .def("eventGetCategoryKey", &AWillowGrenadeMod::eventGetCategoryKey)
        .def("eventSetGrenadeStorage", &AWillowGrenadeMod::eventSetGrenadeStorage)
        .def("RemoveFromShop", &AWillowGrenadeMod::RemoveFromShop)
        .def("CreatePickup", &AWillowGrenadeMod::CreatePickup, py::return_value_policy::reference)
        .def("GetPickup", &AWillowGrenadeMod::GetPickup, py::return_value_policy::reference)
        .def("GetHolsteredGearLikenessType", &AWillowGrenadeMod::GetHolsteredGearLikenessType)
        .def("GetAttributePresentationOverride", &AWillowGrenadeMod::GetAttributePresentationOverride, py::return_value_policy::reference)
        .def("CanAIUse", &AWillowGrenadeMod::CanAIUse)
        .def("GetProjectileDefinition", &AWillowGrenadeMod::GetProjectileDefinition, py::return_value_policy::reference)
        .def("Init", &AWillowGrenadeMod::Init)
        .def("SpawnProjectile", &AWillowGrenadeMod::SpawnProjectile, py::return_value_policy::reference)
        .def("SetElementalFrame", &AWillowGrenadeMod::SetElementalFrame)
        .def("ValidateDefinitions", &AWillowGrenadeMod::ValidateDefinitions)
        .def("GetEquippedStat", &AWillowGrenadeMod::GetEquippedStat)
        .def("eventGetEquipmentLocation", &AWillowGrenadeMod::eventGetEquipmentLocation)
        .def("OnGrenadeKilledEnemy", &AWillowGrenadeMod::OnGrenadeKilledEnemy)
        .def("OnGrenadeKilledFriendly", &AWillowGrenadeMod::OnGrenadeKilledFriendly)
        .def("OnGrenadeKilledNeutral", &AWillowGrenadeMod::OnGrenadeKilledNeutral)
        .def("OnGrenadeDamagedNeutral", &AWillowGrenadeMod::OnGrenadeDamagedNeutral)
        .def("OnGrenadeDamagedFriendly", &AWillowGrenadeMod::OnGrenadeDamagedFriendly)
        .def("OnGrenadeDamagedEnemy", &AWillowGrenadeMod::OnGrenadeDamagedEnemy)
        .def("OnGrenadeExploded", &AWillowGrenadeMod::OnGrenadeExploded)
        .def("OnGrenadeSpawned", &AWillowGrenadeMod::OnGrenadeSpawned)
        .staticmethod("StaticClass")
  ;
}