#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UGearboxAnimDefinition(py::module &m)
{
    py::class_< UGearboxAnimDefinition,  USpecialMoveDefinition   >(m, "UGearboxAnimDefinition")
		.def_static("StaticClass", &UGearboxAnimDefinition::StaticClass, py::return_value_policy::reference)
        .def_readwrite("VfTable_IIBehaviorProvider", &UGearboxAnimDefinition::VfTable_IIBehaviorProvider)
        .def_readwrite("AnimName", &UGearboxAnimDefinition::AnimName)
        .def_readwrite("BlendInTime", &UGearboxAnimDefinition::BlendInTime)
        .def_readwrite("BlendOutTime", &UGearboxAnimDefinition::BlendOutTime)
        .def_readwrite("PlayRate", &UGearboxAnimDefinition::PlayRate)
        .def_readwrite("EndingCondition", &UGearboxAnimDefinition::EndingCondition)
        .def_readwrite("AnimSet", &UGearboxAnimDefinition::AnimSet)
        .def_readwrite("AnimNodeName", &UGearboxAnimDefinition::AnimNodeName)
        .def_readwrite("RootMotionDef", &UGearboxAnimDefinition::RootMotionDef)
        .def_readwrite("BoneBlendDef", &UGearboxAnimDefinition::BoneBlendDef)
        .def_readwrite("BoneNames", &UGearboxAnimDefinition::BoneNames)
        .def_readwrite("StartBehaviors", &UGearboxAnimDefinition::StartBehaviors)
        .def_readwrite("SMNotifies", &UGearboxAnimDefinition::SMNotifies)
        .def_readwrite("StopBehaviors", &UGearboxAnimDefinition::StopBehaviors)
        .def_readwrite("TimedBehaviorEvents", &UGearboxAnimDefinition::TimedBehaviorEvents)
        .def_readwrite("BehaviorProviderDefinition", &UGearboxAnimDefinition::BehaviorProviderDefinition)
        .def("GetAnimLength", &UGearboxAnimDefinition::GetAnimLength)
        .def("eventIsPlayingLocally", &UGearboxAnimDefinition::eventIsPlayingLocally)
        .def("GetSMNode", &UGearboxAnimDefinition::GetSMNode, py::return_value_policy::reference)
        .def("PlayAnim", &UGearboxAnimDefinition::PlayAnim)
        .def("eventAnimFinished", &UGearboxAnimDefinition::eventAnimFinished)
        .def("eventClientFinished", &UGearboxAnimDefinition::eventClientFinished)
        .def("eventClientStarted", &UGearboxAnimDefinition::eventClientStarted)
        .def("eventServerFinished", &UGearboxAnimDefinition::eventServerFinished)
        .def("eventServerStarted", &UGearboxAnimDefinition::eventServerStarted)
        .def("AddAnimSet", &UGearboxAnimDefinition::AddAnimSet)
        .def("GetSkeletalMesh", &UGearboxAnimDefinition::GetSkeletalMesh, py::return_value_policy::reference)
        .def("eventAuthorityCanPlay", &UGearboxAnimDefinition::eventAuthorityCanPlay)
        .def("OnTimedEvent", &UGearboxAnimDefinition::OnTimedEvent)
        .def("OnServerStop", &UGearboxAnimDefinition::OnServerStop)
        .def("OnServerStart", &UGearboxAnimDefinition::OnServerStart)
        .def("OnStop", &UGearboxAnimDefinition::OnStop)
        .def("OnStart", &UGearboxAnimDefinition::OnStart)
        .def("SetBehaviorProviderDefinition", &UGearboxAnimDefinition::SetBehaviorProviderDefinition)
        .def("GetBehaviorProviderDefinition", &UGearboxAnimDefinition::GetBehaviorProviderDefinition, py::return_value_policy::reference)
          ;
}