#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UOnlineAuthInterface()
{
    class_< UOnlineAuthInterface, bases< UInterface >  , boost::noncopyable>("UOnlineAuthInterface", no_init)
        .def("StaticClass", &UOnlineAuthInterface::StaticClass, return_value_policy< reference_existing_object >())
        .def("GetServerAddr", &UOnlineAuthInterface::GetServerAddr)
        .def("GetServerUniqueId", &UOnlineAuthInterface::GetServerUniqueId)
        .def("EndRemoteServerAuthSession", &UOnlineAuthInterface::EndRemoteServerAuthSession)
        .def("EndLocalServerAuthSession", &UOnlineAuthInterface::EndLocalServerAuthSession)
        .def("VerifyServerAuthSession", &UOnlineAuthInterface::VerifyServerAuthSession)
        .def("CreateServerAuthSession", &UOnlineAuthInterface::CreateServerAuthSession)
        .def("EndRemoteClientAuthSession", &UOnlineAuthInterface::EndRemoteClientAuthSession)
        .def("EndLocalClientAuthSession", &UOnlineAuthInterface::EndLocalClientAuthSession)
        .def("VerifyClientAuthSession", &UOnlineAuthInterface::VerifyClientAuthSession)
        .def("CreateClientAuthSession", &UOnlineAuthInterface::CreateClientAuthSession)
        .def("SendAuthRetryServer", &UOnlineAuthInterface::SendAuthRetryServer)
        .def("SendAuthKillClient", &UOnlineAuthInterface::SendAuthKillClient)
        .def("SendAuthBlobServer", &UOnlineAuthInterface::SendAuthBlobServer)
        .def("SendAuthBlobClient", &UOnlineAuthInterface::SendAuthBlobClient)
        .def("SendAuthRequestServer", &UOnlineAuthInterface::SendAuthRequestServer)
        .def("SendAuthRequestClient", &UOnlineAuthInterface::SendAuthRequestClient)
        .def("ClearServerConnectionCloseDelegate", &UOnlineAuthInterface::ClearServerConnectionCloseDelegate)
        .def("AddServerConnectionCloseDelegate", &UOnlineAuthInterface::AddServerConnectionCloseDelegate)
        .def("OnServerConnectionClose", &UOnlineAuthInterface::OnServerConnectionClose)
        .def("ClearClientConnectionCloseDelegate", &UOnlineAuthInterface::ClearClientConnectionCloseDelegate)
        .def("AddClientConnectionCloseDelegate", &UOnlineAuthInterface::AddClientConnectionCloseDelegate)
        .def("OnClientConnectionClose", &UOnlineAuthInterface::OnClientConnectionClose)
        .def("ClearAuthRetryServerDelegate", &UOnlineAuthInterface::ClearAuthRetryServerDelegate)
        .def("AddAuthRetryServerDelegate", &UOnlineAuthInterface::AddAuthRetryServerDelegate)
        .def("OnAuthRetryServer", &UOnlineAuthInterface::OnAuthRetryServer)
        .def("ClearAuthKillClientDelegate", &UOnlineAuthInterface::ClearAuthKillClientDelegate)
        .def("AddAuthKillClientDelegate", &UOnlineAuthInterface::AddAuthKillClientDelegate)
        .def("OnAuthKillClient", &UOnlineAuthInterface::OnAuthKillClient)
        .def("ClearAuthCompleteServerDelegate", &UOnlineAuthInterface::ClearAuthCompleteServerDelegate)
        .def("AddAuthCompleteServerDelegate", &UOnlineAuthInterface::AddAuthCompleteServerDelegate)
        .def("OnAuthCompleteServer", &UOnlineAuthInterface::OnAuthCompleteServer)
        .def("ClearAuthCompleteClientDelegate", &UOnlineAuthInterface::ClearAuthCompleteClientDelegate)
        .def("AddAuthCompleteClientDelegate", &UOnlineAuthInterface::AddAuthCompleteClientDelegate)
        .def("OnAuthCompleteClient", &UOnlineAuthInterface::OnAuthCompleteClient)
        .def("ClearAuthBlobReceivedServerDelegate", &UOnlineAuthInterface::ClearAuthBlobReceivedServerDelegate)
        .def("AddAuthBlobReceivedServerDelegate", &UOnlineAuthInterface::AddAuthBlobReceivedServerDelegate)
        .def("OnAuthBlobReceivedServer", &UOnlineAuthInterface::OnAuthBlobReceivedServer)
        .def("ClearAuthBlobReceivedClientDelegate", &UOnlineAuthInterface::ClearAuthBlobReceivedClientDelegate)
        .def("AddAuthBlobReceivedClientDelegate", &UOnlineAuthInterface::AddAuthBlobReceivedClientDelegate)
        .def("OnAuthBlobReceivedClient", &UOnlineAuthInterface::OnAuthBlobReceivedClient)
        .def("ClearAuthRequestServerDelegate", &UOnlineAuthInterface::ClearAuthRequestServerDelegate)
        .def("AddAuthRequestServerDelegate", &UOnlineAuthInterface::AddAuthRequestServerDelegate)
        .def("OnAuthRequestServer", &UOnlineAuthInterface::OnAuthRequestServer)
        .def("ClearAuthRequestClientDelegate", &UOnlineAuthInterface::ClearAuthRequestClientDelegate)
        .def("AddAuthRequestClientDelegate", &UOnlineAuthInterface::AddAuthRequestClientDelegate)
        .def("OnAuthRequestClient", &UOnlineAuthInterface::OnAuthRequestClient)
        .def("ClearAuthReadyDelegate", &UOnlineAuthInterface::ClearAuthReadyDelegate)
        .def("AddAuthReadyDelegate", &UOnlineAuthInterface::AddAuthReadyDelegate)
        .def("OnAuthReady", &UOnlineAuthInterface::OnAuthReady)
        .def("IsReady", &UOnlineAuthInterface::IsReady)
        .staticmethod("StaticClass")
  ;
}