#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UPopulationMaster(py::module &m)
{
    py::class_< UPopulationMaster,  UObject   >(m, "UPopulationMaster")
        .def_readwrite("OpportunityList", &UPopulationMaster::OpportunityList)
        .def_readwrite("ActiveActorCost", &UPopulationMaster::ActiveActorCost)
        .def_readwrite("MaxActorCost", &UPopulationMaster::MaxActorCost)
        .def_readwrite("MasterThinkRate", &UPopulationMaster::MasterThinkRate)
        .def_readwrite("MasterTestForDestroyRate", &UPopulationMaster::MasterTestForDestroyRate)
        .def_readwrite("IfIrrelevantDestroyTimeout", &UPopulationMaster::IfIrrelevantDestroyTimeout)
        .def_readwrite("PopulationMasterStats", &UPopulationMaster::PopulationMasterStats)
        .def_readwrite("EncounterList", &UPopulationMaster::EncounterList)
        .def_readwrite("SecondsElapsed", &UPopulationMaster::SecondsElapsed)
        .def_readwrite("NextOpportunityTickTime", &UPopulationMaster::NextOpportunityTickTime)
        .def_readwrite("NextDestroyTestTickTime", &UPopulationMaster::NextDestroyTestTickTime)
        .def_readwrite("PopulationRespawnDelayInSeconds", &UPopulationMaster::PopulationRespawnDelayInSeconds)
        .def("GetActorSpawnedFromOpportunity", &UPopulationMaster::GetActorSpawnedFromOpportunity, py::return_value_policy::reference)
        .def("GetSavedActorDebugInfoForOpportunity", &UPopulationMaster::GetSavedActorDebugInfoForOpportunity)
        .def("GetNumberOfSavedActorsForOpportunity", &UPopulationMaster::GetNumberOfSavedActorsForOpportunity)
        .def("WillActorsOpportunityBeResetOnLevelLoad", &UPopulationMaster::WillActorsOpportunityBeResetOnLevelLoad)
        .def("ResetRespawn", &UPopulationMaster::ResetRespawn)
        .def("GetStreamingLevelForActor", &UPopulationMaster::GetStreamingLevelForActor, py::return_value_policy::reference)
        .def("HasCapacityToSpawnFromFactories", &UPopulationMaster::HasCapacityToSpawnFromFactories)
        .def("HasCapacityToSpawnFromFactory", &UPopulationMaster::HasCapacityToSpawnFromFactory)
        .def("IsPopulationSystemAtCapacity", &UPopulationMaster::IsPopulationSystemAtCapacity)
        .def("StatProfileStop", &UPopulationMaster::StatProfileStop)
        .def("StatProfileStart", &UPopulationMaster::StatProfileStart)
        .def("GetStatProfileTime", &UPopulationMaster::GetStatProfileTime)
        .def("AddSavedActor", &UPopulationMaster::AddSavedActor)
        .def("DisconnectEncounter", &UPopulationMaster::DisconnectEncounter)
        .def("ConnectEncounter", &UPopulationMaster::ConnectEncounter)
        .def("DisconnectOpportunity", &UPopulationMaster::DisconnectOpportunity)
        .def("ConnectOpportunity", &UPopulationMaster::ConnectOpportunity)
        .def("GetWorldInfo", &UPopulationMaster::GetWorldInfo, py::return_value_policy::reference)
        .def("DestroySpawnedActors", &UPopulationMaster::DestroySpawnedActors)
        .def("RemoveSpawnedActor", &UPopulationMaster::RemoveSpawnedActor)
        .def("SetSpawnedActorsReuse", &UPopulationMaster::SetSpawnedActorsReuse)
        .def("AddExternalActor", &UPopulationMaster::AddExternalActor)
        .def("SpawnActorFromOpportunity", &UPopulationMaster::SpawnActorFromOpportunity, py::return_value_policy::reference)
        .def("SpawnActor", &UPopulationMaster::SpawnActor, py::return_value_policy::reference)
        .def("GetPopulationOpportunityIndex", &UPopulationMaster::GetPopulationOpportunityIndex)
        .def("GetActorsOpportunity", &UPopulationMaster::GetActorsOpportunity, py::return_value_policy::reference)
        .def("SpawnPopulationControlledActor", &UPopulationMaster::SpawnPopulationControlledActor, py::return_value_policy::reference)
          ;
}