#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_APopulationOpportunity(py::object m)
{
    py::class_< APopulationOpportunity,  AInfo   >(m, "APopulationOpportunity")
        .def_readwrite("VfTable_IIBodyCompositionInstance", &APopulationOpportunity::VfTable_IIBodyCompositionInstance)
        .def_readwrite("CleanupParams", &APopulationOpportunity::CleanupParams)
        .def_readwrite("SpawnPoints", &APopulationOpportunity::SpawnPoints)
        .def_readwrite("StreamingLevel", &APopulationOpportunity::StreamingLevel)
        .def_readwrite("SystemID", &APopulationOpportunity::SystemID)
        .def_readwrite("NextInitialDestinationIdx", &APopulationOpportunity::NextInitialDestinationIdx)
        .def_readwrite("SequenceActionLink", &APopulationOpportunity::SequenceActionLink)
        .def_readwrite("LastTimeBlockedFromSpawningDueToPopLimits", &APopulationOpportunity::LastTimeBlockedFromSpawningDueToPopLimits)
        .def_readwrite("RespawnDelayStartTime", &APopulationOpportunity::RespawnDelayStartTime)
        .def_readwrite("GameStageRegion", &APopulationOpportunity::GameStageRegion)
        .def_readwrite("Aspect", &APopulationOpportunity::Aspect)
        .def_readwrite("SpawnIndex", &APopulationOpportunity::SpawnIndex)
        .def_readwrite("SpawnList", &APopulationOpportunity::SpawnList)
        .def_readwrite("InclusiveSpawnIndex", &APopulationOpportunity::InclusiveSpawnIndex)
        .def_readwrite("InclusiveSpawnList", &APopulationOpportunity::InclusiveSpawnList)
        .def("StaticClass", &APopulationOpportunity::StaticClass, py::return_value_policy::reference)
        .def("ClearBodyCompositionInstance", &APopulationOpportunity::ClearBodyCompositionInstance)
        .def("ApplyPreviewBodyComposition", &APopulationOpportunity::ApplyPreviewBodyComposition)
        .def("GetBodyInfoProvider", &APopulationOpportunity::GetBodyInfoProvider, py::return_value_policy::reference)
        .def("ChangeInstanceDataSwitch", &APopulationOpportunity::ChangeInstanceDataSwitch)
        .def("PostInitBodyComposition", &APopulationOpportunity::PostInitBodyComposition)
        .def("PreRemoveBodyComposition", &APopulationOpportunity::PreRemoveBodyComposition)
        .def("GetNumSpawned", &APopulationOpportunity::GetNumSpawned)
        .def("GetNumAlive", &APopulationOpportunity::GetNumAlive)
        .def("GetNumDied", &APopulationOpportunity::GetNumDied)
        .def("eventDestroyed", &APopulationOpportunity::eventDestroyed)
        .def("GetRarity", &APopulationOpportunity::GetRarity)
        .def("GetGameStage", &APopulationOpportunity::GetGameStage)
        .def("GetOpportunityGameStage", &APopulationOpportunity::GetOpportunityGameStage)
        .def("eventTriggerKismetAllSpawnedEvent", &APopulationOpportunity::eventTriggerKismetAllSpawnedEvent)
        .def("eventClearSequenceActionLink", &APopulationOpportunity::eventClearSequenceActionLink)
        .def("eventSetSequenceActionLink", &APopulationOpportunity::eventSetSequenceActionLink)
        .def("SetEnabledStatus", &APopulationOpportunity::SetEnabledStatus)
        .def("OnToggle", &APopulationOpportunity::OnToggle)
        .def("GetNumLeftToSpawnAndStillAlive", &APopulationOpportunity::GetNumLeftToSpawnAndStillAlive)
        .def("GetNextSpawnTime", &APopulationOpportunity::GetNextSpawnTime)
        .def("RespawnKilledActors", &APopulationOpportunity::RespawnKilledActors)
        .def("DoSpawning", &APopulationOpportunity::DoSpawning)
          ;
}