#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_ULocalPlayer(py::module &m)
{
    py::class_< ULocalPlayer, UPlayer  >(m, "ULocalPlayer")
		.def_static("StaticClass", &ULocalPlayer::StaticClass, py::return_value_policy::reference)
        .def_readwrite("VfTable_FObserverInterface", &ULocalPlayer::VfTable_FObserverInterface)
        .def_readwrite("ControllerId", &ULocalPlayer::ControllerId)
        .def_readwrite("ViewportClient", &ULocalPlayer::ViewportClient)
        .def_readwrite("Origin", &ULocalPlayer::Origin)
        .def_readwrite("Size", &ULocalPlayer::Size)
        .def_readwrite("PlayerPostProcess", &ULocalPlayer::PlayerPostProcess)
        .def_readwrite("PlayerPostProcessChains", &ULocalPlayer::PlayerPostProcessChains)
        .def_readwrite("ViewState", &ULocalPlayer::ViewState)
        .def_readwrite("ActorVisibilityHistory", &ULocalPlayer::ActorVisibilityHistory)
        .def_readwrite("LastViewLocation", &ULocalPlayer::LastViewLocation)
        .def_readwrite("CurrentPPInfo", &ULocalPlayer::CurrentPPInfo)
        .def_readwrite("LevelPPInfo", &ULocalPlayer::LevelPPInfo)
        .def_readwrite("ActivePPOverrides", &ULocalPlayer::ActivePPOverrides)
        .def_readwrite("WorldLightingOverrides", &ULocalPlayer::WorldLightingOverrides)
        .def_readwrite("AspectRatioAxisConstraint", &ULocalPlayer::AspectRatioAxisConstraint)
        .def_readwrite("LastMap", &ULocalPlayer::LastMap)
        .def_readwrite("TagContext", &ULocalPlayer::TagContext)
        .def_readwrite("CachedAuthInt", &ULocalPlayer::CachedAuthInt)
        .def_readwrite("ServerAuthTimestamp", &ULocalPlayer::ServerAuthTimestamp)
        .def_readwrite("ServerAuthTimeout", &ULocalPlayer::ServerAuthTimeout)
        .def_readwrite("ServerAuthRetryCount", &ULocalPlayer::ServerAuthRetryCount)
        .def_readwrite("MaxServerAuthRetryCount", &ULocalPlayer::MaxServerAuthRetryCount)
        .def_readwrite("ServerAuthUID", &ULocalPlayer::ServerAuthUID)
        .def_readwrite("ViewProjectionMatrix", &ULocalPlayer::ViewProjectionMatrix)
        .def_readwrite("ViewProjMatTimestamp", &ULocalPlayer::ViewProjMatTimestamp)
        .def("Cleanup", &ULocalPlayer::Cleanup)
        .def("eventExit", &ULocalPlayer::eventExit)
        .def("eventNotifyServerConnectionClose", &ULocalPlayer::eventNotifyServerConnectionClose)
        .def("eventViewportClosed", &ULocalPlayer::eventViewportClosed)
        .def("StaticOnServerConnectionClose", &ULocalPlayer::StaticOnServerConnectionClose)
        .def("OnServerConnectionClose", &ULocalPlayer::OnServerConnectionClose)
        .def("ServerAuthFailure", &ULocalPlayer::ServerAuthFailure)
        .def("eventServerAuthTimedOut", &ULocalPlayer::eventServerAuthTimedOut)
        .def("OnAuthCompleteServer", &ULocalPlayer::OnAuthCompleteServer)
        .def("OnAuthBlobReceivedServer", &ULocalPlayer::OnAuthBlobReceivedServer)
        .def("OnAuthKillClient", &ULocalPlayer::OnAuthKillClient)
        .def("OnAuthRequestClient", &ULocalPlayer::OnAuthRequestClient)
        .def("eventNotifyServerConnectionOpen", &ULocalPlayer::eventNotifyServerConnectionOpen)
        .def("eventGetNickname", &ULocalPlayer::eventGetNickname)
        .def("eventGetUniqueNetId", &ULocalPlayer::eventGetUniqueNetId)
        .def("DeProject", &ULocalPlayer::DeProject)
        .def("Project", &ULocalPlayer::Project)
        .def("UpdateLightingOverrides", &ULocalPlayer::UpdateLightingOverrides)
        .def("RemoveWorldLightingOverride", &ULocalPlayer::RemoveWorldLightingOverride)
        .def("OverrideWorldLighting", &ULocalPlayer::OverrideWorldLighting)
        .def("TouchPlayerPostProcessChain", &ULocalPlayer::TouchPlayerPostProcessChain)
        .def("GetPostProcessChain", &ULocalPlayer::GetPostProcessChain, py::return_value_policy::reference)
        .def("RemoveAllPostProcessingChains", &ULocalPlayer::RemoveAllPostProcessingChains)
        .def("RemovePostProcessingChain", &ULocalPlayer::RemovePostProcessingChain)
        .def("InsertPostProcessingChain", &ULocalPlayer::InsertPostProcessingChain)
        .def("GetTranslationContext", &ULocalPlayer::GetTranslationContext, py::return_value_policy::reference)
        .def("SetControllerId", &ULocalPlayer::SetControllerId)
        .def("ClearPostProcessSettingsOverride", &ULocalPlayer::ClearPostProcessSettingsOverride)
        .def("OverridePostProcessSettings", &ULocalPlayer::OverridePostProcessSettings)
        .def("GetActorVisibility", &ULocalPlayer::GetActorVisibility)
        .def("SendSplitJoin", &ULocalPlayer::SendSplitJoin)
        .def("SpawnPlayActor", &ULocalPlayer::SpawnPlayActor)
          ;
}