#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UDownloadableContentManager(py::object m)
{
    py::class_< UDownloadableContentManager,  UObject   >(m, "UDownloadableContentManager")
        .def_readwrite("DLCConfigCacheChanges", &UDownloadableContentManager::DLCConfigCacheChanges)
        .def_readwrite("DlcOffers", &UDownloadableContentManager::DlcOffers)
        .def_readwrite("InstalledContent", &UDownloadableContentManager::InstalledContent)
        .def_readwrite("RejectedContent", &UDownloadableContentManager::RejectedContent)
        .def_readwrite("CookInstanceGuid", &UDownloadableContentManager::CookInstanceGuid)
        .def_readwrite("NonPackageFilePathMapExtensions", &UDownloadableContentManager::NonPackageFilePathMapExtensions)
        .def_readwrite("NonPackageFilePathMap", &UDownloadableContentManager::NonPackageFilePathMap)
        .def_readwrite("AudioPackageFilePathmap", &UDownloadableContentManager::AudioPackageFilePathmap)
        .def_readwrite("ClassesToReload", &UDownloadableContentManager::ClassesToReload)
        .def_readwrite("ObjectsToReload", &UDownloadableContentManager::ObjectsToReload)
        .def_readwrite("LicensedSeasonPassIds", &UDownloadableContentManager::LicensedSeasonPassIds)
        .def_readwrite("LastRefreshStartTime", &UDownloadableContentManager::LastRefreshStartTime)
        .def_readwrite("LastRefreshFinishTime", &UDownloadableContentManager::LastRefreshFinishTime)
        .def_readwrite("RefreshCount", &UDownloadableContentManager::RefreshCount)
        .def_readwrite("GameEngine", &UDownloadableContentManager::GameEngine)
        .def_readwrite("RefreshCompleteDelegates", &UDownloadableContentManager::RefreshCompleteDelegates)
        .def("StaticClass", &UDownloadableContentManager::StaticClass, py::return_value_policy::reference)
        .def("IsSeasonPassLicensed", &UDownloadableContentManager::IsSeasonPassLicensed)
        .def("GetMarketplaceOfferInstalledState", &UDownloadableContentManager::GetMarketplaceOfferInstalledState)
        .def("GetMarketplaceContentInstalledState", &UDownloadableContentManager::GetMarketplaceContentInstalledState)
        .def("StaticSetUsesAsynchronousInstallation", &UDownloadableContentManager::StaticSetUsesAsynchronousInstallation)
        .def("StaticUsesAsynchronousInstallation", &UDownloadableContentManager::StaticUsesAsynchronousInstallation)
        .def("NeedsRefresh", &UDownloadableContentManager::NeedsRefresh)
        .def("IsInStartMenu", &UDownloadableContentManager::IsInStartMenu)
        .def("IsBusy", &UDownloadableContentManager::IsBusy)
        .def("CouldEnumerateMarketplaceContent", &UDownloadableContentManager::CouldEnumerateMarketplaceContent)
        .def("CanEnumerateMarketplaceContent", &UDownloadableContentManager::CanEnumerateMarketplaceContent)
        .def("CouldInstallCompatibilityContent", &UDownloadableContentManager::CouldInstallCompatibilityContent)
        .def("CanInstallCompatibilityContent", &UDownloadableContentManager::CanInstallCompatibilityContent)
        .def("TriggerRefreshCompleteDelegates", &UDownloadableContentManager::TriggerRefreshCompleteDelegates)
        .def("ClearRefreshCompleteDelegate", &UDownloadableContentManager::ClearRefreshCompleteDelegate)
        .def("AddRefreshCompleteDelegate", &UDownloadableContentManager::AddRefreshCompleteDelegate)
        .def("OnRefreshComplete", &UDownloadableContentManager::OnRefreshComplete)
        .def("AddPackagesToFullyLoad", &UDownloadableContentManager::AddPackagesToFullyLoad)
        .def("TriggerRefreshComplete", &UDownloadableContentManager::TriggerRefreshComplete)
        .def("GetAppSeconds", &UDownloadableContentManager::GetAppSeconds)
        .def("RefreshOffersComplete", &UDownloadableContentManager::RefreshOffersComplete)
        .def("RefreshDLCComplete", &UDownloadableContentManager::RefreshDLCComplete)
        .def("eventRefreshDLC", &UDownloadableContentManager::eventRefreshDLC)
        .def("HasBeenRefreshed", &UDownloadableContentManager::HasBeenRefreshed)
        .def("TryContentChangeEventRefresh", &UDownloadableContentManager::TryContentChangeEventRefresh)
        .def("OnContentChange", &UDownloadableContentManager::OnContentChange)
        .def("OnStorageDeviceChange", &UDownloadableContentManager::OnStorageDeviceChange)
        .def("OnLoginChange", &UDownloadableContentManager::OnLoginChange)
        .def("NativeInit", &UDownloadableContentManager::NativeInit)
        .def("eventInit", &UDownloadableContentManager::eventInit)
        .def("HasEnumeratedMarketplaceContent", &UDownloadableContentManager::HasEnumeratedMarketplaceContent)
        .def("HasUnseenUninstallableEngineVersionContent", &UDownloadableContentManager::HasUnseenUninstallableEngineVersionContent)
        .def("HasUnseenInstalledContent", &UDownloadableContentManager::HasUnseenInstalledContent)
        .def("HasUnseenUninstallableLicensedContent", &UDownloadableContentManager::HasUnseenUninstallableLicensedContent)
        .def("HasUninstallableCompatibilityContent", &UDownloadableContentManager::HasUninstallableCompatibilityContent)
        .def("HasUnseenUninstallableCompatibilityContent", &UDownloadableContentManager::HasUnseenUninstallableCompatibilityContent)
        .def("GetCorruptContentNames", &UDownloadableContentManager::GetCorruptContentNames)
        .def("HasUnseenCorruptContent", &UDownloadableContentManager::HasUnseenCorruptContent)
        .def("InstallNonPackageFiles", &UDownloadableContentManager::InstallNonPackageFiles)
        .def("InstallPackages", &UDownloadableContentManager::InstallPackages)
        .def("UpdateObjectLists", &UDownloadableContentManager::UpdateObjectLists)
        .def("MarkPerObjectConfigPendingKill", &UDownloadableContentManager::MarkPerObjectConfigPendingKill)
        .def("AddSectionToObjectList", &UDownloadableContentManager::AddSectionToObjectList)
        .def("GetDLCAudioPackageBasePath", &UDownloadableContentManager::GetDLCAudioPackageBasePath)
        .def("GetDLCNonPackageFilePath", &UDownloadableContentManager::GetDLCNonPackageFilePath)
        .def("ClearDLC", &UDownloadableContentManager::ClearDLC)
        .def("InstallDLCs", &UDownloadableContentManager::InstallDLCs)
        .def("InstallCompatibilityDLC", &UDownloadableContentManager::InstallCompatibilityDLC)
        .def("InstallNamedDLC", &UDownloadableContentManager::InstallNamedDLC)
        .def("InstallDLC", &UDownloadableContentManager::InstallDLC)
          ;
}