#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UTwoPanelInterfaceGFxMovie(py::module &m)
{
    py::class_< UTwoPanelInterfaceGFxMovie,  UWillowInventoryGFxMovie   >(m, "UTwoPanelInterfaceGFxMovie")
		.def_static("StaticClass", &UTwoPanelInterfaceGFxMovie::StaticClass, py::return_value_policy::reference)
        .def_readwrite("TwoPanelInterface", &UTwoPanelInterfaceGFxMovie::TwoPanelInterface)
        .def_readwrite("GenericSortConfigurations", &UTwoPanelInterfaceGFxMovie::GenericSortConfigurations)
        .def_readwrite("GenericSortConfigIndex_Storage", &UTwoPanelInterfaceGFxMovie::GenericSortConfigIndex_Storage)
        .def_readwrite("GenericSortConfigIndex_Player", &UTwoPanelInterfaceGFxMovie::GenericSortConfigIndex_Player)
        .def_readwrite("InteractiveObjectContext", &UTwoPanelInterfaceGFxMovie::InteractiveObjectContext)
        .def_readwrite("StoragePanelLabel", &UTwoPanelInterfaceGFxMovie::StoragePanelLabel)
        .def_readwrite("PlayerPanelLabel", &UTwoPanelInterfaceGFxMovie::PlayerPanelLabel)
        .def_readwrite("NumHeaderButtons", &UTwoPanelInterfaceGFxMovie::NumHeaderButtons)
        .def("SetItemLocation", &UTwoPanelInterfaceGFxMovie::SetItemLocation)
        .def("PressedHotkeyNumber", &UTwoPanelInterfaceGFxMovie::PressedHotkeyNumber)
        .def("extGenericButtonClicked", &UTwoPanelInterfaceGFxMovie::extGenericButtonClicked)
        .def("InitForConsole", &UTwoPanelInterfaceGFxMovie::InitForConsole)
        .def("InitForPC", &UTwoPanelInterfaceGFxMovie::InitForPC)
        .def("SetTooltips", &UTwoPanelInterfaceGFxMovie::SetTooltips)
        .def("_GetAddTip", &UTwoPanelInterfaceGFxMovie::_GetAddTip)
        .def("GetAddTip", &UTwoPanelInterfaceGFxMovie::GetAddTip)
        .def("AttachBackgroundClip", &UTwoPanelInterfaceGFxMovie::AttachBackgroundClip)
        .def("OnCellPressed", &UTwoPanelInterfaceGFxMovie::OnCellPressed)
        .def("PanelOnItemSelected", &UTwoPanelInterfaceGFxMovie::PanelOnItemSelected)
        .def("ShouldStoragePanelHighlightFrozen", &UTwoPanelInterfaceGFxMovie::ShouldStoragePanelHighlightFrozen)
        .def("GetSelectedThing", &UTwoPanelInterfaceGFxMovie::GetSelectedThing, py::return_value_policy::reference)
        .def("GetPlayerPanelLabel", &UTwoPanelInterfaceGFxMovie::GetPlayerPanelLabel)
        .def("GetStoragePanelLabel", &UTwoPanelInterfaceGFxMovie::GetStoragePanelLabel)
        .def("ShouldShowPanelNavTooltips", &UTwoPanelInterfaceGFxMovie::ShouldShowPanelNavTooltips)
        .def("NotifySelectionChange", &UTwoPanelInterfaceGFxMovie::NotifySelectionChange)
        .def("GetCurrencyTypeForInventory", &UTwoPanelInterfaceGFxMovie::GetCurrencyTypeForInventory)
        .def("GetOverridePriceForInventory", &UTwoPanelInterfaceGFxMovie::GetOverridePriceForInventory)
        .def("GetSortConfigDataForPanel", &UTwoPanelInterfaceGFxMovie::GetSortConfigDataForPanel)
        .def("OnLeftPanelInit", &UTwoPanelInterfaceGFxMovie::OnLeftPanelInit)
        .def("GetStorageReferenceForTransferring", &UTwoPanelInterfaceGFxMovie::GetStorageReferenceForTransferring, py::return_value_policy::reference)
        .def("GetStorageReferenceForSwapping", &UTwoPanelInterfaceGFxMovie::GetStorageReferenceForSwapping, py::return_value_policy::reference)
        .def("GetPlayerPanelItems", &UTwoPanelInterfaceGFxMovie::GetPlayerPanelItems)
        .def("GetStoragePanelItems", &UTwoPanelInterfaceGFxMovie::GetStoragePanelItems)
        .def("GetTitle", &UTwoPanelInterfaceGFxMovie::GetTitle)
        .def("ShouldStartOnLeftPanel", &UTwoPanelInterfaceGFxMovie::ShouldStartOnLeftPanel)
        .def("InitCardCellData", &UTwoPanelInterfaceGFxMovie::InitCardCellData)
        .def("extInitMainPanel", &UTwoPanelInterfaceGFxMovie::extInitMainPanel)
        .def("eventOnClose", &UTwoPanelInterfaceGFxMovie::eventOnClose)
        .def("eventStart", &UTwoPanelInterfaceGFxMovie::eventStart)
          ;
}