#include "stdafx.h"
// Using =======================================================================
using namespace boost::python;

// Module ======================================================================
void Export_pystes_UMarketplaceGFxMovie()
{
    class_< UMarketplaceGFxMovie, bases< UWillowGFxMovie3D >  , boost::noncopyable>("UMarketplaceGFxMovie", no_init)
        .def_readwrite("BasicFilters", &UMarketplaceGFxMovie::BasicFilters)
        .def_readwrite("MarketPlacePanelObject", &UMarketplaceGFxMovie::MarketPlacePanelObject)
        .def_readwrite("MarketplaceDef", &UMarketplaceGFxMovie::MarketplaceDef)
        .def_readwrite("FilterAll", &UMarketplaceGFxMovie::FilterAll)
        .def_readwrite("FilterCompatibility", &UMarketplaceGFxMovie::FilterCompatibility)
        .def_readwrite("FilterSeasonPass", &UMarketplaceGFxMovie::FilterSeasonPass)
        .def_readwrite("FilterAddOn", &UMarketplaceGFxMovie::FilterAddOn)
        .def_readwrite("FilterMisc", &UMarketplaceGFxMovie::FilterMisc)
        .def_readwrite("TipPurchase", &UMarketplaceGFxMovie::TipPurchase)
        .def_readwrite("TipCancel", &UMarketplaceGFxMovie::TipCancel)
        .def_readwrite("TipRedeemCode", &UMarketplaceGFxMovie::TipRedeemCode)
        .def_readwrite("TipSort", &UMarketplaceGFxMovie::TipSort)
        .def_readwrite("TipDownload", &UMarketplaceGFxMovie::TipDownload)
        .def_readwrite("TipDetails", &UMarketplaceGFxMovie::TipDetails)
        .def_readwrite("TipPSNStore", &UMarketplaceGFxMovie::TipPSNStore)
        .def_readwrite("CostFormatPS3", &UMarketplaceGFxMovie::CostFormatPS3)
        .def_readwrite("CostFormatPS3Free", &UMarketplaceGFxMovie::CostFormatPS3Free)
        .def_readwrite("CostFormat360", &UMarketplaceGFxMovie::CostFormat360)
        .def_readwrite("CostFormat360Free", &UMarketplaceGFxMovie::CostFormat360Free)
        .def_readwrite("Purchased", &UMarketplaceGFxMovie::Purchased)
        .def_readwrite("StatusPurchased", &UMarketplaceGFxMovie::StatusPurchased)
        .def_readwrite("StatusDownloaded", &UMarketplaceGFxMovie::StatusDownloaded)
        .def_readwrite("StatusInstalled", &UMarketplaceGFxMovie::StatusInstalled)
        .def_readwrite("StatusNew", &UMarketplaceGFxMovie::StatusNew)
        .def_readwrite("MessageEnumerating", &UMarketplaceGFxMovie::MessageEnumerating)
        .def_readwrite("DefaultHeader", &UMarketplaceGFxMovie::DefaultHeader)
        .def_readwrite("DefaultFeature", &UMarketplaceGFxMovie::DefaultFeature)
        .def_readwrite("DefaultFeatureDescription", &UMarketplaceGFxMovie::DefaultFeatureDescription)
        .def_readwrite("Prop_offeringId", &UMarketplaceGFxMovie::Prop_offeringId)
        .def_readwrite("Prop_isPurchased", &UMarketplaceGFxMovie::Prop_isPurchased)
        .def_readwrite("Prop_isSeasonPass", &UMarketplaceGFxMovie::Prop_isSeasonPass)
        .def_readwrite("Prop_isNewOffer", &UMarketplaceGFxMovie::Prop_isNewOffer)
        .def_readwrite("Prop_isDownloaded", &UMarketplaceGFxMovie::Prop_isDownloaded)
        .def_readwrite("Prop_isInstalled", &UMarketplaceGFxMovie::Prop_isInstalled)
        .def_readwrite("Prop_isFree", &UMarketplaceGFxMovie::Prop_isFree)
        .def_readwrite("Prop_isCompatibility", &UMarketplaceGFxMovie::Prop_isCompatibility)
        .def_readwrite("Prop_isAddOn", &UMarketplaceGFxMovie::Prop_isAddOn)
        .def_readwrite("Prop_isMisc", &UMarketplaceGFxMovie::Prop_isMisc)
        .def_readwrite("Prop_contentTitleText", &UMarketplaceGFxMovie::Prop_contentTitleText)
        .def_readwrite("Prop_messageText", &UMarketplaceGFxMovie::Prop_messageText)
        .def_readwrite("Prop_costText", &UMarketplaceGFxMovie::Prop_costText)
        .def_readwrite("Prop_statusText", &UMarketplaceGFxMovie::Prop_statusText)
        .def_readwrite("Prop_descriptionText", &UMarketplaceGFxMovie::Prop_descriptionText)
        .def_readwrite("WarningDlg", &UMarketplaceGFxMovie::WarningDlg)
        .def("StaticClass", &UMarketplaceGFxMovie::StaticClass, return_value_policy< reference_existing_object >())
        .def("GetSelectedObject", &UMarketplaceGFxMovie::GetSelectedObject, return_value_policy< reference_existing_object >())
        .def("FinalizeContentData", &UMarketplaceGFxMovie::FinalizeContentData, return_value_policy< reference_existing_object >())
        .def("SetContentData", &UMarketplaceGFxMovie::SetContentData)
        .def("AddContentData", &UMarketplaceGFxMovie::AddContentData)
        .def("SetFilterFromStringAndSortNew", &UMarketplaceGFxMovie::SetFilterFromStringAndSortNew, return_value_policy< reference_existing_object >())
        .def("SetFilterFromString", &UMarketplaceGFxMovie::SetFilterFromString, return_value_policy< reference_existing_object >())
        .def("ClearFilters", &UMarketplaceGFxMovie::ClearFilters)
        .def("CycleFilter", &UMarketplaceGFxMovie::CycleFilter)
        .def("ApplyFilter", &UMarketplaceGFxMovie::ApplyFilter)
        .def("ScrollDescription", &UMarketplaceGFxMovie::ScrollDescription)
        .def("ShowMessage", &UMarketplaceGFxMovie::ShowMessage)
        .def("ShowMarketplaceElements", &UMarketplaceGFxMovie::ShowMarketplaceElements)
        .def("SetStoreHeader", &UMarketplaceGFxMovie::SetStoreHeader)
        .def("SetTooltips", &UMarketplaceGFxMovie::SetTooltips)
        .def("CreateContentItem", &UMarketplaceGFxMovie::CreateContentItem, return_value_policy< reference_existing_object >())
        .def("CreateMarketplaceItem", &UMarketplaceGFxMovie::CreateMarketplaceItem, return_value_policy< reference_existing_object >())
        .def("GetOfferingStatusMessage", &UMarketplaceGFxMovie::GetOfferingStatusMessage)
        .def("FormatCost", &UMarketplaceGFxMovie::FormatCost)
        .def("extOnOfferingChanged", &UMarketplaceGFxMovie::extOnOfferingChanged)
        .def("SetShoppingTooltips", &UMarketplaceGFxMovie::SetShoppingTooltips)
        .def("OnFailureDialogClicked", &UMarketplaceGFxMovie::OnFailureDialogClicked)
        .def("ShowDeferredFailureMessage", &UMarketplaceGFxMovie::ShowDeferredFailureMessage)
        .def("PostContentLoaded", &UMarketplaceGFxMovie::PostContentLoaded)
        .def("OnHiddenDownloadableContentListRead", &UMarketplaceGFxMovie::OnHiddenDownloadableContentListRead)
        .def("IsOfferOwned", &UMarketplaceGFxMovie::IsOfferOwned)
        .def("OnDownloadableContentListRead", &UMarketplaceGFxMovie::OnDownloadableContentListRead)
        .def("GetHiddenDLCList", &UMarketplaceGFxMovie::GetHiddenDLCList)
        .def("RefreshDLC", &UMarketplaceGFxMovie::RefreshDLC)
        .def("extOnMarketPlacePanelLoad", &UMarketplaceGFxMovie::extOnMarketPlacePanelLoad)
        .def("extPopupMessage", &UMarketplaceGFxMovie::extPopupMessage)
        .def("OnClickShowMarketplace", &UMarketplaceGFxMovie::OnClickShowMarketplace)
        .def("OnClickShowMarketplaceOffer", &UMarketplaceGFxMovie::OnClickShowMarketplaceOffer)
        .def("ShopInputKey", &UMarketplaceGFxMovie::ShopInputKey)
        .def("eventOnClose", &UMarketplaceGFxMovie::eventOnClose)
        .def("eventStart", &UMarketplaceGFxMovie::eventStart)
        .staticmethod("StaticClass")
  ;
}