#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UPlayerClassDefinition(py::module &m)
{
    py::class_< UPlayerClassDefinition,  UCharacterClassDefinition   >(m, "UPlayerClassDefinition")
		.def_static("StaticClass", &UPlayerClassDefinition::StaticClass, py::return_value_policy::reference)
        .def_readwrite("VfTable_IIConstructObject", &UPlayerClassDefinition::VfTable_IIConstructObject)
        .def_readwrite("PawnArchetypePath", &UPlayerClassDefinition::PawnArchetypePath)
        .def_readwrite("SkillTreePath", &UPlayerClassDefinition::SkillTreePath)
        .def_readwrite("InitialFOVModifierSpeed", &UPlayerClassDefinition::InitialFOVModifierSpeed)
        .def_readwrite("InitialEyeHeightModifierSpeed", &UPlayerClassDefinition::InitialEyeHeightModifierSpeed)
        .def_readwrite("GotFirstSkillPointStatID", &UPlayerClassDefinition::GotFirstSkillPointStatID)
        .def_readwrite("MaximumCoDependentDamageReturnRange", &UPlayerClassDefinition::MaximumCoDependentDamageReturnRange)
        .def_readwrite("ActionSkillAvailableAkEvent", &UPlayerClassDefinition::ActionSkillAvailableAkEvent)
        .def_readwrite("ExperiencePoolDefinition", &UPlayerClassDefinition::ExperiencePoolDefinition)
        .def_readwrite("SkillCooldownPoolDefinition", &UPlayerClassDefinition::SkillCooldownPoolDefinition)
        .def_readwrite("MeleeSkillCooldownPoolDefinition", &UPlayerClassDefinition::MeleeSkillCooldownPoolDefinition)
        .def_readwrite("OnLevelUp", &UPlayerClassDefinition::OnLevelUp)
        .def_readwrite("OnLevelUpNaturally", &UPlayerClassDefinition::OnLevelUpNaturally)
        .def_readwrite("BulletReflectionParticle", &UPlayerClassDefinition::BulletReflectionParticle)
        .def_readwrite("GFxUIManagerDefinition", &UPlayerClassDefinition::GFxUIManagerDefinition)
        .def_readwrite("CharacterSelectUIPrimaryStandInOffset", &UPlayerClassDefinition::CharacterSelectUIPrimaryStandInOffset)
        .def_readwrite("CharacterSelectUIPrimaryStandInRotation", &UPlayerClassDefinition::CharacterSelectUIPrimaryStandInRotation)
        .def_readwrite("CharacterSelectUISplitStandInOffset", &UPlayerClassDefinition::CharacterSelectUISplitStandInOffset)
        .def_readwrite("CharacterSelectUISplitStandInRotation", &UPlayerClassDefinition::CharacterSelectUISplitStandInRotation)
        .def_readwrite("LowHealthPercent", &UPlayerClassDefinition::LowHealthPercent)
        .def_readwrite("OnLowHealth", &UPlayerClassDefinition::OnLowHealth)
        .def_readwrite("OnLowHealthRecover", &UPlayerClassDefinition::OnLowHealthRecover)
        .def_readwrite("CharacterNameId", &UPlayerClassDefinition::CharacterNameId)
        .def_readwrite("InputContexts", &UPlayerClassDefinition::InputContexts)
        .def_readwrite("InputContextSelector", &UPlayerClassDefinition::InputContextSelector)
        .def_readwrite("InputDeviceCollection", &UPlayerClassDefinition::InputDeviceCollection)
        .def_readwrite("SprintSettings", &UPlayerClassDefinition::SprintSettings)
        .def_readwrite("FocusDef", &UPlayerClassDefinition::FocusDef)
        .def_readwrite("ExtraClipPostTranslate", &UPlayerClassDefinition::ExtraClipPostTranslate)
        .def_readwrite("TradeInteractionDefinition", &UPlayerClassDefinition::TradeInteractionDefinition)
        .def_readwrite("CharacterInjuredDefinitionOverride", &UPlayerClassDefinition::CharacterInjuredDefinitionOverride)
        .def_readwrite("PlayerClassAchievementData", &UPlayerClassDefinition::PlayerClassAchievementData)
        .def_readwrite("InjuredDefOverridePath", &UPlayerClassDefinition::InjuredDefOverridePath)
        .def_readwrite("VfTable_IIBehaviorProvider", &UWillowCharacterClassDefinition::VfTable_IIBehaviorProvider)
        .def_readwrite("AttributeParentClass", &UWillowCharacterClassDefinition::AttributeParentClass)
        .def_readwrite("AttributeStartingValues", &UWillowCharacterClassDefinition::AttributeStartingValues)
        .def_readwrite("DesignerFlagStartingValues", &UWillowCharacterClassDefinition::DesignerFlagStartingValues)
        .def_readwrite("AttributeStartingValuesNew", &UWillowCharacterClassDefinition::AttributeStartingValuesNew)
        .def_readwrite("BaseCommerceMarkup", &UWillowCharacterClassDefinition::BaseCommerceMarkup)
        .def_readwrite("EligibleUsage", &UWillowCharacterClassDefinition::EligibleUsage)
        .def_readwrite("KilledStatID", &UWillowCharacterClassDefinition::KilledStatID)
        .def_readwrite("KilledCriticalStatID", &UWillowCharacterClassDefinition::KilledCriticalStatID)
        .def_readwrite("RanOverStatID", &UWillowCharacterClassDefinition::RanOverStatID)
        .def_readwrite("KillByWeaponStatList", &UWillowCharacterClassDefinition::KillByWeaponStatList)
        .def_readwrite("KillByDamageTypeStatList", &UWillowCharacterClassDefinition::KillByDamageTypeStatList)
        .def_readwrite("KillByWeaponDamageStatList", &UWillowCharacterClassDefinition::KillByWeaponDamageStatList)
        .def_readwrite("LevelUpKillStat", &UWillowCharacterClassDefinition::LevelUpKillStat)
        .def_readwrite("BaseIgniteChanceResistanceModifier", &UWillowCharacterClassDefinition::BaseIgniteChanceResistanceModifier)
        .def_readwrite("BaseShockChanceResistanceModifier", &UWillowCharacterClassDefinition::BaseShockChanceResistanceModifier)
        .def_readwrite("BaseCorrosiveChanceResistanceModifier", &UWillowCharacterClassDefinition::BaseCorrosiveChanceResistanceModifier)
        .def_readwrite("BaseSlowChanceResistanceModifier", &UWillowCharacterClassDefinition::BaseSlowChanceResistanceModifier)
        .def_readwrite("BaseAmpChanceResistanceModifier", &UWillowCharacterClassDefinition::BaseAmpChanceResistanceModifier)
        .def_readwrite("BaseIgniteDurationResistanceModifier", &UWillowCharacterClassDefinition::BaseIgniteDurationResistanceModifier)
        .def_readwrite("BaseShockDurationResistanceModifier", &UWillowCharacterClassDefinition::BaseShockDurationResistanceModifier)
        .def_readwrite("BaseCorrosiveDurationResistanceModifier", &UWillowCharacterClassDefinition::BaseCorrosiveDurationResistanceModifier)
        .def_readwrite("BaseSlowDurationResistanceModifier", &UWillowCharacterClassDefinition::BaseSlowDurationResistanceModifier)
        .def_readwrite("BaseAmpDurationResistanceModifier", &UWillowCharacterClassDefinition::BaseAmpDurationResistanceModifier)
        .def_readwrite("BehaviorProviderDefinition", &UWillowCharacterClassDefinition::BehaviorProviderDefinition)
        .def_readwrite("RevivalHealthMultiplier", &UWillowCharacterClassDefinition::RevivalHealthMultiplier)
        .def_readwrite("CharacterInjuredDefinition", &UWillowCharacterClassDefinition::CharacterInjuredDefinition)
        .def("ShouldUnlockPlayerClassAchievement", &UPlayerClassDefinition::ShouldUnlockPlayerClassAchievement)
        .def("SetBehaviorProviderDefinition", &UWillowCharacterClassDefinition::SetBehaviorProviderDefinition)
        .def("GetBehaviorProviderDefinition", &UWillowCharacterClassDefinition::GetBehaviorProviderDefinition, py::return_value_policy::reference)
          ;
}