#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UUberPostProcessEffect(py::object m)
{
    py::class_< UUberPostProcessEffect,  UPostProcessEffect   >(m, "UUberPostProcessEffect")
        .def_readwrite("SceneShadows", &UUberPostProcessEffect::SceneShadows)
        .def_readwrite("SceneHighLights", &UUberPostProcessEffect::SceneHighLights)
        .def_readwrite("SceneMidTones", &UUberPostProcessEffect::SceneMidTones)
        .def_readwrite("SceneDesaturation", &UUberPostProcessEffect::SceneDesaturation)
        .def_readwrite("SceneColorize", &UUberPostProcessEffect::SceneColorize)
        .def_readwrite("VignetteColor", &UUberPostProcessEffect::VignetteColor)
        .def_readwrite("VignetteBrightness", &UUberPostProcessEffect::VignetteBrightness)
        .def_readwrite("VignetteTexture", &UUberPostProcessEffect::VignetteTexture)
        .def_readwrite("TonemapperType", &UUberPostProcessEffect::TonemapperType)
        .def_readwrite("TonemapperRange", &UUberPostProcessEffect::TonemapperRange)
        .def_readwrite("TonemapperToeFactor", &UUberPostProcessEffect::TonemapperToeFactor)
        .def_readwrite("TonemapperScale", &UUberPostProcessEffect::TonemapperScale)
        .def_readwrite("MotionBlurSoftEdgeKernelSize", &UUberPostProcessEffect::MotionBlurSoftEdgeKernelSize)
        .def_readwrite("SceneImageGrainScale", &UUberPostProcessEffect::SceneImageGrainScale)
        .def_readwrite("BloomWeightSmall", &UUberPostProcessEffect::BloomWeightSmall)
        .def_readwrite("BloomWeightMedium", &UUberPostProcessEffect::BloomWeightMedium)
        .def_readwrite("BloomWeightLarge", &UUberPostProcessEffect::BloomWeightLarge)
        .def_readwrite("BloomSizeScaleSmall", &UUberPostProcessEffect::BloomSizeScaleSmall)
        .def_readwrite("BloomSizeScaleMedium", &UUberPostProcessEffect::BloomSizeScaleMedium)
        .def_readwrite("BloomSizeScaleLarge", &UUberPostProcessEffect::BloomSizeScaleLarge)
        .def_readwrite("PreviousLUTBlender", &UUberPostProcessEffect::PreviousLUTBlender)
        .def_readwrite("SceneHDRTonemapperScale", &UUberPostProcessEffect::SceneHDRTonemapperScale)
        .def_readwrite("MaxVelocity", &UDOFBloomMotionBlurEffect::MaxVelocity)
        .def_readwrite("MotionBlurAmount", &UDOFBloomMotionBlurEffect::MotionBlurAmount)
        .def_readwrite("CameraRotationThreshold", &UDOFBloomMotionBlurEffect::CameraRotationThreshold)
        .def_readwrite("CameraTranslationThreshold", &UDOFBloomMotionBlurEffect::CameraTranslationThreshold)
        .def_readwrite("BloomScale", &UDOFAndBloomEffect::BloomScale)
        .def_readwrite("BloomThreshold", &UDOFAndBloomEffect::BloomThreshold)
        .def_readwrite("BloomTint", &UDOFAndBloomEffect::BloomTint)
        .def_readwrite("BloomScreenBlendThreshold", &UDOFAndBloomEffect::BloomScreenBlendThreshold)
        .def_readwrite("SceneMultiplier", &UDOFAndBloomEffect::SceneMultiplier)
        .def_readwrite("BlurBloomKernelSize", &UDOFAndBloomEffect::BlurBloomKernelSize)
        .def_readwrite("DepthOfFieldType", &UDOFAndBloomEffect::DepthOfFieldType)
        .def_readwrite("DepthOfFieldQuality", &UDOFAndBloomEffect::DepthOfFieldQuality)
        .def_readwrite("BokehTexture", &UDOFAndBloomEffect::BokehTexture)
        .def_readwrite("FalloffExponent", &UDOFEffect::FalloffExponent)
        .def_readwrite("BlurKernelSize", &UDOFEffect::BlurKernelSize)
        .def_readwrite("MaxNearBlurAmount", &UDOFEffect::MaxNearBlurAmount)
        .def_readwrite("MinBlurAmount", &UDOFEffect::MinBlurAmount)
        .def_readwrite("MaxFarBlurAmount", &UDOFEffect::MaxFarBlurAmount)
        .def_readwrite("FocusType", &UDOFEffect::FocusType)
        .def_readwrite("FocusInnerRadius", &UDOFEffect::FocusInnerRadius)
        .def_readwrite("FocusDistance", &UDOFEffect::FocusDistance)
        .def_readwrite("FocusPosition", &UDOFEffect::FocusPosition)
        .def_readwrite("TunnelVisionScale", &UDOFEffect::TunnelVisionScale)
        .def_readwrite("TunnelVisionYOffset", &UDOFEffect::TunnelVisionYOffset)
        .def_readwrite("FalloffExponentOverride", &UDOFEffect::FalloffExponentOverride)
        .def_readwrite("BlurKernelSizeOverride", &UDOFEffect::BlurKernelSizeOverride)
        .def_readwrite("MaxNearBlurAmountOverride", &UDOFEffect::MaxNearBlurAmountOverride)
        .def_readwrite("MaxFarBlurAmountOverride", &UDOFEffect::MaxFarBlurAmountOverride)
        .def_readwrite("MinBlurAmountOverride", &UDOFEffect::MinBlurAmountOverride)
        .def_readwrite("FocusInnerRadiusOverride", &UDOFEffect::FocusInnerRadiusOverride)
        .def_readwrite("FocusDistanceOverride", &UDOFEffect::FocusDistanceOverride)
        .def_readwrite("TunnelVisionScaleOverride", &UDOFEffect::TunnelVisionScaleOverride)
        .def_readwrite("TunnelVisionYOffsetOverride", &UDOFEffect::TunnelVisionYOffsetOverride)
        .def("StaticClass", &UUberPostProcessEffect::StaticClass, py::return_value_policy::reference)
          ;
}