#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_AWillowPlayerReplicationInfo(py::module &m)
{
    py::class_< AWillowPlayerReplicationInfo,  APlayerReplicationInfo   >(m, "AWillowPlayerReplicationInfo")
		.def_static("StaticClass", &AWillowPlayerReplicationInfo::StaticClass, py::return_value_policy::reference)
        .def_readwrite("VfTable_IINounAttributeProvider", &AWillowPlayerReplicationInfo::VfTable_IINounAttributeProvider)
        .def_readwrite("ExpLevel", &AWillowPlayerReplicationInfo::ExpLevel)
        .def_readwrite("ExpPointsNextLevelAt", &AWillowPlayerReplicationInfo::ExpPointsNextLevelAt)
        .def_readwrite("ExpPointsNextLevelAtBaseValue", &AWillowPlayerReplicationInfo::ExpPointsNextLevelAtBaseValue)
        .def_readwrite("ExpPointsNextLevelAtModifierStack", &AWillowPlayerReplicationInfo::ExpPointsNextLevelAtModifierStack)
        .def_readwrite("LevelUpCount", &AWillowPlayerReplicationInfo::LevelUpCount)
        .def_readwrite("GeneralSkillPoints", &AWillowPlayerReplicationInfo::GeneralSkillPoints)
        .def_readwrite("SpecialistSkillPoints", &AWillowPlayerReplicationInfo::SpecialistSkillPoints)
        .def_readwrite("bClassModIsBuffingTeam", &AWillowPlayerReplicationInfo::bClassModIsBuffingTeam)
        .def_readwrite("bClassModIsBuffingTeamHealth", &AWillowPlayerReplicationInfo::bClassModIsBuffingTeamHealth)
        .def_readwrite("bClassModIsBuffingTeamShields", &AWillowPlayerReplicationInfo::bClassModIsBuffingTeamShields)
        .def_readwrite("bClassModIsBuffingTeamGuns", &AWillowPlayerReplicationInfo::bClassModIsBuffingTeamGuns)
        .def_readwrite("bClassModIsBuffingTeamAmmo", &AWillowPlayerReplicationInfo::bClassModIsBuffingTeamAmmo)
        .def_readwrite("bClassModIsBuffingTeamActionSkill", &AWillowPlayerReplicationInfo::bClassModIsBuffingTeamActionSkill)
        .def_readwrite("CurrencyChangedDelegates", &AWillowPlayerReplicationInfo::CurrencyChangedDelegates)
        .def_readwrite("HealthPool", &AWillowPlayerReplicationInfo::HealthPool)
        .def_readwrite("ShieldArmor", &AWillowPlayerReplicationInfo::ShieldArmor)
        .def_readwrite("PawnLocation", &AWillowPlayerReplicationInfo::PawnLocation)
        .def_readwrite("PawnAllegiance", &AWillowPlayerReplicationInfo::PawnAllegiance)
        .def_readwrite("VehicleBuddy", &AWillowPlayerReplicationInfo::VehicleBuddy)
        .def_readwrite("InjuredState", &AWillowPlayerReplicationInfo::InjuredState)
        .def_readwrite("InjuredDeadState", &AWillowPlayerReplicationInfo::InjuredDeadState)
        .def_readwrite("bGFxMenuOpen", &AWillowPlayerReplicationInfo::bGFxMenuOpen)
        .def_readwrite("NumTrackedSkillSlotsInUse", &AWillowPlayerReplicationInfo::NumTrackedSkillSlotsInUse)
        .def_readwrite("InjuredRemainingPct", &AWillowPlayerReplicationInfo::InjuredRemainingPct)
        .def_readwrite("RevivePct", &AWillowPlayerReplicationInfo::RevivePct)
        .def_readwrite("CharacterNameIdDef", &AWillowPlayerReplicationInfo::CharacterNameIdDef)
        .def_readwrite("ClassModNamePart", &AWillowPlayerReplicationInfo::ClassModNamePart)
        .def_readwrite("HighestCompletedPlayThrough", &AWillowPlayerReplicationInfo::HighestCompletedPlayThrough)
        .def_readwrite("NumReplicatedNouns", &AWillowPlayerReplicationInfo::NumReplicatedNouns)
        .def_readwrite("NounState", &AWillowPlayerReplicationInfo::NounState)
        .def_readwrite("PrimaryColor", &AWillowPlayerReplicationInfo::PrimaryColor)
        .def_readwrite("SecondaryColor", &AWillowPlayerReplicationInfo::SecondaryColor)
        .def_readwrite("TertiaryColor", &AWillowPlayerReplicationInfo::TertiaryColor)
        .def_readwrite("StandInGear", &AWillowPlayerReplicationInfo::StandInGear)
        .def_readwrite("InitializeFor", &AWillowPlayerReplicationInfo::InitializeFor)
        .def_readwrite("NumOverpowerLevelsUnlocked", &AWillowPlayerReplicationInfo::NumOverpowerLevelsUnlocked)
        .def("ServerMigrateUniqueId", &AWillowPlayerReplicationInfo::ServerMigrateUniqueId)
        .def("RefreshStandInGear", &AWillowPlayerReplicationInfo::RefreshStandInGear)
        .def("ServerSetStandInGear", &AWillowPlayerReplicationInfo::ServerSetStandInGear)
        .def("CopyProperties", &AWillowPlayerReplicationInfo::CopyProperties)
        .def("OnPlayerJoinLeave", &AWillowPlayerReplicationInfo::OnPlayerJoinLeave)
        .def("eventDestroyed", &AWillowPlayerReplicationInfo::eventDestroyed)
        .def("IsRemotePlayer", &AWillowPlayerReplicationInfo::IsRemotePlayer)
        .def("eventGetPrimaryPlayerPC", &AWillowPlayerReplicationInfo::eventGetPrimaryPlayerPC, py::return_value_policy::reference)
        .def("ServerUpdatePRIRemoteCustomizationArray", &AWillowPlayerReplicationInfo::ServerUpdatePRIRemoteCustomizationArray)
        .def("ClientInitiateCustomizationRequest", &AWillowPlayerReplicationInfo::ClientInitiateCustomizationRequest)
        .def("ServerInitiateCustomizationRequest", &AWillowPlayerReplicationInfo::ServerInitiateCustomizationRequest)
        .def("eventInitiateCustomizationRequest", &AWillowPlayerReplicationInfo::eventInitiateCustomizationRequest)
        .def("eventOnLevelUpCountIncremented", &AWillowPlayerReplicationInfo::eventOnLevelUpCountIncremented)
        .def("GetTrackedSkillDebugInfo", &AWillowPlayerReplicationInfo::GetTrackedSkillDebugInfo)
        .def("DisplayDebugTrackedSkills", &AWillowPlayerReplicationInfo::DisplayDebugTrackedSkills)
        .def("DisplayDebugAllPlayerNouns", &AWillowPlayerReplicationInfo::DisplayDebugAllPlayerNouns)
        .def("eventNotifySaveStatus", &AWillowPlayerReplicationInfo::eventNotifySaveStatus)
        .def("ServerSetPlayerNameAsCharName", &AWillowPlayerReplicationInfo::ServerSetPlayerNameAsCharName)
        .def("IsInvalidName", &AWillowPlayerReplicationInfo::IsInvalidName)
        .def("eventNotifyCurrencyDelegates", &AWillowPlayerReplicationInfo::eventNotifyCurrencyDelegates)
        .def("UnregisterCurrencyChangedDelegate", &AWillowPlayerReplicationInfo::UnregisterCurrencyChangedDelegate)
        .def("RegisterCurrencyChangedDelegate", &AWillowPlayerReplicationInfo::RegisterCurrencyChangedDelegate)
        .def("OnCurrencyChanged", &AWillowPlayerReplicationInfo::OnCurrencyChanged)
        .def("AddCurrencyOnHand", &AWillowPlayerReplicationInfo::AddCurrencyOnHand)
        .def("SetCurrencyOnHand", &AWillowPlayerReplicationInfo::SetCurrencyOnHand)
        .def("GetCurrencyOnHand", &AWillowPlayerReplicationInfo::GetCurrencyOnHand)
        .def("GetAllCurrencyOnHand", &AWillowPlayerReplicationInfo::GetAllCurrencyOnHand)
        .def("InitializeAllCurrencyOnHand", &AWillowPlayerReplicationInfo::InitializeAllCurrencyOnHand)
        .def("ServerDetermineViralAchievementSpread", &AWillowPlayerReplicationInfo::ServerDetermineViralAchievementSpread)
        .def("HandlePlayerJoinWithValidName", &AWillowPlayerReplicationInfo::HandlePlayerJoinWithValidName)
        .def("GetClassModName", &AWillowPlayerReplicationInfo::GetClassModName)
        .def("NotifyPlayerExpLevelUpdated", &AWillowPlayerReplicationInfo::NotifyPlayerExpLevelUpdated)
        .def("NotifyPlayerCharacterClassUpdated", &AWillowPlayerReplicationInfo::NotifyPlayerCharacterClassUpdated)
        .def("NotifyPrimaryPlayerOfNewCharacterSelection", &AWillowPlayerReplicationInfo::NotifyPrimaryPlayerOfNewCharacterSelection)
        .def("SetUniqueId", &AWillowPlayerReplicationInfo::SetUniqueId)
        .def("NotifyPlayerUidUpdated", &AWillowPlayerReplicationInfo::NotifyPlayerUidUpdated)
        .def("NotifyPlayerNameUpdated", &AWillowPlayerReplicationInfo::NotifyPlayerNameUpdated)
        .def("RunOnceClientinitialize", &AWillowPlayerReplicationInfo::RunOnceClientinitialize)
        .def("ClientInitialize", &AWillowPlayerReplicationInfo::ClientInitialize)
        .def("eventReplicatedEvent", &AWillowPlayerReplicationInfo::eventReplicatedEvent)
          ;
}