#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_UWillowAIComponent()
{
    py::class_< UWillowAIComponent,  UAIComponent   >("UWillowAIComponent")
        .def_readwrite("MyWillowMind", &UWillowAIComponent::MyWillowMind)
        .def_readwrite("MyDen", &UWillowAIComponent::MyDen)
        .def_readwrite("MyBlackboard", &UWillowAIComponent::MyBlackboard)
        .def_readwrite("TargetLeader", &UWillowAIComponent::TargetLeader)
        .def_readonly("UnknownData00", &UWillowAIComponent::UnknownData00)
        .def_readwrite("FormationLeader", &UWillowAIComponent::FormationLeader)
        .def_readonly("UnknownData01", &UWillowAIComponent::UnknownData01)
        .def_readwrite("InvalidCombatZones", &UWillowAIComponent::InvalidCombatZones)
        .def_readwrite("ClaimedCombatZones", &UWillowAIComponent::ClaimedCombatZones)
        .def_readwrite("ZoneTime", &UWillowAIComponent::ZoneTime)
        .def_readwrite("LastZone", &UWillowAIComponent::LastZone)
        .def_readwrite("CurrentZone", &UWillowAIComponent::CurrentZone)
        .def_readwrite("ClaimedZone", &UWillowAIComponent::ClaimedZone)
        .def_readwrite("CombatVolume", &UWillowAIComponent::CombatVolume)
        .def_readwrite("DesiredCover", &UWillowAIComponent::DesiredCover)
        .def_readwrite("LastHurtTime", &UWillowAIComponent::LastHurtTime)
        .def_readwrite("LastAttackedTime", &UWillowAIComponent::LastAttackedTime)
        .def_readwrite("LastAttacker", &UWillowAIComponent::LastAttacker)
        .def_readwrite("HeadLookHolds", &UWillowAIComponent::HeadLookHolds)
        .def_readwrite("PhaseLockHolds", &UWillowAIComponent::PhaseLockHolds)
        .def_readwrite("LastTickTime", &UWillowAIComponent::LastTickTime)
        .def_readwrite("TickThrottleTime", &UWillowAIComponent::TickThrottleTime)
        .def("StaticClass", &UWillowAIComponent::StaticClass, py::return_value_policy::reference)
        .def("IsAIThrottled", &UWillowAIComponent::IsAIThrottled)
        .def("IsAttackDebugEnabled", &UWillowAIComponent::IsAttackDebugEnabled)
        .def("ToggleAttackDebug", &UWillowAIComponent::ToggleAttackDebug)
        .def("DrawAttackDebug", &UWillowAIComponent::DrawAttackDebug)
        .def("ClaimNearbyVehicle", &UWillowAIComponent::ClaimNearbyVehicle, py::return_value_policy::reference)
        .def("CanPhaseLock", &UWillowAIComponent::CanPhaseLock)
        .def("ReleasePhaseLock", &UWillowAIComponent::ReleasePhaseLock)
        .def("HoldPhaseLock", &UWillowAIComponent::HoldPhaseLock)
        .def("PhaseLockOnHold", &UWillowAIComponent::PhaseLockOnHold)
        .def("ReleaseHeadLook", &UWillowAIComponent::ReleaseHeadLook)
        .def("HoldHeadLook", &UWillowAIComponent::HoldHeadLook)
        .def("HeadLookOnHold", &UWillowAIComponent::HeadLookOnHold)
        .def("OnHold", &UWillowAIComponent::OnHold)
        .def("GetTimeSinceAttacked", &UWillowAIComponent::GetTimeSinceAttacked)
        .def("GetTimeSinceHurt", &UWillowAIComponent::GetTimeSinceHurt)
        .def("SetThreatLevel", &UWillowAIComponent::SetThreatLevel)
        .def("GetThreatLevel", &UWillowAIComponent::GetThreatLevel)
        .def("GetHighestThreatLevel", &UWillowAIComponent::GetHighestThreatLevel)
        .def("GetCoverExposure", &UWillowAIComponent::GetCoverExposure)
        .def("TryEnterCover", &UWillowAIComponent::TryEnterCover)
        .def("TryExitCover", &UWillowAIComponent::TryExitCover)
        .def("IsLocationValid", &UWillowAIComponent::IsLocationValid)
        .def("GetLocationScore", &UWillowAIComponent::GetLocationScore)
        .def("InvalidateCombatZone", &UWillowAIComponent::InvalidateCombatZone)
        .def("MarkCurrentCombatZone", &UWillowAIComponent::MarkCurrentCombatZone)
        .def("GetCombatZoneByLocation", &UWillowAIComponent::GetCombatZoneByLocation)
        .def("CombatZoneAvailable", &UWillowAIComponent::CombatZoneAvailable)
        .def("UnclaimCombatZone", &UWillowAIComponent::UnclaimCombatZone)
        .def("ClaimCombatZone", &UWillowAIComponent::ClaimCombatZone)
        .def("DistToFormationLeader", &UWillowAIComponent::DistToFormationLeader)
        .def("GetFormation", &UWillowAIComponent::GetFormation, py::return_value_policy::reference)
        .def("SetFormationLeader", &UWillowAIComponent::SetFormationLeader)
        .def("GetFormationLeader", &UWillowAIComponent::GetFormationLeader, py::return_value_policy::reference)
        .def("SetTargetLeader", &UWillowAIComponent::SetTargetLeader)
        .def("GetTargetLeader", &UWillowAIComponent::GetTargetLeader, py::return_value_policy::reference)
        .def("GetForcedTarget", &UWillowAIComponent::GetForcedTarget, py::return_value_policy::reference)
        .def("HasForcedTarget", &UWillowAIComponent::HasForcedTarget)
        .def("Release", &UWillowAIComponent::Release)
        .def("Hold", &UWillowAIComponent::Hold)
        .def("TargetChanged", &UWillowAIComponent::TargetChanged)
        .def("InitializeTargetRecord", &UWillowAIComponent::InitializeTargetRecord)
        .def("TargetRemoved", &UWillowAIComponent::TargetRemoved)
        .def("ValidCurrentTarget", &UWillowAIComponent::ValidCurrentTarget)
        .def("ValidTarget", &UWillowAIComponent::ValidTarget)
        .def("AddDenTargets", &UWillowAIComponent::AddDenTargets)
        .def("GetTargetsFromParents", &UWillowAIComponent::GetTargetsFromParents)
        .def("GetTargets", &UWillowAIComponent::GetTargets)
        .def("NotifyAttackedBy", &UWillowAIComponent::NotifyAttackedBy)
        .def("ClearState", &UWillowAIComponent::ClearState)
        .staticmethod("StaticClass")
  ;
}