#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_ATcpLink(py::module &m)
{
    py::class_< ATcpLink,  AInfo   >(m, "ATcpLink")
        .def_readwrite("LinkState", &ATcpLink::LinkState)
        .def_readwrite("RemoteAddr", &ATcpLink::RemoteAddr)
        .def_readwrite("AcceptClass", &ATcpLink::AcceptClass)
        .def_readwrite("SendFIFO", &ATcpLink::SendFIFO)
        .def_readwrite("RecvBuf", &ATcpLink::RecvBuf)
        .def_readwrite("LinkMode", &AInternetLink::LinkMode)
        .def_readwrite("InLineMode", &AInternetLink::InLineMode)
        .def_readwrite("OutLineMode", &AInternetLink::OutLineMode)
        .def_readwrite("ReceiveMode", &AInternetLink::ReceiveMode)
        .def_readwrite("Socket", &AInternetLink::Socket)
        .def_readwrite("Port", &AInternetLink::Port)
        .def_readwrite("RemoteSocket", &AInternetLink::RemoteSocket)
        .def_readwrite("PrivateResolveInfo", &AInternetLink::PrivateResolveInfo)
        .def_readwrite("DataPending", &AInternetLink::DataPending)
        .def("StaticClass", &ATcpLink::StaticClass, py::return_value_policy::reference)
        .def("eventReceivedBinary", &ATcpLink::eventReceivedBinary)
        .def("eventReceivedLine", &ATcpLink::eventReceivedLine)
        .def("eventReceivedText", &ATcpLink::eventReceivedText)
        .def("eventClosed", &ATcpLink::eventClosed)
        .def("eventOpened", &ATcpLink::eventOpened)
        .def("eventAccepted", &ATcpLink::eventAccepted)
        .def("ReadBinary", &ATcpLink::ReadBinary)
        .def("ReadText", &ATcpLink::ReadText)
        .def("SendBinary", &ATcpLink::SendBinary)
        .def("SendText", &ATcpLink::SendText)
        .def("IsConnected", &ATcpLink::IsConnected)
        .def("Close", &ATcpLink::Close)
        .def("Open", &ATcpLink::Open)
        .def("Listen", &ATcpLink::Listen)
        .def("BindPort", &ATcpLink::BindPort)
        .def("eventResolveFailed", &AInternetLink::eventResolveFailed)
        .def("eventResolved", &AInternetLink::eventResolved)
        .def("GetLocalIP", &AInternetLink::GetLocalIP)
        .def("StringToIpAddr", &AInternetLink::StringToIpAddr)
        .def("IpAddrToString", &AInternetLink::IpAddrToString)
        .def("GetLastError", &AInternetLink::GetLastError)
        .def("Resolve", &AInternetLink::Resolve)
        .def("ParseURL", &AInternetLink::ParseURL)
        .def("IsDataPending", &AInternetLink::IsDataPending)
          ;
}