#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_Core_classes(py::module &m)
{
	py::class_< UObject >(m, "UObject")
		.def_static("StaticClass", &UObject::StaticClass, py::return_value_policy::reference)
		.def_readwrite("HashNext", &UObject::HashNext, py::return_value_policy::reference)
		.def_readwrite("ObjectFlags", &UObject::ObjectFlags, py::return_value_policy::reference)
		.def_readwrite("HashOuterNext", &UObject::HashOuterNext, py::return_value_policy::reference)
		.def_readwrite("StateFrame", &UObject::StateFrame, py::return_value_policy::reference)
		.def_readwrite("Linker", &UObject::Linker, py::return_value_policy::reference)
		.def_readwrite("LinkerIndex", &UObject::LinkerIndex, py::return_value_policy::reference)
		.def_readwrite("ObjectInternalInteger", &UObject::ObjectInternalInteger)
		.def_readwrite("NetIndex", &UObject::NetIndex)
		.def_readwrite("Outer", &UObject::Outer, py::return_value_policy::reference)
		.def_readwrite("Name", &UObject::Name, py::return_value_policy::reference)
		.def_readwrite("Class", &UObject::Class, py::return_value_policy::reference)
		.def_readwrite("ObjectArchetype", &UObject::ObjectArchetype, py::return_value_policy::reference)
		.def_readwrite("const", &UObject::const, py::return_value_policy::reference)
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{}, py::return_value_policy::reference)
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def_readwrite("{}", &UObject::{})
		.def("GetName", &UObject::GetName)
		.def("GetNameCPP", &UObject::GetNameCPP)
		.def("GetFullName", &UObject::GetFullName)
		.def("IsRelevantForDebugging", &UObject::IsRelevantForDebugging)
		.def("GetGlobalDebugTarget", &UObject::GetGlobalDebugTarget, py::return_value_policy::reference)
		.def("SetGlobalDebugTarget", &UObject::SetGlobalDebugTarget)
		.def("LogContentDebug", &UObject::LogContentDebug)
		.def("GetLanguage", &UObject::GetLanguage, py::return_value_policy::reference)
		.def("GetRandomOptionSumFrequency", &UObject::GetRandomOptionSumFrequency)
		.def("GetBuildChangelistNumber", &UObject::GetBuildChangelistNumber)
		.def("GetEngineVersion", &UObject::GetEngineVersion)
		.def("TimeStamp", &UObject::TimeStamp, py::return_value_policy::reference)
		.def("TransformVectorByRotation", &UObject::TransformVectorByRotation, py::return_value_policy::reference)
		.def("GetPackageName", &UObject::GetPackageName, py::return_value_policy::reference)
		.def("IsPendingKill", &UObject::IsPendingKill)
		.def("ByteToFloat", &UObject::ByteToFloat)
		.def("FloatToByte", &UObject::FloatToByte)
		.def("UnwindHeading", &UObject::UnwindHeading)
		.def("FindDeltaAngle", &UObject::FindDeltaAngle)
		.def("GetHeadingAngle", &UObject::GetHeadingAngle)
		.def("GetAngularDegreesFromRadians", &UObject::GetAngularDegreesFromRadians)
		.def("GetAngularFromDotDist", &UObject::GetAngularFromDotDist)
		.def("GetAngularDistance", &UObject::GetAngularDistance)
		.def("GetDotDistance", &UObject::GetDotDistance)
		.def("PointProjectToPlane", &UObject::PointProjectToPlane, py::return_value_policy::reference)
		.def("PointDistToPlane", &UObject::PointDistToPlane)
		.def("PointDistToSegment", &UObject::PointDistToSegment)
		.def("PointDistToLine", &UObject::PointDistToLine)
		.def("GetPerObjectConfigSections", &UObject::GetPerObjectConfigSections)
		.def("StaticSaveConfig", &UObject::StaticSaveConfig)
		.def("SaveConfig", &UObject::SaveConfig)
		.def("GetAttributeModiferDescriptor", &UObject::GetAttributeModiferDescriptor, py::return_value_policy::reference)
		.def("GetAttributeValueByName", &UObject::GetAttributeValueByName)
		.def("RemoveModifier", &UObject::RemoveModifier)
		.def("AddModifier", &UObject::AddModifier)
		.def("FindObject", &UObject::FindObject, py::return_value_policy::reference)
		.def("DynamicLoadObject", &UObject::DynamicLoadObject, py::return_value_policy::reference)
		.def("GetEnum", &UObject::GetEnum, py::return_value_policy::reference)
		.def("Disable", &UObject::Disable)
		.def("Enable", &UObject::Enable)
		.def("eventContinuedState", &UObject::eventContinuedState)
		.def("eventPausedState", &UObject::eventPausedState)
		.def("eventPoppedState", &UObject::eventPoppedState)
		.def("eventPushedState", &UObject::eventPushedState)
		.def("eventEndState", &UObject::eventEndState)
		.def("eventBeginState", &UObject::eventBeginState)
		.def("BreakPoint", &UObject::BreakPoint)
		.def("PrintScriptStack", &UObject::PrintScriptStack)
		.def("DumpStateStack", &UObject::DumpStateStack)
		.def("PopState", &UObject::PopState)
		.def("PushState", &UObject::PushState)
		.def("GetStateName", &UObject::GetStateName, py::return_value_policy::reference)
		.def("IsChildState", &UObject::IsChildState)
		.def("IsInState", &UObject::IsInState)
		.def("GotoState", &UObject::GotoState)
		.def("IsUTracing", &UObject::IsUTracing)
		.def("SetUTracing", &UObject::SetUTracing)
		.def("GetFuncName", &UObject::GetFuncName, py::return_value_policy::reference)
		.def("DebugBreak", &UObject::DebugBreak)
		.def("GetScriptTrace", &UObject::GetScriptTrace, py::return_value_policy::reference)
		.def("ScriptTrace", &UObject::ScriptTrace)
		.def("ParseLocalizedPropertyPath", &UObject::ParseLocalizedPropertyPath, py::return_value_policy::reference)
		.def("Localize", &UObject::Localize, py::return_value_policy::reference)
		.def("LogIndentedInternal", &UObject::LogIndentedInternal)
		.def("WarnInternal", &UObject::WarnInternal)
		.def("LogInternal", &UObject::LogInternal)
		.def("GetStringForNameBasedObjectPath", &UObject::GetStringForNameBasedObjectPath, py::return_value_policy::reference)
		.def("SetNameBasedObjectPath", &UObject::SetNameBasedObjectPath)
		.def("FlagHasBeenTrueFor", &UObject::FlagHasBeenTrueFor)
		.def("FlagTimeRemaining", &UObject::FlagTimeRemaining)
		.def("FlagTimeSinceRaised", &UObject::FlagTimeSinceRaised)
		.def("FlagSetValue", &UObject::FlagSetValue)
		.def("FlagIsLowered", &UObject::FlagIsLowered)
		.def("FlagIsRaised", &UObject::FlagIsRaised)
		.def("FlagIsFalse", &UObject::FlagIsFalse)
		.def("FlagIsTrue", &UObject::FlagIsTrue)
		.def("FlagSetTrueTimed", &UObject::FlagSetTrueTimed)
		.def("SmartVectTimeRemaining", &UObject::SmartVectTimeRemaining)
		.def("SmartVectTimeSinceSet", &UObject::SmartVectTimeSinceSet)
		.def("SmartVectGetVector", &UObject::SmartVectGetVector)
		.def("SmartVectIsSet", &UObject::SmartVectIsSet)
		.def("SmartVectSetVectorTimed", &UObject::SmartVectSetVectorTimed)
		.def("SmartVectValue", &UObject::SmartVectValue, py::return_value_policy::reference)
		.def("SmartVectReset", &UObject::SmartVectReset)
		.def("SmartVectSetVector", &UObject::SmartVectSetVector)
		.def("Subtract_LinearColorLinearColor", &UObject::Subtract_LinearColorLinearColor, py::return_value_policy::reference)
		.def("Multiply_LinearColorFloat", &UObject::Multiply_LinearColorFloat, py::return_value_policy::reference)
		.def("ColorToLinearColor", &UObject::ColorToLinearColor, py::return_value_policy::reference)
		.def("MakeLinearColor", &UObject::MakeLinearColor, py::return_value_policy::reference)
		.def("GetHTMLColor", &UObject::GetHTMLColor, py::return_value_policy::reference)
		.def("LerpColor", &UObject::LerpColor, py::return_value_policy::reference)
		.def("MakeColor", &UObject::MakeColor, py::return_value_policy::reference)
		.def("Add_ColorColor", &UObject::Add_ColorColor, py::return_value_policy::reference)
		.def("Multiply_ColorFloat", &UObject::Multiply_ColorFloat, py::return_value_policy::reference)
		.def("Multiply_FloatColor", &UObject::Multiply_FloatColor, py::return_value_policy::reference)
		.def("Subtract_ColorColor", &UObject::Subtract_ColorColor, py::return_value_policy::reference)
		.def("EvalInterpCurveVector2D", &UObject::EvalInterpCurveVector2D, py::return_value_policy::reference)
		.def("EvalInterpCurveVector", &UObject::EvalInterpCurveVector, py::return_value_policy::reference)
		.def("EvalInterpCurveFloat", &UObject::EvalInterpCurveFloat)
		.def("vect2d", &UObject::vect2d, py::return_value_policy::reference)
		.def("GetMappedRangeValue", &UObject::GetMappedRangeValue)
		.def("GetRangePctByValue", &UObject::GetRangePctByValue)
		.def("GetRangeValueByPct", &UObject::GetRangeValueByPct)
		.def("SubtractEqual_Vector2DVector2D", &UObject::SubtractEqual_Vector2DVector2D, py::return_value_policy::reference)
		.def("AddEqual_Vector2DVector2D", &UObject::AddEqual_Vector2DVector2D, py::return_value_policy::reference)
		.def("DivideEqual_Vector2DFloat", &UObject::DivideEqual_Vector2DFloat, py::return_value_policy::reference)
		.def("MultiplyEqual_Vector2DFloat", &UObject::MultiplyEqual_Vector2DFloat, py::return_value_policy::reference)
		.def("Divide_Vector2DFloat", &UObject::Divide_Vector2DFloat, py::return_value_policy::reference)
		.def("Multiply_Vector2DFloat", &UObject::Multiply_Vector2DFloat, py::return_value_policy::reference)
		.def("Subtract_Vector2DVector2D", &UObject::Subtract_Vector2DVector2D, py::return_value_policy::reference)
		.def("Add_Vector2DVector2D", &UObject::Add_Vector2DVector2D, py::return_value_policy::reference)
		.def("Subtract_QuatQuat", &UObject::Subtract_QuatQuat, py::return_value_policy::reference)
		.def("Add_QuatQuat", &UObject::Add_QuatQuat, py::return_value_policy::reference)
		.def("QuatSlerp", &UObject::QuatSlerp, py::return_value_policy::reference)
		.def("QuatToRotator", &UObject::QuatToRotator, py::return_value_policy::reference)
		.def("QuatFromRotator", &UObject::QuatFromRotator, py::return_value_policy::reference)
		.def("QuatFromAxisAndAngle", &UObject::QuatFromAxisAndAngle, py::return_value_policy::reference)
		.def("QuatFindBetween", &UObject::QuatFindBetween, py::return_value_policy::reference)
		.def("QuatRotateVector", &UObject::QuatRotateVector, py::return_value_policy::reference)
		.def("QuatInvert", &UObject::QuatInvert, py::return_value_policy::reference)
		.def("QuatDot", &UObject::QuatDot)
		.def("QuatProduct", &UObject::QuatProduct, py::return_value_policy::reference)
		.def("MatrixGetAxis", &UObject::MatrixGetAxis, py::return_value_policy::reference)
		.def("MatrixGetOrigin", &UObject::MatrixGetOrigin, py::return_value_policy::reference)
		.def("MatrixGetRotator", &UObject::MatrixGetRotator, py::return_value_policy::reference)
		.def("MakeRotationMatrix", &UObject::MakeRotationMatrix, py::return_value_policy::reference)
		.def("MakeRotationTranslationMatrix", &UObject::MakeRotationTranslationMatrix, py::return_value_policy::reference)
		.def("InverseTransformNormal", &UObject::InverseTransformNormal, py::return_value_policy::reference)
		.def("TransformNormal", &UObject::TransformNormal, py::return_value_policy::reference)
		.def("InverseTransformVector", &UObject::InverseTransformVector, py::return_value_policy::reference)
		.def("TransformVector", &UObject::TransformVector, py::return_value_policy::reference)
		.def("Multiply_MatrixMatrix", &UObject::Multiply_MatrixMatrix, py::return_value_policy::reference)
		.def("NotEqual_NameName", &UObject::NotEqual_NameName)
		.def("EqualEqual_NameName", &UObject::EqualEqual_NameName)
		.def("QueryInterface", &UObject::QueryInterface, py::return_value_policy::reference)
		.def("IsA", &UObject::IsA)
		.def("ClassIsChildOf", &UObject::ClassIsChildOf)
		.def("NotEqual_InterfaceInterface", &UObject::NotEqual_InterfaceInterface)
		.def("EqualEqual_InterfaceInterface", &UObject::EqualEqual_InterfaceInterface)
		.def("NotEqual_ObjectObject", &UObject::NotEqual_ObjectObject)
		.def("EqualEqual_ObjectObject", &UObject::EqualEqual_ObjectObject)
		.def("GuidToString", &UObject::GuidToString, py::return_value_policy::reference)
		.def("PathName", &UObject::PathName, py::return_value_policy::reference)
		.def("SplitString", &UObject::SplitString, py::return_value_policy::reference)
		.def("ParseStringIntoArray", &UObject::ParseStringIntoArray)
		.def("JoinArray", &UObject::JoinArray)
		.def("GetRightMost", &UObject::GetRightMost, py::return_value_policy::reference)
		.def("Split", &UObject::Split, py::return_value_policy::reference)
		.def("StringHash", &UObject::StringHash)
		.def("Repl", &UObject::Repl, py::return_value_policy::reference)
		.def("Asc", &UObject::Asc)
		.def("Chr", &UObject::Chr, py::return_value_policy::reference)
		.def("Locs", &UObject::Locs, py::return_value_policy::reference)
		.def("Caps", &UObject::Caps, py::return_value_policy::reference)
		.def("Right", &UObject::Right, py::return_value_policy::reference)
		.def("Left", &UObject::Left, py::return_value_policy::reference)
		.def("Mid", &UObject::Mid, py::return_value_policy::reference)
		.def("InStr", &UObject::InStr)
		.def("Len", &UObject::Len)
		.def("SubtractEqual_StrStr", &UObject::SubtractEqual_StrStr, py::return_value_policy::reference)
		.def("AtEqual_StrStr", &UObject::AtEqual_StrStr, py::return_value_policy::reference)
		.def("ConcatEqual_StrStr", &UObject::ConcatEqual_StrStr, py::return_value_policy::reference)
		.def("ComplementEqual_StrStr", &UObject::ComplementEqual_StrStr)
		.def("NotEqual_StrStr", &UObject::NotEqual_StrStr)
		.def("EqualEqual_StrStr", &UObject::EqualEqual_StrStr)
		.def("GreaterEqual_StrStr", &UObject::GreaterEqual_StrStr)
		.def("LessEqual_StrStr", &UObject::LessEqual_StrStr)
		.def("Greater_StrStr", &UObject::Greater_StrStr)
		.def("Less_StrStr", &UObject::Less_StrStr)
		.def("At_StrStr", &UObject::At_StrStr, py::return_value_policy::reference)
		.def("Concat_StrStr", &UObject::Concat_StrStr, py::return_value_policy::reference)
		.def("MakeRotator", &UObject::MakeRotator, py::return_value_policy::reference)
		.def("ClampRotAxisFromRange", &UObject::ClampRotAxisFromRange)
		.def("ClampRotAxisFromBase", &UObject::ClampRotAxisFromBase)
		.def("RSize", &UObject::RSize)
		.def("RDiff", &UObject::RDiff)
		.def("NormalizeRotAxis", &UObject::NormalizeRotAxis)
		.def("RInterpTo", &UObject::RInterpTo, py::return_value_policy::reference)
		.def("RTransform", &UObject::RTransform, py::return_value_policy::reference)
		.def("RLerp", &UObject::RLerp, py::return_value_policy::reference)
		.def("Normalize", &UObject::Normalize, py::return_value_policy::reference)
		.def("OrthoRotation", &UObject::OrthoRotation, py::return_value_policy::reference)
		.def("RotRand", &UObject::RotRand, py::return_value_policy::reference)
		.def("GetRotatorAxis", &UObject::GetRotatorAxis, py::return_value_policy::reference)
		.def("GetUnAxes", &UObject::GetUnAxes)
		.def("GetAxes", &UObject::GetAxes)
		.def("ClockwiseFrom_IntInt", &UObject::ClockwiseFrom_IntInt)
		.def("SubtractEqual_RotatorRotator", &UObject::SubtractEqual_RotatorRotator, py::return_value_policy::reference)
		.def("AddEqual_RotatorRotator", &UObject::AddEqual_RotatorRotator, py::return_value_policy::reference)
		.def("Subtract_RotatorRotator", &UObject::Subtract_RotatorRotator, py::return_value_policy::reference)
		.def("Add_RotatorRotator", &UObject::Add_RotatorRotator, py::return_value_policy::reference)
		.def("DivideEqual_RotatorFloat", &UObject::DivideEqual_RotatorFloat, py::return_value_policy::reference)
		.def("MultiplyEqual_RotatorFloat", &UObject::MultiplyEqual_RotatorFloat, py::return_value_policy::reference)
		.def("Divide_RotatorFloat", &UObject::Divide_RotatorFloat, py::return_value_policy::reference)
		.def("Multiply_FloatRotator", &UObject::Multiply_FloatRotator, py::return_value_policy::reference)
		.def("Multiply_RotatorFloat", &UObject::Multiply_RotatorFloat, py::return_value_policy::reference)
		.def("NotEqual_RotatorRotator", &UObject::NotEqual_RotatorRotator)
		.def("EqualEqual_RotatorRotator", &UObject::EqualEqual_RotatorRotator)
		.def("InCylinder", &UObject::InCylinder)
		.def("NoZDot", &UObject::NoZDot)
		.def("ClampLength", &UObject::ClampLength, py::return_value_policy::reference)
		.def("VInterpTo", &UObject::VInterpTo, py::return_value_policy::reference)
		.def("IsZero", &UObject::IsZero)
		.def("ProjectOnTo", &UObject::ProjectOnTo, py::return_value_policy::reference)
		.def("MirrorVectorByNormal", &UObject::MirrorVectorByNormal, py::return_value_policy::reference)
		.def("VRandCone2", &UObject::VRandCone2, py::return_value_policy::reference)
		.def("VRandCone", &UObject::VRandCone, py::return_value_policy::reference)
		.def("VRand", &UObject::VRand, py::return_value_policy::reference)
		.def("VLerp", &UObject::VLerp, py::return_value_policy::reference)
		.def("Normal", &UObject::Normal, py::return_value_policy::reference)
		.def("VSizeSq2D", &UObject::VSizeSq2D)
		.def("VSizeSq", &UObject::VSizeSq)
		.def("VSize2D", &UObject::VSize2D)
		.def("VSize", &UObject::VSize)
		.def("SubtractEqual_VectorVector", &UObject::SubtractEqual_VectorVector, py::return_value_policy::reference)
		.def("AddEqual_VectorVector", &UObject::AddEqual_VectorVector, py::return_value_policy::reference)
		.def("DivideEqual_VectorFloat", &UObject::DivideEqual_VectorFloat, py::return_value_policy::reference)
		.def("MultiplyEqual_VectorVector", &UObject::MultiplyEqual_VectorVector, py::return_value_policy::reference)
		.def("MultiplyEqual_VectorFloat", &UObject::MultiplyEqual_VectorFloat, py::return_value_policy::reference)
		.def("Cross_VectorVector", &UObject::Cross_VectorVector, py::return_value_policy::reference)
		.def("Dot_VectorVector", &UObject::Dot_VectorVector)
		.def("NotEqual_VectorVector", &UObject::NotEqual_VectorVector)
		.def("EqualEqual_VectorVector", &UObject::EqualEqual_VectorVector)
		.def("GreaterGreater_VectorRotator", &UObject::GreaterGreater_VectorRotator, py::return_value_policy::reference)
		.def("LessLess_VectorRotator", &UObject::LessLess_VectorRotator, py::return_value_policy::reference)
		.def("Subtract_VectorVector", &UObject::Subtract_VectorVector, py::return_value_policy::reference)
		.def("Add_VectorVector", &UObject::Add_VectorVector, py::return_value_policy::reference)
		.def("Divide_VectorFloat", &UObject::Divide_VectorFloat, py::return_value_policy::reference)
		.def("Multiply_VectorVector", &UObject::Multiply_VectorVector, py::return_value_policy::reference)
		.def("Multiply_FloatVector", &UObject::Multiply_FloatVector, py::return_value_policy::reference)
		.def("Multiply_VectorFloat", &UObject::Multiply_VectorFloat, py::return_value_policy::reference)
		.def("Subtract_PreVector", &UObject::Subtract_PreVector, py::return_value_policy::reference)
		.def("SmoothInterp", &UObject::SmoothInterp)
		.def("FInterpConstantTo", &UObject::FInterpConstantTo)
		.def("FInterpTo", &UObject::FInterpTo)
		.def("FPctByRange", &UObject::FPctByRange)
		.def("RandRange", &UObject::RandRange)
		.def("FInterpEaseInOut", &UObject::FInterpEaseInOut)
		.def("FInterpEaseOut", &UObject::FInterpEaseOut)
		.def("FInterpEaseIn", &UObject::FInterpEaseIn)
		.def("FCubicInterp", &UObject::FCubicInterp)
		.def("FCeil", &UObject::FCeil)
		.def("FFloor", &UObject::FFloor)
		.def("Round", &UObject::Round)
		.def("Lerp", &UObject::Lerp)
		.def("FClamp", &UObject::FClamp)
		.def("FMax", &UObject::FMax)
		.def("FMin", &UObject::FMin)
		.def("FRand", &UObject::FRand)
		.def("Square", &UObject::Square)
		.def("Sqrt", &UObject::Sqrt)
		.def("Loge", &UObject::Loge)
		.def("Exp", &UObject::Exp)
		.def("Atan2", &UObject::Atan2)
		.def("Atan", &UObject::Atan)
		.def("Tan", &UObject::Tan)
		.def("Acos", &UObject::Acos)
		.def("Cos", &UObject::Cos)
		.def("Asin", &UObject::Asin)
		.def("Sin", &UObject::Sin)
		.def("Abs", &UObject::Abs)
		.def("NotEqual_FloatFloat", &UObject::NotEqual_FloatFloat)
		.def("ComplementEqual_FloatFloat", &UObject::ComplementEqual_FloatFloat)
		.def("EqualEqual_FloatFloat", &UObject::EqualEqual_FloatFloat)
		.def("GreaterEqual_FloatFloat", &UObject::GreaterEqual_FloatFloat)
		.def("LessEqual_FloatFloat", &UObject::LessEqual_FloatFloat)
		.def("Greater_FloatFloat", &UObject::Greater_FloatFloat)
		.def("Less_FloatFloat", &UObject::Less_FloatFloat)
		.def("Subtract_FloatFloat", &UObject::Subtract_FloatFloat)
		.def("Add_FloatFloat", &UObject::Add_FloatFloat)
		.def("Percent_FloatFloat", &UObject::Percent_FloatFloat)
		.def("Divide_FloatFloat", &UObject::Divide_FloatFloat)
		.def("Multiply_FloatFloat", &UObject::Multiply_FloatFloat)
		.def("MultiplyMultiply_FloatFloat", &UObject::MultiplyMultiply_FloatFloat)
		.def("Subtract_PreFloat", &UObject::Subtract_PreFloat)
		.def("ToHex", &UObject::ToHex, py::return_value_policy::reference)
		.def("Clamp", &UObject::Clamp)
		.def("Max", &UObject::Max)
		.def("Min", &UObject::Min)
		.def("Rand", &UObject::Rand)
		.def("Or_IntInt", &UObject::Or_IntInt)
		.def("Xor_IntInt", &UObject::Xor_IntInt)
		.def("And_IntInt", &UObject::And_IntInt)
		.def("NotEqual_IntInt", &UObject::NotEqual_IntInt)
		.def("EqualEqual_IntInt", &UObject::EqualEqual_IntInt)
		.def("GreaterEqual_IntInt", &UObject::GreaterEqual_IntInt)
		.def("LessEqual_IntInt", &UObject::LessEqual_IntInt)
		.def("Greater_IntInt", &UObject::Greater_IntInt)
		.def("Less_IntInt", &UObject::Less_IntInt)
		.def("GreaterGreaterGreater_IntInt", &UObject::GreaterGreaterGreater_IntInt)
		.def("GreaterGreater_IntInt", &UObject::GreaterGreater_IntInt)
		.def("LessLess_IntInt", &UObject::LessLess_IntInt)
		.def("Subtract_IntInt", &UObject::Subtract_IntInt)
		.def("Add_IntInt", &UObject::Add_IntInt)
		.def("Percent_IntInt", &UObject::Percent_IntInt)
		.def("Divide_IntInt", &UObject::Divide_IntInt)
		.def("Multiply_IntInt", &UObject::Multiply_IntInt)
		.def("Subtract_PreInt", &UObject::Subtract_PreInt)
		.def("Complement_PreInt", &UObject::Complement_PreInt)
		.def("OrOr_BoolBool", &UObject::OrOr_BoolBool)
		.def("XorXor_BoolBool", &UObject::XorXor_BoolBool)
		.def("AndAnd_BoolBool", &UObject::AndAnd_BoolBool)
		.def("NotEqual_BoolBool", &UObject::NotEqual_BoolBool)
		.def("EqualEqual_BoolBool", &UObject::EqualEqual_BoolBool)
		.def("Not_PreBool", &UObject::Not_PreBool)
		.def("GetSystemTime", [](UObject &self ) { int* pyYear = (int*)malloc(sizeof(int)) ; int* pyMonth = (int*)malloc(sizeof(int)) ; int* pyDayOfWeek = (int*)malloc(sizeof(int)) ; int* pyDay = (int*)malloc(sizeof(int)) ; int* pyHour = (int*)malloc(sizeof(int)) ; int* pyMin = (int*)malloc(sizeof(int)) ; int* pySec = (int*)malloc(sizeof(int)) ; int* pyMSec = (int*)malloc(sizeof(int)) ;   self.GetSystemTime(pyYear, pyMonth, pyDayOfWeek, pyDay, pyHour, pyMin, pySec, pyMSec); return py::make_tuple(*pyYear, *pyMonth, *pyDayOfWeek, *pyDay, *pyHour, *pyMin, *pySec, *pyMSec); })
		.def("SClampRotAxis", [](UObject &self , float DeltaTime, int ViewAxis, int MaxLimit, int MinLimit, float InterpolationSpeed) { int* pyout_DeltaViewAxis = (int*)malloc(sizeof(int)) ;  bool ret =  self.SClampRotAxis(DeltaTime, ViewAxis, MaxLimit, MinLimit, InterpolationSpeed, pyout_DeltaViewAxis); return py::make_tuple(ret, *pyout_DeltaViewAxis); })
		.def("ClampRotAxis", [](UObject &self , int ViewAxis, int MaxLimit, int MinLimit) { int* pyout_DeltaViewAxis = (int*)malloc(sizeof(int)) ;   self.ClampRotAxis(ViewAxis, MaxLimit, MinLimit, pyout_DeltaViewAxis); return py::make_tuple(*pyout_DeltaViewAxis); })
		.def("SubtractEqual_FloatFloat", [](UObject &self , float B) { float* pyA = (float*)malloc(sizeof(float)) ;  float ret =  self.SubtractEqual_FloatFloat(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("AddEqual_FloatFloat", [](UObject &self , float B) { float* pyA = (float*)malloc(sizeof(float)) ;  float ret =  self.AddEqual_FloatFloat(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("DivideEqual_FloatFloat", [](UObject &self , float B) { float* pyA = (float*)malloc(sizeof(float)) ;  float ret =  self.DivideEqual_FloatFloat(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("MultiplyEqual_FloatFloat", [](UObject &self , float B) { float* pyA = (float*)malloc(sizeof(float)) ;  float ret =  self.MultiplyEqual_FloatFloat(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("SubtractSubtract_Int", [](UObject &self ) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.SubtractSubtract_Int(pyA); return py::make_tuple(ret, *pyA); })
		.def("AddAdd_Int", [](UObject &self ) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.AddAdd_Int(pyA); return py::make_tuple(ret, *pyA); })
		.def("SubtractSubtract_PreInt", [](UObject &self ) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.SubtractSubtract_PreInt(pyA); return py::make_tuple(ret, *pyA); })
		.def("AddAdd_PreInt", [](UObject &self ) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.AddAdd_PreInt(pyA); return py::make_tuple(ret, *pyA); })
		.def("SubtractEqual_IntInt", [](UObject &self , int B) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.SubtractEqual_IntInt(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("AddEqual_IntInt", [](UObject &self , int B) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.AddEqual_IntInt(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("DivideEqual_IntFloat", [](UObject &self , float B) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.DivideEqual_IntFloat(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("MultiplyEqual_IntFloat", [](UObject &self , float B) { int* pyA = (int*)malloc(sizeof(int)) ;  int ret =  self.MultiplyEqual_IntFloat(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("SubtractSubtract_Byte", [](UObject &self ) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.SubtractSubtract_Byte(pyA); return py::make_tuple(ret, *pyA); })
		.def("AddAdd_Byte", [](UObject &self ) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.AddAdd_Byte(pyA); return py::make_tuple(ret, *pyA); })
		.def("SubtractSubtract_PreByte", [](UObject &self ) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.SubtractSubtract_PreByte(pyA); return py::make_tuple(ret, *pyA); })
		.def("AddAdd_PreByte", [](UObject &self ) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.AddAdd_PreByte(pyA); return py::make_tuple(ret, *pyA); })
		.def("SubtractEqual_ByteByte", [](UObject &self , unsigned char B) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.SubtractEqual_ByteByte(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("AddEqual_ByteByte", [](UObject &self , unsigned char B) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.AddEqual_ByteByte(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("DivideEqual_ByteByte", [](UObject &self , unsigned char B) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.DivideEqual_ByteByte(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("MultiplyEqual_ByteFloat", [](UObject &self , float B) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.MultiplyEqual_ByteFloat(B, pyA); return py::make_tuple(ret, *pyA); })
		.def("MultiplyEqual_ByteByte", [](UObject &self , unsigned char B) { unsigned char* pyA = (unsigned char*)malloc(sizeof(unsigned char)) ;  unsigned char ret =  self.MultiplyEqual_ByteByte(B, pyA); return py::make_tuple(ret, *pyA); })
		;
	py::class_< UTextBuffer, UObject >(m, "UTextBuffer")
		.def_static("StaticClass", &UTextBuffer::StaticClass, py::return_value_policy::reference)
		;
	py::class_< USubsystem, UObject >(m, "USubsystem")
		.def_static("StaticClass", &USubsystem::StaticClass, py::return_value_policy::reference)
		.def_readwrite("VfTable_FExec", &USubsystem::VfTable_FExec, py::return_value_policy::reference)
		;
	py::class_< USystem, USubsystem >(m, "USystem")
		.def_static("StaticClass", &USystem::StaticClass, py::return_value_policy::reference)
		.def_readwrite("StaleCacheDays", &USystem::StaleCacheDays)
		.def_readwrite("MaxStaleCacheSize", &USystem::MaxStaleCacheSize)
		.def_readwrite("MaxOverallCacheSize", &USystem::MaxOverallCacheSize)
		.def_readwrite("PackageSizeSoftLimit", &USystem::PackageSizeSoftLimit)
		.def_readwrite("AsyncIOBandwidthLimit", &USystem::AsyncIOBandwidthLimit)
		.def_readwrite("SavePath", &USystem::SavePath, py::return_value_policy::reference)
		.def_readwrite("CachePath", &USystem::CachePath, py::return_value_policy::reference)
		.def_readwrite("CacheExt", &USystem::CacheExt, py::return_value_policy::reference)
		.def_readwrite("ScreenShotPath", &USystem::ScreenShotPath, py::return_value_policy::reference)
		.def_readwrite("Paths", &USystem::Paths, py::return_value_policy::reference)
		.def_readwrite("IgnoredPaths", &USystem::IgnoredPaths, py::return_value_policy::reference)
		.def_readwrite("SeekFreePCPaths", &USystem::SeekFreePCPaths, py::return_value_policy::reference)
		.def_readwrite("ScriptPaths", &USystem::ScriptPaths, py::return_value_policy::reference)
		.def_readwrite("FRScriptPaths", &USystem::FRScriptPaths, py::return_value_policy::reference)
		.def_readwrite("FRCheatScriptPaths", &USystem::FRCheatScriptPaths, py::return_value_policy::reference)
		.def_readwrite("CutdownPaths", &USystem::CutdownPaths, py::return_value_policy::reference)
		.def_readwrite("Suppress", &USystem::Suppress, py::return_value_policy::reference)
		.def_readwrite("Extensions", &USystem::Extensions, py::return_value_policy::reference)
		.def_readwrite("SeekFreePCExtensions", &USystem::SeekFreePCExtensions, py::return_value_policy::reference)
		.def_readwrite("LocalizationPaths", &USystem::LocalizationPaths, py::return_value_policy::reference)
		.def_readwrite("TextureFileCacheExtension", &USystem::TextureFileCacheExtension, py::return_value_policy::reference)
		.def_readwrite("AudioFileCacheExtension", &USystem::AudioFileCacheExtension, py::return_value_policy::reference)
		.def_readwrite("MissingRedirectClassName", &USystem::MissingRedirectClassName, py::return_value_policy::reference)
		.def_readwrite("MissingRedirectObjectName", &USystem::MissingRedirectObjectName, py::return_value_policy::reference)
		.def_readwrite("Unsuppress", &USystem::Unsuppress, py::return_value_policy::reference)
		;
	py::class_< UPackageMap, UObject >(m, "UPackageMap")
		.def_static("StaticClass", &UPackageMap::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UObjectSerializer, UObject >(m, "UObjectSerializer")
		.def_static("StaticClass", &UObjectSerializer::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UObjectRedirector, UObject >(m, "UObjectRedirector")
		.def_static("StaticClass", &UObjectRedirector::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UMetaData, UObject >(m, "UMetaData")
		.def_static("StaticClass", &UMetaData::StaticClass, py::return_value_policy::reference)
		;
	py::class_< ULinker, UObject >(m, "ULinker")
		.def_static("StaticClass", &ULinker::StaticClass, py::return_value_policy::reference)
		;
	py::class_< ULinkerSave, ULinker >(m, "ULinkerSave")
		.def_static("StaticClass", &ULinkerSave::StaticClass, py::return_value_policy::reference)
		;
	py::class_< ULinkerLoad, ULinker >(m, "ULinkerLoad")
		.def_static("StaticClass", &ULinkerLoad::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UInterface, UObject >(m, "UInterface")
		.def_static("StaticClass", &UInterface::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UField, UObject >(m, "UField")
		.def_static("StaticClass", &UField::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Next", &UField::Next, py::return_value_policy::reference)
		;
	py::class_< UStruct, UField >(m, "UStruct")
		.def_static("StaticClass", &UStruct::StaticClass, py::return_value_policy::reference)
		.def_readwrite("UField*			SuperField", &UStruct::UField*			SuperField, py::return_value_policy::reference)
		.def_readwrite("UField*			Children", &UStruct::UField*			Children, py::return_value_policy::reference)
		.def_readwrite("short			PropertySize", &UStruct::short			PropertySize)
		;
	py::class_< UScriptStruct, UStruct >(m, "UScriptStruct")
		.def_static("StaticClass", &UScriptStruct::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UFunction, UStruct >(m, "UFunction")
		.def_static("StaticClass", &UFunction::StaticClass, py::return_value_policy::reference)
		.def_readwrite("long		FunctionFlags", &UFunction::long		FunctionFlags)
		.def_readwrite("short		iNative", &UFunction::short		iNative)
		.def_readwrite("short		RepOffset", &UFunction::short		RepOffset)
		.def_readwrite("FName		FriendlyName", &UFunction::FName		FriendlyName, py::return_value_policy::reference)
		.def_readwrite("short		NumParms", &UFunction::short		NumParms)
		.def_readwrite("short		ParmsSize", &UFunction::short		ParmsSize)
		.def_readwrite("long		ReturnValueOffset", &UFunction::long		ReturnValueOffset)
		.def_readwrite("void*				Func", &UFunction::void*				Func, py::return_value_policy::reference)
		;
	py::class_< UProperty, UField >(m, "UProperty")
		.def_static("StaticClass", &UProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UStructProperty, UProperty >(m, "UStructProperty")
		.def_static("StaticClass", &UStructProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UStrProperty, UProperty >(m, "UStrProperty")
		.def_static("StaticClass", &UStrProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UObjectProperty, UProperty >(m, "UObjectProperty")
		.def_static("StaticClass", &UObjectProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UComponentProperty, UObjectProperty >(m, "UComponentProperty")
		.def_static("StaticClass", &UComponentProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UClassProperty, UObjectProperty >(m, "UClassProperty")
		.def_static("StaticClass", &UClassProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UNameProperty, UProperty >(m, "UNameProperty")
		.def_static("StaticClass", &UNameProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UMapProperty, UProperty >(m, "UMapProperty")
		.def_static("StaticClass", &UMapProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UIntProperty, UProperty >(m, "UIntProperty")
		.def_static("StaticClass", &UIntProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UIntAttributeProperty, UIntProperty >(m, "UIntAttributeProperty")
		.def_static("StaticClass", &UIntAttributeProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UInterfaceProperty, UProperty >(m, "UInterfaceProperty")
		.def_static("StaticClass", &UInterfaceProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UFloatProperty, UProperty >(m, "UFloatProperty")
		.def_static("StaticClass", &UFloatProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UFloatAttributeProperty, UFloatProperty >(m, "UFloatAttributeProperty")
		.def_static("StaticClass", &UFloatAttributeProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UDelegateProperty, UProperty >(m, "UDelegateProperty")
		.def_static("StaticClass", &UDelegateProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UByteProperty, UProperty >(m, "UByteProperty")
		.def_static("StaticClass", &UByteProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UByteAttributeProperty, UByteProperty >(m, "UByteAttributeProperty")
		.def_static("StaticClass", &UByteAttributeProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UBoolProperty, UProperty >(m, "UBoolProperty")
		.def_static("StaticClass", &UBoolProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UArrayProperty, UProperty >(m, "UArrayProperty")
		.def_static("StaticClass", &UArrayProperty::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UEnum, UField >(m, "UEnum")
		.def_static("StaticClass", &UEnum::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UConst, UField >(m, "UConst")
		.def_static("StaticClass", &UConst::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UFactory, UObject >(m, "UFactory")
		.def_static("StaticClass", &UFactory::StaticClass, py::return_value_policy::reference)
		.def_property("bCreateNew", [](UFactory &self){return self.bCreateNew;}, [](UFactory &self, bool value){self.bCreateNew = value ? 1 : 0;})
		.def_property("bEditAfterNew", [](UFactory &self){return self.bEditAfterNew;}, [](UFactory &self, bool value){self.bEditAfterNew = value ? 1 : 0;})
		.def_property("bEditorImport", [](UFactory &self){return self.bEditorImport;}, [](UFactory &self, bool value){self.bEditorImport = value ? 1 : 0;})
		.def_property("bText", [](UFactory &self){return self.bText;}, [](UFactory &self, bool value){self.bText = value ? 1 : 0;})
		.def_readwrite("SupportedClass", &UFactory::SupportedClass, py::return_value_policy::reference)
		.def_readwrite("ContextClass", &UFactory::ContextClass, py::return_value_policy::reference)
		.def_readwrite("Description", &UFactory::Description, py::return_value_policy::reference)
		.def_readwrite("Formats", &UFactory::Formats, py::return_value_policy::reference)
		.def_readwrite("AutoPriority", &UFactory::AutoPriority)
		.def_readwrite("ValidGameNames", &UFactory::ValidGameNames, py::return_value_policy::reference)
		;
	py::class_< UTextBufferFactory, UFactory >(m, "UTextBufferFactory")
		.def_static("StaticClass", &UTextBufferFactory::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UExporter, UObject >(m, "UExporter")
		.def_static("StaticClass", &UExporter::StaticClass, py::return_value_policy::reference)
		.def_readwrite("FormatExtension", &UExporter::FormatExtension, py::return_value_policy::reference)
		.def_readwrite("FormatDescription", &UExporter::FormatDescription, py::return_value_policy::reference)
		;
	py::class_< UComponent, UObject >(m, "UComponent")
		.def_static("StaticClass", &UComponent::StaticClass, py::return_value_policy::reference)
		.def_readwrite("TemplateOwnerClass", &UComponent::TemplateOwnerClass, py::return_value_policy::reference)
		.def_readwrite("TemplateName", &UComponent::TemplateName, py::return_value_policy::reference)
		;
	py::class_< UDistributionVector, UComponent >(m, "UDistributionVector")
		.def_static("StaticClass", &UDistributionVector::StaticClass, py::return_value_policy::reference)
		.def_property("bCanBeBaked", [](UDistributionVector &self){return self.bCanBeBaked;}, [](UDistributionVector &self, bool value){self.bCanBeBaked = value ? 1 : 0;})
		.def_property("bIsDirty", [](UDistributionVector &self){return self.bIsDirty;}, [](UDistributionVector &self, bool value){self.bIsDirty = value ? 1 : 0;})
		.def_readwrite("VfTable_FCurveEdInterface", &UDistributionVector::VfTable_FCurveEdInterface, py::return_value_policy::reference)
		.def("GetVectorValue", &UDistributionVector::GetVectorValue, py::return_value_policy::reference)
		;
	py::class_< UDistributionFloat, UComponent >(m, "UDistributionFloat")
		.def_static("StaticClass", &UDistributionFloat::StaticClass, py::return_value_policy::reference)
		.def_property("bCanBeBaked", [](UDistributionFloat &self){return self.bCanBeBaked;}, [](UDistributionFloat &self, bool value){self.bCanBeBaked = value ? 1 : 0;})
		.def_property("bIsDirty", [](UDistributionFloat &self){return self.bIsDirty;}, [](UDistributionFloat &self, bool value){self.bIsDirty = value ? 1 : 0;})
		.def_readwrite("VfTable_FCurveEdInterface", &UDistributionFloat::VfTable_FCurveEdInterface, py::return_value_policy::reference)
		.def("GetFloatValue", &UDistributionFloat::GetFloatValue)
		;
	py::class_< UCommandlet, UObject >(m, "UCommandlet")
		.def_static("StaticClass", &UCommandlet::StaticClass, py::return_value_policy::reference)
		.def_property("IsServer", [](UCommandlet &self){return self.IsServer;}, [](UCommandlet &self, bool value){self.IsServer = value ? 1 : 0;})
		.def_property("IsClient", [](UCommandlet &self){return self.IsClient;}, [](UCommandlet &self, bool value){self.IsClient = value ? 1 : 0;})
		.def_property("IsEditor", [](UCommandlet &self){return self.IsEditor;}, [](UCommandlet &self, bool value){self.IsEditor = value ? 1 : 0;})
		.def_property("LogToConsole", [](UCommandlet &self){return self.LogToConsole;}, [](UCommandlet &self, bool value){self.LogToConsole = value ? 1 : 0;})
		.def_property("ShowErrorCount", [](UCommandlet &self){return self.ShowErrorCount;}, [](UCommandlet &self, bool value){self.ShowErrorCount = value ? 1 : 0;})
		.def_readwrite("HelpDescription", &UCommandlet::HelpDescription, py::return_value_policy::reference)
		.def_readwrite("HelpUsage", &UCommandlet::HelpUsage, py::return_value_policy::reference)
		.def_readwrite("HelpWebLink", &UCommandlet::HelpWebLink, py::return_value_policy::reference)
		.def_readwrite("HelpParamNames", &UCommandlet::HelpParamNames, py::return_value_policy::reference)
		.def_readwrite("HelpParamDescriptions", &UCommandlet::HelpParamDescriptions, py::return_value_policy::reference)
		.def("eventMain", &UCommandlet::eventMain)
		;
	py::class_< UHelpCommandlet, UCommandlet >(m, "UHelpCommandlet")
		.def_static("StaticClass", &UHelpCommandlet::StaticClass, py::return_value_policy::reference)
		.def("eventMain", &UHelpCommandlet::eventMain)
		;
	py::class_< UAttributeModifier, UObject >(m, "UAttributeModifier")
		.def_static("StaticClass", &UAttributeModifier::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Type", &UAttributeModifier::Type)
		.def_readwrite("Value", &UAttributeModifier::Value)
		;
	py::class_< UState, UStruct >(m, "UState")
		.def_static("StaticClass", &UState::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UPackage, UObject >(m, "UPackage")
		.def_static("StaticClass", &UPackage::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UClass, UState >(m, "UClass")
		.def_static("StaticClass", &UClass::StaticClass, py::return_value_policy::reference)
		;

}