#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_GFxUI_classes(py::module &m)
{
	py::class_< UGFxEngine, UAudioDevice >(m, "UGFxEngine")
		.def_static("StaticClass", &UGFxEngine::StaticClass, py::return_value_policy::reference)
		.def_readwrite("GCReferences", &UGFxEngine::GCReferences, py::return_value_policy::reference)
		.def_readwrite("RefCount", &UGFxEngine::RefCount)
		;
	py::class_< UGFxFSCmdHandler, UAudioDevice >(m, "UGFxFSCmdHandler")
		.def_static("StaticClass", &UGFxFSCmdHandler::StaticClass, py::return_value_policy::reference)
		.def("eventFSCommand", &UGFxFSCmdHandler::eventFSCommand)
		;
	py::class_< UGFxInteraction, UAudioDevice >(m, "UGFxInteraction")
		.def_static("StaticClass", &UGFxInteraction::StaticClass, py::return_value_policy::reference)
		.def_readwrite("VfTable_FCallbackEventDevice", &UGFxInteraction::VfTable_FCallbackEventDevice, py::return_value_policy::reference)
		.def("CloseAllMoviePlayers", &UGFxInteraction::CloseAllMoviePlayers)
		.def("NotifySplitscreenLayoutChanged", &UGFxInteraction::NotifySplitscreenLayoutChanged)
		.def("NotifyPlayerRemoved", &UGFxInteraction::NotifyPlayerRemoved)
		.def("NotifyPlayerAdded", &UGFxInteraction::NotifyPlayerAdded)
		.def("NotifyGameSessionEnded", &UGFxInteraction::NotifyGameSessionEnded)
		.def("GetFocusMovie", &UGFxInteraction::GetFocusMovie, py::return_value_policy::reference)
		;
	py::class_< UGFxManager, UAudioDevice >(m, "UGFxManager")
		.def_static("StaticClass", &UGFxManager::StaticClass, py::return_value_policy::reference)
		.def_readwrite("MyDefinition", &UGFxManager::MyDefinition, py::return_value_policy::reference)
		.def("GetFocusMovie", &UGFxManager::GetFocusMovie, py::return_value_policy::reference)
		.def("eventLookupSound", &UGFxManager::eventLookupSound, py::return_value_policy::reference)
		.def("eventShowDialog", &UGFxManager::eventShowDialog, py::return_value_policy::reference)
		.def("eventInit", &UGFxManager::eventInit)
		;
	py::class_< UGFxManagerDefinition, UAudioDevice >(m, "UGFxManagerDefinition")
		.def_static("StaticClass", &UGFxManagerDefinition::StaticClass, py::return_value_policy::reference)
		.def_readwrite("ManagerClass", &UGFxManagerDefinition::ManagerClass, py::return_value_policy::reference)
		.def_readwrite("GFxDialogBox", &UGFxManagerDefinition::GFxDialogBox, py::return_value_policy::reference)
		.def_readwrite("UnknownData00[0x4]", &UGFxManagerDefinition::UnknownData00[0x4])
		.def_readwrite("InteractionSounds", &UGFxManagerDefinition::InteractionSounds, py::return_value_policy::reference)
		;
	py::class_< UGFxMoviePlayer, UAudioDevice >(m, "UGFxMoviePlayer")
		.def_static("StaticClass", &UGFxMoviePlayer::StaticClass, py::return_value_policy::reference)
		.def_property("bMovieIsOpen", [](UGFxMoviePlayer &self){return self.bMovieIsOpen;}, [](UGFxMoviePlayer &self, bool value){self.bMovieIsOpen = value ? 1 : 0;})
		.def_property("bDisplayWithHudOff", [](UGFxMoviePlayer &self){return self.bDisplayWithHudOff;}, [](UGFxMoviePlayer &self, bool value){self.bDisplayWithHudOff = value ? 1 : 0;})
		.def_property("bEnableGammaCorrection", [](UGFxMoviePlayer &self){return self.bEnableGammaCorrection;}, [](UGFxMoviePlayer &self, bool value){self.bEnableGammaCorrection = value ? 1 : 0;})
		.def_property("bWidgetsInitializedThisFrame", [](UGFxMoviePlayer &self){return self.bWidgetsInitializedThisFrame;}, [](UGFxMoviePlayer &self, bool value){self.bWidgetsInitializedThisFrame = value ? 1 : 0;})
		.def_property("bLogUnhandedWidgetInitializations", [](UGFxMoviePlayer &self){return self.bLogUnhandedWidgetInitializations;}, [](UGFxMoviePlayer &self, bool value){self.bLogUnhandedWidgetInitializations = value ? 1 : 0;})
		.def_property("bAllowInput", [](UGFxMoviePlayer &self){return self.bAllowInput;}, [](UGFxMoviePlayer &self, bool value){self.bAllowInput = value ? 1 : 0;})
		.def_property("bAllowFocus", [](UGFxMoviePlayer &self){return self.bAllowFocus;}, [](UGFxMoviePlayer &self, bool value){self.bAllowFocus = value ? 1 : 0;})
		.def_property("bAutoPlay", [](UGFxMoviePlayer &self){return self.bAutoPlay;}, [](UGFxMoviePlayer &self, bool value){self.bAutoPlay = value ? 1 : 0;})
		.def_property("bPauseGameWhileActive", [](UGFxMoviePlayer &self){return self.bPauseGameWhileActive;}, [](UGFxMoviePlayer &self, bool value){self.bPauseGameWhileActive = value ? 1 : 0;})
		.def_property("bCloseOnLevelChange", [](UGFxMoviePlayer &self){return self.bCloseOnLevelChange;}, [](UGFxMoviePlayer &self, bool value){self.bCloseOnLevelChange = value ? 1 : 0;})
		.def_property("bOnlyOwnerFocusable", [](UGFxMoviePlayer &self){return self.bOnlyOwnerFocusable;}, [](UGFxMoviePlayer &self, bool value){self.bOnlyOwnerFocusable = value ? 1 : 0;})
		.def_property("bForceFullViewport", [](UGFxMoviePlayer &self){return self.bForceFullViewport;}, [](UGFxMoviePlayer &self, bool value){self.bForceFullViewport = value ? 1 : 0;})
		.def_property("bDiscardNonOwnerInput", [](UGFxMoviePlayer &self){return self.bDiscardNonOwnerInput;}, [](UGFxMoviePlayer &self, bool value){self.bDiscardNonOwnerInput = value ? 1 : 0;})
		.def_property("bCaptureInput", [](UGFxMoviePlayer &self){return self.bCaptureInput;}, [](UGFxMoviePlayer &self, bool value){self.bCaptureInput = value ? 1 : 0;})
		.def_property("bIgnoreMouseInput", [](UGFxMoviePlayer &self){return self.bIgnoreMouseInput;}, [](UGFxMoviePlayer &self, bool value){self.bIgnoreMouseInput = value ? 1 : 0;})
		.def_property("bAcceptsUnregisteredInput", [](UGFxMoviePlayer &self){return self.bAcceptsUnregisteredInput;}, [](UGFxMoviePlayer &self, bool value){self.bAcceptsUnregisteredInput = value ? 1 : 0;})
		.def_property("bIsSplitscreenLayoutModified", [](UGFxMoviePlayer &self){return self.bIsSplitscreenLayoutModified;}, [](UGFxMoviePlayer &self, bool value){self.bIsSplitscreenLayoutModified = value ? 1 : 0;})
		.def_property("bInputAllKeys", [](UGFxMoviePlayer &self){return self.bInputAllKeys;}, [](UGFxMoviePlayer &self, bool value){self.bInputAllKeys = value ? 1 : 0;})
		.def_property("bInputOwnerOnly", [](UGFxMoviePlayer &self){return self.bInputOwnerOnly;}, [](UGFxMoviePlayer &self, bool value){self.bInputOwnerOnly = value ? 1 : 0;})
		.def_property("bKeepTopMost", [](UGFxMoviePlayer &self){return self.bKeepTopMost;}, [](UGFxMoviePlayer &self, bool value){self.bKeepTopMost = value ? 1 : 0;})
		.def_property("bBlurLesserMovies", [](UGFxMoviePlayer &self){return self.bBlurLesserMovies;}, [](UGFxMoviePlayer &self, bool value){self.bBlurLesserMovies = value ? 1 : 0;})
		.def_property("bHideLesserMovies", [](UGFxMoviePlayer &self){return self.bHideLesserMovies;}, [](UGFxMoviePlayer &self, bool value){self.bHideLesserMovies = value ? 1 : 0;})
		.def_property("bIsPriorityBlurred", [](UGFxMoviePlayer &self){return self.bIsPriorityBlurred;}, [](UGFxMoviePlayer &self, bool value){self.bIsPriorityBlurred = value ? 1 : 0;})
		.def_property("bIsPriorityHidden", [](UGFxMoviePlayer &self){return self.bIsPriorityHidden;}, [](UGFxMoviePlayer &self, bool value){self.bIsPriorityHidden = value ? 1 : 0;})
		.def_property("bIgnoreVisibilityEffect", [](UGFxMoviePlayer &self){return self.bIgnoreVisibilityEffect;}, [](UGFxMoviePlayer &self, bool value){self.bIgnoreVisibilityEffect = value ? 1 : 0;})
		.def_property("bIgnoreBlurEffect", [](UGFxMoviePlayer &self){return self.bIgnoreBlurEffect;}, [](UGFxMoviePlayer &self, bool value){self.bIgnoreBlurEffect = value ? 1 : 0;})
		.def_readwrite("pMovie", &UGFxMoviePlayer::pMovie, py::return_value_policy::reference)
		.def_readwrite("pCaptureKeys", &UGFxMoviePlayer::pCaptureKeys, py::return_value_policy::reference)
		.def_readwrite("pFocusIgnoreKeys", &UGFxMoviePlayer::pFocusIgnoreKeys, py::return_value_policy::reference)
		.def_readwrite("UnknownData00[0x3C]", &UGFxMoviePlayer::UnknownData00[0x3C])
		.def_readwrite("UnknownData01[0x3C]", &UGFxMoviePlayer::UnknownData01[0x3C])
		.def_readwrite("NextASUObject", &UGFxMoviePlayer::NextASUObject)
		.def_readwrite("MovieInfo", &UGFxMoviePlayer::MovieInfo, py::return_value_policy::reference)
		.def_readwrite("RenderTexture", &UGFxMoviePlayer::RenderTexture, py::return_value_policy::reference)
		.def_readwrite("LocalPlayerOwnerIndex", &UGFxMoviePlayer::LocalPlayerOwnerIndex)
		.def_readwrite("ExternalInterface", &UGFxMoviePlayer::ExternalInterface, py::return_value_policy::reference)
		.def_readwrite("CaptureKeys", &UGFxMoviePlayer::CaptureKeys, py::return_value_policy::reference)
		.def_readwrite("FocusIgnoreKeys", &UGFxMoviePlayer::FocusIgnoreKeys, py::return_value_policy::reference)
		.def_readwrite("SceneDPG", &UGFxMoviePlayer::SceneDPG)
		.def_readwrite("TimingMode", &UGFxMoviePlayer::TimingMode)
		.def_readwrite("RenderTextureMode", &UGFxMoviePlayer::RenderTextureMode)
		.def_readwrite("Priority", &UGFxMoviePlayer::Priority)
		.def_readwrite("ExternalTextures", &UGFxMoviePlayer::ExternalTextures, py::return_value_policy::reference)
		.def_readwrite("SoundThemes", &UGFxMoviePlayer::SoundThemes, py::return_value_policy::reference)
		.def_readwrite("DataStoreBindings", &UGFxMoviePlayer::DataStoreBindings, py::return_value_policy::reference)
		.def_readwrite("DataStoreSubscriber", &UGFxMoviePlayer::DataStoreSubscriber, py::return_value_policy::reference)
		.def_readwrite("WidgetBindings", &UGFxMoviePlayer::WidgetBindings, py::return_value_policy::reference)
		.def_readwrite("UnknownData02[0x3C]", &UGFxMoviePlayer::UnknownData02[0x3C])
		.def_readwrite("UnknownData03[0x3C]", &UGFxMoviePlayer::UnknownData03[0x3C])
		.def_readwrite("SplitscreenLayoutObject", &UGFxMoviePlayer::SplitscreenLayoutObject, py::return_value_policy::reference)
		.def_readwrite("SplitscreenLayoutYAdjust", &UGFxMoviePlayer::SplitscreenLayoutYAdjust)
		.def_readwrite("DepthPriority", &UGFxMoviePlayer::DepthPriority)
		.def_readwrite("LastKeyInputTime", &UGFxMoviePlayer::LastKeyInputTime)
		.def_readwrite("__OnPostAdvance__Delegate", &UGFxMoviePlayer::__OnPostAdvance__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnInputKey__Delegate", &UGFxMoviePlayer::__OnInputKey__Delegate, py::return_value_policy::reference)
		.def("UnregisterGFxObject", &UGFxMoviePlayer::UnregisterGFxObject)
		.def("RegisterGFxObject", &UGFxMoviePlayer::RegisterGFxObject)
		.def("SendMousePos", &UGFxMoviePlayer::SendMousePos)
		.def("IsShowingFlashMouse", &UGFxMoviePlayer::IsShowingFlashMouse)
		.def("HookSaveScreenshot", &UGFxMoviePlayer::HookSaveScreenshot)
		.def("UpdateRenderTexture", &UGFxMoviePlayer::UpdateRenderTexture)
		.def("OnInputKey", &UGFxMoviePlayer::OnInputKey)
		.def("WantsInput", &UGFxMoviePlayer::WantsInput)
		.def("WantsControllerInput", &UGFxMoviePlayer::WantsControllerInput)
		.def("InputKey", &UGFxMoviePlayer::InputKey)
		.def("GetGFxManager", &UGFxMoviePlayer::GetGFxManager, py::return_value_policy::reference)
		.def("ResolveDataStoreMarkup", &UGFxMoviePlayer::ResolveDataStoreMarkup, py::return_value_policy::reference)
		.def("UpdateSplitscreenLayout", &UGFxMoviePlayer::UpdateSplitscreenLayout)
		.def("ApplyPriorityVisibilityEffect", &UGFxMoviePlayer::ApplyPriorityVisibilityEffect)
		.def("ApplyPriorityBlurEffect", &UGFxMoviePlayer::ApplyPriorityBlurEffect)
		.def("eventApplyPriorityEffect", &UGFxMoviePlayer::eventApplyPriorityEffect)
		.def("PlaySoundFromTheme", &UGFxMoviePlayer::PlaySoundFromTheme)
		.def("eventOnFocusLost", &UGFxMoviePlayer::eventOnFocusLost)
		.def("eventOnFocusGained", &UGFxMoviePlayer::eventOnFocusGained)
		.def("ConsoleCommand", &UGFxMoviePlayer::ConsoleCommand)
		.def("SetLP", &UGFxMoviePlayer::SetLP)
		.def("GetPC", &UGFxMoviePlayer::GetPC, py::return_value_policy::reference)
		.def("GetLP", &UGFxMoviePlayer::GetLP, py::return_value_policy::reference)
		.def("Init", &UGFxMoviePlayer::Init)
		.def("SetWidgetPathBinding", &UGFxMoviePlayer::SetWidgetPathBinding)
		.def("eventPostWidgetInit", &UGFxMoviePlayer::eventPostWidgetInit)
		.def("eventWidgetUnloaded", &UGFxMoviePlayer::eventWidgetUnloaded)
		.def("eventWidgetInitialized", &UGFxMoviePlayer::eventWidgetInitialized)
		.def("ActionScriptObject", &UGFxMoviePlayer::ActionScriptObject, py::return_value_policy::reference)
		.def("ActionScriptString", &UGFxMoviePlayer::ActionScriptString, py::return_value_policy::reference)
		.def("ActionScriptFloat", &UGFxMoviePlayer::ActionScriptFloat)
		.def("ActionScriptInt", &UGFxMoviePlayer::ActionScriptInt)
		.def("ActionScriptVoid", &UGFxMoviePlayer::ActionScriptVoid)
		.def("ActionScript", &UGFxMoviePlayer::ActionScript)
		.def("Invoke", &UGFxMoviePlayer::Invoke, py::return_value_policy::reference)
		.def("ActionScriptSetFunction", &UGFxMoviePlayer::ActionScriptSetFunction)
		.def("CreateArray", &UGFxMoviePlayer::CreateArray, py::return_value_policy::reference)
		.def("CreateObject", &UGFxMoviePlayer::CreateObject, py::return_value_policy::reference)
		.def("SetVariableStringArray", &UGFxMoviePlayer::SetVariableStringArray)
		.def("SetVariableFloatArray", &UGFxMoviePlayer::SetVariableFloatArray)
		.def("SetVariableIntArray", &UGFxMoviePlayer::SetVariableIntArray)
		.def("SetVariableArray", &UGFxMoviePlayer::SetVariableArray)
		.def("GetVariableStringArray", &UGFxMoviePlayer::GetVariableStringArray)
		.def("GetVariableFloatArray", &UGFxMoviePlayer::GetVariableFloatArray)
		.def("GetVariableIntArray", &UGFxMoviePlayer::GetVariableIntArray)
		.def("GetVariableArray", &UGFxMoviePlayer::GetVariableArray)
		.def("SetVariableObject", &UGFxMoviePlayer::SetVariableObject)
		.def("SetVariableString", &UGFxMoviePlayer::SetVariableString)
		.def("SetVariableNumber", &UGFxMoviePlayer::SetVariableNumber)
		.def("SetVariableBool", &UGFxMoviePlayer::SetVariableBool)
		.def("SetVariable", &UGFxMoviePlayer::SetVariable)
		.def("GetVariableObject", &UGFxMoviePlayer::GetVariableObject, py::return_value_policy::reference)
		.def("GetVariableString", &UGFxMoviePlayer::GetVariableString, py::return_value_policy::reference)
		.def("GetVariableNumber", &UGFxMoviePlayer::GetVariableNumber)
		.def("GetVariableBool", &UGFxMoviePlayer::GetVariableBool)
		.def("GetVariable", &UGFxMoviePlayer::GetVariable, py::return_value_policy::reference)
		.def("eventFilterAxisInput", &UGFxMoviePlayer::eventFilterAxisInput)
		.def("eventFilterButtonInput", &UGFxMoviePlayer::eventFilterButtonInput)
		.def("FlushPlayerInput", &UGFxMoviePlayer::FlushPlayerInput)
		.def("ClearFocusIgnoreKeys", &UGFxMoviePlayer::ClearFocusIgnoreKeys)
		.def("AddFocusIgnoreKey", &UGFxMoviePlayer::AddFocusIgnoreKey)
		.def("ClearCaptureKeys", &UGFxMoviePlayer::ClearCaptureKeys)
		.def("AddCaptureKey", &UGFxMoviePlayer::AddCaptureKey)
		.def("SetMovieCanReceiveInput", &UGFxMoviePlayer::SetMovieCanReceiveInput)
		.def("SetMovieCanReceiveFocus", &UGFxMoviePlayer::SetMovieCanReceiveFocus)
		.def("SetSceneDPG", &UGFxMoviePlayer::SetSceneDPG)
		.def("SetPerspective3D", &UGFxMoviePlayer::SetPerspective3D)
		.def("SetView3D", &UGFxMoviePlayer::SetView3D)
		.def("SetAlignment", &UGFxMoviePlayer::SetAlignment)
		.def("SetViewScaleMode", &UGFxMoviePlayer::SetViewScaleMode)
		.def("eventOnSetViewport", &UGFxMoviePlayer::eventOnSetViewport)
		.def("SetViewport", &UGFxMoviePlayer::SetViewport)
		.def("GetGameViewportClient", &UGFxMoviePlayer::GetGameViewportClient, py::return_value_policy::reference)
		.def("SetPriority", &UGFxMoviePlayer::SetPriority)
		.def("PublishDataStoreValues", &UGFxMoviePlayer::PublishDataStoreValues)
		.def("RefreshDataStoreBindings", &UGFxMoviePlayer::RefreshDataStoreBindings)
		.def("SetExternalTexture", &UGFxMoviePlayer::SetExternalTexture)
		.def("SetExternalInterface", &UGFxMoviePlayer::SetExternalInterface)
		.def("SetTimingMode", &UGFxMoviePlayer::SetTimingMode)
		.def("SetMovieInfo", &UGFxMoviePlayer::SetMovieInfo)
		.def("eventConditionalClearPause", &UGFxMoviePlayer::eventConditionalClearPause)
		.def("eventOnCleanup", &UGFxMoviePlayer::eventOnCleanup)
		.def("eventOnClose", &UGFxMoviePlayer::eventOnClose)
		.def("Close", &UGFxMoviePlayer::Close)
		.def("SetPause", &UGFxMoviePlayer::SetPause)
		.def("OnPostAdvance", &UGFxMoviePlayer::OnPostAdvance)
		.def("PostAdvance", &UGFxMoviePlayer::PostAdvance)
		.def("Advance", &UGFxMoviePlayer::Advance)
		.def("eventStart", &UGFxMoviePlayer::eventStart)
		.def("GetVisibleFrameRect", [](UGFxMoviePlayer &self ) { float* pyx0 = (float*)malloc(sizeof(float)) ; float* pyy0 = (float*)malloc(sizeof(float)) ; float* pyX1 = (float*)malloc(sizeof(float)) ; float* pyY1 = (float*)malloc(sizeof(float)) ;   self.GetVisibleFrameRect(pyx0, pyy0, pyX1, pyY1); return py::make_tuple(*pyx0, *pyy0, *pyX1, *pyY1); })
		;
	py::class_< UGFxMovie, UAudioDevice >(m, "UGFxMovie")
		.def_static("StaticClass", &UGFxMovie::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UGFxObject, UAudioDevice >(m, "UGFxObject")
		.def_static("StaticClass", &UGFxObject::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Value[0xC]", &UGFxObject::Value[0xC])
		.def_readwrite("SubWidgetBindings", &UGFxObject::SubWidgetBindings, py::return_value_policy::reference)
		.def("eventWidgetUnloaded", &UGFxObject::eventWidgetUnloaded)
		.def("eventWidgetInitialized", &UGFxObject::eventWidgetInitialized)
		.def("MouseHitTest", &UGFxObject::MouseHitTest)
		.def("HitTest", &UGFxObject::HitTest)
		.def("_HitTest", &UGFxObject::_HitTest)
		.def("GetNextHighestDepth", &UGFxObject::GetNextHighestDepth)
		.def("RemoveMovieClip", &UGFxObject::RemoveMovieClip)
		.def("AttachMovie", &UGFxObject::AttachMovie, py::return_value_policy::reference)
		.def("CreateEmptyMovieClip", &UGFxObject::CreateEmptyMovieClip, py::return_value_policy::reference)
		.def("GotoAndStopI", &UGFxObject::GotoAndStopI)
		.def("GotoAndStop", &UGFxObject::GotoAndStop)
		.def("GotoAndPlayI", &UGFxObject::GotoAndPlayI)
		.def("GotoAndPlay", &UGFxObject::GotoAndPlay)
		.def("ActionScriptArray", &UGFxObject::ActionScriptArray, py::return_value_policy::reference)
		.def("ActionScriptObject", &UGFxObject::ActionScriptObject, py::return_value_policy::reference)
		.def("ActionScriptString", &UGFxObject::ActionScriptString, py::return_value_policy::reference)
		.def("ActionScriptFloat", &UGFxObject::ActionScriptFloat)
		.def("ActionScriptInt", &UGFxObject::ActionScriptInt)
		.def("ActionScriptVoid", &UGFxObject::ActionScriptVoid)
		.def("Invoke", &UGFxObject::Invoke, py::return_value_policy::reference)
		.def("ActionScriptSetFunctionOn", &UGFxObject::ActionScriptSetFunctionOn)
		.def("ActionScriptSetFunction", &UGFxObject::ActionScriptSetFunction)
		.def("SetElementMemberString", &UGFxObject::SetElementMemberString)
		.def("SetElementMemberFloat", &UGFxObject::SetElementMemberFloat)
		.def("SetElementMemberBool", &UGFxObject::SetElementMemberBool)
		.def("SetElementMemberObject", &UGFxObject::SetElementMemberObject)
		.def("SetElementMember", &UGFxObject::SetElementMember)
		.def("GetElementMemberString", &UGFxObject::GetElementMemberString, py::return_value_policy::reference)
		.def("GetElementMemberFloat", &UGFxObject::GetElementMemberFloat)
		.def("GetElementMemberBool", &UGFxObject::GetElementMemberBool)
		.def("GetElementMemberObject", &UGFxObject::GetElementMemberObject, py::return_value_policy::reference)
		.def("GetElementMember", &UGFxObject::GetElementMember, py::return_value_policy::reference)
		.def("SetElementColorTransform", &UGFxObject::SetElementColorTransform)
		.def("SetElementPosition", &UGFxObject::SetElementPosition)
		.def("SetElementVisible", &UGFxObject::SetElementVisible)
		.def("SetElementDisplayMatrix", &UGFxObject::SetElementDisplayMatrix)
		.def("SetElementDisplayInfo", &UGFxObject::SetElementDisplayInfo)
		.def("GetElementDisplayMatrix", &UGFxObject::GetElementDisplayMatrix, py::return_value_policy::reference)
		.def("GetElementDisplayInfo", &UGFxObject::GetElementDisplayInfo, py::return_value_policy::reference)
		.def("SetElementString", &UGFxObject::SetElementString)
		.def("SetElementFloat", &UGFxObject::SetElementFloat)
		.def("SetElementBool", &UGFxObject::SetElementBool)
		.def("SetElementObject", &UGFxObject::SetElementObject)
		.def("SetElement", &UGFxObject::SetElement)
		.def("GetElementString", &UGFxObject::GetElementString, py::return_value_policy::reference)
		.def("GetElementFloat", &UGFxObject::GetElementFloat)
		.def("GetElementBool", &UGFxObject::GetElementBool)
		.def("GetElementObject", &UGFxObject::GetElementObject, py::return_value_policy::reference)
		.def("GetElement", &UGFxObject::GetElement, py::return_value_policy::reference)
		.def("SetText", &UGFxObject::SetText)
		.def("GetText", &UGFxObject::GetText, py::return_value_policy::reference)
		.def("SetVisible", &UGFxObject::SetVisible)
		.def("SetDisplayMatrix3D", &UGFxObject::SetDisplayMatrix3D)
		.def("SetDisplayMatrix", &UGFxObject::SetDisplayMatrix)
		.def("SetColorTransform", &UGFxObject::SetColorTransform)
		.def("SetPosition", &UGFxObject::SetPosition)
		.def("SetDisplayInfo", &UGFxObject::SetDisplayInfo)
		.def("GetDisplayMatrix", &UGFxObject::GetDisplayMatrix, py::return_value_policy::reference)
		.def("GetColorTransform", &UGFxObject::GetColorTransform, py::return_value_policy::reference)
		.def("GetDisplayInfo", &UGFxObject::GetDisplayInfo)
		.def("TranslateString", &UGFxObject::TranslateString, py::return_value_policy::reference)
		.def("SetFunction", &UGFxObject::SetFunction)
		.def("SetObject", &UGFxObject::SetObject)
		.def("SetString", &UGFxObject::SetString)
		.def("SetFloat", &UGFxObject::SetFloat)
		.def("SetBool", &UGFxObject::SetBool)
		.def("Set", &UGFxObject::Set)
		.def("GetObject", &UGFxObject::GetObject, py::return_value_policy::reference)
		.def("GetString", &UGFxObject::GetString, py::return_value_policy::reference)
		.def("GetFloat", &UGFxObject::GetFloat)
		.def("GetBool", &UGFxObject::GetBool)
		.def("Get", &UGFxObject::Get, py::return_value_policy::reference)
		.def("GetPosition", [](UGFxObject &self ) { float* pyX = (float*)malloc(sizeof(float)) ; float* pyY = (float*)malloc(sizeof(float)) ;  bool ret =  self.GetPosition(pyX, pyY); return py::make_tuple(ret, *pyX, *pyY); })
		;
	py::class_< UGFxClikWidget, UAudioDevice >(m, "UGFxClikWidget")
		.def_static("StaticClass", &UGFxClikWidget::StaticClass, py::return_value_policy::reference)
		.def_readwrite("__EventListener__Delegate", &UGFxClikWidget::__EventListener__Delegate, py::return_value_policy::reference)
		.def("ASRemoveAllEventListeners", &UGFxClikWidget::ASRemoveAllEventListeners)
		.def("ASAddEventListener", &UGFxClikWidget::ASAddEventListener)
		.def("SetListener", &UGFxClikWidget::SetListener)
		.def("GetEventStringFromTypename", &UGFxClikWidget::GetEventStringFromTypename, py::return_value_policy::reference)
		.def("RemoveAllEventListeners", &UGFxClikWidget::RemoveAllEventListeners)
		.def("AddEventListener", &UGFxClikWidget::AddEventListener)
		.def("EventListener", &UGFxClikWidget::EventListener)
		;
	py::class_< UGFxRawData, UAudioDevice >(m, "UGFxRawData")
		.def_static("StaticClass", &UGFxRawData::StaticClass, py::return_value_policy::reference)
		.def_readwrite("RawData", &UGFxRawData::RawData, py::return_value_policy::reference)
		.def_readwrite("ReferencedSwfs", &UGFxRawData::ReferencedSwfs, py::return_value_policy::reference)
		.def_readwrite("References", &UGFxRawData::References, py::return_value_policy::reference)
		.def_readwrite("UserReferences", &UGFxRawData::UserReferences, py::return_value_policy::reference)
		;
	py::class_< USwfMovie, UAudioDevice >(m, "USwfMovie")
		.def_static("StaticClass", &USwfMovie::StaticClass, py::return_value_policy::reference)
		.def_property("bUsesFontlib", [](USwfMovie &self){return self.bUsesFontlib;}, [](USwfMovie &self, bool value){self.bUsesFontlib = value ? 1 : 0;})
		.def_property("bSetSRGBOnImportedTextures", [](USwfMovie &self){return self.bSetSRGBOnImportedTextures;}, [](USwfMovie &self, bool value){self.bSetSRGBOnImportedTextures = value ? 1 : 0;})
		.def_property("bPackTextures", [](USwfMovie &self){return self.bPackTextures;}, [](USwfMovie &self, bool value){self.bPackTextures = value ? 1 : 0;})
		.def_property("bPreload", [](USwfMovie &self){return self.bPreload;}, [](USwfMovie &self, bool value){self.bPreload = value ? 1 : 0;})
		.def_property("bDoNotPlaceInVM", [](USwfMovie &self){return self.bDoNotPlaceInVM;}, [](USwfMovie &self, bool value){self.bDoNotPlaceInVM = value ? 1 : 0;})
		.def_readwrite("PackTextureSize", &USwfMovie::PackTextureSize)
		.def_readwrite("TextureRescale", &USwfMovie::TextureRescale)
		.def_readwrite("DesiredMemArena", &USwfMovie::DesiredMemArena)
		.def_readwrite("TextureFormat", &USwfMovie::TextureFormat, py::return_value_policy::reference)
		.def_readwrite("RTTextures", &USwfMovie::RTTextures)
		.def_readwrite("RTVideoTextures", &USwfMovie::RTVideoTextures)
		.def_readwrite("MovieInfo[0x9]", &USwfMovie::MovieInfo[0x9])
		.def_readwrite("pMovieDef", &USwfMovie::pMovieDef, py::return_value_policy::reference)
		.def("GetPathForLoadMovie", &USwfMovie::GetPathForLoadMovie, py::return_value_policy::reference)
		;
	py::class_< UFlashMovie, UAudioDevice >(m, "UFlashMovie")
		.def_static("StaticClass", &UFlashMovie::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UGFxMovieInfo, UAudioDevice >(m, "UGFxMovieInfo")
		.def_static("StaticClass", &UGFxMovieInfo::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UGFxValue, UAudioDevice >(m, "UGFxValue")
		.def_static("StaticClass", &UGFxValue::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Value[0xC]", &UGFxValue::Value[0xC])
		;
	py::class_< UGFxAction_CloseMovie, UAudioDevice >(m, "UGFxAction_CloseMovie")
		.def_static("StaticClass", &UGFxAction_CloseMovie::StaticClass, py::return_value_policy::reference)
		.def_property("bUnload", [](UGFxAction_CloseMovie &self){return self.bUnload;}, [](UGFxAction_CloseMovie &self, bool value){self.bUnload = value ? 1 : 0;})
		.def_readwrite("Movie", &UGFxAction_CloseMovie::Movie, py::return_value_policy::reference)
		.def("eventIsValidLevelSequenceObject", &UGFxAction_CloseMovie::eventIsValidLevelSequenceObject)
		;
	py::class_< UGFxAction_GetVariable, UAudioDevice >(m, "UGFxAction_GetVariable")
		.def_static("StaticClass", &UGFxAction_GetVariable::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Movie", &UGFxAction_GetVariable::Movie, py::return_value_policy::reference)
		.def_readwrite("Variable", &UGFxAction_GetVariable::Variable, py::return_value_policy::reference)
		.def("eventIsValidLevelSequenceObject", &UGFxAction_GetVariable::eventIsValidLevelSequenceObject)
		;
	py::class_< UGFxAction_Invoke, UAudioDevice >(m, "UGFxAction_Invoke")
		.def_static("StaticClass", &UGFxAction_Invoke::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Movie", &UGFxAction_Invoke::Movie, py::return_value_policy::reference)
		.def_readwrite("MethodName", &UGFxAction_Invoke::MethodName, py::return_value_policy::reference)
		.def_readwrite("Arguments", &UGFxAction_Invoke::Arguments, py::return_value_policy::reference)
		.def("eventIsValidLevelSequenceObject", &UGFxAction_Invoke::eventIsValidLevelSequenceObject)
		;
	py::class_< UGFxAction_OpenMovie, UAudioDevice >(m, "UGFxAction_OpenMovie")
		.def_static("StaticClass", &UGFxAction_OpenMovie::StaticClass, py::return_value_policy::reference)
		.def_property("bTakeFocus", [](UGFxAction_OpenMovie &self){return self.bTakeFocus;}, [](UGFxAction_OpenMovie &self, bool value){self.bTakeFocus = value ? 1 : 0;})
		.def_property("bCaptureInput", [](UGFxAction_OpenMovie &self){return self.bCaptureInput;}, [](UGFxAction_OpenMovie &self, bool value){self.bCaptureInput = value ? 1 : 0;})
		.def_property("bStartPaused", [](UGFxAction_OpenMovie &self){return self.bStartPaused;}, [](UGFxAction_OpenMovie &self, bool value){self.bStartPaused = value ? 1 : 0;})
		.def_property("bEnableGammaCorrection", [](UGFxAction_OpenMovie &self){return self.bEnableGammaCorrection;}, [](UGFxAction_OpenMovie &self, bool value){self.bEnableGammaCorrection = value ? 1 : 0;})
		.def_property("bDisplayWithHudOff", [](UGFxAction_OpenMovie &self){return self.bDisplayWithHudOff;}, [](UGFxAction_OpenMovie &self, bool value){self.bDisplayWithHudOff = value ? 1 : 0;})
		.def_readwrite("Movie", &UGFxAction_OpenMovie::Movie, py::return_value_policy::reference)
		.def_readwrite("MoviePlayerClass", &UGFxAction_OpenMovie::MoviePlayerClass, py::return_value_policy::reference)
		.def_readwrite("MoviePlayer", &UGFxAction_OpenMovie::MoviePlayer, py::return_value_policy::reference)
		.def_readwrite("LegacyMovieObject", &UGFxAction_OpenMovie::LegacyMovieObject, py::return_value_policy::reference)
		.def_readwrite("RenderTextureMode", &UGFxAction_OpenMovie::RenderTextureMode)
		.def_readwrite("ScaleMode", &UGFxAction_OpenMovie::ScaleMode)
		.def_readwrite("AlignMode", &UGFxAction_OpenMovie::AlignMode)
		.def_readwrite("RenderTexture", &UGFxAction_OpenMovie::RenderTexture, py::return_value_policy::reference)
		.def_readwrite("CaptureKeys", &UGFxAction_OpenMovie::CaptureKeys, py::return_value_policy::reference)
		.def_readwrite("FocusIgnoreKeys", &UGFxAction_OpenMovie::FocusIgnoreKeys, py::return_value_policy::reference)
		.def("eventIsValidLevelSequenceObject", &UGFxAction_OpenMovie::eventIsValidLevelSequenceObject)
		;
	py::class_< UGFxAction_SetCaptureKeys, UAudioDevice >(m, "UGFxAction_SetCaptureKeys")
		.def_static("StaticClass", &UGFxAction_SetCaptureKeys::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Movie", &UGFxAction_SetCaptureKeys::Movie, py::return_value_policy::reference)
		.def_readwrite("CaptureKeys", &UGFxAction_SetCaptureKeys::CaptureKeys, py::return_value_policy::reference)
		;
	py::class_< UGFxAction_SetVariable, UAudioDevice >(m, "UGFxAction_SetVariable")
		.def_static("StaticClass", &UGFxAction_SetVariable::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Movie", &UGFxAction_SetVariable::Movie, py::return_value_policy::reference)
		.def_readwrite("Variable", &UGFxAction_SetVariable::Variable, py::return_value_policy::reference)
		.def("eventIsValidLevelSequenceObject", &UGFxAction_SetVariable::eventIsValidLevelSequenceObject)
		;
	py::class_< UGFxEvent_FSCommand, UAudioDevice >(m, "UGFxEvent_FSCommand")
		.def_static("StaticClass", &UGFxEvent_FSCommand::StaticClass, py::return_value_policy::reference)
		.def_readwrite("Movie", &UGFxEvent_FSCommand::Movie, py::return_value_policy::reference)
		.def_readwrite("FSCommand", &UGFxEvent_FSCommand::FSCommand, py::return_value_policy::reference)
		.def_readwrite("Handler", &UGFxEvent_FSCommand::Handler, py::return_value_policy::reference)
		;
	py::class_< UGFxFSCmdHandler_Kismet, UAudioDevice >(m, "UGFxFSCmdHandler_Kismet")
		.def_static("StaticClass", &UGFxFSCmdHandler_Kismet::StaticClass, py::return_value_policy::reference)
		.def("eventFSCommand", &UGFxFSCmdHandler_Kismet::eventFSCommand)
		;
	py::class_< UGFxDataStoreSubscriber, UAudioDevice >(m, "UGFxDataStoreSubscriber")
		.def_static("StaticClass", &UGFxDataStoreSubscriber::StaticClass, py::return_value_policy::reference)
		.def_readwrite("VfTable_IUIDataStorePublisher", &UGFxDataStoreSubscriber::VfTable_IUIDataStorePublisher, py::return_value_policy::reference)
		.def_readwrite("Movie", &UGFxDataStoreSubscriber::Movie, py::return_value_policy::reference)
		.def("SaveSubscriberValue", &UGFxDataStoreSubscriber::SaveSubscriberValue)
		.def("ClearBoundDataStores", &UGFxDataStoreSubscriber::ClearBoundDataStores)
		.def("GetBoundDataStores", &UGFxDataStoreSubscriber::GetBoundDataStores)
		.def("NotifyDataStoreValueUpdated", &UGFxDataStoreSubscriber::NotifyDataStoreValueUpdated)
		.def("RefreshSubscriberValue", &UGFxDataStoreSubscriber::RefreshSubscriberValue)
		.def("GetDataStoreBinding", &UGFxDataStoreSubscriber::GetDataStoreBinding, py::return_value_policy::reference)
		.def("SetDataStoreBinding", &UGFxDataStoreSubscriber::SetDataStoreBinding)
		.def("PublishValues", &UGFxDataStoreSubscriber::PublishValues)
		;

}