#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_IpDrv_classes(py::module &m)
{
	py::class_< UClientBeaconAddressResolver, UObject >(m, "UClientBeaconAddressResolver")
		.def_readwrite("BeaconPort", &UClientBeaconAddressResolver::BeaconPort)
		.def_readwrite("BeaconName", &UClientBeaconAddressResolver::BeaconName, py::return_value_policy::reference)
		;
	py::class_< UHTTPDownload, UDownload >(m, "UHTTPDownload")
		.def_property("MaxRedirection", [](UHTTPDownload &self){return self.MaxRedirection;}, [](UHTTPDownload &self, bool value){self.MaxRedirection = value ? 1 : 0;})
		.def_readwrite("ProxyServerHost", &UHTTPDownload::ProxyServerHost, py::return_value_policy::reference)
		.def_readwrite("ProxyServerPort", &UHTTPDownload::ProxyServerPort)
		.def_readwrite("ConnectionTimeout", &UHTTPDownload::ConnectionTimeout)
		;
	py::class_< AInternetLink, AInfo >(m, "AInternetLink")
		.def_readwrite("LinkMode", &AInternetLink::LinkMode)
		.def_readwrite("InLineMode", &AInternetLink::InLineMode)
		.def_readwrite("OutLineMode", &AInternetLink::OutLineMode)
		.def_readwrite("ReceiveMode", &AInternetLink::ReceiveMode)
		.def_readwrite("Socket", &AInternetLink::Socket, py::return_value_policy::reference)
		.def_readwrite("Port", &AInternetLink::Port)
		.def_readwrite("RemoteSocket", &AInternetLink::RemoteSocket, py::return_value_policy::reference)
		.def_readwrite("PrivateResolveInfo", &AInternetLink::PrivateResolveInfo, py::return_value_policy::reference)
		.def_readwrite("DataPending", &AInternetLink::DataPending)
		.def("eventResolveFailed", &AInternetLink::eventResolveFailed)
		.def("eventResolved", &AInternetLink::eventResolved)
		.def("GetLocalIP", &AInternetLink::GetLocalIP)
		.def("StringToIpAddr", &AInternetLink::StringToIpAddr)
		.def("IpAddrToString", &AInternetLink::IpAddrToString, py::return_value_policy::reference)
		.def("GetLastError", &AInternetLink::GetLastError)
		.def("Resolve", &AInternetLink::Resolve)
		.def("IsDataPending", &AInternetLink::IsDataPending)
		.def("ParseURL", [](AInternetLink &self , struct FString URL, struct FString* Addr, struct FString* LevelName, struct FString* EntryName) { int* pyPortNum = (int*)malloc(sizeof(int)) ;  bool ret =  self.ParseURL(URL, Addr, pyPortNum, LevelName, EntryName); return py::make_tuple(ret, *pyPortNum); })
		;
	py::class_< ATcpLink, AInternetLink >(m, "ATcpLink")
		.def_readwrite("LinkState", &ATcpLink::LinkState)
		.def_readwrite("RemoteAddr", &ATcpLink::RemoteAddr, py::return_value_policy::reference)
		.def_readwrite("AcceptClass", &ATcpLink::AcceptClass, py::return_value_policy::reference)
		.def_readwrite("SendFIFO", &ATcpLink::SendFIFO, py::return_value_policy::reference)
		.def_readwrite("RecvBuf", &ATcpLink::RecvBuf, py::return_value_policy::reference)
		.def("eventReceivedLine", &ATcpLink::eventReceivedLine)
		.def("eventReceivedText", &ATcpLink::eventReceivedText)
		.def("eventClosed", &ATcpLink::eventClosed)
		.def("eventOpened", &ATcpLink::eventOpened)
		.def("eventAccepted", &ATcpLink::eventAccepted)
		.def("ReadText", &ATcpLink::ReadText)
		.def("SendText", &ATcpLink::SendText)
		.def("IsConnected", &ATcpLink::IsConnected)
		.def("Close", &ATcpLink::Close)
		.def("Open", &ATcpLink::Open)
		.def("Listen", &ATcpLink::Listen)
		.def("BindPort", &ATcpLink::BindPort)
		.def("eventReceivedBinary", [](ATcpLink &self , int Count) { unsigned char* pyB = (unsigned char*)malloc(sizeof(unsigned char)) ;   self.eventReceivedBinary(Count, pyB); return py::make_tuple(*pyB); })
		.def("ReadBinary", [](ATcpLink &self , int Count) { unsigned char* pyB = (unsigned char*)malloc(sizeof(unsigned char)) ;  int ret =  self.ReadBinary(Count, pyB); return py::make_tuple(ret, *pyB); })
		.def("SendBinary", [](ATcpLink &self , int Count) { unsigned char* pyB = (unsigned char*)malloc(sizeof(unsigned char)) ;  int ret =  self.SendBinary(Count, pyB); return py::make_tuple(ret, *pyB); })
		;
	py::class_< UMCPBase, UObject >(m, "UMCPBase")
		.def_readwrite("VfTable_FTickableObject", &UMCPBase::VfTable_FTickableObject, py::return_value_policy::reference)
		;
	py::class_< UOnlineEventsInterfaceMcp, UMCPBase >(m, "UOnlineEventsInterfaceMcp")
		.def_property("bBinaryStats", [](UOnlineEventsInterfaceMcp &self){return self.bBinaryStats;}, [](UOnlineEventsInterfaceMcp &self, bool value){self.bBinaryStats = value ? 1 : 0;})
		.def_readwrite("EventUploadConfigs", &UOnlineEventsInterfaceMcp::EventUploadConfigs, py::return_value_policy::reference)
		.def_readwrite("MCPEventPostObjects", &UOnlineEventsInterfaceMcp::MCPEventPostObjects, py::return_value_policy::reference)
		.def_readwrite("DisabledUploadTypes", &UOnlineEventsInterfaceMcp::DisabledUploadTypes, py::return_value_policy::reference)
		.def("UploadMatchmakingStats", &UOnlineEventsInterfaceMcp::UploadMatchmakingStats)
		.def("UpdatePlaylistPopulation", &UOnlineEventsInterfaceMcp::UpdatePlaylistPopulation)
		.def("UploadGameplayEventsData", &UOnlineEventsInterfaceMcp::UploadGameplayEventsData)
		.def("UploadPlayerData", &UOnlineEventsInterfaceMcp::UploadPlayerData)
		;
	py::class_< UOnlineNewsInterfaceMcp, UMCPBase >(m, "UOnlineNewsInterfaceMcp")
		.def_property("bNeedsTicking", [](UOnlineNewsInterfaceMcp &self){return self.bNeedsTicking;}, [](UOnlineNewsInterfaceMcp &self, bool value){self.bNeedsTicking = value ? 1 : 0;})
		.def_readwrite("NewsItems", &UOnlineNewsInterfaceMcp::NewsItems, py::return_value_policy::reference)
		.def_readwrite("ReadNewsDelegates", &UOnlineNewsInterfaceMcp::ReadNewsDelegates, py::return_value_policy::reference)
		.def_readwrite("__OnReadNewsCompleted__Delegate", &UOnlineNewsInterfaceMcp::__OnReadNewsCompleted__Delegate, py::return_value_policy::reference)
		.def("GetNews", &UOnlineNewsInterfaceMcp::GetNews, py::return_value_policy::reference)
		.def("ClearReadNewsCompletedDelegate", &UOnlineNewsInterfaceMcp::ClearReadNewsCompletedDelegate)
		.def("AddReadNewsCompletedDelegate", &UOnlineNewsInterfaceMcp::AddReadNewsCompletedDelegate)
		.def("OnReadNewsCompleted", &UOnlineNewsInterfaceMcp::OnReadNewsCompleted)
		.def("ReadNews", &UOnlineNewsInterfaceMcp::ReadNews)
		;
	py::class_< UOnlineTitleFileDownloadMcp, UMCPBase >(m, "UOnlineTitleFileDownloadMcp")
		.def_readwrite("ReadTitleFileCompleteDelegates", &UOnlineTitleFileDownloadMcp::ReadTitleFileCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("TitleFiles", &UOnlineTitleFileDownloadMcp::TitleFiles, py::return_value_policy::reference)
		.def_readwrite("DownloadCount", &UOnlineTitleFileDownloadMcp::DownloadCount)
		.def_readwrite("BaseUrl", &UOnlineTitleFileDownloadMcp::BaseUrl, py::return_value_policy::reference)
		.def_readwrite("TimeOut", &UOnlineTitleFileDownloadMcp::TimeOut)
		.def_readwrite("FilesToUrls", &UOnlineTitleFileDownloadMcp::FilesToUrls, py::return_value_policy::reference)
		.def_readwrite("__OnReadTitleFileComplete__Delegate", &UOnlineTitleFileDownloadMcp::__OnReadTitleFileComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnShareTitleFileComplete__Delegate", &UOnlineTitleFileDownloadMcp::__OnShareTitleFileComplete__Delegate, py::return_value_policy::reference)
		.def("ClearShareTitleFileCompleteDelegate", &UOnlineTitleFileDownloadMcp::ClearShareTitleFileCompleteDelegate)
		.def("AddShareTitleFileCompleteDelegate", &UOnlineTitleFileDownloadMcp::AddShareTitleFileCompleteDelegate)
		.def("ShareTitleFile", &UOnlineTitleFileDownloadMcp::ShareTitleFile)
		.def("ClearDownloadedFile", &UOnlineTitleFileDownloadMcp::ClearDownloadedFile)
		.def("ClearDownloadedFiles", &UOnlineTitleFileDownloadMcp::ClearDownloadedFiles)
		.def("GetTitleFileState", &UOnlineTitleFileDownloadMcp::GetTitleFileState)
		.def("GetTitleFileContents", &UOnlineTitleFileDownloadMcp::GetTitleFileContents)
		.def("ClearReadTitleFileCompleteDelegate", &UOnlineTitleFileDownloadMcp::ClearReadTitleFileCompleteDelegate)
		.def("AddReadTitleFileCompleteDelegate", &UOnlineTitleFileDownloadMcp::AddReadTitleFileCompleteDelegate)
		.def("ReadTitleFile", &UOnlineTitleFileDownloadMcp::ReadTitleFile)
		.def("OnShareTitleFileComplete", &UOnlineTitleFileDownloadMcp::OnShareTitleFileComplete)
		.def("OnReadTitleFileComplete", &UOnlineTitleFileDownloadMcp::OnReadTitleFileComplete)
		;
	py::class_< UMeshBeacon, UObject >(m, "UMeshBeacon")
		.def_property("bIsInTick", [](UMeshBeacon &self){return self.bIsInTick;}, [](UMeshBeacon &self, bool value){self.bIsInTick = value ? 1 : 0;})
		.def_property("bWantsDeferredDestroy", [](UMeshBeacon &self){return self.bWantsDeferredDestroy;}, [](UMeshBeacon &self, bool value){self.bWantsDeferredDestroy = value ? 1 : 0;})
		.def_property("bShouldTick", [](UMeshBeacon &self){return self.bShouldTick;}, [](UMeshBeacon &self, bool value){self.bShouldTick = value ? 1 : 0;})
		.def_readwrite("VfTable_FTickableObject", &UMeshBeacon::VfTable_FTickableObject, py::return_value_policy::reference)
		.def_readwrite("MeshBeaconPort", &UMeshBeacon::MeshBeaconPort)
		.def_readwrite("Socket", &UMeshBeacon::Socket, py::return_value_policy::reference)
		.def_readwrite("HeartbeatTimeout", &UMeshBeacon::HeartbeatTimeout)
		.def_readwrite("ElapsedHeartbeatTime", &UMeshBeacon::ElapsedHeartbeatTime)
		.def_readwrite("BeaconName", &UMeshBeacon::BeaconName, py::return_value_policy::reference)
		.def_readwrite("SocketSendBufferSize", &UMeshBeacon::SocketSendBufferSize)
		.def_readwrite("SocketReceiveBufferSize", &UMeshBeacon::SocketReceiveBufferSize)
		.def_readwrite("MaxBandwidthTestBufferSize", &UMeshBeacon::MaxBandwidthTestBufferSize)
		.def_readwrite("MinBandwidthTestBufferSize", &UMeshBeacon::MinBandwidthTestBufferSize)
		.def_readwrite("MaxBandwidthTestSendTime", &UMeshBeacon::MaxBandwidthTestSendTime)
		.def_readwrite("MaxBandwidthTestReceiveTime", &UMeshBeacon::MaxBandwidthTestReceiveTime)
		.def_readwrite("MaxBandwidthHistoryEntries", &UMeshBeacon::MaxBandwidthHistoryEntries)
		.def("eventDestroyBeacon", &UMeshBeacon::eventDestroyBeacon)
		;
	py::class_< UMeshBeaconClient, UMeshBeacon >(m, "UMeshBeaconClient")
		.def_property("bUsingRegisteredAddr", [](UMeshBeaconClient &self){return self.bUsingRegisteredAddr;}, [](UMeshBeaconClient &self, bool value){self.bUsingRegisteredAddr = value ? 1 : 0;})
		.def_readwrite("HostPendingRequest", &UMeshBeaconClient::HostPendingRequest, py::return_value_policy::reference)
		.def_readwrite("ClientPendingRequest", &UMeshBeaconClient::ClientPendingRequest, py::return_value_policy::reference)
		.def_readwrite("CurrentBandwidthTest", &UMeshBeaconClient::CurrentBandwidthTest, py::return_value_policy::reference)
		.def_readwrite("ClientBeaconState", &UMeshBeaconClient::ClientBeaconState)
		.def_readwrite("ClientBeaconRequestType", &UMeshBeaconClient::ClientBeaconRequestType)
		.def_readwrite("ConnectionRequestTimeout", &UMeshBeaconClient::ConnectionRequestTimeout)
		.def_readwrite("ConnectionRequestElapsedTime", &UMeshBeaconClient::ConnectionRequestElapsedTime)
		.def_readwrite("ResolverClassName", &UMeshBeaconClient::ResolverClassName, py::return_value_policy::reference)
		.def_readwrite("ResolverClass", &UMeshBeaconClient::ResolverClass, py::return_value_policy::reference)
		.def_readwrite("Resolver", &UMeshBeaconClient::Resolver, py::return_value_policy::reference)
		.def_readwrite("__OnConnectionRequestResult__Delegate", &UMeshBeaconClient::__OnConnectionRequestResult__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReceivedBandwidthTestRequest__Delegate", &UMeshBeaconClient::__OnReceivedBandwidthTestRequest__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReceivedBandwidthTestResults__Delegate", &UMeshBeaconClient::__OnReceivedBandwidthTestResults__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnTravelRequestReceived__Delegate", &UMeshBeaconClient::__OnTravelRequestReceived__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnCreateNewSessionRequestReceived__Delegate", &UMeshBeaconClient::__OnCreateNewSessionRequestReceived__Delegate, py::return_value_policy::reference)
		.def("OnCreateNewSessionRequestReceived", &UMeshBeaconClient::OnCreateNewSessionRequestReceived)
		.def("OnReceivedBandwidthTestResults", &UMeshBeaconClient::OnReceivedBandwidthTestResults)
		.def("OnReceivedBandwidthTestRequest", &UMeshBeaconClient::OnReceivedBandwidthTestRequest)
		.def("OnConnectionRequestResult", &UMeshBeaconClient::OnConnectionRequestResult)
		.def("BeginBandwidthTest", &UMeshBeaconClient::BeginBandwidthTest)
		.def("RequestConnection", &UMeshBeaconClient::RequestConnection)
		.def("eventDestroyBeacon", &UMeshBeaconClient::eventDestroyBeacon)
		.def("SendHostNewGameSessionResponse", [](UMeshBeaconClient &self , unsigned long bSuccess, struct FName SessionName, class UClass* SearchClass) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.SendHostNewGameSessionResponse(bSuccess, SessionName, SearchClass, pyPlatformSpecificInfo); return py::make_tuple(ret, *pyPlatformSpecificInfo); })
		.def("OnTravelRequestReceived", [](UMeshBeaconClient &self , struct FName SessionName, class UClass* SearchClass) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;   self.OnTravelRequestReceived(SessionName, SearchClass, pyPlatformSpecificInfo); return py::make_tuple(*pyPlatformSpecificInfo); })
		;
	py::class_< UMeshBeaconHost, UMeshBeacon >(m, "UMeshBeaconHost")
		.def_property("bAllowBandwidthTesting", [](UMeshBeaconHost &self){return self.bAllowBandwidthTesting;}, [](UMeshBeaconHost &self, bool value){self.bAllowBandwidthTesting = value ? 1 : 0;})
		.def_readwrite("ClientConnections", &UMeshBeaconHost::ClientConnections, py::return_value_policy::reference)
		.def_readwrite("PendingPlayerConnections", &UMeshBeaconHost::PendingPlayerConnections, py::return_value_policy::reference)
		.def_readwrite("OwningPlayerId", &UMeshBeaconHost::OwningPlayerId, py::return_value_policy::reference)
		.def_readwrite("ConnectionBacklog", &UMeshBeaconHost::ConnectionBacklog)
		.def_readwrite("__OnReceivedClientConnectionRequest__Delegate", &UMeshBeaconHost::__OnReceivedClientConnectionRequest__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnStartedBandwidthTest__Delegate", &UMeshBeaconHost::__OnStartedBandwidthTest__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnFinishedBandwidthTest__Delegate", &UMeshBeaconHost::__OnFinishedBandwidthTest__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnAllPendingPlayersConnected__Delegate", &UMeshBeaconHost::__OnAllPendingPlayersConnected__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReceivedClientCreateNewSessionResult__Delegate", &UMeshBeaconHost::__OnReceivedClientCreateNewSessionResult__Delegate, py::return_value_policy::reference)
		.def("RequestClientCreateNewSession", &UMeshBeaconHost::RequestClientCreateNewSession)
		.def("OnAllPendingPlayersConnected", &UMeshBeaconHost::OnAllPendingPlayersConnected)
		.def("AllPlayersConnected", &UMeshBeaconHost::AllPlayersConnected)
		.def("GetConnectionIndexForPlayer", &UMeshBeaconHost::GetConnectionIndexForPlayer)
		.def("SetPendingPlayerConnections", &UMeshBeaconHost::SetPendingPlayerConnections)
		.def("OnFinishedBandwidthTest", &UMeshBeaconHost::OnFinishedBandwidthTest)
		.def("OnStartedBandwidthTest", &UMeshBeaconHost::OnStartedBandwidthTest)
		.def("OnReceivedClientConnectionRequest", &UMeshBeaconHost::OnReceivedClientConnectionRequest)
		.def("AllowBandwidthTesting", &UMeshBeaconHost::AllowBandwidthTesting)
		.def("CancelPendingBandwidthTests", &UMeshBeaconHost::CancelPendingBandwidthTests)
		.def("HasPendingBandwidthTest", &UMeshBeaconHost::HasPendingBandwidthTest)
		.def("CancelInProgressBandwidthTests", &UMeshBeaconHost::CancelInProgressBandwidthTests)
		.def("HasInProgressBandwidthTest", &UMeshBeaconHost::HasInProgressBandwidthTest)
		.def("RequestClientBandwidthTest", &UMeshBeaconHost::RequestClientBandwidthTest)
		.def("eventDestroyBeacon", &UMeshBeaconHost::eventDestroyBeacon)
		.def("InitHostBeacon", &UMeshBeaconHost::InitHostBeacon)
		.def("OnReceivedClientCreateNewSessionResult", [](UMeshBeaconHost &self , unsigned long bSucceeded, struct FName SessionName, class UClass* SearchClass) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;   self.OnReceivedClientCreateNewSessionResult(bSucceeded, SessionName, SearchClass, pyPlatformSpecificInfo); return py::make_tuple(*pyPlatformSpecificInfo); })
		.def("TellClientsToTravel", [](UMeshBeaconHost &self , struct FName SessionName, class UClass* SearchClass) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;   self.TellClientsToTravel(SessionName, SearchClass, pyPlatformSpecificInfo); return py::make_tuple(*pyPlatformSpecificInfo); })
		;
	py::class_< UOnlineSubsystemCommonImpl, UOnlineSubsystem >(m, "UOnlineSubsystemCommonImpl")
		.def_property("bIsUsingSpeechRecognition", [](UOnlineSubsystemCommonImpl &self){return self.bIsUsingSpeechRecognition;}, [](UOnlineSubsystemCommonImpl &self, bool value){self.bIsUsingSpeechRecognition = value ? 1 : 0;})
		.def_readwrite("VoiceEngine", &UOnlineSubsystemCommonImpl::VoiceEngine, py::return_value_policy::reference)
		.def_readwrite("MaxLocalTalkers", &UOnlineSubsystemCommonImpl::MaxLocalTalkers)
		.def_readwrite("MaxRemoteTalkers", &UOnlineSubsystemCommonImpl::MaxRemoteTalkers)
		.def_readwrite("GameInterfaceImpl", &UOnlineSubsystemCommonImpl::GameInterfaceImpl, py::return_value_policy::reference)
		.def_readwrite("AuthInterfaceImpl", &UOnlineSubsystemCommonImpl::AuthInterfaceImpl, py::return_value_policy::reference)
		.def("GetRegisteredPlayers", &UOnlineSubsystemCommonImpl::GetRegisteredPlayers)
		.def("IsPlayerInSession", &UOnlineSubsystemCommonImpl::IsPlayerInSession)
		.def("eventGetPlayerNicknameFromIndex", &UOnlineSubsystemCommonImpl::eventGetPlayerNicknameFromIndex, py::return_value_policy::reference)
		;
	py::class_< UOnlineAuthInterfaceImpl, UOnlineAuthInterfaceBaseImpl >(m, "UOnlineAuthInterfaceImpl")
		.def_readwrite("OwningSubsystem", &UOnlineAuthInterfaceImpl::OwningSubsystem, py::return_value_policy::reference)
		.def_readwrite("AuthReadyDelegates", &UOnlineAuthInterfaceImpl::AuthReadyDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthRequestClientDelegates", &UOnlineAuthInterfaceImpl::AuthRequestClientDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthRequestServerDelegates", &UOnlineAuthInterfaceImpl::AuthRequestServerDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthBlobReceivedClientDelegates", &UOnlineAuthInterfaceImpl::AuthBlobReceivedClientDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthBlobReceivedServerDelegates", &UOnlineAuthInterfaceImpl::AuthBlobReceivedServerDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthCompleteClientDelegates", &UOnlineAuthInterfaceImpl::AuthCompleteClientDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthCompleteServerDelegates", &UOnlineAuthInterfaceImpl::AuthCompleteServerDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthKillClientDelegates", &UOnlineAuthInterfaceImpl::AuthKillClientDelegates, py::return_value_policy::reference)
		.def_readwrite("AuthRetryServerDelegates", &UOnlineAuthInterfaceImpl::AuthRetryServerDelegates, py::return_value_policy::reference)
		.def_readwrite("ClientConnectionCloseDelegates", &UOnlineAuthInterfaceImpl::ClientConnectionCloseDelegates, py::return_value_policy::reference)
		.def_readwrite("ServerConnectionCloseDelegates", &UOnlineAuthInterfaceImpl::ServerConnectionCloseDelegates, py::return_value_policy::reference)
		.def("FindLocalServerAuthSession", &UOnlineAuthInterfaceImpl::FindLocalServerAuthSession)
		.def("FindServerAuthSession", &UOnlineAuthInterfaceImpl::FindServerAuthSession)
		.def("FindLocalClientAuthSession", &UOnlineAuthInterfaceImpl::FindLocalClientAuthSession)
		.def("FindClientAuthSession", &UOnlineAuthInterfaceImpl::FindClientAuthSession)
		.def("SendAuthRetryServer", &UOnlineAuthInterfaceImpl::SendAuthRetryServer)
		.def("SendAuthKillClient", &UOnlineAuthInterfaceImpl::SendAuthKillClient)
		.def("SendAuthBlobServer", &UOnlineAuthInterfaceImpl::SendAuthBlobServer)
		.def("SendAuthBlobClient", &UOnlineAuthInterfaceImpl::SendAuthBlobClient)
		.def("ClearServerConnectionCloseDelegate", &UOnlineAuthInterfaceImpl::ClearServerConnectionCloseDelegate)
		.def("AddServerConnectionCloseDelegate", &UOnlineAuthInterfaceImpl::AddServerConnectionCloseDelegate)
		.def("ClearClientConnectionCloseDelegate", &UOnlineAuthInterfaceImpl::ClearClientConnectionCloseDelegate)
		.def("AddClientConnectionCloseDelegate", &UOnlineAuthInterfaceImpl::AddClientConnectionCloseDelegate)
		.def("ClearAuthRetryServerDelegate", &UOnlineAuthInterfaceImpl::ClearAuthRetryServerDelegate)
		.def("AddAuthRetryServerDelegate", &UOnlineAuthInterfaceImpl::AddAuthRetryServerDelegate)
		.def("ClearAuthKillClientDelegate", &UOnlineAuthInterfaceImpl::ClearAuthKillClientDelegate)
		.def("AddAuthKillClientDelegate", &UOnlineAuthInterfaceImpl::AddAuthKillClientDelegate)
		.def("ClearAuthCompleteServerDelegate", &UOnlineAuthInterfaceImpl::ClearAuthCompleteServerDelegate)
		.def("AddAuthCompleteServerDelegate", &UOnlineAuthInterfaceImpl::AddAuthCompleteServerDelegate)
		.def("ClearAuthCompleteClientDelegate", &UOnlineAuthInterfaceImpl::ClearAuthCompleteClientDelegate)
		.def("AddAuthCompleteClientDelegate", &UOnlineAuthInterfaceImpl::AddAuthCompleteClientDelegate)
		.def("ClearAuthBlobReceivedServerDelegate", &UOnlineAuthInterfaceImpl::ClearAuthBlobReceivedServerDelegate)
		.def("AddAuthBlobReceivedServerDelegate", &UOnlineAuthInterfaceImpl::AddAuthBlobReceivedServerDelegate)
		.def("ClearAuthBlobReceivedClientDelegate", &UOnlineAuthInterfaceImpl::ClearAuthBlobReceivedClientDelegate)
		.def("AddAuthBlobReceivedClientDelegate", &UOnlineAuthInterfaceImpl::AddAuthBlobReceivedClientDelegate)
		.def("ClearAuthRequestServerDelegate", &UOnlineAuthInterfaceImpl::ClearAuthRequestServerDelegate)
		.def("AddAuthRequestServerDelegate", &UOnlineAuthInterfaceImpl::AddAuthRequestServerDelegate)
		.def("ClearAuthRequestClientDelegate", &UOnlineAuthInterfaceImpl::ClearAuthRequestClientDelegate)
		.def("AddAuthRequestClientDelegate", &UOnlineAuthInterfaceImpl::AddAuthRequestClientDelegate)
		.def("ClearAuthReadyDelegate", &UOnlineAuthInterfaceImpl::ClearAuthReadyDelegate)
		.def("AddAuthReadyDelegate", &UOnlineAuthInterfaceImpl::AddAuthReadyDelegate)
		;
	py::class_< UOnlineGameInterfaceImpl, UObject >(m, "UOnlineGameInterfaceImpl")
		.def_readwrite("OwningSubsystem", &UOnlineGameInterfaceImpl::OwningSubsystem, py::return_value_policy::reference)
		.def_readwrite("GameSettings", &UOnlineGameInterfaceImpl::GameSettings, py::return_value_policy::reference)
		.def_readwrite("GameSearch", &UOnlineGameInterfaceImpl::GameSearch, py::return_value_policy::reference)
		.def_readwrite("CurrentGameState", &UOnlineGameInterfaceImpl::CurrentGameState)
		.def_readwrite("LanBeaconState", &UOnlineGameInterfaceImpl::LanBeaconState)
		.def_readwrite("CreateOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::CreateOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("UpdateOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::UpdateOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("DestroyOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::DestroyOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("JoinOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::JoinOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("MigrateOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::MigrateOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("JoinMigratedOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::JoinMigratedOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("RecalculateSkillRatingCompleteDelegates", &UOnlineGameInterfaceImpl::RecalculateSkillRatingCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("StartOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::StartOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("EndOnlineGameCompleteDelegates", &UOnlineGameInterfaceImpl::EndOnlineGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("FindOnlineGamesCompleteDelegates", &UOnlineGameInterfaceImpl::FindOnlineGamesCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("CancelFindOnlineGamesCompleteDelegates", &UOnlineGameInterfaceImpl::CancelFindOnlineGamesCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("LanAnnouncePort", &UOnlineGameInterfaceImpl::LanAnnouncePort)
		.def_readwrite("LanGameUniqueId", &UOnlineGameInterfaceImpl::LanGameUniqueId)
		.def_readwrite("LanPacketPlatformMask", &UOnlineGameInterfaceImpl::LanPacketPlatformMask)
		.def_readwrite("LanQueryTimeLeft", &UOnlineGameInterfaceImpl::LanQueryTimeLeft)
		.def_readwrite("LanQueryTimeout", &UOnlineGameInterfaceImpl::LanQueryTimeout)
		.def_readwrite("LanBeacon", &UOnlineGameInterfaceImpl::LanBeacon, py::return_value_policy::reference)
		.def_readwrite("SessionInfo", &UOnlineGameInterfaceImpl::SessionInfo, py::return_value_policy::reference)
		.def_readwrite("NATResolutionTimeout", &UOnlineGameInterfaceImpl::NATResolutionTimeout)
		.def_readwrite("__OnFindOnlineGamesComplete__Delegate", &UOnlineGameInterfaceImpl::__OnFindOnlineGamesComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnCreateOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnCreateOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnUpdateOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnUpdateOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnDestroyOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnDestroyOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnCancelFindOnlineGamesComplete__Delegate", &UOnlineGameInterfaceImpl::__OnCancelFindOnlineGamesComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnJoinOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnJoinOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnRegisterPlayerComplete__Delegate", &UOnlineGameInterfaceImpl::__OnRegisterPlayerComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnUnregisterPlayerComplete__Delegate", &UOnlineGameInterfaceImpl::__OnUnregisterPlayerComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnStartOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnStartOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnEndOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnEndOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnArbitrationRegistrationComplete__Delegate", &UOnlineGameInterfaceImpl::__OnArbitrationRegistrationComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnGameInviteAccepted__Delegate", &UOnlineGameInterfaceImpl::__OnGameInviteAccepted__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnGameInviteProcessingStarted__Delegate", &UOnlineGameInterfaceImpl::__OnGameInviteProcessingStarted__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnRecalculateSkillRatingComplete__Delegate", &UOnlineGameInterfaceImpl::__OnRecalculateSkillRatingComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnMigrateOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnMigrateOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnJoinMigratedOnlineGameComplete__Delegate", &UOnlineGameInterfaceImpl::__OnJoinMigratedOnlineGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnQosStatusChanged__Delegate", &UOnlineGameInterfaceImpl::__OnQosStatusChanged__Delegate, py::return_value_policy::reference)
		.def("HasPendingBootInvite", &UOnlineGameInterfaceImpl::HasPendingBootInvite)
		.def("CancelNATNegotiation", &UOnlineGameInterfaceImpl::CancelNATNegotiation)
		.def("ClearQosStatusChangedDelegate", &UOnlineGameInterfaceImpl::ClearQosStatusChangedDelegate)
		.def("AddQosStatusChangedDelegate", &UOnlineGameInterfaceImpl::AddQosStatusChangedDelegate)
		.def("OnQosStatusChanged", &UOnlineGameInterfaceImpl::OnQosStatusChanged)
		.def("QueryNonAdvertisedData", &UOnlineGameInterfaceImpl::QueryNonAdvertisedData)
		.def("ClearJoinMigratedOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearJoinMigratedOnlineGameCompleteDelegate)
		.def("AddJoinMigratedOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddJoinMigratedOnlineGameCompleteDelegate)
		.def("OnJoinMigratedOnlineGameComplete", &UOnlineGameInterfaceImpl::OnJoinMigratedOnlineGameComplete)
		.def("JoinMigratedOnlineGame", &UOnlineGameInterfaceImpl::JoinMigratedOnlineGame)
		.def("ClearMigrateOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearMigrateOnlineGameCompleteDelegate)
		.def("AddMigrateOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddMigrateOnlineGameCompleteDelegate)
		.def("OnMigrateOnlineGameComplete", &UOnlineGameInterfaceImpl::OnMigrateOnlineGameComplete)
		.def("MigrateOnlineGame", &UOnlineGameInterfaceImpl::MigrateOnlineGame)
		.def("ClearRecalculateSkillRatingCompleteDelegate", &UOnlineGameInterfaceImpl::ClearRecalculateSkillRatingCompleteDelegate)
		.def("AddRecalculateSkillRatingCompleteDelegate", &UOnlineGameInterfaceImpl::AddRecalculateSkillRatingCompleteDelegate)
		.def("OnRecalculateSkillRatingComplete", &UOnlineGameInterfaceImpl::OnRecalculateSkillRatingComplete)
		.def("RecalculateSkillRating", &UOnlineGameInterfaceImpl::RecalculateSkillRating)
		.def("ClearGameInviteProcessingStartedDelegate", &UOnlineGameInterfaceImpl::ClearGameInviteProcessingStartedDelegate)
		.def("AddGameInviteProcessingStartedDelegate", &UOnlineGameInterfaceImpl::AddGameInviteProcessingStartedDelegate)
		.def("OnGameInviteProcessingStarted", &UOnlineGameInterfaceImpl::OnGameInviteProcessingStarted)
		.def("AcceptGameInvite", &UOnlineGameInterfaceImpl::AcceptGameInvite)
		.def("ClearGameInviteAcceptedDelegate", &UOnlineGameInterfaceImpl::ClearGameInviteAcceptedDelegate)
		.def("AddGameInviteAcceptedDelegate", &UOnlineGameInterfaceImpl::AddGameInviteAcceptedDelegate)
		.def("OnGameInviteAccepted", &UOnlineGameInterfaceImpl::OnGameInviteAccepted)
		.def("GetArbitratedPlayers", &UOnlineGameInterfaceImpl::GetArbitratedPlayers, py::return_value_policy::reference)
		.def("ClearArbitrationRegistrationCompleteDelegate", &UOnlineGameInterfaceImpl::ClearArbitrationRegistrationCompleteDelegate)
		.def("AddArbitrationRegistrationCompleteDelegate", &UOnlineGameInterfaceImpl::AddArbitrationRegistrationCompleteDelegate)
		.def("OnArbitrationRegistrationComplete", &UOnlineGameInterfaceImpl::OnArbitrationRegistrationComplete)
		.def("RegisterForArbitration", &UOnlineGameInterfaceImpl::RegisterForArbitration)
		.def("ClearEndOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearEndOnlineGameCompleteDelegate)
		.def("AddEndOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddEndOnlineGameCompleteDelegate)
		.def("OnEndOnlineGameComplete", &UOnlineGameInterfaceImpl::OnEndOnlineGameComplete)
		.def("EndOnlineGame", &UOnlineGameInterfaceImpl::EndOnlineGame)
		.def("ClearStartOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearStartOnlineGameCompleteDelegate)
		.def("AddStartOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddStartOnlineGameCompleteDelegate)
		.def("OnStartOnlineGameComplete", &UOnlineGameInterfaceImpl::OnStartOnlineGameComplete)
		.def("StartOnlineGame", &UOnlineGameInterfaceImpl::StartOnlineGame)
		.def("ClearUnregisterPlayerCompleteDelegate", &UOnlineGameInterfaceImpl::ClearUnregisterPlayerCompleteDelegate)
		.def("AddUnregisterPlayerCompleteDelegate", &UOnlineGameInterfaceImpl::AddUnregisterPlayerCompleteDelegate)
		.def("OnUnregisterPlayerComplete", &UOnlineGameInterfaceImpl::OnUnregisterPlayerComplete)
		.def("UnregisterPlayers", &UOnlineGameInterfaceImpl::UnregisterPlayers)
		.def("UnregisterPlayer", &UOnlineGameInterfaceImpl::UnregisterPlayer)
		.def("ClearRegisterPlayerCompleteDelegate", &UOnlineGameInterfaceImpl::ClearRegisterPlayerCompleteDelegate)
		.def("AddRegisterPlayerCompleteDelegate", &UOnlineGameInterfaceImpl::AddRegisterPlayerCompleteDelegate)
		.def("OnRegisterPlayerComplete", &UOnlineGameInterfaceImpl::OnRegisterPlayerComplete)
		.def("RegisterPlayers", &UOnlineGameInterfaceImpl::RegisterPlayers)
		.def("RegisterPlayer", &UOnlineGameInterfaceImpl::RegisterPlayer)
		.def("GetResolvedConnectString", &UOnlineGameInterfaceImpl::GetResolvedConnectString)
		.def("ClearJoinOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearJoinOnlineGameCompleteDelegate)
		.def("AddJoinOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddJoinOnlineGameCompleteDelegate)
		.def("OnJoinOnlineGameComplete", &UOnlineGameInterfaceImpl::OnJoinOnlineGameComplete)
		.def("JoinOnlineGame", &UOnlineGameInterfaceImpl::JoinOnlineGame)
		.def("FreeSearchResults", &UOnlineGameInterfaceImpl::FreeSearchResults)
		.def("ClearCancelFindOnlineGamesCompleteDelegate", &UOnlineGameInterfaceImpl::ClearCancelFindOnlineGamesCompleteDelegate)
		.def("AddCancelFindOnlineGamesCompleteDelegate", &UOnlineGameInterfaceImpl::AddCancelFindOnlineGamesCompleteDelegate)
		.def("OnCancelFindOnlineGamesComplete", &UOnlineGameInterfaceImpl::OnCancelFindOnlineGamesComplete)
		.def("CancelFindOnlineGames", &UOnlineGameInterfaceImpl::CancelFindOnlineGames)
		.def("ClearFindOnlineGamesCompleteDelegate", &UOnlineGameInterfaceImpl::ClearFindOnlineGamesCompleteDelegate)
		.def("AddFindOnlineGamesCompleteDelegate", &UOnlineGameInterfaceImpl::AddFindOnlineGamesCompleteDelegate)
		.def("FindOnlineGames", &UOnlineGameInterfaceImpl::FindOnlineGames)
		.def("ClearDestroyOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearDestroyOnlineGameCompleteDelegate)
		.def("AddDestroyOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddDestroyOnlineGameCompleteDelegate)
		.def("OnDestroyOnlineGameComplete", &UOnlineGameInterfaceImpl::OnDestroyOnlineGameComplete)
		.def("DestroyOnlineGame", &UOnlineGameInterfaceImpl::DestroyOnlineGame)
		.def("ClearUpdateOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearUpdateOnlineGameCompleteDelegate)
		.def("AddUpdateOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddUpdateOnlineGameCompleteDelegate)
		.def("OnUpdateOnlineGameComplete", &UOnlineGameInterfaceImpl::OnUpdateOnlineGameComplete)
		.def("UpdateOnlineGame", &UOnlineGameInterfaceImpl::UpdateOnlineGame)
		.def("ClearCreateOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::ClearCreateOnlineGameCompleteDelegate)
		.def("AddCreateOnlineGameCompleteDelegate", &UOnlineGameInterfaceImpl::AddCreateOnlineGameCompleteDelegate)
		.def("OnCreateOnlineGameComplete", &UOnlineGameInterfaceImpl::OnCreateOnlineGameComplete)
		.def("CreateOnlineGame", &UOnlineGameInterfaceImpl::CreateOnlineGame)
		.def("GetGameSearch", &UOnlineGameInterfaceImpl::GetGameSearch, py::return_value_policy::reference)
		.def("GetGameSettings", &UOnlineGameInterfaceImpl::GetGameSettings, py::return_value_policy::reference)
		.def("OnFindOnlineGamesComplete", &UOnlineGameInterfaceImpl::OnFindOnlineGamesComplete)
		.def("BindPlatformSpecificSessionToSearch", [](UOnlineGameInterfaceImpl &self , unsigned char SearchingPlayerNum, class UOnlineGameSearch* SearchSettings) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.BindPlatformSpecificSessionToSearch(SearchingPlayerNum, SearchSettings, pyPlatformSpecificInfo); return py::make_tuple(ret, *pyPlatformSpecificInfo); })
		.def("ReadPlatformSpecificSessionInfoBySessionName", [](UOnlineGameInterfaceImpl &self , struct FName SessionName) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.ReadPlatformSpecificSessionInfoBySessionName(SessionName, pyPlatformSpecificInfo); return py::make_tuple(ret, *pyPlatformSpecificInfo); })
		.def("ReadPlatformSpecificSessionInfo", [](UOnlineGameInterfaceImpl &self , struct FOnlineGameSearchResult* DesiredGame) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.ReadPlatformSpecificSessionInfo(DesiredGame, pyPlatformSpecificInfo); return py::make_tuple(ret, *pyPlatformSpecificInfo); })
		;
	py::class_< UOnlinePlaylistManager, UObject >(m, "UOnlinePlaylistManager")
		.def_readwrite("VfTable_FTickableObject", &UOnlinePlaylistManager::VfTable_FTickableObject, py::return_value_policy::reference)
		.def_readwrite("Playlists", &UOnlinePlaylistManager::Playlists, py::return_value_policy::reference)
		.def_readwrite("PlaylistFileNames", &UOnlinePlaylistManager::PlaylistFileNames, py::return_value_policy::reference)
		.def_readwrite("DatastoresToRefresh", &UOnlinePlaylistManager::DatastoresToRefresh, py::return_value_policy::reference)
		.def_readwrite("DownloadCount", &UOnlinePlaylistManager::DownloadCount)
		.def_readwrite("SuccessfulCount", &UOnlinePlaylistManager::SuccessfulCount)
		.def_readwrite("VersionNumber", &UOnlinePlaylistManager::VersionNumber)
		.def_readwrite("PopulationData", &UOnlinePlaylistManager::PopulationData, py::return_value_policy::reference)
		.def_readwrite("WorldwideTotalPlayers", &UOnlinePlaylistManager::WorldwideTotalPlayers)
		.def_readwrite("RegionTotalPlayers", &UOnlinePlaylistManager::RegionTotalPlayers)
		.def_readwrite("TitleFileInterface", &UOnlinePlaylistManager::TitleFileInterface, py::return_value_policy::reference)
		.def_readwrite("PopulationFileName", &UOnlinePlaylistManager::PopulationFileName, py::return_value_policy::reference)
		.def_readwrite("NextPlaylistPopulationUpdateTime", &UOnlinePlaylistManager::NextPlaylistPopulationUpdateTime)
		.def_readwrite("PlaylistPopulationUpdateInterval", &UOnlinePlaylistManager::PlaylistPopulationUpdateInterval)
		.def_readwrite("MinPlaylistIdToReport", &UOnlinePlaylistManager::MinPlaylistIdToReport)
		.def_readwrite("CurrentPlaylistId", &UOnlinePlaylistManager::CurrentPlaylistId)
		.def_readwrite("EventsInterfaceName", &UOnlinePlaylistManager::EventsInterfaceName, py::return_value_policy::reference)
		.def_readwrite("DataCenterId", &UOnlinePlaylistManager::DataCenterId)
		.def_readwrite("DataCenterFileName", &UOnlinePlaylistManager::DataCenterFileName, py::return_value_policy::reference)
		.def_readwrite("LastPlaylistDownloadTime", &UOnlinePlaylistManager::LastPlaylistDownloadTime)
		.def_readwrite("PlaylistRefreshInterval", &UOnlinePlaylistManager::PlaylistRefreshInterval)
		.def_readwrite("__OnReadPlaylistComplete__Delegate", &UOnlinePlaylistManager::__OnReadPlaylistComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnPlaylistPopulationDataUpdated__Delegate", &UOnlinePlaylistManager::__OnPlaylistPopulationDataUpdated__Delegate, py::return_value_policy::reference)
		.def("ParseDataCenterId", &UOnlinePlaylistManager::ParseDataCenterId)
		.def("OnReadDataCenterIdComplete", &UOnlinePlaylistManager::OnReadDataCenterIdComplete)
		.def("ReadDataCenterId", &UOnlinePlaylistManager::ReadDataCenterId)
		.def("eventSendPlaylistPopulationUpdate", &UOnlinePlaylistManager::eventSendPlaylistPopulationUpdate)
		.def("ParsePlaylistPopulationData", &UOnlinePlaylistManager::ParsePlaylistPopulationData)
		.def("OnPlaylistPopulationDataUpdated", &UOnlinePlaylistManager::OnPlaylistPopulationDataUpdated)
		.def("OnReadPlaylistPopulationComplete", &UOnlinePlaylistManager::OnReadPlaylistPopulationComplete)
		.def("ReadPlaylistPopulation", &UOnlinePlaylistManager::ReadPlaylistPopulation)
		.def("Reset", &UOnlinePlaylistManager::Reset)
		.def("GetContentIdsFromPlaylist", &UOnlinePlaylistManager::GetContentIdsFromPlaylist)
		.def("GetInventorySwapFromPlaylist", &UOnlinePlaylistManager::GetInventorySwapFromPlaylist, py::return_value_policy::reference)
		.def("GetMapCycleFromPlaylist", &UOnlinePlaylistManager::GetMapCycleFromPlaylist)
		.def("GetUrlFromPlaylist", &UOnlinePlaylistManager::GetUrlFromPlaylist, py::return_value_policy::reference)
		.def("GetMatchType", &UOnlinePlaylistManager::GetMatchType)
		.def("IsPlaylistArbitrated", &UOnlinePlaylistManager::IsPlaylistArbitrated)
		.def("PlaylistSupportsDedicatedServers", &UOnlinePlaylistManager::PlaylistSupportsDedicatedServers)
		.def("HasAnyGameSettings", &UOnlinePlaylistManager::HasAnyGameSettings)
		.def("GetGameSettings", &UOnlinePlaylistManager::GetGameSettings, py::return_value_policy::reference)
		.def("FinalizePlaylistObjects", &UOnlinePlaylistManager::FinalizePlaylistObjects)
		.def("OnReadTitleFileComplete", &UOnlinePlaylistManager::OnReadTitleFileComplete)
		.def("ShouldRefreshPlaylists", &UOnlinePlaylistManager::ShouldRefreshPlaylists)
		.def("DetermineFilesToDownload", &UOnlinePlaylistManager::DetermineFilesToDownload)
		.def("DownloadPlaylist", &UOnlinePlaylistManager::DownloadPlaylist)
		.def("OnReadPlaylistComplete", &UOnlinePlaylistManager::OnReadPlaylistComplete)
		.def("GetPopulationInfoFromPlaylist", [](UOnlinePlaylistManager &self , int PlaylistId) { int* pyWorldwideTotal = (int*)malloc(sizeof(int)) ; int* pyRegionTotal = (int*)malloc(sizeof(int)) ;   self.GetPopulationInfoFromPlaylist(PlaylistId, pyWorldwideTotal, pyRegionTotal); return py::make_tuple(*pyWorldwideTotal, *pyRegionTotal); })
		.def("GetLoadBalanceIdFromPlaylist", [](UOnlinePlaylistManager &self , int PlaylistId) { int* pyLoadBalanceId = (int*)malloc(sizeof(int)) ;   self.GetLoadBalanceIdFromPlaylist(PlaylistId, pyLoadBalanceId); return py::make_tuple(*pyLoadBalanceId); })
		.def("GetTeamInfoFromPlaylist", [](UOnlinePlaylistManager &self , int PlaylistId) { int* pyTeamSize = (int*)malloc(sizeof(int)) ; int* pyTeamCount = (int*)malloc(sizeof(int)) ; int* pyMaxPartySize = (int*)malloc(sizeof(int)) ;   self.GetTeamInfoFromPlaylist(PlaylistId, pyTeamSize, pyTeamCount, pyMaxPartySize); return py::make_tuple(*pyTeamSize, *pyTeamCount, *pyMaxPartySize); })
		;
	py::class_< UPartyBeacon, UObject >(m, "UPartyBeacon")
		.def_property("bIsInTick", [](UPartyBeacon &self){return self.bIsInTick;}, [](UPartyBeacon &self, bool value){self.bIsInTick = value ? 1 : 0;})
		.def_property("bWantsDeferredDestroy", [](UPartyBeacon &self){return self.bWantsDeferredDestroy;}, [](UPartyBeacon &self, bool value){self.bWantsDeferredDestroy = value ? 1 : 0;})
		.def_property("bShouldTick", [](UPartyBeacon &self){return self.bShouldTick;}, [](UPartyBeacon &self, bool value){self.bShouldTick = value ? 1 : 0;})
		.def_readwrite("VfTable_FTickableObject", &UPartyBeacon::VfTable_FTickableObject, py::return_value_policy::reference)
		.def_readwrite("PartyBeaconPort", &UPartyBeacon::PartyBeaconPort)
		.def_readwrite("Socket", &UPartyBeacon::Socket, py::return_value_policy::reference)
		.def_readwrite("HeartbeatTimeout", &UPartyBeacon::HeartbeatTimeout)
		.def_readwrite("ElapsedHeartbeatTime", &UPartyBeacon::ElapsedHeartbeatTime)
		.def_readwrite("BeaconName", &UPartyBeacon::BeaconName, py::return_value_policy::reference)
		.def_readwrite("__OnDestroyComplete__Delegate", &UPartyBeacon::__OnDestroyComplete__Delegate, py::return_value_policy::reference)
		.def("OnDestroyComplete", &UPartyBeacon::OnDestroyComplete)
		.def("eventDestroyBeacon", &UPartyBeacon::eventDestroyBeacon)
		;
	py::class_< UPartyBeaconClient, UPartyBeacon >(m, "UPartyBeaconClient")
		.def_readwrite("HostPendingRequest", &UPartyBeaconClient::HostPendingRequest, py::return_value_policy::reference)
		.def_readwrite("PendingRequest", &UPartyBeaconClient::PendingRequest, py::return_value_policy::reference)
		.def_readwrite("ClientBeaconState", &UPartyBeaconClient::ClientBeaconState)
		.def_readwrite("ClientBeaconRequestType", &UPartyBeaconClient::ClientBeaconRequestType)
		.def_readwrite("ReservationRequestTimeout", &UPartyBeaconClient::ReservationRequestTimeout)
		.def_readwrite("ReservationRequestElapsedTime", &UPartyBeaconClient::ReservationRequestElapsedTime)
		.def_readwrite("ResolverClassName", &UPartyBeaconClient::ResolverClassName, py::return_value_policy::reference)
		.def_readwrite("ResolverClass", &UPartyBeaconClient::ResolverClass, py::return_value_policy::reference)
		.def_readwrite("Resolver", &UPartyBeaconClient::Resolver, py::return_value_policy::reference)
		.def_readwrite("__OnReservationRequestComplete__Delegate", &UPartyBeaconClient::__OnReservationRequestComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReservationCountUpdated__Delegate", &UPartyBeaconClient::__OnReservationCountUpdated__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnTravelRequestReceived__Delegate", &UPartyBeaconClient::__OnTravelRequestReceived__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnHostIsReady__Delegate", &UPartyBeaconClient::__OnHostIsReady__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnHostHasCancelled__Delegate", &UPartyBeaconClient::__OnHostHasCancelled__Delegate, py::return_value_policy::reference)
		.def("eventDestroyBeacon", &UPartyBeaconClient::eventDestroyBeacon)
		.def("CancelReservation", &UPartyBeaconClient::CancelReservation)
		.def("RequestReservationUpdate", &UPartyBeaconClient::RequestReservationUpdate)
		.def("RequestReservation", &UPartyBeaconClient::RequestReservation)
		.def("OnHostHasCancelled", &UPartyBeaconClient::OnHostHasCancelled)
		.def("OnHostIsReady", &UPartyBeaconClient::OnHostIsReady)
		.def("OnReservationCountUpdated", &UPartyBeaconClient::OnReservationCountUpdated)
		.def("OnReservationRequestComplete", &UPartyBeaconClient::OnReservationRequestComplete)
		.def("OnTravelRequestReceived", [](UPartyBeaconClient &self , struct FName SessionName, class UClass* SearchClass) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;   self.OnTravelRequestReceived(SessionName, SearchClass, pyPlatformSpecificInfo); return py::make_tuple(*pyPlatformSpecificInfo); })
		;
	py::class_< UPartyBeaconHost, UPartyBeacon >(m, "UPartyBeaconHost")
		.def_property("bBestFitTeamAssignment", [](UPartyBeaconHost &self){return self.bBestFitTeamAssignment;}, [](UPartyBeaconHost &self, bool value){self.bBestFitTeamAssignment = value ? 1 : 0;})
		.def_readwrite("Clients", &UPartyBeaconHost::Clients, py::return_value_policy::reference)
		.def_readwrite("NumTeams", &UPartyBeaconHost::NumTeams)
		.def_readwrite("NumPlayersPerTeam", &UPartyBeaconHost::NumPlayersPerTeam)
		.def_readwrite("NumReservations", &UPartyBeaconHost::NumReservations)
		.def_readwrite("NumConsumedReservations", &UPartyBeaconHost::NumConsumedReservations)
		.def_readwrite("Reservations", &UPartyBeaconHost::Reservations, py::return_value_policy::reference)
		.def_readwrite("OnlineSessionName", &UPartyBeaconHost::OnlineSessionName, py::return_value_policy::reference)
		.def_readwrite("ConnectionBacklog", &UPartyBeaconHost::ConnectionBacklog)
		.def_readwrite("ForceTeamNum", &UPartyBeaconHost::ForceTeamNum)
		.def_readwrite("ReservedHostTeamNum", &UPartyBeaconHost::ReservedHostTeamNum)
		.def_readwrite("BeaconState", &UPartyBeaconHost::BeaconState)
		.def_readwrite("__OnReservationChange__Delegate", &UPartyBeaconHost::__OnReservationChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReservationsFull__Delegate", &UPartyBeaconHost::__OnReservationsFull__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnClientCancellationReceived__Delegate", &UPartyBeaconHost::__OnClientCancellationReceived__Delegate, py::return_value_policy::reference)
		.def("GetMaxAvailableTeamSize", &UPartyBeaconHost::GetMaxAvailableTeamSize)
		.def("GetPartyLeaders", &UPartyBeaconHost::GetPartyLeaders)
		.def("GetPlayers", &UPartyBeaconHost::GetPlayers)
		.def("AppendReservationSkillsToSearch", &UPartyBeaconHost::AppendReservationSkillsToSearch)
		.def("eventUnregisterParty", &UPartyBeaconHost::eventUnregisterParty)
		.def("eventUnregisterPartyMembers", &UPartyBeaconHost::eventUnregisterPartyMembers)
		.def("eventRegisterPartyMembers", &UPartyBeaconHost::eventRegisterPartyMembers)
		.def("AreReservationsFull", &UPartyBeaconHost::AreReservationsFull)
		.def("TellClientsHostHasCancelled", &UPartyBeaconHost::TellClientsHostHasCancelled)
		.def("TellClientsHostIsReady", &UPartyBeaconHost::TellClientsHostIsReady)
		.def("eventDestroyBeacon", &UPartyBeaconHost::eventDestroyBeacon)
		.def("OnClientCancellationReceived", &UPartyBeaconHost::OnClientCancellationReceived)
		.def("OnReservationsFull", &UPartyBeaconHost::OnReservationsFull)
		.def("OnReservationChange", &UPartyBeaconHost::OnReservationChange)
		.def("HandlePlayerLogout", &UPartyBeaconHost::HandlePlayerLogout)
		.def("GetExistingReservation", &UPartyBeaconHost::GetExistingReservation)
		.def("UpdatePartyReservationEntry", &UPartyBeaconHost::UpdatePartyReservationEntry)
		.def("AddPartyReservationEntry", &UPartyBeaconHost::AddPartyReservationEntry)
		.def("InitHostBeacon", &UPartyBeaconHost::InitHostBeacon)
		.def("PauseReservationRequests", &UPartyBeaconHost::PauseReservationRequests)
		.def("TellClientsToTravel", [](UPartyBeaconHost &self , struct FName SessionName, class UClass* SearchClass) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;   self.TellClientsToTravel(SessionName, SearchClass, pyPlatformSpecificInfo); return py::make_tuple(*pyPlatformSpecificInfo); })
		;
	py::class_< UTcpipConnection, UNetConnection >(m, "UTcpipConnection")
		;
	py::class_< UTcpNetDriver, UNetDriver >(m, "UTcpNetDriver")
		.def_property("AllowPlayerPortUnreach", [](UTcpNetDriver &self){return self.AllowPlayerPortUnreach;}, [](UTcpNetDriver &self, bool value){self.AllowPlayerPortUnreach = value ? 1 : 0;})
		.def_property("LogPortUnreach", [](UTcpNetDriver &self){return self.LogPortUnreach;}, [](UTcpNetDriver &self, bool value){self.LogPortUnreach = value ? 1 : 0;})
		;
	py::class_< UWebRequest, UObject >(m, "UWebRequest")
		.def_readwrite("RemoteAddr", &UWebRequest::RemoteAddr, py::return_value_policy::reference)
		.def_readwrite("URI", &UWebRequest::URI, py::return_value_policy::reference)
		.def_readwrite("UserName", &UWebRequest::UserName, py::return_value_policy::reference)
		.def_readwrite("Password", &UWebRequest::Password, py::return_value_policy::reference)
		.def_readwrite("ContentLength", &UWebRequest::ContentLength)
		.def_readwrite("ContentType", &UWebRequest::ContentType, py::return_value_policy::reference)
		.def_readwrite("RequestType", &UWebRequest::RequestType)
		.def_readwrite("HeaderMap", &UWebRequest::HeaderMap, py::return_value_policy::reference)
		.def_readwrite("VariableMap", &UWebRequest::VariableMap, py::return_value_policy::reference)
		.def("GetHexDigit", &UWebRequest::GetHexDigit)
		.def("DecodeFormData", &UWebRequest::DecodeFormData)
		.def("ProcessHeaderString", &UWebRequest::ProcessHeaderString)
		.def("Dump", &UWebRequest::Dump)
		.def("GetVariables", &UWebRequest::GetVariables)
		.def("GetVariableNumber", &UWebRequest::GetVariableNumber, py::return_value_policy::reference)
		.def("GetVariableCount", &UWebRequest::GetVariableCount)
		.def("GetVariable", &UWebRequest::GetVariable, py::return_value_policy::reference)
		.def("AddVariable", &UWebRequest::AddVariable)
		.def("GetHeaders", &UWebRequest::GetHeaders)
		.def("GetHeader", &UWebRequest::GetHeader, py::return_value_policy::reference)
		.def("AddHeader", &UWebRequest::AddHeader)
		.def("EncodeBase64", &UWebRequest::EncodeBase64, py::return_value_policy::reference)
		.def("DecodeBase64", &UWebRequest::DecodeBase64, py::return_value_policy::reference)
		;
	py::class_< UWebResponse, UObject >(m, "UWebResponse")
		.def_property("bSentText", [](UWebResponse &self){return self.bSentText;}, [](UWebResponse &self, bool value){self.bSentText = value ? 1 : 0;})
		.def_property("bSentResponse", [](UWebResponse &self){return self.bSentResponse;}, [](UWebResponse &self, bool value){self.bSentResponse = value ? 1 : 0;})
		.def_readwrite("headers", &UWebResponse::headers, py::return_value_policy::reference)
		.def_readwrite("ReplacementMap", &UWebResponse::ReplacementMap, py::return_value_policy::reference)
		.def_readwrite("IncludePath", &UWebResponse::IncludePath, py::return_value_policy::reference)
		.def_readwrite("CharSet", &UWebResponse::CharSet, py::return_value_policy::reference)
		.def_readwrite("Connection", &UWebResponse::Connection, py::return_value_policy::reference)
		.def("SentResponse", &UWebResponse::SentResponse)
		.def("SentText", &UWebResponse::SentText)
		.def("Redirect", &UWebResponse::Redirect)
		.def("SendStandardHeaders", &UWebResponse::SendStandardHeaders)
		.def("HTTPError", &UWebResponse::HTTPError)
		.def("SendHeaders", &UWebResponse::SendHeaders)
		.def("AddHeader", &UWebResponse::AddHeader)
		.def("HTTPHeader", &UWebResponse::HTTPHeader)
		.def("HTTPResponse", &UWebResponse::HTTPResponse)
		.def("FailAuthentication", &UWebResponse::FailAuthentication)
		.def("SendCachedFile", &UWebResponse::SendCachedFile)
		.def("eventSendText", &UWebResponse::eventSendText)
		.def("Dump", &UWebResponse::Dump)
		.def("GetHTTPExpiration", &UWebResponse::GetHTTPExpiration, py::return_value_policy::reference)
		.def("LoadParsedUHTM", &UWebResponse::LoadParsedUHTM, py::return_value_policy::reference)
		.def("IncludeBinaryFile", &UWebResponse::IncludeBinaryFile)
		.def("IncludeUHTM", &UWebResponse::IncludeUHTM)
		.def("ClearSubst", &UWebResponse::ClearSubst)
		.def("Subst", &UWebResponse::Subst)
		.def("FileExists", &UWebResponse::FileExists)
		.def("eventSendBinary", [](UWebResponse &self , int Count) { unsigned char* pyB = (unsigned char*)malloc(sizeof(unsigned char)) ;   self.eventSendBinary(Count, pyB); return py::make_tuple(*pyB); })
		;
	py::class_< UOnlinePlaylistProvider, UUIResourceDataProvider >(m, "UOnlinePlaylistProvider")
		.def_readwrite("PlaylistId", &UOnlinePlaylistProvider::PlaylistId)
		.def_readwrite("PlaylistGameTypeNames", &UOnlinePlaylistProvider::PlaylistGameTypeNames, py::return_value_policy::reference)
		.def_readwrite("DisplayName", &UOnlinePlaylistProvider::DisplayName, py::return_value_policy::reference)
		.def_readwrite("Priority", &UOnlinePlaylistProvider::Priority)
		;
	py::class_< UUIDataStore_OnlinePlaylists, UUIDataStore >(m, "UUIDataStore_OnlinePlaylists")
		.def_readwrite("VfTable_IUIListElementProvider", &UUIDataStore_OnlinePlaylists::VfTable_IUIListElementProvider, py::return_value_policy::reference)
		.def_readwrite("ProviderClassName", &UUIDataStore_OnlinePlaylists::ProviderClassName, py::return_value_policy::reference)
		.def_readwrite("ProviderClass", &UUIDataStore_OnlinePlaylists::ProviderClass, py::return_value_policy::reference)
		.def_readwrite("RankedDataProviders", &UUIDataStore_OnlinePlaylists::RankedDataProviders, py::return_value_policy::reference)
		.def_readwrite("UnrankedDataProviders", &UUIDataStore_OnlinePlaylists::UnrankedDataProviders, py::return_value_policy::reference)
		.def_readwrite("RecModeDataProviders", &UUIDataStore_OnlinePlaylists::RecModeDataProviders, py::return_value_policy::reference)
		.def_readwrite("PrivateDataProviders", &UUIDataStore_OnlinePlaylists::PrivateDataProviders, py::return_value_policy::reference)
		.def_readwrite("PlaylistMan", &UUIDataStore_OnlinePlaylists::PlaylistMan, py::return_value_policy::reference)
		.def("eventGetMatchTypeForPlaylistId", &UUIDataStore_OnlinePlaylists::eventGetMatchTypeForPlaylistId)
		.def("FindProviderIndexByFieldValue", &UUIDataStore_OnlinePlaylists::FindProviderIndexByFieldValue)
		.def("GetProviderFieldValue", &UUIDataStore_OnlinePlaylists::GetProviderFieldValue)
		.def("GetResourceProviderFields", &UUIDataStore_OnlinePlaylists::GetResourceProviderFields)
		.def("GetResourceProviders", &UUIDataStore_OnlinePlaylists::GetResourceProviders)
		.def("GetProviderCount", &UUIDataStore_OnlinePlaylists::GetProviderCount)
		.def("eventInit", &UUIDataStore_OnlinePlaylists::eventInit)
		.def("GetOnlinePlaylistProvider", [](UUIDataStore_OnlinePlaylists &self , struct FName ProviderTag, int PlaylistId) { int* pyProviderIndex = (int*)malloc(sizeof(int)) ;  class UOnlinePlaylistProvider* ret =  self.GetOnlinePlaylistProvider(ProviderTag, PlaylistId, pyProviderIndex); return py::make_tuple(ret, *pyProviderIndex); })
		.def("GetPlaylistProvider", [](UUIDataStore_OnlinePlaylists &self , struct FName ProviderTag, int ProviderIndex) { class UUIResourceDataProvider** pyout_Provider = 0 ;  bool ret =  self.GetPlaylistProvider(ProviderTag, ProviderIndex, pyout_Provider); return py::make_tuple(ret, *pyout_Provider); })
		;
	py::class_< UWebApplication, UObject >(m, "UWebApplication")
		.def_readwrite("WorldInfo", &UWebApplication::WorldInfo, py::return_value_policy::reference)
		.def_readwrite("WebServer", &UWebApplication::WebServer, py::return_value_policy::reference)
		.def_readwrite("Path", &UWebApplication::Path, py::return_value_policy::reference)
		.def("PostQuery", &UWebApplication::PostQuery)
		.def("Query", &UWebApplication::Query)
		.def("PreQuery", &UWebApplication::PreQuery)
		.def("CleanupApp", &UWebApplication::CleanupApp)
		.def("Cleanup", &UWebApplication::Cleanup)
		.def("Init", &UWebApplication::Init)
		;
	py::class_< AWebServer, ATcpLink >(m, "AWebServer")
		.def_property("bEnabled", [](AWebServer &self){return self.bEnabled;}, [](AWebServer &self, bool value){self.bEnabled = value ? 1 : 0;})
		.def_readwrite("ServerName", &AWebServer::ServerName, py::return_value_policy::reference)
		.def_readwrite("ListenPort", &AWebServer::ListenPort)
		.def_readwrite("MaxConnections", &AWebServer::MaxConnections)
		.def_readwrite("DefaultApplication", &AWebServer::DefaultApplication)
		.def_readwrite("ExpirationSeconds", &AWebServer::ExpirationSeconds)
		.def_readwrite("ServerURL", &AWebServer::ServerURL, py::return_value_policy::reference)
		.def_readwrite("ConnectionCount", &AWebServer::ConnectionCount)
		.def_readwrite("ConnID", &AWebServer::ConnID)
		.def("GetApplication", &AWebServer::GetApplication, py::return_value_policy::reference)
		.def("eventLostChild", &AWebServer::eventLostChild)
		.def("eventGainedChild", &AWebServer::eventGainedChild)
		.def("eventDestroyed", &AWebServer::eventDestroyed)
		.def("PostBeginPlay", &AWebServer::PostBeginPlay)
		;
	py::class_< UHelloWeb, UWebApplication >(m, "UHelloWeb")
		.def("eventQuery", &UHelloWeb::eventQuery)
		.def("Init", &UHelloWeb::Init)
		;
	py::class_< UImageServer, UWebApplication >(m, "UImageServer")
		.def("eventQuery", &UImageServer::eventQuery)
		;
	py::class_< AWebConnection, ATcpLink >(m, "AWebConnection")
		.def_property("bDelayCleanup", [](AWebConnection &self){return self.bDelayCleanup;}, [](AWebConnection &self, bool value){self.bDelayCleanup = value ? 1 : 0;})
		.def_readwrite("WebServer", &AWebConnection::WebServer, py::return_value_policy::reference)
		.def_readwrite("ReceivedData", &AWebConnection::ReceivedData, py::return_value_policy::reference)
		.def_readwrite("Request", &AWebConnection::Request, py::return_value_policy::reference)
		.def_readwrite("Response", &AWebConnection::Response, py::return_value_policy::reference)
		.def_readwrite("Application", &AWebConnection::Application, py::return_value_policy::reference)
		.def_readwrite("RawBytesExpecting", &AWebConnection::RawBytesExpecting)
		.def_readwrite("MaxValueLength", &AWebConnection::MaxValueLength)
		.def_readwrite("MaxLineLength", &AWebConnection::MaxLineLength)
		.def_readwrite("ConnID", &AWebConnection::ConnID)
		.def("IsHanging", &AWebConnection::IsHanging)
		.def("Cleanup", &AWebConnection::Cleanup)
		.def("CheckRawBytes", &AWebConnection::CheckRawBytes)
		.def("EndOfHeaders", &AWebConnection::EndOfHeaders)
		.def("CreateResponseObject", &AWebConnection::CreateResponseObject)
		.def("ProcessPost", &AWebConnection::ProcessPost)
		.def("ProcessGet", &AWebConnection::ProcessGet)
		.def("ProcessHead", &AWebConnection::ProcessHead)
		.def("ReceivedLine", &AWebConnection::ReceivedLine)
		.def("eventReceivedText", &AWebConnection::eventReceivedText)
		.def("eventTimer", &AWebConnection::eventTimer)
		.def("eventClosed", &AWebConnection::eventClosed)
		.def("eventAccepted", &AWebConnection::eventAccepted)
		;

}