#include "stdafx.h"
// Using =======================================================================
namespace py = pybind11;

// Module ======================================================================
void Export_pystes_OnlineSubsystemSteamworks_classes(py::module &m)
{
	py::class_< UOnlineAuthInterfaceSteamworks, UOnlineAuthInterfaceImpl >(m, "UOnlineAuthInterfaceSteamworks")
		.def_static("StaticClass", &UOnlineAuthInterfaceSteamworks::StaticClass, py::return_value_policy::reference)
		.def_readwrite("AuthCallbackBridge", &UOnlineAuthInterfaceSteamworks::AuthCallbackBridge, py::return_value_policy::reference)
		.def("GetServerUniqueId", &UOnlineAuthInterfaceSteamworks::GetServerUniqueId)
		.def("EndRemoteServerAuthSession", &UOnlineAuthInterfaceSteamworks::EndRemoteServerAuthSession)
		.def("EndLocalServerAuthSession", &UOnlineAuthInterfaceSteamworks::EndLocalServerAuthSession)
		.def("VerifyServerAuthSession", &UOnlineAuthInterfaceSteamworks::VerifyServerAuthSession)
		.def("EndRemoteClientAuthSession", &UOnlineAuthInterfaceSteamworks::EndRemoteClientAuthSession)
		.def("EndLocalClientAuthSession", &UOnlineAuthInterfaceSteamworks::EndLocalClientAuthSession)
		.def("VerifyClientAuthSession", &UOnlineAuthInterfaceSteamworks::VerifyClientAuthSession)
		.def("SendAuthRequestServer", &UOnlineAuthInterfaceSteamworks::SendAuthRequestServer)
		.def("SendAuthRequestClient", &UOnlineAuthInterfaceSteamworks::SendAuthRequestClient)
		.def("GetServerAddr", [](UOnlineAuthInterfaceSteamworks &self ) { int* pyOutServerIP = (int*)malloc(sizeof(int)) ; int* pyOutServerPort = (int*)malloc(sizeof(int)) ;  bool ret =  self.GetServerAddr(pyOutServerIP, pyOutServerPort); return py::make_tuple(ret, *pyOutServerIP, *pyOutServerPort); })
		.def("CreateServerAuthSession", [](UOnlineAuthInterfaceSteamworks &self , struct FUniqueNetId ClientUID, int ClientIP, int ClientPort) { int* pyOutAuthBlobUID = (int*)malloc(sizeof(int)) ;  bool ret =  self.CreateServerAuthSession(ClientUID, ClientIP, ClientPort, pyOutAuthBlobUID); return py::make_tuple(ret, *pyOutAuthBlobUID); })
		.def("CreateClientAuthSession", [](UOnlineAuthInterfaceSteamworks &self , struct FUniqueNetId ServerUID, int ServerIP, int ServerPort, unsigned long bSecure) { int* pyOutAuthBlobUID = (int*)malloc(sizeof(int)) ;  bool ret =  self.CreateClientAuthSession(ServerUID, ServerIP, ServerPort, bSecure, pyOutAuthBlobUID); return py::make_tuple(ret, *pyOutAuthBlobUID); })
		;
	py::class_< UOnlineGameInterfaceSteamworks, UOnlineGameInterfaceImpl >(m, "UOnlineGameInterfaceSteamworks")
		.def_static("StaticClass", &UOnlineGameInterfaceSteamworks::StaticClass, py::return_value_policy::reference)
		.def_property("bFilterEngineBuild", [](UOnlineGameInterfaceSteamworks &self){return self.bFilterEngineBuild;}, [](UOnlineGameInterfaceSteamworks &self, bool value){self.bFilterEngineBuild = value ? 1 : 0;})
		.def_readwrite("QueryToRulesResponseMap", &UOnlineGameInterfaceSteamworks::QueryToRulesResponseMap, py::return_value_policy::reference)
		.def_readwrite("QueryToPingResponseMap", &UOnlineGameInterfaceSteamworks::QueryToPingResponseMap, py::return_value_policy::reference)
		.def_readwrite("ServerListResponse", &UOnlineGameInterfaceSteamworks::ServerListResponse, py::return_value_policy::reference)
		.def_readwrite("CurrentMatchmakingType", &UOnlineGameInterfaceSteamworks::CurrentMatchmakingType)
		.def_readwrite("CurrentMatchmakingQuery", &UOnlineGameInterfaceSteamworks::CurrentMatchmakingQuery, py::return_value_policy::reference)
		.def_readwrite("GameInviteAcceptedDelegates", &UOnlineGameInterfaceSteamworks::GameInviteAcceptedDelegates, py::return_value_policy::reference)
		.def_readwrite("InviteGameSearch", &UOnlineGameInterfaceSteamworks::InviteGameSearch, py::return_value_policy::reference)
		.def_readwrite("RegisterPlayerCompleteDelegates", &UOnlineGameInterfaceSteamworks::RegisterPlayerCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("UnregisterPlayerCompleteDelegates", &UOnlineGameInterfaceSteamworks::UnregisterPlayerCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("ActiveClientsideFilters", &UOnlineGameInterfaceSteamworks::ActiveClientsideFilters, py::return_value_policy::reference)
		.def_readwrite("FilterKeyToSteamKeyMap", &UOnlineGameInterfaceSteamworks::FilterKeyToSteamKeyMap, py::return_value_policy::reference)
		.def_readwrite("ServerSessionName", &UOnlineGameInterfaceSteamworks::ServerSessionName, py::return_value_policy::reference)
		.def_readwrite("__OnGameInviteAccepted__Delegate", &UOnlineGameInterfaceSteamworks::__OnGameInviteAccepted__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnRegisterPlayerComplete__Delegate", &UOnlineGameInterfaceSteamworks::__OnRegisterPlayerComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnUnregisterPlayerComplete__Delegate", &UOnlineGameInterfaceSteamworks::__OnUnregisterPlayerComplete__Delegate, py::return_value_policy::reference)
		.def("GetGameSettings", &UOnlineGameInterfaceSteamworks::GetGameSettings, py::return_value_policy::reference)
		.def("GetResolvedConnectString", &UOnlineGameInterfaceSteamworks::GetResolvedConnectString)
		.def("QueryNonAdvertisedData", &UOnlineGameInterfaceSteamworks::QueryNonAdvertisedData)
		.def("ClearUnregisterPlayerCompleteDelegate", &UOnlineGameInterfaceSteamworks::ClearUnregisterPlayerCompleteDelegate)
		.def("AddUnregisterPlayerCompleteDelegate", &UOnlineGameInterfaceSteamworks::AddUnregisterPlayerCompleteDelegate)
		.def("OnUnregisterPlayerComplete", &UOnlineGameInterfaceSteamworks::OnUnregisterPlayerComplete)
		.def("UnregisterPlayer", &UOnlineGameInterfaceSteamworks::UnregisterPlayer)
		.def("ClearRegisterPlayerCompleteDelegate", &UOnlineGameInterfaceSteamworks::ClearRegisterPlayerCompleteDelegate)
		.def("AddRegisterPlayerCompleteDelegate", &UOnlineGameInterfaceSteamworks::AddRegisterPlayerCompleteDelegate)
		.def("OnRegisterPlayerComplete", &UOnlineGameInterfaceSteamworks::OnRegisterPlayerComplete)
		.def("RegisterPlayer", &UOnlineGameInterfaceSteamworks::RegisterPlayer)
		.def("AcceptGameInvite", &UOnlineGameInterfaceSteamworks::AcceptGameInvite)
		.def("OnGameInviteAccepted", &UOnlineGameInterfaceSteamworks::OnGameInviteAccepted)
		.def("ClearGameInviteAcceptedDelegate", &UOnlineGameInterfaceSteamworks::ClearGameInviteAcceptedDelegate)
		.def("AddGameInviteAcceptedDelegate", &UOnlineGameInterfaceSteamworks::AddGameInviteAcceptedDelegate)
		.def("UpdateOnlineGame", &UOnlineGameInterfaceSteamworks::UpdateOnlineGame)
		.def("BindPlatformSpecificSessionToSearch", [](UOnlineGameInterfaceSteamworks &self , unsigned char SearchingPlayerNum, class UOnlineGameSearch* SearchSettings) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.BindPlatformSpecificSessionToSearch(SearchingPlayerNum, SearchSettings, pyPlatformSpecificInfo); return py::make_tuple(ret, *pyPlatformSpecificInfo); })
		.def("ReadPlatformSpecificSessionInfoBySessionName", [](UOnlineGameInterfaceSteamworks &self , struct FName SessionName) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.ReadPlatformSpecificSessionInfoBySessionName(SessionName, pyPlatformSpecificInfo); return py::make_tuple(ret, *pyPlatformSpecificInfo); })
		.def("ReadPlatformSpecificSessionInfo", [](UOnlineGameInterfaceSteamworks &self , struct FOnlineGameSearchResult* DesiredGame) { unsigned char* pyPlatformSpecificInfo = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.ReadPlatformSpecificSessionInfo(DesiredGame, pyPlatformSpecificInfo); return py::make_tuple(ret, *pyPlatformSpecificInfo); })
		;
	py::class_< UOnlineLobbyInterfaceSteamworks, UObject >(m, "UOnlineLobbyInterfaceSteamworks")
		.def_static("StaticClass", &UOnlineLobbyInterfaceSteamworks::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UOnlineSubsystemSteamworks, UOnlineSubsystemCommonImpl >(m, "UOnlineSubsystemSteamworks")
		.def_static("StaticClass", &UOnlineSubsystemSteamworks::StaticClass, py::return_value_policy::reference)
		.def_property("bStoringAchievement", [](UOnlineSubsystemSteamworks &self){return self.bStoringAchievement;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bStoringAchievement = value ? 1 : 0;})
		.def_property("bGSStatsStoresSuccess", [](UOnlineSubsystemSteamworks &self){return self.bGSStatsStoresSuccess;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bGSStatsStoresSuccess = value ? 1 : 0;})
		.def_property("bNeedsKeyboardTicking", [](UOnlineSubsystemSteamworks &self){return self.bNeedsKeyboardTicking;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bNeedsKeyboardTicking = value ? 1 : 0;})
		.def_property("bLastHasConnection", [](UOnlineSubsystemSteamworks &self){return self.bLastHasConnection;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bLastHasConnection = value ? 1 : 0;})
		.def_property("bHasSteamworksAccount", [](UOnlineSubsystemSteamworks &self){return self.bHasSteamworksAccount;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bHasSteamworksAccount = value ? 1 : 0;})
		.def_property("bShouldUseMcp", [](UOnlineSubsystemSteamworks &self){return self.bShouldUseMcp;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bShouldUseMcp = value ? 1 : 0;})
		.def_property("bIncrementStatValues", [](UOnlineSubsystemSteamworks &self){return self.bIncrementStatValues;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bIncrementStatValues = value ? 1 : 0;})
		.def_property("bEnableSteamQoS", [](UOnlineSubsystemSteamworks &self){return self.bEnableSteamQoS;}, [](UOnlineSubsystemSteamworks &self, bool value){self.bEnableSteamQoS = value ? 1 : 0;})
		.def_readwrite("CallbackBridge", &UOnlineSubsystemSteamworks::CallbackBridge, py::return_value_policy::reference)
		.def_readwrite("AsyncTasks", &UOnlineSubsystemSteamworks::AsyncTasks, py::return_value_policy::reference)
		.def_readwrite("TotalGSStatsStoresPending", &UOnlineSubsystemSteamworks::TotalGSStatsStoresPending)
		.def_readwrite("UserStatsReceivedState", &UOnlineSubsystemSteamworks::UserStatsReceivedState)
		.def_readwrite("LoggedInStatus", &UOnlineSubsystemSteamworks::LoggedInStatus)
		.def_readwrite("bWasKeyboardInputCanceled", &UOnlineSubsystemSteamworks::bWasKeyboardInputCanceled)
		.def_readwrite("CurrentNotificationPosition", &UOnlineSubsystemSteamworks::CurrentNotificationPosition)
		.def_readwrite("CachedGameInt", &UOnlineSubsystemSteamworks::CachedGameInt, py::return_value_policy::reference)
		.def_readwrite("LocalProfileName", &UOnlineSubsystemSteamworks::LocalProfileName, py::return_value_policy::reference)
		.def_readwrite("LoggedInPlayerName", &UOnlineSubsystemSteamworks::LoggedInPlayerName, py::return_value_policy::reference)
		.def_readwrite("LoggedInPlayerId", &UOnlineSubsystemSteamworks::LoggedInPlayerId, py::return_value_policy::reference)
		.def_readwrite("LoggedInPlayerNum", &UOnlineSubsystemSteamworks::LoggedInPlayerNum)
		.def_readwrite("ProfileDataDirectory", &UOnlineSubsystemSteamworks::ProfileDataDirectory, py::return_value_policy::reference)
		.def_readwrite("ProfileDataExtension", &UOnlineSubsystemSteamworks::ProfileDataExtension, py::return_value_policy::reference)
		.def_readwrite("WriteProfileSettingsDelegates", &UOnlineSubsystemSteamworks::WriteProfileSettingsDelegates, py::return_value_policy::reference)
		.def_readwrite("CachedProfile", &UOnlineSubsystemSteamworks::CachedProfile, py::return_value_policy::reference)
		.def_readwrite("LocalPlayerStorageReadDelegates", &UOnlineSubsystemSteamworks::LocalPlayerStorageReadDelegates, py::return_value_policy::reference)
		.def_readwrite("LocalPlayerStorageWriteDelegates", &UOnlineSubsystemSteamworks::LocalPlayerStorageWriteDelegates, py::return_value_policy::reference)
		.def_readwrite("RemotePlayerStorageReadDelegates", &UOnlineSubsystemSteamworks::RemotePlayerStorageReadDelegates, py::return_value_policy::reference)
		.def_readwrite("SpeechRecognitionCompleteDelegates", &UOnlineSubsystemSteamworks::SpeechRecognitionCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("ReadFriendsDelegates", &UOnlineSubsystemSteamworks::ReadFriendsDelegates, py::return_value_policy::reference)
		.def_readwrite("FriendsChangeDelegates", &UOnlineSubsystemSteamworks::FriendsChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("MutingChangeDelegates", &UOnlineSubsystemSteamworks::MutingChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("LoginChangeDelegates", &UOnlineSubsystemSteamworks::LoginChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("LoginFailedDelegates", &UOnlineSubsystemSteamworks::LoginFailedDelegates, py::return_value_policy::reference)
		.def_readwrite("LogoutCompletedDelegates", &UOnlineSubsystemSteamworks::LogoutCompletedDelegates, py::return_value_policy::reference)
		.def_readwrite("GetUserAgeGroupCompletedDelegates", &UOnlineSubsystemSteamworks::GetUserAgeGroupCompletedDelegates, py::return_value_policy::reference)
		.def_readwrite("LoginStatusChangeDelegates", &UOnlineSubsystemSteamworks::LoginStatusChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("AccountCreateDelegates", &UOnlineSubsystemSteamworks::AccountCreateDelegates, py::return_value_policy::reference)
		.def_readwrite("TalkingDelegates", &UOnlineSubsystemSteamworks::TalkingDelegates, py::return_value_policy::reference)
		.def_readwrite("ReadOnlineStatsCompleteDelegates", &UOnlineSubsystemSteamworks::ReadOnlineStatsCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("FlushOnlineStatsDelegates", &UOnlineSubsystemSteamworks::FlushOnlineStatsDelegates, py::return_value_policy::reference)
		.def_readwrite("ConnectionStatusChangeDelegates", &UOnlineSubsystemSteamworks::ConnectionStatusChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("ControllerChangeDelegates", &UOnlineSubsystemSteamworks::ControllerChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("LinkStatusDelegates", &UOnlineSubsystemSteamworks::LinkStatusDelegates, py::return_value_policy::reference)
		.def_readwrite("ShareTitleFileCompleteDelegates", &UOnlineSubsystemSteamworks::ShareTitleFileCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("ReadTitleFileCompleteDelegates", &UOnlineSubsystemSteamworks::ReadTitleFileCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("AchievementDelegates", &UOnlineSubsystemSteamworks::AchievementDelegates, py::return_value_policy::reference)
		.def_readwrite("AchievementReadDelegates", &UOnlineSubsystemSteamworks::AchievementReadDelegates, py::return_value_policy::reference)
		.def_readwrite("AnyContentChangeDelegates", &UOnlineSubsystemSteamworks::AnyContentChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("CurrentLocalTalker", &UOnlineSubsystemSteamworks::CurrentLocalTalker, py::return_value_policy::reference)
		.def_readwrite("RemoteTalkers", &UOnlineSubsystemSteamworks::RemoteTalkers, py::return_value_policy::reference)
		.def_readwrite("GameID", &UOnlineSubsystemSteamworks::GameID)
		.def_readwrite("CurrentStatsRead", &UOnlineSubsystemSteamworks::CurrentStatsRead, py::return_value_policy::reference)
		.def_readwrite("StatWriteKeyMapping", &UOnlineSubsystemSteamworks::StatWriteKeyMapping, py::return_value_policy::reference)
		.def_readwrite("PendingStats", &UOnlineSubsystemSteamworks::PendingStats, py::return_value_policy::reference)
		.def_readwrite("KeyboardResultsString", &UOnlineSubsystemSteamworks::KeyboardResultsString, py::return_value_policy::reference)
		.def_readwrite("KeyboardInputDelegates", &UOnlineSubsystemSteamworks::KeyboardInputDelegates, py::return_value_policy::reference)
		.def_readwrite("FriendInviteReceivedDelegates", &UOnlineSubsystemSteamworks::FriendInviteReceivedDelegates, py::return_value_policy::reference)
		.def_readwrite("AddFriendByNameCompleteDelegates", &UOnlineSubsystemSteamworks::AddFriendByNameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("ProfileCache", &UOnlineSubsystemSteamworks::ProfileCache, py::return_value_policy::reference)
		.def_readwrite("PlayerStorageCache", &UOnlineSubsystemSteamworks::PlayerStorageCache, py::return_value_policy::reference)
		.def_readwrite("DeviceCache", &UOnlineSubsystemSteamworks::DeviceCache, py::return_value_policy::reference)
		.def_readwrite("LocationUrl", &UOnlineSubsystemSteamworks::LocationUrl, py::return_value_policy::reference)
		.def_readwrite("SentGameInviteDelegates", &UOnlineSubsystemSteamworks::SentGameInviteDelegates, py::return_value_policy::reference)
		.def_readwrite("ReceivedGameInviteDelegates", &UOnlineSubsystemSteamworks::ReceivedGameInviteDelegates, py::return_value_policy::reference)
		.def_readwrite("JoinFriendGameCompleteDelegates", &UOnlineSubsystemSteamworks::JoinFriendGameCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("GetNumberOfCurrentPlayersCompleteDelegates", &UOnlineSubsystemSteamworks::GetNumberOfCurrentPlayersCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("RegisterHostStatGuidCompleteDelegates", &UOnlineSubsystemSteamworks::RegisterHostStatGuidCompleteDelegates, py::return_value_policy::reference)
		.def_readwrite("CheckDownloadableContentListDelegates", &UOnlineSubsystemSteamworks::CheckDownloadableContentListDelegates, py::return_value_policy::reference)
		.def_readwrite("StatusMappings", &UOnlineSubsystemSteamworks::StatusMappings, py::return_value_policy::reference)
		.def_readwrite("StatusPropertyMappings", &UOnlineSubsystemSteamworks::StatusPropertyMappings, py::return_value_policy::reference)
		.def_readwrite("StatusContextMappings", &UOnlineSubsystemSteamworks::StatusContextMappings, py::return_value_policy::reference)
		.def_readwrite("DefaultStatus", &UOnlineSubsystemSteamworks::DefaultStatus, py::return_value_policy::reference)
		.def_readwrite("GameInviteMessage", &UOnlineSubsystemSteamworks::GameInviteMessage, py::return_value_policy::reference)
		.def_readwrite("ConnectionPresenceTimeInterval", &UOnlineSubsystemSteamworks::ConnectionPresenceTimeInterval)
		.def_readwrite("ConnectionPresenceElapsedTime", &UOnlineSubsystemSteamworks::ConnectionPresenceElapsedTime)
		.def_readwrite("EncryptedProductKey", &UOnlineSubsystemSteamworks::EncryptedProductKey, py::return_value_policy::reference)
		.def_readwrite("MuteList", &UOnlineSubsystemSteamworks::MuteList, py::return_value_policy::reference)
		.def_readwrite("TitleManagedFiles", &UOnlineSubsystemSteamworks::TitleManagedFiles, py::return_value_policy::reference)
		.def_readwrite("TitleFileMappings", &UOnlineSubsystemSteamworks::TitleFileMappings, py::return_value_policy::reference)
		.def_readwrite("QueuedAvatarRequests", &UOnlineSubsystemSteamworks::QueuedAvatarRequests, py::return_value_policy::reference)
		.def_readwrite("AchievementMappings", &UOnlineSubsystemSteamworks::AchievementMappings, py::return_value_policy::reference)
		.def_readwrite("PendingAchievementProgress", &UOnlineSubsystemSteamworks::PendingAchievementProgress, py::return_value_policy::reference)
		.def_readwrite("LeaderboardList", &UOnlineSubsystemSteamworks::LeaderboardList, py::return_value_policy::reference)
		.def_readwrite("DeferredLeaderboardReads", &UOnlineSubsystemSteamworks::DeferredLeaderboardReads, py::return_value_policy::reference)
		.def_readwrite("DeferredLeaderboardWrites", &UOnlineSubsystemSteamworks::DeferredLeaderboardWrites, py::return_value_policy::reference)
		.def_readwrite("PendingLeaderboardStats", &UOnlineSubsystemSteamworks::PendingLeaderboardStats, py::return_value_policy::reference)
		.def_readwrite("ProcessedLeaderboardReads", &UOnlineSubsystemSteamworks::ProcessedLeaderboardReads, py::return_value_policy::reference)
		.def_readwrite("LeaderboardNameMappings", &UOnlineSubsystemSteamworks::LeaderboardNameMappings, py::return_value_policy::reference)
		.def_readwrite("CachedAuthInt", &UOnlineSubsystemSteamworks::CachedAuthInt, py::return_value_policy::reference)
		.def_readwrite("PendingRedirects", &UOnlineSubsystemSteamworks::PendingRedirects, py::return_value_policy::reference)
		.def_readwrite("ExternalUIChangeDelegates", &UOnlineSubsystemSteamworks::ExternalUIChangeDelegates, py::return_value_policy::reference)
		.def_readwrite("DLCListCache", &UOnlineSubsystemSteamworks::DLCListCache, py::return_value_policy::reference)
		.def_readwrite("MarketplaceOffers", &UOnlineSubsystemSteamworks::MarketplaceOffers, py::return_value_policy::reference)
		.def_readwrite("QoSHandler", &UOnlineSubsystemSteamworks::QoSHandler, py::return_value_policy::reference)
		.def_readwrite("__OnLoginChange__Delegate", &UOnlineSubsystemSteamworks::__OnLoginChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnLoginCancelled__Delegate", &UOnlineSubsystemSteamworks::__OnLoginCancelled__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnMutingChange__Delegate", &UOnlineSubsystemSteamworks::__OnMutingChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnFriendsChange__Delegate", &UOnlineSubsystemSteamworks::__OnFriendsChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnLoginFailed__Delegate", &UOnlineSubsystemSteamworks::__OnLoginFailed__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnLogoutCompleted__Delegate", &UOnlineSubsystemSteamworks::__OnLogoutCompleted__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnGetUserAgeGroup__Delegate", &UOnlineSubsystemSteamworks::__OnGetUserAgeGroup__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnLoginStatusChange__Delegate", &UOnlineSubsystemSteamworks::__OnLoginStatusChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadProfileSettingsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadProfileSettingsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnWriteProfileSettingsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnWriteProfileSettingsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadPlayerStorageComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadPlayerStorageComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadPlayerStorageForNetIdComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadPlayerStorageForNetIdComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnWritePlayerStorageComplete__Delegate", &UOnlineSubsystemSteamworks::__OnWritePlayerStorageComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadFriendsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadFriendsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnPlayerTalkingStateChange__Delegate", &UOnlineSubsystemSteamworks::__OnPlayerTalkingStateChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnRecognitionComplete__Delegate", &UOnlineSubsystemSteamworks::__OnRecognitionComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadOnlineStatsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadOnlineStatsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnFlushOnlineStatsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnFlushOnlineStatsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnLinkStatusChange__Delegate", &UOnlineSubsystemSteamworks::__OnLinkStatusChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnExternalUIChange__Delegate", &UOnlineSubsystemSteamworks::__OnExternalUIChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnControllerChange__Delegate", &UOnlineSubsystemSteamworks::__OnControllerChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnConnectionStatusChange__Delegate", &UOnlineSubsystemSteamworks::__OnConnectionStatusChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnStorageDeviceChange__Delegate", &UOnlineSubsystemSteamworks::__OnStorageDeviceChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnShareTitleFileComplete__Delegate", &UOnlineSubsystemSteamworks::__OnShareTitleFileComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadTitleFileComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadTitleFileComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnCreateOnlineAccountCompleted__Delegate", &UOnlineSubsystemSteamworks::__OnCreateOnlineAccountCompleted__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnKeyboardInputComplete__Delegate", &UOnlineSubsystemSteamworks::__OnKeyboardInputComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnAddFriendByNameComplete__Delegate", &UOnlineSubsystemSteamworks::__OnAddFriendByNameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnFriendInviteReceived__Delegate", &UOnlineSubsystemSteamworks::__OnFriendInviteReceived__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnSentGameInvite__Delegate", &UOnlineSubsystemSteamworks::__OnSentGameInvite__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReceivedGameInvite__Delegate", &UOnlineSubsystemSteamworks::__OnReceivedGameInvite__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnJoinFriendGameComplete__Delegate", &UOnlineSubsystemSteamworks::__OnJoinFriendGameComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnFriendMessageReceived__Delegate", &UOnlineSubsystemSteamworks::__OnFriendMessageReceived__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnRegisterHostStatGuidComplete__Delegate", &UOnlineSubsystemSteamworks::__OnRegisterHostStatGuidComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnDeviceSelectionComplete__Delegate", &UOnlineSubsystemSteamworks::__OnDeviceSelectionComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnUnlockAchievementComplete__Delegate", &UOnlineSubsystemSteamworks::__OnUnlockAchievementComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnProfileDataChanged__Delegate", &UOnlineSubsystemSteamworks::__OnProfileDataChanged__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadAchievementsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadAchievementsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadOnlineAvatarComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadOnlineAvatarComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnGetNumberOfCurrentPlayersComplete__Delegate", &UOnlineSubsystemSteamworks::__OnGetNumberOfCurrentPlayersComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadCrossTitleProfileSettingsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadCrossTitleProfileSettingsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnUnlockAvatarAwardComplete__Delegate", &UOnlineSubsystemSteamworks::__OnUnlockAvatarAwardComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnContentChange__Delegate", &UOnlineSubsystemSteamworks::__OnContentChange__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadContentComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadContentComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadCrossTitleContentComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadCrossTitleContentComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadCrossTitleSaveGameDataComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadCrossTitleSaveGameDataComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnQueryAvailableDownloadsComplete__Delegate", &UOnlineSubsystemSteamworks::__OnQueryAvailableDownloadsComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadSaveGameDataComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadSaveGameDataComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnWriteSaveGameDataComplete__Delegate", &UOnlineSubsystemSteamworks::__OnWriteSaveGameDataComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadSaveGamesComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadSaveGamesComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadDownloadableContentListComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadDownloadableContentListComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadHiddenDownloadableContentListComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadHiddenDownloadableContentListComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnReadCriticalDownloadableContentListComplete__Delegate", &UOnlineSubsystemSteamworks::__OnReadCriticalDownloadableContentListComplete__Delegate, py::return_value_policy::reference)
		.def_readwrite("__OnCheckDownloadableContentList__Delegate", &UOnlineSubsystemSteamworks::__OnCheckDownloadableContentList__Delegate, py::return_value_policy::reference)
		.def("ClearCheckDownloadableContentListDelegate", &UOnlineSubsystemSteamworks::ClearCheckDownloadableContentListDelegate)
		.def("AddCheckDownloadableContentListDelegate", &UOnlineSubsystemSteamworks::AddCheckDownloadableContentListDelegate)
		.def("CheckDownloadableContentList", &UOnlineSubsystemSteamworks::CheckDownloadableContentList)
		.def("OnCheckDownloadableContentList", &UOnlineSubsystemSteamworks::OnCheckDownloadableContentList)
		.def("GetCriticalDownloadableContentList", &UOnlineSubsystemSteamworks::GetCriticalDownloadableContentList)
		.def("ReadCriticalDownloadableContentList", &UOnlineSubsystemSteamworks::ReadCriticalDownloadableContentList)
		.def("ClearReadCriticalDownloadableContentListComplete", &UOnlineSubsystemSteamworks::ClearReadCriticalDownloadableContentListComplete)
		.def("AddReadCriticalDownloadableContentListComplete", &UOnlineSubsystemSteamworks::AddReadCriticalDownloadableContentListComplete)
		.def("OnReadCriticalDownloadableContentListComplete", &UOnlineSubsystemSteamworks::OnReadCriticalDownloadableContentListComplete)
		.def("GetHiddenDownloadableContentList", &UOnlineSubsystemSteamworks::GetHiddenDownloadableContentList)
		.def("ReadHiddenDownloadableContentList", &UOnlineSubsystemSteamworks::ReadHiddenDownloadableContentList)
		.def("ClearReadHiddenDownloadableContentListComplete", &UOnlineSubsystemSteamworks::ClearReadHiddenDownloadableContentListComplete)
		.def("AddReadHiddenDownloadableContentListComplete", &UOnlineSubsystemSteamworks::AddReadHiddenDownloadableContentListComplete)
		.def("OnReadHiddenDownloadableContentListComplete", &UOnlineSubsystemSteamworks::OnReadHiddenDownloadableContentListComplete)
		.def("GetDownloadableContentList", &UOnlineSubsystemSteamworks::GetDownloadableContentList)
		.def("ReadDownloadableContentList", &UOnlineSubsystemSteamworks::ReadDownloadableContentList)
		.def("ClearReadDownloadableContentListComplete", &UOnlineSubsystemSteamworks::ClearReadDownloadableContentListComplete)
		.def("AddReadDownloadableContentListComplete", &UOnlineSubsystemSteamworks::AddReadDownloadableContentListComplete)
		.def("OnReadDownloadableContentListComplete", &UOnlineSubsystemSteamworks::OnReadDownloadableContentListComplete)
		.def("GetSaveGamesList", &UOnlineSubsystemSteamworks::GetSaveGamesList)
		.def("ReadSaveGamesList", &UOnlineSubsystemSteamworks::ReadSaveGamesList)
		.def("ClearReadSaveGamesComplete", &UOnlineSubsystemSteamworks::ClearReadSaveGamesComplete)
		.def("AddReadSaveGamesComplete", &UOnlineSubsystemSteamworks::AddReadSaveGamesComplete)
		.def("OnReadSaveGamesComplete", &UOnlineSubsystemSteamworks::OnReadSaveGamesComplete)
		.def("ClearSaveGames", &UOnlineSubsystemSteamworks::ClearSaveGames)
		.def("DeleteSaveGame", &UOnlineSubsystemSteamworks::DeleteSaveGame)
		.def("ClearWriteSaveGameDataComplete", &UOnlineSubsystemSteamworks::ClearWriteSaveGameDataComplete)
		.def("AddWriteSaveGameDataComplete", &UOnlineSubsystemSteamworks::AddWriteSaveGameDataComplete)
		.def("OnWriteSaveGameDataComplete", &UOnlineSubsystemSteamworks::OnWriteSaveGameDataComplete)
		.def("WriteSaveGameData", &UOnlineSubsystemSteamworks::WriteSaveGameData)
		.def("ClearReadSaveGameDataComplete", &UOnlineSubsystemSteamworks::ClearReadSaveGameDataComplete)
		.def("AddReadSaveGameDataComplete", &UOnlineSubsystemSteamworks::AddReadSaveGameDataComplete)
		.def("OnReadSaveGameDataComplete", &UOnlineSubsystemSteamworks::OnReadSaveGameDataComplete)
		.def("ReadSaveGameData", &UOnlineSubsystemSteamworks::ReadSaveGameData)
		.def("ClearQueryAvailableDownloadsComplete", &UOnlineSubsystemSteamworks::ClearQueryAvailableDownloadsComplete)
		.def("AddQueryAvailableDownloadsComplete", &UOnlineSubsystemSteamworks::AddQueryAvailableDownloadsComplete)
		.def("OnQueryAvailableDownloadsComplete", &UOnlineSubsystemSteamworks::OnQueryAvailableDownloadsComplete)
		.def("QueryAvailableDownloads", &UOnlineSubsystemSteamworks::QueryAvailableDownloads)
		.def("ClearCrossTitleSaveGames", &UOnlineSubsystemSteamworks::ClearCrossTitleSaveGames)
		.def("ClearReadCrossTitleSaveGameDataComplete", &UOnlineSubsystemSteamworks::ClearReadCrossTitleSaveGameDataComplete)
		.def("AddReadCrossTitleSaveGameDataComplete", &UOnlineSubsystemSteamworks::AddReadCrossTitleSaveGameDataComplete)
		.def("OnReadCrossTitleSaveGameDataComplete", &UOnlineSubsystemSteamworks::OnReadCrossTitleSaveGameDataComplete)
		.def("ReadCrossTitleSaveGameData", &UOnlineSubsystemSteamworks::ReadCrossTitleSaveGameData)
		.def("ClearReadCrossTitleContentCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadCrossTitleContentCompleteDelegate)
		.def("AddReadCrossTitleContentCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadCrossTitleContentCompleteDelegate)
		.def("OnReadCrossTitleContentComplete", &UOnlineSubsystemSteamworks::OnReadCrossTitleContentComplete)
		.def("GetCrossTitleContentList", &UOnlineSubsystemSteamworks::GetCrossTitleContentList)
		.def("ClearCrossTitleContentList", &UOnlineSubsystemSteamworks::ClearCrossTitleContentList)
		.def("ReadCrossTitleContentList", &UOnlineSubsystemSteamworks::ReadCrossTitleContentList)
		.def("GetContentList", &UOnlineSubsystemSteamworks::GetContentList)
		.def("ClearContentList", &UOnlineSubsystemSteamworks::ClearContentList)
		.def("ReadContentList", &UOnlineSubsystemSteamworks::ReadContentList)
		.def("ClearReadContentComplete", &UOnlineSubsystemSteamworks::ClearReadContentComplete)
		.def("AddReadContentComplete", &UOnlineSubsystemSteamworks::AddReadContentComplete)
		.def("OnReadContentComplete", &UOnlineSubsystemSteamworks::OnReadContentComplete)
		.def("ClearContentChangeDelegate", &UOnlineSubsystemSteamworks::ClearContentChangeDelegate)
		.def("AddContentChangeDelegate", &UOnlineSubsystemSteamworks::AddContentChangeDelegate)
		.def("ClearContentChangeDelegateEx", &UOnlineSubsystemSteamworks::ClearContentChangeDelegateEx)
		.def("AddContentChangeDelegateEx", &UOnlineSubsystemSteamworks::AddContentChangeDelegateEx)
		.def("OnContentChange", &UOnlineSubsystemSteamworks::OnContentChange)
		.def("ShowRedeemCodeUI", &UOnlineSubsystemSteamworks::ShowRedeemCodeUI)
		.def("DumpSteamworksSessionState", &UOnlineSubsystemSteamworks::DumpSteamworksSessionState)
		.def("DumpSessionState", &UOnlineSubsystemSteamworks::DumpSessionState)
		.def("SetVoiceVolume", &UOnlineSubsystemSteamworks::SetVoiceVolume)
		.def("ClearUnlockAvatarAwardCompleteDelegate", &UOnlineSubsystemSteamworks::ClearUnlockAvatarAwardCompleteDelegate)
		.def("AddUnlockAvatarAwardCompleteDelegate", &UOnlineSubsystemSteamworks::AddUnlockAvatarAwardCompleteDelegate)
		.def("OnUnlockAvatarAwardComplete", &UOnlineSubsystemSteamworks::OnUnlockAvatarAwardComplete)
		.def("GetFriendJoinURL", &UOnlineSubsystemSteamworks::GetFriendJoinURL)
		.def("GetCommandlineJoinURL", &UOnlineSubsystemSteamworks::GetCommandlineJoinURL)
		.def("Int64ToUniqueNetId", &UOnlineSubsystemSteamworks::Int64ToUniqueNetId)
		.def("UniqueNetIdToInt64", &UOnlineSubsystemSteamworks::UniqueNetIdToInt64, py::return_value_policy::reference)
		.def("NotifyVOIPPlaybackFinished", &UOnlineSubsystemSteamworks::NotifyVOIPPlaybackFinished)
		.def("OnVOIPPlaybackFinished", &UOnlineSubsystemSteamworks::OnVOIPPlaybackFinished)
		.def("ShowProfileUI", &UOnlineSubsystemSteamworks::ShowProfileUI)
		.def("UniqueNetIdToPlayerName", &UOnlineSubsystemSteamworks::UniqueNetIdToPlayerName, py::return_value_policy::reference)
		.def("DisplayAchievementProgress", &UOnlineSubsystemSteamworks::DisplayAchievementProgress)
		.def("CreateLeaderboard", &UOnlineSubsystemSteamworks::CreateLeaderboard)
		.def("ResetStats", &UOnlineSubsystemSteamworks::ResetStats)
		.def("ShowCustomMessageUI", &UOnlineSubsystemSteamworks::ShowCustomMessageUI)
		.def("ClearCrossTitleProfileSettings", &UOnlineSubsystemSteamworks::ClearCrossTitleProfileSettings)
		.def("GetCrossTitleProfileSettings", &UOnlineSubsystemSteamworks::GetCrossTitleProfileSettings, py::return_value_policy::reference)
		.def("ClearReadCrossTitleProfileSettingsCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadCrossTitleProfileSettingsCompleteDelegate)
		.def("AddReadCrossTitleProfileSettingsCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadCrossTitleProfileSettingsCompleteDelegate)
		.def("OnReadCrossTitleProfileSettingsComplete", &UOnlineSubsystemSteamworks::OnReadCrossTitleProfileSettingsComplete)
		.def("ReadCrossTitleProfileSettings", &UOnlineSubsystemSteamworks::ReadCrossTitleProfileSettings)
		.def("UnlockAvatarAward", &UOnlineSubsystemSteamworks::UnlockAvatarAward)
		.def("EnumerateFilesOnRemoteStorage", &UOnlineSubsystemSteamworks::EnumerateFilesOnRemoteStorage, py::return_value_policy::reference)
		.def("DeleteFileFromRemoteStorage", &UOnlineSubsystemSteamworks::DeleteFileFromRemoteStorage)
		.def("ReadBytesFromRemoteStorage", &UOnlineSubsystemSteamworks::ReadBytesFromRemoteStorage)
		.def("ReadStringFromRemoteStorage", &UOnlineSubsystemSteamworks::ReadStringFromRemoteStorage)
		.def("WriteBytesToRemoteStorage", &UOnlineSubsystemSteamworks::WriteBytesToRemoteStorage)
		.def("WriteStringToRemoteStorage", &UOnlineSubsystemSteamworks::WriteStringToRemoteStorage)
		.def("GetSteamClanData", &UOnlineSubsystemSteamworks::GetSteamClanData)
		.def("ClearGetNumberOfCurrentPlayersCompleteDelegate", &UOnlineSubsystemSteamworks::ClearGetNumberOfCurrentPlayersCompleteDelegate)
		.def("AddGetNumberOfCurrentPlayersCompleteDelegate", &UOnlineSubsystemSteamworks::AddGetNumberOfCurrentPlayersCompleteDelegate)
		.def("OnGetNumberOfCurrentPlayersComplete", &UOnlineSubsystemSteamworks::OnGetNumberOfCurrentPlayersComplete)
		.def("GetNumberOfCurrentPlayers", &UOnlineSubsystemSteamworks::GetNumberOfCurrentPlayers)
		.def("ReadOnlineAvatar", &UOnlineSubsystemSteamworks::ReadOnlineAvatar)
		.def("OnReadOnlineAvatarComplete", &UOnlineSubsystemSteamworks::OnReadOnlineAvatarComplete)
		.def("ShowCustomPlayersUI", &UOnlineSubsystemSteamworks::ShowCustomPlayersUI)
		.def("GetAchievements", &UOnlineSubsystemSteamworks::GetAchievements)
		.def("ClearReadAchievementsCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadAchievementsCompleteDelegate)
		.def("AddReadAchievementsCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadAchievementsCompleteDelegate)
		.def("OnReadAchievementsComplete", &UOnlineSubsystemSteamworks::OnReadAchievementsComplete)
		.def("ReadAchievements", &UOnlineSubsystemSteamworks::ReadAchievements)
		.def("ShowPlayersUI", &UOnlineSubsystemSteamworks::ShowPlayersUI)
		.def("ShowFriendsInviteUI", &UOnlineSubsystemSteamworks::ShowFriendsInviteUI)
		.def("ShowFriendsUI", &UOnlineSubsystemSteamworks::ShowFriendsUI)
		.def("ClearProfileDataChangedDelegate", &UOnlineSubsystemSteamworks::ClearProfileDataChangedDelegate)
		.def("AddProfileDataChangedDelegate", &UOnlineSubsystemSteamworks::AddProfileDataChangedDelegate)
		.def("OnProfileDataChanged", &UOnlineSubsystemSteamworks::OnProfileDataChanged)
		.def("UnlockGamerPicture", &UOnlineSubsystemSteamworks::UnlockGamerPicture)
		.def("ClearUnlockAchievementCompleteDelegate", &UOnlineSubsystemSteamworks::ClearUnlockAchievementCompleteDelegate)
		.def("AddUnlockAchievementCompleteDelegate", &UOnlineSubsystemSteamworks::AddUnlockAchievementCompleteDelegate)
		.def("OnUnlockAchievementComplete", &UOnlineSubsystemSteamworks::OnUnlockAchievementComplete)
		.def("UnlockAchievement", &UOnlineSubsystemSteamworks::UnlockAchievement)
		.def("IsDeviceValid", &UOnlineSubsystemSteamworks::IsDeviceValid)
		.def("GetDeviceSelectionResults", &UOnlineSubsystemSteamworks::GetDeviceSelectionResults)
		.def("ClearDeviceSelectionDoneDelegate", &UOnlineSubsystemSteamworks::ClearDeviceSelectionDoneDelegate)
		.def("AddDeviceSelectionDoneDelegate", &UOnlineSubsystemSteamworks::AddDeviceSelectionDoneDelegate)
		.def("OnDeviceSelectionComplete", &UOnlineSubsystemSteamworks::OnDeviceSelectionComplete)
		.def("ShowDeviceSelectionUI", &UOnlineSubsystemSteamworks::ShowDeviceSelectionUI)
		.def("ShowMembershipMarketplaceUI", &UOnlineSubsystemSteamworks::ShowMembershipMarketplaceUI)
		.def("ShowContentMarketplaceUI", &UOnlineSubsystemSteamworks::ShowContentMarketplaceUI)
		.def("ShowInviteUI", &UOnlineSubsystemSteamworks::ShowInviteUI)
		.def("ShowAchievementsUI", &UOnlineSubsystemSteamworks::ShowAchievementsUI)
		.def("ShowMessagesUI", &UOnlineSubsystemSteamworks::ShowMessagesUI)
		.def("ShowGamerCardUI", &UOnlineSubsystemSteamworks::ShowGamerCardUI)
		.def("ShowFeedbackUI", &UOnlineSubsystemSteamworks::ShowFeedbackUI)
		.def("DeleteMessage", &UOnlineSubsystemSteamworks::DeleteMessage)
		.def("UnmuteAll", &UOnlineSubsystemSteamworks::UnmuteAll)
		.def("MuteAll", &UOnlineSubsystemSteamworks::MuteAll)
		.def("CalcAggregateSkill", &UOnlineSubsystemSteamworks::CalcAggregateSkill)
		.def("RegisterStatGuid", &UOnlineSubsystemSteamworks::RegisterStatGuid)
		.def("GetClientStatGuid", &UOnlineSubsystemSteamworks::GetClientStatGuid, py::return_value_policy::reference)
		.def("ClearRegisterHostStatGuidCompleteDelegateDelegate", &UOnlineSubsystemSteamworks::ClearRegisterHostStatGuidCompleteDelegateDelegate)
		.def("AddRegisterHostStatGuidCompleteDelegate", &UOnlineSubsystemSteamworks::AddRegisterHostStatGuidCompleteDelegate)
		.def("OnRegisterHostStatGuidComplete", &UOnlineSubsystemSteamworks::OnRegisterHostStatGuidComplete)
		.def("RegisterHostStatGuid", &UOnlineSubsystemSteamworks::RegisterHostStatGuid)
		.def("GetHostStatGuid", &UOnlineSubsystemSteamworks::GetHostStatGuid, py::return_value_policy::reference)
		.def("ClearFriendMessageReceivedDelegate", &UOnlineSubsystemSteamworks::ClearFriendMessageReceivedDelegate)
		.def("AddFriendMessageReceivedDelegate", &UOnlineSubsystemSteamworks::AddFriendMessageReceivedDelegate)
		.def("OnFriendMessageReceived", &UOnlineSubsystemSteamworks::OnFriendMessageReceived)
		.def("GetFriendMessages", &UOnlineSubsystemSteamworks::GetFriendMessages)
		.def("ClearJoinFriendGameCompleteDelegate", &UOnlineSubsystemSteamworks::ClearJoinFriendGameCompleteDelegate)
		.def("AddJoinFriendGameCompleteDelegate", &UOnlineSubsystemSteamworks::AddJoinFriendGameCompleteDelegate)
		.def("OnJoinFriendGameComplete", &UOnlineSubsystemSteamworks::OnJoinFriendGameComplete)
		.def("JoinFriendGame", &UOnlineSubsystemSteamworks::JoinFriendGame)
		.def("ClearReceivedGameInviteDelegate", &UOnlineSubsystemSteamworks::ClearReceivedGameInviteDelegate)
		.def("AddReceivedGameInviteDelegate", &UOnlineSubsystemSteamworks::AddReceivedGameInviteDelegate)
		.def("OnReceivedGameInvite", &UOnlineSubsystemSteamworks::OnReceivedGameInvite)
		.def("ClearSentGameInviteDelegate", &UOnlineSubsystemSteamworks::ClearSentGameInviteDelegate)
		.def("AddSentGameInviteDelegate", &UOnlineSubsystemSteamworks::AddSentGameInviteDelegate)
		.def("OnSentGameInvite", &UOnlineSubsystemSteamworks::OnSentGameInvite)
		.def("SendGameInviteToFriends", &UOnlineSubsystemSteamworks::SendGameInviteToFriends)
		.def("SendGameInviteToFriend", &UOnlineSubsystemSteamworks::SendGameInviteToFriend)
		.def("SendMessageToFriend", &UOnlineSubsystemSteamworks::SendMessageToFriend)
		.def("ClearFriendInviteReceivedDelegate", &UOnlineSubsystemSteamworks::ClearFriendInviteReceivedDelegate)
		.def("AddFriendInviteReceivedDelegate", &UOnlineSubsystemSteamworks::AddFriendInviteReceivedDelegate)
		.def("OnFriendInviteReceived", &UOnlineSubsystemSteamworks::OnFriendInviteReceived)
		.def("DenyFriendInvite", &UOnlineSubsystemSteamworks::DenyFriendInvite)
		.def("AcceptFriendInvite", &UOnlineSubsystemSteamworks::AcceptFriendInvite)
		.def("RemoveFriend", &UOnlineSubsystemSteamworks::RemoveFriend)
		.def("ClearAddFriendByNameCompleteDelegate", &UOnlineSubsystemSteamworks::ClearAddFriendByNameCompleteDelegate)
		.def("AddAddFriendByNameCompleteDelegate", &UOnlineSubsystemSteamworks::AddAddFriendByNameCompleteDelegate)
		.def("OnAddFriendByNameComplete", &UOnlineSubsystemSteamworks::OnAddFriendByNameComplete)
		.def("AddFriendByName", &UOnlineSubsystemSteamworks::AddFriendByName)
		.def("AddFriend", &UOnlineSubsystemSteamworks::AddFriend)
		.def("ClearKeyboardInputDoneDelegate", &UOnlineSubsystemSteamworks::ClearKeyboardInputDoneDelegate)
		.def("AddKeyboardInputDoneDelegate", &UOnlineSubsystemSteamworks::AddKeyboardInputDoneDelegate)
		.def("OnKeyboardInputComplete", &UOnlineSubsystemSteamworks::OnKeyboardInputComplete)
		.def("ShowKeyboardUI", &UOnlineSubsystemSteamworks::ShowKeyboardUI)
		.def("SetOnlineStatus", &UOnlineSubsystemSteamworks::SetOnlineStatus)
		.def("GetLocalAccountNames", &UOnlineSubsystemSteamworks::GetLocalAccountNames)
		.def("DeleteLocalAccount", &UOnlineSubsystemSteamworks::DeleteLocalAccount)
		.def("RenameLocalAccount", &UOnlineSubsystemSteamworks::RenameLocalAccount)
		.def("CreateLocalAccount", &UOnlineSubsystemSteamworks::CreateLocalAccount)
		.def("ClearCreateOnlineAccountCompletedDelegate", &UOnlineSubsystemSteamworks::ClearCreateOnlineAccountCompletedDelegate)
		.def("AddCreateOnlineAccountCompletedDelegate", &UOnlineSubsystemSteamworks::AddCreateOnlineAccountCompletedDelegate)
		.def("OnCreateOnlineAccountCompleted", &UOnlineSubsystemSteamworks::OnCreateOnlineAccountCompleted)
		.def("CreateOnlineAccount", &UOnlineSubsystemSteamworks::CreateOnlineAccount)
		.def("ClearDownloadedFile", &UOnlineSubsystemSteamworks::ClearDownloadedFile)
		.def("ClearDownloadedFiles", &UOnlineSubsystemSteamworks::ClearDownloadedFiles)
		.def("GetTitleFileState", &UOnlineSubsystemSteamworks::GetTitleFileState)
		.def("GetTitleFileContents", &UOnlineSubsystemSteamworks::GetTitleFileContents)
		.def("ClearReadTitleFileCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadTitleFileCompleteDelegate)
		.def("AddReadTitleFileCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadTitleFileCompleteDelegate)
		.def("ReadTitleFile", &UOnlineSubsystemSteamworks::ReadTitleFile)
		.def("OnReadTitleFileComplete", &UOnlineSubsystemSteamworks::OnReadTitleFileComplete)
		.def("ClearShareTitleFileCompleteDelegate", &UOnlineSubsystemSteamworks::ClearShareTitleFileCompleteDelegate)
		.def("AddShareTitleFileCompleteDelegate", &UOnlineSubsystemSteamworks::AddShareTitleFileCompleteDelegate)
		.def("ShareTitleFile", &UOnlineSubsystemSteamworks::ShareTitleFile)
		.def("OnShareTitleFileComplete", &UOnlineSubsystemSteamworks::OnShareTitleFileComplete)
		.def("ClearStorageDeviceChangeDelegate", &UOnlineSubsystemSteamworks::ClearStorageDeviceChangeDelegate)
		.def("AddStorageDeviceChangeDelegate", &UOnlineSubsystemSteamworks::AddStorageDeviceChangeDelegate)
		.def("OnStorageDeviceChange", &UOnlineSubsystemSteamworks::OnStorageDeviceChange)
		.def("GetLocale", &UOnlineSubsystemSteamworks::GetLocale)
		.def("GetNATType", &UOnlineSubsystemSteamworks::GetNATType)
		.def("ClearConnectionStatusChangeDelegate", &UOnlineSubsystemSteamworks::ClearConnectionStatusChangeDelegate)
		.def("AddConnectionStatusChangeDelegate", &UOnlineSubsystemSteamworks::AddConnectionStatusChangeDelegate)
		.def("OnConnectionStatusChange", &UOnlineSubsystemSteamworks::OnConnectionStatusChange)
		.def("IsControllerConnected", &UOnlineSubsystemSteamworks::IsControllerConnected)
		.def("ClearControllerChangeDelegate", &UOnlineSubsystemSteamworks::ClearControllerChangeDelegate)
		.def("AddControllerChangeDelegate", &UOnlineSubsystemSteamworks::AddControllerChangeDelegate)
		.def("OnControllerChange", &UOnlineSubsystemSteamworks::OnControllerChange)
		.def("SetNetworkNotificationPosition", &UOnlineSubsystemSteamworks::SetNetworkNotificationPosition)
		.def("GetNetworkNotificationPosition", &UOnlineSubsystemSteamworks::GetNetworkNotificationPosition)
		.def("ClearExternalUIChangeDelegate", &UOnlineSubsystemSteamworks::ClearExternalUIChangeDelegate)
		.def("AddExternalUIChangeDelegate", &UOnlineSubsystemSteamworks::AddExternalUIChangeDelegate)
		.def("OnExternalUIChange", &UOnlineSubsystemSteamworks::OnExternalUIChange)
		.def("ClearLinkStatusChangeDelegate", &UOnlineSubsystemSteamworks::ClearLinkStatusChangeDelegate)
		.def("AddLinkStatusChangeDelegate", &UOnlineSubsystemSteamworks::AddLinkStatusChangeDelegate)
		.def("OnLinkStatusChange", &UOnlineSubsystemSteamworks::OnLinkStatusChange)
		.def("HasLinkConnection", &UOnlineSubsystemSteamworks::HasLinkConnection)
		.def("eventGetPlayerUniqueNetIdFromIndex", &UOnlineSubsystemSteamworks::eventGetPlayerUniqueNetIdFromIndex, py::return_value_policy::reference)
		.def("eventGetPlayerNicknameFromIndex", &UOnlineSubsystemSteamworks::eventGetPlayerNicknameFromIndex, py::return_value_policy::reference)
		.def("WriteOnlinePlayerScores", &UOnlineSubsystemSteamworks::WriteOnlinePlayerScores)
		.def("ClearFlushOnlineStatsCompleteDelegate", &UOnlineSubsystemSteamworks::ClearFlushOnlineStatsCompleteDelegate)
		.def("AddFlushOnlineStatsCompleteDelegate", &UOnlineSubsystemSteamworks::AddFlushOnlineStatsCompleteDelegate)
		.def("OnFlushOnlineStatsComplete", &UOnlineSubsystemSteamworks::OnFlushOnlineStatsComplete)
		.def("FlushOnlineStats", &UOnlineSubsystemSteamworks::FlushOnlineStats)
		.def("WriteOnlineStats", &UOnlineSubsystemSteamworks::WriteOnlineStats)
		.def("FreeStats", &UOnlineSubsystemSteamworks::FreeStats)
		.def("ClearReadOnlineStatsCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadOnlineStatsCompleteDelegate)
		.def("AddReadOnlineStatsCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadOnlineStatsCompleteDelegate)
		.def("OnReadOnlineStatsComplete", &UOnlineSubsystemSteamworks::OnReadOnlineStatsComplete)
		.def("ReadOnlineStatsByRankAroundPlayer", &UOnlineSubsystemSteamworks::ReadOnlineStatsByRankAroundPlayer)
		.def("ReadOnlineStatsByRank", &UOnlineSubsystemSteamworks::ReadOnlineStatsByRank)
		.def("ReadOnlineStatsForFriends", &UOnlineSubsystemSteamworks::ReadOnlineStatsForFriends)
		.def("ReadOnlineStats", &UOnlineSubsystemSteamworks::ReadOnlineStats)
		.def("SetSpeechRecognitionObject", &UOnlineSubsystemSteamworks::SetSpeechRecognitionObject)
		.def("SelectVocabulary", &UOnlineSubsystemSteamworks::SelectVocabulary)
		.def("ClearRecognitionCompleteDelegate", &UOnlineSubsystemSteamworks::ClearRecognitionCompleteDelegate)
		.def("AddRecognitionCompleteDelegate", &UOnlineSubsystemSteamworks::AddRecognitionCompleteDelegate)
		.def("OnRecognitionComplete", &UOnlineSubsystemSteamworks::OnRecognitionComplete)
		.def("GetRecognitionResults", &UOnlineSubsystemSteamworks::GetRecognitionResults)
		.def("StopSpeechRecognition", &UOnlineSubsystemSteamworks::StopSpeechRecognition)
		.def("StartSpeechRecognition", &UOnlineSubsystemSteamworks::StartSpeechRecognition)
		.def("StopNetworkedVoice", &UOnlineSubsystemSteamworks::StopNetworkedVoice)
		.def("StartNetworkedVoice", &UOnlineSubsystemSteamworks::StartNetworkedVoice)
		.def("ClearPlayerTalkingDelegate", &UOnlineSubsystemSteamworks::ClearPlayerTalkingDelegate)
		.def("AddPlayerTalkingDelegate", &UOnlineSubsystemSteamworks::AddPlayerTalkingDelegate)
		.def("OnPlayerTalkingStateChange", &UOnlineSubsystemSteamworks::OnPlayerTalkingStateChange)
		.def("UnmuteRemoteTalker", &UOnlineSubsystemSteamworks::UnmuteRemoteTalker)
		.def("MuteRemoteTalker", &UOnlineSubsystemSteamworks::MuteRemoteTalker)
		.def("SetRemoteTalkerPriority", &UOnlineSubsystemSteamworks::SetRemoteTalkerPriority)
		.def("IsHeadsetPresent", &UOnlineSubsystemSteamworks::IsHeadsetPresent)
		.def("IsRemotePlayerTalking", &UOnlineSubsystemSteamworks::IsRemotePlayerTalking)
		.def("IsLocalPlayerTalking", &UOnlineSubsystemSteamworks::IsLocalPlayerTalking)
		.def("UnregisterRemoteTalker", &UOnlineSubsystemSteamworks::UnregisterRemoteTalker)
		.def("RegisterRemoteTalker", &UOnlineSubsystemSteamworks::RegisterRemoteTalker)
		.def("UnregisterLocalTalker", &UOnlineSubsystemSteamworks::UnregisterLocalTalker)
		.def("RegisterLocalTalker", &UOnlineSubsystemSteamworks::RegisterLocalTalker)
		.def("GetFriendsList", &UOnlineSubsystemSteamworks::GetFriendsList)
		.def("ClearReadFriendsCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadFriendsCompleteDelegate)
		.def("AddReadFriendsCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadFriendsCompleteDelegate)
		.def("OnReadFriendsComplete", &UOnlineSubsystemSteamworks::OnReadFriendsComplete)
		.def("ReadFriendsList", &UOnlineSubsystemSteamworks::ReadFriendsList)
		.def("ClearWritePlayerStorageCompleteDelegate", &UOnlineSubsystemSteamworks::ClearWritePlayerStorageCompleteDelegate)
		.def("AddWritePlayerStorageCompleteDelegate", &UOnlineSubsystemSteamworks::AddWritePlayerStorageCompleteDelegate)
		.def("OnWritePlayerStorageComplete", &UOnlineSubsystemSteamworks::OnWritePlayerStorageComplete)
		.def("WritePlayerStorage", &UOnlineSubsystemSteamworks::WritePlayerStorage)
		.def("GetPlayerStorage", &UOnlineSubsystemSteamworks::GetPlayerStorage, py::return_value_policy::reference)
		.def("ClearReadPlayerStorageForNetIdCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadPlayerStorageForNetIdCompleteDelegate)
		.def("AddReadPlayerStorageForNetIdCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadPlayerStorageForNetIdCompleteDelegate)
		.def("OnReadPlayerStorageForNetIdComplete", &UOnlineSubsystemSteamworks::OnReadPlayerStorageForNetIdComplete)
		.def("ReadPlayerStorageForNetId", &UOnlineSubsystemSteamworks::ReadPlayerStorageForNetId)
		.def("ClearReadPlayerStorageCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadPlayerStorageCompleteDelegate)
		.def("AddReadPlayerStorageCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadPlayerStorageCompleteDelegate)
		.def("OnReadPlayerStorageComplete", &UOnlineSubsystemSteamworks::OnReadPlayerStorageComplete)
		.def("ReadPlayerStorage", &UOnlineSubsystemSteamworks::ReadPlayerStorage)
		.def("ClearWriteProfileSettingsCompleteDelegate", &UOnlineSubsystemSteamworks::ClearWriteProfileSettingsCompleteDelegate)
		.def("AddWriteProfileSettingsCompleteDelegate", &UOnlineSubsystemSteamworks::AddWriteProfileSettingsCompleteDelegate)
		.def("OnWriteProfileSettingsComplete", &UOnlineSubsystemSteamworks::OnWriteProfileSettingsComplete)
		.def("WriteProfileSettings", &UOnlineSubsystemSteamworks::WriteProfileSettings)
		.def("GetProfileSettings", &UOnlineSubsystemSteamworks::GetProfileSettings, py::return_value_policy::reference)
		.def("ClearReadProfileSettingsCompleteDelegate", &UOnlineSubsystemSteamworks::ClearReadProfileSettingsCompleteDelegate)
		.def("AddReadProfileSettingsCompleteDelegate", &UOnlineSubsystemSteamworks::AddReadProfileSettingsCompleteDelegate)
		.def("OnReadProfileSettingsComplete", &UOnlineSubsystemSteamworks::OnReadProfileSettingsComplete)
		.def("ReadProfileSettings", &UOnlineSubsystemSteamworks::ReadProfileSettings)
		.def("ClearFriendsChangeDelegate", &UOnlineSubsystemSteamworks::ClearFriendsChangeDelegate)
		.def("AddFriendsChangeDelegate", &UOnlineSubsystemSteamworks::AddFriendsChangeDelegate)
		.def("ClearMutingChangeDelegate", &UOnlineSubsystemSteamworks::ClearMutingChangeDelegate)
		.def("AddMutingChangeDelegate", &UOnlineSubsystemSteamworks::AddMutingChangeDelegate)
		.def("ClearLoginCancelledDelegate", &UOnlineSubsystemSteamworks::ClearLoginCancelledDelegate)
		.def("AddLoginCancelledDelegate", &UOnlineSubsystemSteamworks::AddLoginCancelledDelegate)
		.def("ClearLoginStatusChangeDelegate", &UOnlineSubsystemSteamworks::ClearLoginStatusChangeDelegate)
		.def("AddLoginStatusChangeDelegate", &UOnlineSubsystemSteamworks::AddLoginStatusChangeDelegate)
		.def("OnLoginStatusChange", &UOnlineSubsystemSteamworks::OnLoginStatusChange)
		.def("ClearLoginChangeDelegate", &UOnlineSubsystemSteamworks::ClearLoginChangeDelegate)
		.def("AddLoginChangeDelegate", &UOnlineSubsystemSteamworks::AddLoginChangeDelegate)
		.def("IsMuted", &UOnlineSubsystemSteamworks::IsMuted)
		.def("AreAnyFriends", &UOnlineSubsystemSteamworks::AreAnyFriends)
		.def("IsFriend", &UOnlineSubsystemSteamworks::IsFriend)
		.def("CanShowPresenceInformation", &UOnlineSubsystemSteamworks::CanShowPresenceInformation)
		.def("CanViewPlayerProfiles", &UOnlineSubsystemSteamworks::CanViewPlayerProfiles)
		.def("CanPurchaseContent", &UOnlineSubsystemSteamworks::CanPurchaseContent)
		.def("CanDownloadUserContent", &UOnlineSubsystemSteamworks::CanDownloadUserContent)
		.def("CanCommunicate", &UOnlineSubsystemSteamworks::CanCommunicate)
		.def("CanPlayOnline", &UOnlineSubsystemSteamworks::CanPlayOnline)
		.def("ClearGetUserAgeGroupDelegate", &UOnlineSubsystemSteamworks::ClearGetUserAgeGroupDelegate)
		.def("AddGetUserAgeGroupDelegate", &UOnlineSubsystemSteamworks::AddGetUserAgeGroupDelegate)
		.def("GetUserAgeGroup", &UOnlineSubsystemSteamworks::GetUserAgeGroup)
		.def("OnGetUserAgeGroup", &UOnlineSubsystemSteamworks::OnGetUserAgeGroup)
		.def("GetPlayerNickname", &UOnlineSubsystemSteamworks::GetPlayerNickname, py::return_value_policy::reference)
		.def("GetUniquePlayerId", &UOnlineSubsystemSteamworks::GetUniquePlayerId)
		.def("IsLocalLogin", &UOnlineSubsystemSteamworks::IsLocalLogin)
		.def("IsGuestLogin", &UOnlineSubsystemSteamworks::IsGuestLogin)
		.def("GetLoginStatus", &UOnlineSubsystemSteamworks::GetLoginStatus)
		.def("ClearLogoutCompletedDelegate", &UOnlineSubsystemSteamworks::ClearLogoutCompletedDelegate)
		.def("AddLogoutCompletedDelegate", &UOnlineSubsystemSteamworks::AddLogoutCompletedDelegate)
		.def("OnLogoutCompleted", &UOnlineSubsystemSteamworks::OnLogoutCompleted)
		.def("Logout", &UOnlineSubsystemSteamworks::Logout)
		.def("ClearLoginFailedDelegate", &UOnlineSubsystemSteamworks::ClearLoginFailedDelegate)
		.def("AddLoginFailedDelegate", &UOnlineSubsystemSteamworks::AddLoginFailedDelegate)
		.def("OnLoginFailed", &UOnlineSubsystemSteamworks::OnLoginFailed)
		.def("AutoLogin", &UOnlineSubsystemSteamworks::AutoLogin)
		.def("Login", &UOnlineSubsystemSteamworks::Login)
		.def("ShowLoginUI", &UOnlineSubsystemSteamworks::ShowLoginUI)
		.def("OnFriendsChange", &UOnlineSubsystemSteamworks::OnFriendsChange)
		.def("OnMutingChange", &UOnlineSubsystemSteamworks::OnMutingChange)
		.def("OnLoginCancelled", &UOnlineSubsystemSteamworks::OnLoginCancelled)
		.def("OnLoginChange", &UOnlineSubsystemSteamworks::OnLoginChange)
		.def("eventExit", &UOnlineSubsystemSteamworks::eventExit)
		.def("eventInit", &UOnlineSubsystemSteamworks::eventInit)
		.def("GetSaveGameData", [](UOnlineSubsystemSteamworks &self , unsigned char LocalUserNum, int DeviceID, struct FString FriendlyName, struct FString Filename, struct FString SaveFileName, TArray< unsigned char >* SaveGameData) { unsigned char* pybIsValid = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.GetSaveGameData(LocalUserNum, DeviceID, FriendlyName, Filename, SaveFileName, pybIsValid, SaveGameData); return py::make_tuple(ret, *pybIsValid); })
		.def("GetAvailableDownloadCounts", [](UOnlineSubsystemSteamworks &self , unsigned char LocalUserNum) { int* pyNewDownloads = (int*)malloc(sizeof(int)) ; int* pyTotalDownloads = (int*)malloc(sizeof(int)) ;   self.GetAvailableDownloadCounts(LocalUserNum, pyNewDownloads, pyTotalDownloads); return py::make_tuple(*pyNewDownloads, *pyTotalDownloads); })
		.def("GetCrossTitleSaveGameData", [](UOnlineSubsystemSteamworks &self , unsigned char LocalUserNum, int DeviceID, int TitleId, struct FString FriendlyName, struct FString Filename, struct FString SaveFileName, TArray< unsigned char >* SaveGameData) { unsigned char* pybIsValid = (unsigned char*)malloc(sizeof(unsigned char)) ;  bool ret =  self.GetCrossTitleSaveGameData(LocalUserNum, DeviceID, TitleId, FriendlyName, Filename, SaveFileName, pybIsValid, SaveGameData); return py::make_tuple(ret, *pybIsValid); })
		.def("GetKeyboardInputResults", [](UOnlineSubsystemSteamworks &self ) { unsigned char* pybWasCanceled = (unsigned char*)malloc(sizeof(unsigned char)) ;  struct FString ret =  self.GetKeyboardInputResults(pybWasCanceled); return py::make_tuple(ret, *pybWasCanceled); })
		;
	py::class_< UQoSHandlerSteamworks, UObject >(m, "UQoSHandlerSteamworks")
		.def_static("StaticClass", &UQoSHandlerSteamworks::StaticClass, py::return_value_policy::reference)
		.def_property("bEnabled", [](UQoSHandlerSteamworks &self){return self.bEnabled;}, [](UQoSHandlerSteamworks &self, bool value){self.bEnabled = value ? 1 : 0;})
		.def_readwrite("MaxQoSRequest", &UQoSHandlerSteamworks::MaxQoSRequest)
		.def_readwrite("MaxQoSListen", &UQoSHandlerSteamworks::MaxQoSListen)
		.def_readwrite("NumPingProbes", &UQoSHandlerSteamworks::NumPingProbes)
		.def_readwrite("PingProbeSize", &UQoSHandlerSteamworks::PingProbeSize)
		.def_readwrite("PingTimeout", &UQoSHandlerSteamworks::PingTimeout)
		.def_readwrite("ChallengeTimeout", &UQoSHandlerSteamworks::ChallengeTimeout)
		.def_readwrite("ListenTimeout", &UQoSHandlerSteamworks::ListenTimeout)
		.def_readwrite("ListenEntries", &UQoSHandlerSteamworks::ListenEntries, py::return_value_policy::reference)
		.def_readwrite("RequestEntries", &UQoSHandlerSteamworks::RequestEntries, py::return_value_policy::reference)
		.def_readwrite("PendingRequests", &UQoSHandlerSteamworks::PendingRequests, py::return_value_policy::reference)
		;
	py::class_< USparkInterfaceSteamworks, USparkInterfaceImpl >(m, "USparkInterfaceSteamworks")
		.def_static("StaticClass", &USparkInterfaceSteamworks::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UIpNetDriverSteamworks, UTcpNetDriver >(m, "UIpNetDriverSteamworks")
		.def_static("StaticClass", &UIpNetDriverSteamworks::StaticClass, py::return_value_policy::reference)
		;
	py::class_< UIpNetConnectionSteamworks, UTcpipConnection >(m, "UIpNetConnectionSteamworks")
		.def_static("StaticClass", &UIpNetConnectionSteamworks::StaticClass, py::return_value_policy::reference)
		;

}